import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const ASR_PRAYER: PrayerInfo = {
  id: "asr",
  name: {
    en: "Asr",
    bn: "আসর",
    ur: "عصر",
    ar: "العصر",
    tr: "İkindi",
    ms: "Asar",
    id: "Ashar",
  },
  arabicName: "صلاة العصر",
  type: "fard",
  category: "daily",
  totalRakats: "8",
  rakatBreakdown: {
    en: "4 Sunnah (Ghair Muakkadah) + 4 Fard",
    bn: "৪ রাকাত সুন্নাত (গায়রে মুআক্কাদাহ) + ৪ রাকাত ফরজ",
    ur: "۴ رکعت سنت (غیر مؤکدہ) + ۴ رکعت فرض",
    ar: "٤ ركعات سنة (غير مؤكدة) + ٤ ركعات فرض",
    tr: "4 Rekat Sünnet (Gayri Müekked) + 4 Rekat Farz",
    ms: "4 Rakaat Sunat (Ghair Muakkad) + 4 Rakaat Fardu",
    id: "4 Rakaat Sunah (Ghair Muakkad) + 4 Rakaat Fardu",
  },
  time: {
    en: "From when the shadow of an object equals its length until sunset",
    bn: "কোনো বস্তুর ছায়া তার সমান হলে থেকে সূর্যাস্ত পর্যন্ত",
    ur: "جب کسی چیز کا سایہ اس کے برابر ہو جائے سے غروب آفتاب تک",
    ar: "من حين يصير ظل الشيء مثله إلى غروب الشمس",
    tr: "Bir cismin gölgesi kendi boyu kadar olduğunda başlar, güneş batana kadar devam eder",
    ms: "Apabila bayang-bayang sesuatu objek sama panjang dengannya sehingga matahari terbenam",
    id: "Ketika bayangan suatu benda sama panjang dengan bendanya hingga matahari terbenam",
  },
  description: {
    en: "Asr is the afternoon prayer, the third of the five daily prayers. It is performed silently (without reciting aloud). The Prophet (peace be upon him) emphasized the importance of not missing this prayer.",
    bn: "আসর হলো বিকালের নামাজ, পাঁচ ওয়াক্ত নামাজের তৃতীয়। এটি নীরবে (মনে মনে) পড়তে হয়। নবী (সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম) এই নামাজ ছেড়ে না দেওয়ার ওপর বিশেষ গুরুত্ব দিয়েছেন।",
    ur: "عصر دوپہر کی نماز ہے، پانچ فرض نمازوں میں سے تیسری۔ یہ آہستہ (بغیر آواز کے) پڑھی جاتی ہے۔ نبی کریم (صلی اللہ علیہ وسلم) نے اس نماز کو ترک نہ کرنے پر بہت زور دیا۔",
    ar: "العصر هي صلاة بعد الظهر، وهي الثالثة من الصلوات الخمس المفروضة. تُؤدَّى سرًّا (بدون جهر). وقد أكد النبي ﷺ على أهمية عدم تفويت هذه الصلاة.",
    tr: "İkindi namazı, beş vakit namazın üçüncüsüdür. Sessiz olarak (içinden okuyarak) kılınır. Peygamber Efendimiz (s.a.v.) bu namazın kaçırılmamasının önemini vurgulamıştır.",
    ms: "Asar ialah solat petang, solat ketiga daripada lima solat fardu. Ia dilakukan secara senyap (tanpa mengeraskan bacaan). Nabi (s.a.w.) menekankan kepentingan untuk tidak meninggalkan solat ini.",
    id: "Ashar adalah shalat sore, shalat ketiga dari lima shalat fardu. Shalat ini dilakukan secara sirr (tanpa mengeraskan bacaan). Nabi (s.a.w.) menekankan pentingnya untuk tidak meninggalkan shalat ini.",
  },
  steps: [
    // ── Step 1: Niyyah ──
    {
      stepNumber: 1,
      action: {
        en: "Stand facing the Qiblah and make the intention (Niyyah) in your heart to pray 4 Rakat Fard of Asr",
        bn: "কিবলামুখী হয়ে দাঁড়ান এবং অন্তরে আসরের ৪ রাকাত ফরজ নামাজের নিয়ত করুন",
        ur: "قبلہ رخ کھڑے ہوں اور دل میں عصر کی ۴ رکعت فرض نماز کی نیت کریں",
        ar: "قف مستقبلًا القبلة وانوِ في قلبك صلاة ٤ ركعات فرض العصر",
        tr: "Kıbleye dönüp ikindi namazının 4 rekat farzı için kalbinizden niyet edin",
        ms: "Berdiri menghadap kiblat dan niat dalam hati untuk menunaikan 4 rakaat fardu Asar",
        id: "Berdiri menghadap kiblat dan niat dalam hati untuk menunaikan 4 rakaat fardu Ashar",
      },
      arabic: "نَوَيْتُ أَنْ أُصَلِّيَ أَرْبَعَ رَكَعَاتٍ صَلَاةِ الْعَصْرِ فَرْضَ اللَّهِ تَعَالَى",
      transliteration: "Nawaytu an usalliya arba'a raka'atin salatal Asri fardallahi ta'ala",
      meaning: {
        en: "I intend to pray 4 Rakat of the Fard of Asr prayer for the sake of Allah the Most High",
        bn: "আমি আল্লাহ তা'আলার ফরজ আসরের নামাজ ৪ রাকাত পড়ার নিয়ত করছি",
        ur: "میں اللہ تعالیٰ کے فرض عصر کی ۴ رکعت نماز پڑھنے کی نیت کرتا ہوں",
        ar: "نويت أن أصلي أربع ركعات صلاة العصر فرض الله تعالى",
        tr: "Allah Teâlâ'nın farzı olan ikindi namazının 4 rekatını kılmaya niyet ettim",
        ms: "Saya berniat menunaikan 4 rakaat fardu solat Asar kerana Allah Taala",
        id: "Saya berniat menunaikan 4 rakaat fardu shalat Ashar karena Allah Ta'ala",
      },
    },
    // ── Step 2: Takbiratul Ihram ──
    {
      stepNumber: 2,
      action: {
        en: "Raise both hands to the ears (men) or shoulders (women) and say the Takbiratul Ihram",
        bn: "উভয় হাত কান (পুরুষ) বা কাঁধ (মহিলা) পর্যন্ত তুলুন এবং তাকবীরে তাহরীমা বলুন",
        ur: "دونوں ہاتھ کانوں (مرد) یا کندھوں (خواتین) تک اٹھائیں اور تکبیر تحریمہ کہیں",
        ar: "ارفع يديك إلى الأذنين (للرجال) أو الكتفين (للنساء) وكبّر تكبيرة الإحرام",
        tr: "İki elinizi kulaklarınıza (erkekler) veya omuzlarınıza (kadınlar) kaldırıp iftitah tekbiri alın",
        ms: "Angkat kedua tangan ke telinga (lelaki) atau bahu (wanita) dan lafazkan Takbiratul Ihram",
        id: "Angkat kedua tangan ke telinga (laki-laki) atau bahu (wanita) dan ucapkan Takbiratul Ihram",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সবচেয়ে মহান",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    // ── Step 3: Thana (Opening Supplication) ──
    {
      stepNumber: 3,
      action: {
        en: "Place hands on chest (right over left) and recite the opening supplication (Thana) silently",
        bn: "বুকের উপর হাত রাখুন (ডান হাত বামের উপর) এবং নীরবে ছানা পড়ুন",
        ur: "ہاتھ سینے پر رکھیں (دایاں بائیں پر) اور آہستہ سے ثناء پڑھیں",
        ar: "ضع يديك على صدرك (اليمنى فوق اليسرى) واقرأ دعاء الاستفتاح سرًّا",
        tr: "Ellerinizi göğsünüze koyun (sağ el solun üstüne) ve açılış duasını (Sübhaneke) sessizce okuyun",
        ms: "Letakkan tangan di dada (kanan atas kiri) dan baca doa iftitah (Thana) secara senyap",
        id: "Letakkan tangan di dada (kanan di atas kiri) dan baca doa iftitah (Thana) secara perlahan",
      },
      arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ",
      transliteration: "Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta'ala jadduka wa la ilaha ghairuk",
      meaning: {
        en: "Glory be to You, O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, and there is no god but You.",
        bn: "হে আল্লাহ, আপনার পবিত্রতা ঘোষণা করছি এবং আপনার প্রশংসা করছি। আপনার নাম বরকতময়, আপনার মর্যাদা সুউচ্চ, এবং আপনি ছাড়া কোনো ইলাহ নেই।",
        ur: "اے اللہ، تو پاک ہے اور تیری حمد ہے۔ تیرا نام بابرکت ہے، تیری شان بلند ہے، اور تیرے سوا کوئی معبود نہیں۔",
        ar: "سبحانك اللهم وبحمدك، تبارك اسمك وتعالى جدك ولا إله غيرك.",
        tr: "Seni tenzih ederim Allah'ım ve Sana hamdederim. Senin adın mübarektir, şanın yücedir ve Senden başka ilah yoktur.",
        ms: "Maha Suci Engkau ya Allah dan dengan puji-Mu. Berkatilah nama-Mu, Maha Tinggi kebesaran-Mu, dan tiada tuhan selain Engkau.",
        id: "Maha Suci Engkau ya Allah dan dengan puji-Mu. Berkatilah nama-Mu, Maha Tinggi kebesaran-Mu, dan tiada tuhan selain Engkau.",
      },
    },
    // ── Step 4: Ta'awwudh and Bismillah ──
    {
      stepNumber: 4,
      action: {
        en: "Recite Ta'awwudh (seeking refuge) and Bismillah silently",
        bn: "নীরবে তা'আউয ও বিসমিল্লাহ পড়ুন",
        ur: "آہستہ سے تعوذ اور بسم اللہ پڑھیں",
        ar: "اقرأ التعوذ والبسملة سرًّا",
        tr: "Eûzü ve Besmeleyi sessizce okuyun",
        ms: "Baca Ta'awwudz dan Bismillah secara senyap",
        id: "Baca Ta'awwudz dan Bismillah secara perlahan",
      },
      arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ · بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
      transliteration: "A'udhu billahi minash-shaytanir-rajim. Bismillahir-Rahmanir-Rahim",
      meaning: {
        en: "I seek refuge in Allah from the accursed Satan. In the name of Allah, the Most Gracious, the Most Merciful.",
        bn: "আমি অভিশপ্ত শয়তান থেকে আল্লাহর কাছে আশ্রয় চাই। পরম করুণাময় অতি দয়ালু আল্লাহর নামে।",
        ur: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں۔ اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔",
        ar: "أعوذ بالله من الشيطان الرجيم. بسم الله الرحمن الرحيم.",
        tr: "Kovulmuş şeytandan Allah'a sığınırım. Rahman ve Rahim olan Allah'ın adıyla.",
        ms: "Aku berlindung dengan Allah dari syaitan yang terkutuk. Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang.",
        id: "Aku berlindung kepada Allah dari setan yang terkutuk. Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang.",
      },
    },
    // ── Step 5: Surah Al-Fatiha ──
    {
      stepNumber: 5,
      action: {
        en: "Recite Surah Al-Fatiha silently (Asr is a silent prayer)",
        bn: "নীরবে সূরা আল-ফাতিহা পড়ুন (আসর নীরব নামাজ)",
        ur: "آہستہ سے سورۃ الفاتحہ پڑھیں (عصر آہستہ نماز ہے)",
        ar: "اقرأ سورة الفاتحة سرًّا (العصر صلاة سرية)",
        tr: "Fatiha suresini sessizce okuyun (İkindi sessiz namazdır)",
        ms: "Baca Surah Al-Fatihah secara senyap (Asar adalah solat sirr)",
        id: "Baca Surah Al-Fatihah secara perlahan (Ashar adalah shalat sirr)",
      },
      arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ · الرَّحْمَنِ الرَّحِيمِ · مَالِكِ يَوْمِ الدِّينِ · إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ · اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ · صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
      transliteration: "Alhamdu lillahi Rabbil 'alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na'budu wa iyyaka nasta'in. Ihdinas-siratal mustaqim. Siratal-ladhina an'amta 'alaihim ghairil-maghdubi 'alaihim walad-dallin",
      meaning: {
        en: "All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us on the Straight Path. The path of those whom You have blessed, not of those who earned anger, nor of those who went astray.",
        bn: "সমস্ত প্রশংসা আল্লাহর যিনি সমগ্র বিশ্বের প্রতিপালক। পরম করুণাময় অতি দয়ালু। বিচার দিনের মালিক। আমরা কেবল আপনারই ইবাদত করি এবং কেবল আপনারই কাছে সাহায্য চাই। আমাদের সরল পথে পরিচালিত করুন। তাদের পথে যাদের আপনি নেয়ামত দিয়েছেন, তাদের পথে নয় যাদের প্রতি গজব পড়েছে এবং যারা পথভ্রষ্ট হয়েছে।",
        ur: "تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے۔ بڑا مہربان نہایت رحم والا۔ بدلے کے دن کا مالک۔ ہم صرف تیری عبادت کرتے ہیں اور صرف تجھ سے مدد مانگتے ہیں۔ ہمیں سیدھا راستہ دکھا۔ ان لوگوں کا راستہ جن پر تو نے انعام کیا، ان کا نہیں جن پر غضب ہوا اور نہ گمراہوں کا۔",
        ar: "الحمد لله رب العالمين. الرحمن الرحيم. مالك يوم الدين. إياك نعبد وإياك نستعين. اهدنا الصراط المستقيم. صراط الذين أنعمت عليهم غير المغضوب عليهم ولا الضالين.",
        tr: "Hamd, alemlerin Rabbi Allah'a mahsustur. Rahman ve Rahim olan. Din gününün sahibi. Yalnız Sana ibadet ederiz ve yalnız Senden yardım dileriz. Bizi doğru yola ilet. Nimet verdiklerinin yoluna; gazaba uğrayanların ve sapıtanların yoluna değil.",
        ms: "Segala puji bagi Allah, Tuhan semesta alam. Yang Maha Pemurah lagi Maha Penyayang. Pemilik hari pembalasan. Hanya Engkau yang kami sembah dan hanya kepada Engkau kami mohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang yang Engkau beri nikmat, bukan jalan yang dimurkai dan bukan jalan yang sesat.",
        id: "Segala puji bagi Allah, Tuhan seluruh alam. Yang Maha Pengasih lagi Maha Penyayang. Pemilik hari pembalasan. Hanya kepada-Mu kami menyembah dan hanya kepada-Mu kami memohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang yang Engkau beri nikmat, bukan jalan yang dimurkai dan bukan jalan yang sesat.",
      },
    },
    // ── Step 6: Recite an additional Surah ──
    {
      stepNumber: 6,
      action: {
        en: "Recite any short Surah or verses after Al-Fatiha silently (in the first 2 Rakats)",
        bn: "আল-ফাতিহার পরে নীরবে যেকোনো ছোট সূরা বা আয়াত পড়ুন (প্রথম ২ রাকাতে)",
        ur: "الفاتحہ کے بعد آہستہ سے کوئی چھوٹی سورت یا آیات پڑھیں (پہلی ۲ رکعتوں میں)",
        ar: "اقرأ سورة قصيرة أو آيات بعد الفاتحة سرًّا (في الركعتين الأوليين)",
        tr: "Fatiha'dan sonra sessizce kısa bir sure veya ayetler okuyun (ilk 2 rekatta)",
        ms: "Baca surah pendek atau ayat selepas Al-Fatihah secara senyap (dalam 2 rakaat pertama)",
        id: "Baca surah pendek atau ayat setelah Al-Fatihah secara perlahan (dalam 2 rakaat pertama)",
      },
      arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ · اللَّهُ الصَّمَدُ · لَمْ يَلِدْ وَلَمْ يُولَدْ · وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
      transliteration: "Qul Huwa Allahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
      meaning: {
        en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. And there is none comparable to Him. (Surah Al-Ikhlas — example)",
        bn: "বলুন: তিনি আল্লাহ, এক। আল্লাহ অমুখাপেক্ষী। তিনি জন্ম দেননি এবং তাঁকেও জন্ম দেওয়া হয়নি। এবং তাঁর সমকক্ষ কেউ নেই। (সূরা আল-ইখলাস — উদাহরণ)",
        ur: "کہو: وہ اللہ ہے، ایک۔ اللہ بے نیاز ہے۔ نہ اس نے جنا نہ وہ جنا گیا۔ اور کوئی اس کا ہمسر نہیں۔ (سورۃ الاخلاص — مثال)",
        ar: "قل هو الله أحد. الله الصمد. لم يلد ولم يولد. ولم يكن له كفوًا أحد. (سورة الإخلاص — مثال)",
        tr: "De ki: O Allah'tır, bir tektir. Allah Samed'dir. Doğurmamış ve doğmamıştır. Hiçbir şey O'nun dengi değildir. (İhlas Suresi — örnek)",
        ms: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada sesuatu pun yang setara dengan-Nya. (Surah Al-Ikhlas — contoh)",
        id: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada sesuatu pun yang setara dengan-Nya. (Surah Al-Ikhlas — contoh)",
      },
    },
    // ── Step 7: Ruku (Bowing) ──
    {
      stepNumber: 7,
      action: {
        en: "Say Allahu Akbar and bow down for Ruku. Place hands on knees, keep back straight. Recite the Tasbeeh 3 times.",
        bn: "আল্লাহু আকবার বলে রুকুতে যান। হাঁটুতে হাত রাখুন, পিঠ সোজা রাখুন। ৩ বার তাসবীহ পড়ুন।",
        ur: "اللہ اکبر کہہ کر رکوع میں جائیں۔ ہاتھ گھٹنوں پر رکھیں، کمر سیدھی رکھیں۔ ۳ بار تسبیح پڑھیں۔",
        ar: "كبّر واركع. ضع يديك على ركبتيك واجعل ظهرك مستقيمًا. سبّح ثلاث مرات.",
        tr: "Allahu Ekber deyip rükûya eğilin. Ellerinizi dizlerinize koyun, sırtınızı düz tutun. Tesbih'i 3 kez okuyun.",
        ms: "Ucapkan Allahu Akbar dan rukuk. Letakkan tangan di lutut, luruskan belakang. Baca tasbih 3 kali.",
        id: "Ucapkan Allahu Akbar dan rukuk. Letakkan tangan di lutut, luruskan punggung. Baca tasbih 3 kali.",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
      transliteration: "Subhana Rabbiyal Adheem (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most Great (3 times)",
        bn: "আমার মহান প্রতিপালকের পবিত্রতা ঘোষণা করছি (৩ বার)",
        ur: "پاک ہے میرا رب جو بہت عظمت والا ہے (۳ بار)",
        ar: "سبحان ربي العظيم (٣ مرات)",
        tr: "Yüce Rabbimi tenzih ederim (3 kez)",
        ms: "Maha Suci Tuhanku Yang Maha Agung (3 kali)",
        id: "Maha Suci Tuhanku Yang Maha Agung (3 kali)",
      },
    },
    // ── Step 8: Standing from Ruku ──
    {
      stepNumber: 8,
      action: {
        en: "Rise from Ruku saying Sami'Allahu liman hamidah, then say Rabbana lakal hamd while standing upright",
        bn: "সামি'আল্লাহু লিমান হামিদাহ বলে রুকু থেকে উঠুন, তারপর সোজা হয়ে দাঁড়িয়ে রাব্বানা লাকাল হামদ বলুন",
        ur: "سمع اللہ لمن حمدہ کہتے ہوئے رکوع سے اٹھیں، پھر سیدھے کھڑے ہو کر ربنا لک الحمد کہیں",
        ar: "ارفع من الركوع قائلًا سمع الله لمن حمده، ثم قل ربنا لك الحمد وأنت واقف",
        tr: "Semiallahu limen hamideh diyerek rükûdan kalkın, dikildikten sonra Rabbena lekel hamd deyin",
        ms: "Bangkit dari rukuk dengan mengucapkan Sami'Allahu liman hamidah, kemudian ucapkan Rabbana lakal hamd ketika berdiri tegak",
        id: "Bangkit dari rukuk dengan mengucapkan Sami'Allahu liman hamidah, kemudian ucapkan Rabbana lakal hamd ketika berdiri tegak",
      },
      arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ · رَبَّنَا لَكَ الْحَمْدُ",
      transliteration: "Sami'Allahu liman hamidah. Rabbana lakal hamd.",
      meaning: {
        en: "Allah hears the one who praises Him. Our Lord, to You belongs all praise.",
        bn: "যে আল্লাহর প্রশংসা করে আল্লাহ তাকে শোনেন। হে আমাদের প্রতিপালক, সকল প্রশংসা আপনার।",
        ur: "اللہ نے اس کی سنی جس نے اس کی حمد کی۔ اے ہمارے رب، تمام تعریف تیرے لیے ہے۔",
        ar: "سمع الله لمن حمده. ربنا لك الحمد.",
        tr: "Allah kendisine hamdedeni işitir. Rabbimiz, hamd Sana mahsustur.",
        ms: "Allah mendengar orang yang memuji-Nya. Wahai Tuhan kami, bagi-Mu segala pujian.",
        id: "Allah mendengar orang yang memuji-Nya. Wahai Tuhan kami, bagi-Mu segala pujian.",
      },
    },
    // ── Step 9: First Sajdah (Prostration) ──
    {
      stepNumber: 9,
      action: {
        en: "Say Allahu Akbar and go into Sajdah (prostration). Place forehead, nose, both palms, knees, and toes on the ground. Recite the Tasbeeh 3 times.",
        bn: "আল্লাহু আকবার বলে সেজদায় যান। কপাল, নাক, দুই হাতের তালু, হাঁটু ও পায়ের আঙুল মাটিতে রাখুন। ৩ বার তাসবীহ পড়ুন।",
        ur: "اللہ اکبر کہہ کر سجدے میں جائیں۔ پیشانی، ناک، دونوں ہتھیلیاں، گھٹنے اور پاؤں کی انگلیاں زمین پر رکھیں۔ ۳ بار تسبیح پڑھیں۔",
        ar: "كبّر واسجد. ضع جبهتك وأنفك وكفيك وركبتيك وأطراف قدميك على الأرض. سبّح ثلاث مرات.",
        tr: "Allahu Ekber deyip secdeye varın. Alnınızı, burnunuzu, avuçlarınızı, dizlerinizi ve ayak parmaklarınızı yere koyun. Tesbih'i 3 kez okuyun.",
        ms: "Ucapkan Allahu Akbar dan sujud. Letakkan dahi, hidung, kedua tapak tangan, lutut dan hujung jari kaki di atas tanah. Baca tasbih 3 kali.",
        id: "Ucapkan Allahu Akbar dan sujud. Letakkan dahi, hidung, kedua telapak tangan, lutut dan ujung jari kaki di tanah. Baca tasbih 3 kali.",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
      transliteration: "Subhana Rabbiyal A'la (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most High (3 times)",
        bn: "আমার সর্বোচ্চ প্রতিপালকের পবিত্রতা ঘোষণা করছি (৩ বার)",
        ur: "پاک ہے میرا رب جو سب سے بلند ہے (۳ بار)",
        ar: "سبحان ربي الأعلى (٣ مرات)",
        tr: "Yüce Rabbimi tenzih ederim (3 kez)",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi (3 kali)",
        id: "Maha Suci Tuhanku Yang Maha Tinggi (3 kali)",
      },
    },
    // ── Step 10: Sitting between two Sajdahs ──
    {
      stepNumber: 10,
      action: {
        en: "Rise from Sajdah saying Allahu Akbar and sit briefly between the two prostrations. Recite the dua.",
        bn: "আল্লাহু আকবার বলে সেজদা থেকে উঠুন এবং দুই সেজদার মাঝে সংক্ষেপে বসুন। দু'আ পড়ুন।",
        ur: "اللہ اکبر کہتے ہوئے سجدے سے اٹھیں اور دونوں سجدوں کے درمیان مختصر بیٹھیں۔ دعا پڑھیں۔",
        ar: "ارفع من السجود قائلًا الله أكبر واجلس بين السجدتين. اقرأ الدعاء.",
        tr: "Allahu Ekber deyip secdeden kalkın ve iki secde arasında kısa bir süre oturun. Duayı okuyun.",
        ms: "Bangkit dari sujud dengan mengucapkan Allahu Akbar dan duduk sebentar antara dua sujud. Baca doa.",
        id: "Bangkit dari sujud dengan mengucapkan Allahu Akbar dan duduk sebentar antara dua sujud. Baca doa.",
      },
      arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
      transliteration: "Rabbighfir li, Rabbighfir li",
      meaning: {
        en: "My Lord, forgive me. My Lord, forgive me.",
        bn: "হে আমার রব, আমাকে ক্ষমা করুন। হে আমার রব, আমাকে ক্ষমা করুন।",
        ur: "اے میرے رب، مجھے معاف کر دے۔ اے میرے رب، مجھے معاف کر دے۔",
        ar: "رب اغفر لي. رب اغفر لي.",
        tr: "Rabbim beni bağışla. Rabbim beni bağışla.",
        ms: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.",
        id: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.",
      },
    },
    // ── Step 11: Second Sajdah ──
    {
      stepNumber: 11,
      action: {
        en: "Say Allahu Akbar and perform the second Sajdah. Recite the Tasbeeh 3 times, same as the first Sajdah.",
        bn: "আল্লাহু আকবার বলে দ্বিতীয় সেজদা করুন। প্রথম সেজদার মতো ৩ বার তাসবীহ পড়ুন।",
        ur: "اللہ اکبر کہہ کر دوسرا سجدہ کریں۔ پہلے سجدے کی طرح ۳ بار تسبیح پڑھیں۔",
        ar: "كبّر واسجد السجدة الثانية. سبّح ثلاث مرات كالأولى.",
        tr: "Allahu Ekber deyip ikinci secdeyi yapın. Birinci secde gibi tesbih'i 3 kez okuyun.",
        ms: "Ucapkan Allahu Akbar dan lakukan sujud kedua. Baca tasbih 3 kali seperti sujud pertama.",
        id: "Ucapkan Allahu Akbar dan lakukan sujud kedua. Baca tasbih 3 kali seperti sujud pertama.",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
      transliteration: "Subhana Rabbiyal A'la (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most High (3 times)",
        bn: "আমার সর্বোচ্চ প্রতিপালকের পবিত্রতা ঘোষণা করছি (৩ বার)",
        ur: "پاک ہے میرا رب جو سب سے بلند ہے (۳ بار)",
        ar: "سبحان ربي الأعلى (٣ مرات)",
        tr: "Yüce Rabbimi tenzih ederim (3 kez)",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi (3 kali)",
        id: "Maha Suci Tuhanku Yang Maha Tinggi (3 kali)",
      },
    },
    // ── Step 12: Stand for 2nd Rakat ──
    {
      stepNumber: 12,
      action: {
        en: "Say Allahu Akbar and stand up for the 2nd Rakat. Repeat Surah Al-Fatiha and an additional Surah silently, then perform Ruku and two Sajdahs as before.",
        bn: "আল্লাহু আকবার বলে ২য় রাকাতের জন্য দাঁড়ান। নীরবে সূরা আল-ফাতিহা ও অতিরিক্ত সূরা পড়ুন, তারপর আগের মতো রুকু ও দুই সেজদা করুন।",
        ur: "اللہ اکبر کہہ کر دوسری رکعت کے لیے کھڑے ہوں۔ آہستہ سے سورۃ الفاتحہ اور ایک اور سورت پڑھیں، پھر پہلے کی طرح رکوع اور دو سجدے کریں۔",
        ar: "كبّر وقم للركعة الثانية. اقرأ الفاتحة وسورة سرًّا ثم اركع واسجد سجدتين كالأولى.",
        tr: "Allahu Ekber deyip 2. rekata kalkın. Sessizce Fatiha ve ek bir sure okuyun, sonra önceki gibi rükû ve iki secde yapın.",
        ms: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-2. Baca Al-Fatihah dan surah tambahan secara senyap, kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
        id: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-2. Baca Al-Fatihah dan surah tambahan secara perlahan, kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সবচেয়ে মহান",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    // ── Step 13: First Tashahhud (after 2nd Rakat) ──
    {
      stepNumber: 13,
      action: {
        en: "After the 2nd Rakat, sit for the first Tashahhud (At-Tahiyyat). Point the index finger of your right hand during the Shahadah.",
        bn: "২য় রাকাতের পর প্রথম তাশাহহুদ (আত-তাহিয়্যাত) পড়তে বসুন। শাহাদাতের সময় ডান হাতের তর্জনী আঙুল তুলুন।",
        ur: "دوسری رکعت کے بعد پہلا تشہد (التحیات) پڑھنے کے لیے بیٹھیں۔ شہادت کے وقت دائیں ہاتھ کی شہادت کی انگلی اٹھائیں۔",
        ar: "بعد الركعة الثانية اجلس للتشهد الأول (التحيات). أشر بسبابة يدك اليمنى عند الشهادة.",
        tr: "2. rekattan sonra ilk Tahiyyat için oturun. Şehadet sırasında sağ elinizin işaret parmağını kaldırın.",
        ms: "Selepas rakaat ke-2, duduk untuk Tashahhud pertama (At-Tahiyyat). Angkat jari telunjuk tangan kanan semasa Syahadah.",
        id: "Setelah rakaat ke-2, duduk untuk Tashahhud pertama (At-Tahiyyat). Angkat jari telunjuk tangan kanan saat Syahadat.",
      },
      arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
      transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibatu. As-salamu 'alayka ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alaina wa 'ala 'ibadillahis-salihin. Ash-hadu an la ilaha illallahu wa ash-hadu anna Muhammadan 'abduhu wa rasuluh.",
      meaning: {
        en: "All greetings, prayers, and pure words are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger.",
        bn: "সকল সম্মান, সকল নামাজ ও সকল পবিত্র কথা আল্লাহর জন্য। হে নবী, আপনার উপর শান্তি, আল্লাহর রহমত ও বরকত বর্ষিত হোক। আমাদের উপর ও আল্লাহর নেক বান্দাদের উপর শান্তি বর্ষিত হোক। আমি সাক্ষ্য দিচ্ছি যে আল্লাহ ছাড়া কোনো ইলাহ নেই এবং আমি সাক্ষ্য দিচ্ছি যে মুহাম্মাদ তাঁর বান্দা ও রাসূল।",
        ur: "تمام تعظیمات، نمازیں اور پاکیزہ باتیں اللہ کے لیے ہیں۔ اے نبی، آپ پر سلام ہو، اللہ کی رحمت اور برکتیں ہوں۔ ہم پر اور اللہ کے نیک بندوں پر سلام ہو۔ میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں اور میں گواہی دیتا ہوں کہ محمد اس کے بندے اور رسول ہیں۔",
        ar: "التحيات لله والصلوات والطيبات. السلام عليك أيها النبي ورحمة الله وبركاته. السلام علينا وعلى عباد الله الصالحين. أشهد أن لا إله إلا الله وأشهد أن محمدًا عبده ورسوله.",
        tr: "Bütün tahiyyatlar, salatlar ve tayyibatlar Allah'a mahsustur. Ey Peygamber, sana selam olsun, Allah'ın rahmeti ve bereketleri üzerine olsun. Selam bizim ve Allah'ın salih kullarının üzerine olsun. Şehadet ederim ki Allah'tan başka ilah yoktur ve şehadet ederim ki Muhammed O'nun kulu ve elçisidir.",
        ms: "Segala penghormatan, solat dan kebaikan adalah untuk Allah. Salam ke atas engkau wahai Nabi dan rahmat Allah serta keberkatannya. Salam ke atas kami dan hamba-hamba Allah yang soleh. Aku bersaksi bahawa tiada tuhan melainkan Allah dan aku bersaksi bahawa Muhammad adalah hamba dan utusan-Nya.",
        id: "Segala penghormatan, shalat dan kebaikan hanya untuk Allah. Salam atasmu wahai Nabi dan rahmat Allah serta keberkahannya. Salam atas kami dan hamba-hamba Allah yang saleh. Aku bersaksi bahwa tiada tuhan selain Allah dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya.",
      },
    },
    // ── Step 14: 3rd Rakat (Fatiha only) ──
    {
      stepNumber: 14,
      action: {
        en: "Say Allahu Akbar and stand for the 3rd Rakat. Recite only Surah Al-Fatiha silently (no additional Surah). Then perform Ruku and two Sajdahs as before.",
        bn: "আল্লাহু আকবার বলে ৩য় রাকাতের জন্য দাঁড়ান। শুধু নীরবে সূরা আল-ফাতিহা পড়ুন (অতিরিক্ত সূরা নেই)। তারপর আগের মতো রুকু ও দুই সেজদা করুন।",
        ur: "اللہ اکبر کہہ کر تیسری رکعت کے لیے کھڑے ہوں۔ آہستہ سے صرف سورۃ الفاتحہ پڑھیں (اضافی سورت نہیں)۔ پھر پہلے کی طرح رکوع اور دو سجدے کریں۔",
        ar: "كبّر وقم للركعة الثالثة. اقرأ الفاتحة فقط سرًّا (بدون سورة إضافية). ثم اركع واسجد سجدتين كالسابق.",
        tr: "Allahu Ekber deyip 3. rekata kalkın. Sadece Fatiha'yı sessizce okuyun (ek sure yok). Sonra önceki gibi rükû ve iki secde yapın.",
        ms: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-3. Baca hanya Surah Al-Fatihah secara senyap (tiada surah tambahan). Kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
        id: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-3. Baca hanya Surah Al-Fatihah secara perlahan (tanpa surah tambahan). Kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সবচেয়ে মহান",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    // ── Step 15: 4th Rakat ──
    {
      stepNumber: 15,
      action: {
        en: "Say Allahu Akbar and stand for the 4th Rakat. Recite only Surah Al-Fatiha silently. Then perform Ruku and two Sajdahs as before.",
        bn: "আল্লাহু আকবার বলে ৪র্থ রাকাতের জন্য দাঁড়ান। শুধু নীরবে সূরা আল-ফাতিহা পড়ুন। তারপর আগের মতো রুকু ও দুই সেজদা করুন।",
        ur: "اللہ اکبر کہہ کر چوتھی رکعت کے لیے کھڑے ہوں۔ آہستہ سے صرف سورۃ الفاتحہ پڑھیں۔ پھر پہلے کی طرح رکوع اور دو سجدے کریں۔",
        ar: "كبّر وقم للركعة الرابعة. اقرأ الفاتحة فقط سرًّا. ثم اركع واسجد سجدتين كالسابق.",
        tr: "Allahu Ekber deyip 4. rekata kalkın. Sadece Fatiha'yı sessizce okuyun. Sonra önceki gibi rükû ve iki secde yapın.",
        ms: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-4. Baca hanya Surah Al-Fatihah secara senyap. Kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
        id: "Ucapkan Allahu Akbar dan berdiri untuk rakaat ke-4. Baca hanya Surah Al-Fatihah secara perlahan. Kemudian lakukan rukuk dan dua sujud seperti sebelumnya.",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সবচেয়ে মহান",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    // ── Step 16: Final Tashahhud, Durood Ibrahim, and Salam ──
    {
      stepNumber: 16,
      action: {
        en: "After the 4th Rakat, sit for the final Tashahhud. Recite At-Tahiyyat, then Durood Ibrahim, then a dua before Salam. Finally, turn your head to the right and say As-salamu Alaikum wa Rahmatullah, then to the left and repeat.",
        bn: "৪র্থ রাকাতের পর শেষ তাশাহহুদের জন্য বসুন। আত-তাহিয়্যাত পড়ুন, তারপর দুরূদ ইবরাহীম, তারপর সালামের পূর্বে দু'আ পড়ুন। অবশেষে, ডানদিকে মুখ ফিরিয়ে আস-সালামু আলাইকুম ওয়া রাহমাতুল্লাহ বলুন, তারপর বামদিকে একই বলুন।",
        ur: "چوتھی رکعت کے بعد آخری تشہد کے لیے بیٹھیں۔ التحیات پڑھیں، پھر درود ابراہیم، پھر سلام سے پہلے دعا پڑھیں۔ آخر میں، دائیں طرف منہ پھیر کر السلام علیکم ورحمۃ اللہ کہیں، پھر بائیں طرف دہرائیں۔",
        ar: "بعد الركعة الرابعة اجلس للتشهد الأخير. اقرأ التحيات ثم الصلاة الإبراهيمية ثم دعاءً قبل السلام. ثم التفت يمينًا وقل السلام عليكم ورحمة الله، ثم يسارًا وأعدها.",
        tr: "4. rekattan sonra son Tahiyyat için oturun. Et-Tahiyyat, ardından Salli-Barik duaları, sonra selamdan önceki duayı okuyun. Son olarak, başınızı sağa çevirip Es-selamu aleykum ve rahmetullah deyin, ardından sola çevirip tekrarlayın.",
        ms: "Selepas rakaat ke-4, duduk untuk Tashahhud akhir. Baca At-Tahiyyat, kemudian Selawat Ibrahimiyyah, kemudian doa sebelum salam. Akhirnya, palingkan kepala ke kanan dan ucapkan As-salamu Alaikum wa Rahmatullah, kemudian ke kiri dan ulangi.",
        id: "Setelah rakaat ke-4, duduk untuk Tashahhud akhir. Baca At-Tahiyyat, kemudian Shalawat Ibrahimiyyah, kemudian doa sebelum salam. Terakhir, palingkan kepala ke kanan dan ucapkan As-salamu Alaikum wa Rahmatullah, kemudian ke kiri dan ulangi.",
      },
      arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ · السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
      transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallayta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin kama barakta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid. As-salamu Alaikum wa Rahmatullah.",
      meaning: {
        en: "O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and upon the family of Ibrahim. You are indeed Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. You are indeed Praiseworthy, Glorious. Peace and mercy of Allah be upon you.",
        bn: "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর রহমত বর্ষণ করুন যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর রহমত বর্ষণ করেছিলেন। নিশ্চয়ই আপনি প্রশংসিত, মহিমান্বিত। হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর বরকত দান করুন যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর বরকত দান করেছিলেন। নিশ্চয়ই আপনি প্রশংসিত, মহিমান্বিত। আপনার উপর আল্লাহর শান্তি ও রহমত বর্ষিত হোক।",
        ur: "اے اللہ، محمد اور آل محمد پر رحمتیں بھیج جیسا کہ تو نے ابراہیم اور آل ابراہیم پر رحمتیں بھیجیں۔ بے شک تو تعریف کیا گیا بزرگی والا ہے۔ اے اللہ، محمد اور آل محمد پر برکتیں نازل فرما جیسا کہ تو نے ابراہیم اور آل ابراہیم پر برکتیں نازل فرمائیں۔ بے شک تو تعریف کیا گیا بزرگی والا ہے۔ تم پر اللہ کی سلامتی اور رحمت ہو۔",
        ar: "اللهم صل على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. السلام عليكم ورحمة الله.",
        tr: "Allah'ım! Muhammed'e ve Muhammed'in ailesine rahmet eyle, İbrahim'e ve İbrahim'in ailesine rahmet ettiğin gibi. Şüphesiz Sen övülmeye layık ve yücesin. Allah'ım! Muhammed'e ve Muhammed'in ailesine bereket ver, İbrahim'e ve İbrahim'in ailesine bereket verdiğin gibi. Şüphesiz Sen övülmeye layık ve yücesin. Allah'ın selamı ve rahmeti üzerinize olsun.",
        ms: "Ya Allah, selawat ke atas Muhammad dan keluarga Muhammad sebagaimana Engkau selawat ke atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkati Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Salam dan rahmat Allah ke atas kamu.",
        id: "Ya Allah, limpahkanlah shalawat atas Muhammad dan keluarga Muhammad sebagaimana Engkau limpahkan shalawat atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, limpahkanlah keberkahan atas Muhammad dan keluarga Muhammad sebagaimana Engkau limpahkan keberkahan atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Salam dan rahmat Allah atas kamu.",
      },
    },
  ],
  specialNotes: {
    en: "Asr is a silent prayer — all recitations are done quietly, without raising the voice. Delaying Asr unnecessarily until near sunset is strongly disliked (Makruh Tahrimi). The Prophet ﷺ said: 'Whoever misses the Asr prayer, it is as if he lost his family and property.' (Sahih al-Bukhari 552). The 4 Sunnah before Fard are Ghair Muakkadah (non-emphasized) and may be omitted, though the Prophet ﷺ encouraged praying them.",
    bn: "আসর একটি নীরব নামাজ — সমস্ত তিলাওয়াত চুপে চুপে করতে হয়, আওয়াজ উঁচু না করে। অকারণে আসরকে সূর্যাস্তের কাছাকাছি বিলম্বিত করা অত্যন্ত অপছন্দনীয় (মাকরূহ তাহরীমী)। নবী ﷺ বলেছেন: 'যে ব্যক্তি আসরের নামাজ ছেড়ে দেয়, সে যেন তার পরিবার ও সম্পদ হারিয়ে ফেলল।' (সহীহ আল-বুখারী ৫৫২)। ফরজের আগে ৪ রাকাত সুন্নাত গায়রে মুআক্কাদাহ (জোরদার নয়) এবং ছেড়ে দেওয়া যায়, তবে নবী ﷺ এগুলো পড়তে উৎসাহিত করেছেন।",
    ur: "عصر ایک آہستہ نماز ہے — تمام تلاوت خاموشی سے کی جاتی ہے، آواز بلند نہیں کی جاتی۔ بلا وجہ عصر کو غروب آفتاب کے قریب تک تاخیر کرنا سخت ناپسندیدہ (مکروہ تحریمی) ہے۔ نبی کریم ﷺ نے فرمایا: 'جس نے عصر کی نماز چھوڑ دی، گویا اس نے اپنے گھر والوں اور مال کو کھو دیا۔' (صحیح البخاری ۵۵۲)۔ فرض سے پہلے ۴ رکعت سنت غیر مؤکدہ ہیں اور چھوڑی جا سکتی ہیں، لیکن نبی ﷺ نے انہیں پڑھنے کی ترغیب دی۔",
    ar: "العصر صلاة سرية — تُقرأ جميع التلاوات بصوت خافت دون رفع الصوت. تأخير العصر بلا عذر إلى قرب غروب الشمس مكروه تحريمًا. قال النبي ﷺ: «من فاتته صلاة العصر فكأنما وُتر أهله وماله» (صحيح البخاري ٥٥٢). السنة القبلية ٤ ركعات غير مؤكدة ويجوز تركها، لكن النبي ﷺ حثّ على أدائها.",
    tr: "İkindi sessiz bir namazdır — tüm kıraatler sessizce, ses yükseltmeden yapılır. İkindiyi gereksiz yere güneş batmaya yaklaşıncaya kadar geciktirmek şiddetle mekruhtur (Mekruh-u Tahrimi). Peygamber Efendimiz ﷺ buyurmuştur: 'Kim ikindi namazını kaçırırsa, ailesini ve malını kaybetmiş gibidir.' (Sahih Buhari 552). Farzdan önceki 4 rekat sünnet Gayri Müekkede'dir (vurgulanmamış) ve terk edilebilir, ancak Peygamber ﷺ kılınmasını teşvik etmiştir.",
    ms: "Asar adalah solat sirr — semua bacaan dilakukan secara senyap, tanpa mengeraskan suara. Melewatkan Asar tanpa sebab sehingga hampir matahari terbenam sangat tidak disukai (Makruh Tahrimi). Nabi ﷺ bersabda: 'Sesiapa yang meninggalkan solat Asar, seolah-olah dia kehilangan keluarga dan hartanya.' (Sahih al-Bukhari 552). 4 rakaat Sunat sebelum Fardu adalah Ghair Muakkad (tidak ditekankan) dan boleh ditinggalkan, namun Nabi ﷺ menggalakkan menunaikannya.",
    id: "Ashar adalah shalat sirr — semua bacaan dilakukan secara perlahan, tanpa mengeraskan suara. Menunda Ashar tanpa alasan hingga mendekati terbenamnya matahari sangat tidak disukai (Makruh Tahrimi). Nabi ﷺ bersabda: 'Barang siapa yang meninggalkan shalat Ashar, seolah-olah dia kehilangan keluarga dan hartanya.' (Sahih al-Bukhari 552). 4 rakaat Sunah sebelum Fardu adalah Ghair Muakkad (tidak ditekankan) dan boleh ditinggalkan, namun Nabi ﷺ menganjurkan untuk menunaikannya.",
  },
};
