import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const DHUHR_PRAYER: PrayerInfo = {
  id: "dhuhr",
  name: { en: "Dhuhr (Zuhr)", bn: "যোহর (জোহর)", ur: "ظہر", ar: "الظهر", tr: "Öğle", ms: "Zuhur", id: "Dzuhur" },
  arabicName: "صلاة الظهر",
  type: "fard",
  category: "daily",
  totalRakats: "12",
  rakatBreakdown: { en: "4 Sunnah + 4 Fard + 2 Sunnah + 2 Nafl", bn: "৪ সুন্নাত + ৪ ফরজ + ২ সুন্নাত + ২ নফল", ur: "۴ سنت + ۴ فرض + ۲ سنت + ۲ نفل", ar: "٤ سنة + ٤ فرض + ٢ سنة + ٢ نفل", tr: "4 Sünnet + 4 Farz + 2 Sünnet + 2 Nafile", ms: "4 Sunat + 4 Fardhu + 2 Sunat + 2 Sunat", id: "4 Sunnah + 4 Fardhu + 2 Sunnah + 2 Nafl" },
  time: { en: "After the sun passes its zenith until the shadow of an object equals its length", bn: "সূর্য মাথার উপর থেকে হেলে পড়ার পর থেকে আসরের আগ পর্যন্ত", ur: "سورج ڈھلنے سے عصر سے پہلے تک", ar: "من زوال الشمس إلى أن يصير ظل كل شيء مثله", tr: "Güneşin zenitinden geçmesinden gölge boyuna eşit olana kadar", ms: "Selepas matahari melepasi zenith sehingga bayang sama panjang", id: "Setelah matahari melewati zenit hingga bayangan sama panjang" },
  description: { en: "Dhuhr is the midday prayer with 4 Fard rakats. It is prayed silently. On Fridays, Dhuhr is replaced by Jummah prayer for men in congregation.", bn: "যোহর দুপুরের নামাজ, ৪ রাকাত ফরজ। এটি চুপে চুপে পড়া হয়। শুক্রবার পুরুষদের জন্য জুমার নামাজ যোহরের পরিবর্তে আদায় করা হয়।", ur: "ظہر دوپہر کی نماز ہے جس میں ۴ رکعت فرض ہیں۔ یہ آہستہ پڑھی جاتی ہے۔ جمعے کو مردوں کے لیے جمعہ کی نماز ظہر کی جگہ ادا کی جاتی ہے۔", ar: "الظهر هي صلاة الزوال وفيها ٤ ركعات فرض. تُقرأ سراً. يوم الجمعة تُستبدل بصلاة الجمعة للرجال في الجماعة.", tr: "Öğle namazı 4 rekat farz olan öğlen namazıdır. Sessiz kılınır. Cuma günleri erkekler için Cuma namazı ile değiştirilir.", ms: "Zuhur adalah solat tengah hari dengan 4 rakaat fardhu. Ia dibaca secara senyap. Pada hari Jumaat, Zuhur digantikan dengan solat Jumaat untuk lelaki.", id: "Dzuhur adalah shalat tengah hari dengan 4 rakaat fardhu. Dibaca secara pelan. Pada hari Jumat, Dzuhur digantikan shalat Jumat untuk laki-laki." },
  steps: [
    // 1. Niyyah
    { stepNumber: 1, action: { en: "Stand facing Qibla and make intention for 4 Fard rakats of Dhuhr", bn: "কিবলামুখী দাঁড়ান এবং যোহরের ৪ রাকাত ফরজের নিয়ত করুন", ur: "قبلہ رخ کھڑے ہوں اور ظہر کی ۴ رکعت فرض کی نیت کریں", ar: "قف مستقبلاً القبلة وانوِ صلاة أربع ركعات فرض الظهر", tr: "Kıbleye dönüp Öğle'nin 4 rekat farzı için niyet edin", ms: "Berdiri menghadap Kiblat dan niat 4 rakaat fardhu Zuhur", id: "Berdiri menghadap Kiblat dan niat 4 rakaat fardhu Dzuhur" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // 2. Takbiratul Ihram
    { stepNumber: 2, action: { en: "Raise hands to ear level and say Takbir", bn: "দুই হাত কান বরাবর উঠান এবং তাকবীর বলুন", ur: "ہاتھ کانوں تک اٹھائیں اور تکبیر کہیں", ar: "ارفع يديك حذو أذنيك وكبّر", tr: "Ellerinizi kulak hizasına kaldırıp tekbir getirin", ms: "Angkat tangan ke paras telinga dan ucapkan takbir", id: "Angkat tangan ke telinga dan ucapkan takbir" }, arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", meaning: { en: "Allah is the Greatest", bn: "আল্লাহ সবচেয়ে মহান", ur: "اللہ سب سے بڑا ہے", ar: "الله أكبر", tr: "Allah en büyüktür", ms: "Allah Maha Besar", id: "Allah Maha Besar" } },
    // 3. Thana
    { stepNumber: 3, action: { en: "Fold hands and recite Thana (opening dua) silently", bn: "হাত বাঁধুন এবং চুপে চুপে সানা পড়ুন", ur: "ہاتھ باندھیں اور آہستہ ثنا پڑھیں", ar: "ضع يديك واقرأ دعاء الاستفتاح سراً", tr: "Ellerinizi bağlayıp sessizce Sena okuyun", ms: "Lipat tangan dan baca doa iftitah secara senyap", id: "Lipat tangan dan baca doa iftitah secara diam" }, arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ", transliteration: "Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta'ala jadduka, wa la ilaha ghairuk", meaning: { en: "Glory be to You O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, and there is no god but You.", bn: "হে আল্লাহ! তুমি পবিত্র, তোমার প্রশংসা সহ। তোমার নাম বরকতময়, তোমার মর্যাদা সুউচ্চ, তুমি ছাড়া কোনো ইলাহ নেই।", ur: "اے اللہ! تو پاک ہے تیری حمد کے ساتھ، تیرا نام بابرکت ہے، تیری شان بلند ہے، تیرے سوا کوئی معبود نہیں۔", ar: "سبحانك اللهم وبحمدك وتبارك اسمك وتعالى جدك ولا إله غيرك", tr: "Allah'ım! Sen münezzehsin, hamdınla. İsmin mübarektir, şanın yücedir, Senden başka ilah yoktur.", ms: "Maha Suci Engkau ya Allah, dengan segala puji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu, tiada Tuhan selain Engkau.", id: "Maha Suci Engkau ya Allah, dengan segala puji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu, tiada Tuhan selain Engkau." } },
    // 4. Ta'awwudh + Bismillah
    { stepNumber: 4, action: { en: "Recite Ta'awwudh and Bismillah", bn: "আউযুবিল্লাহ ও বিসমিল্লাহ পড়ুন", ur: "تعوذ اور بسملہ پڑھیں", ar: "اقرأ التعوذ والبسملة", tr: "Eûzü ve Besmele okuyun", ms: "Baca ta'awwudz dan bismillah", id: "Baca ta'awwudz dan bismillah" }, arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ ، بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", transliteration: "A'udhu billahi minash-shaitanir-rajeem. Bismillahir-Rahmanir-Raheem", meaning: { en: "I seek refuge in Allah from the accursed Satan. In the name of Allah, the Most Gracious, the Most Merciful.", bn: "আমি বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় চাই। পরম করুণাময় অতি দয়ালু আল্লাহর নামে।", ur: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں۔ اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔", ar: "أعوذ بالله من الشيطان الرجيم. بسم الله الرحمن الرحيم", tr: "Kovulmuş şeytandan Allah'a sığınırım. Rahman ve Rahim olan Allah'ın adıyla.", ms: "Aku berlindung dengan Allah dari syaitan yang terkutuk. Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang.", id: "Aku berlindung kepada Allah dari setan yang terkutuk. Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang." } },
    // 5. Fatiha
    { stepNumber: 5, action: { en: "Recite Surah Al-Fatiha silently, say Ameen at the end", bn: "চুপে চুপে সূরা ফাতিহা পড়ুন, শেষে আমীন বলুন", ur: "آہستہ سورۃ الفاتحہ پڑھیں، آخر میں آمین کہیں", ar: "اقرأ سورة الفاتحة سراً وقل آمين في نهايتها", tr: "Fatiha Suresi'ni sessizce okuyun, sonunda Amin deyin", ms: "Baca Surah Al-Fatihah secara senyap, ucapkan Amin di akhir", id: "Baca Surah Al-Fatihah secara diam, ucapkan Amin di akhir" }, arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ... وَلَا الضَّالِّينَ ، آمِين", transliteration: "Alhamdu lillahi Rabbil 'aalameen ... wa lad-daalleen. Ameen", meaning: { en: "All praise is for Allah, Lord of all worlds ... nor those who went astray. Ameen (Accept our prayer).", bn: "সমস্ত প্রশংসা আল্লাহর, সকল জগতের রব ... এবং পথভ্রষ্টদের পথে নয়। আমীন।", ur: "تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا رب ہے ... نہ گمراہوں کا۔ آمین۔", ar: "الحمد لله رب العالمين ... ولا الضالين. آمين", tr: "Hamd Alemlerin Rabbi Allah'a mahsustur ... ne de sapıtanların. Amin.", ms: "Segala puji bagi Allah Tuhan sekalian alam ... bukan mereka yang sesat. Amin.", id: "Segala puji bagi Allah Tuhan seluruh alam ... bukan mereka yang sesat. Amin." } },
    // 6. Another Surah
    { stepNumber: 6, action: { en: "Recite another Surah (in 1st and 2nd rakat only)", bn: "আরেকটি সূরা পড়ুন (শুধু ১ম ও ২য় রাকাতে)", ur: "ایک اور سورت پڑھیں (صرف پہلی اور دوسری رکعت میں)", ar: "اقرأ سورة أخرى (في الركعتين الأولى والثانية فقط)", tr: "Başka bir sure okuyun (sadece 1. ve 2. rekatta)", ms: "Baca surah lain (hanya pada rakaat 1 dan 2)", id: "Baca surah lain (hanya pada rakaat 1 dan 2)" }, arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ...", transliteration: "Qul Huwal-lahu Ahad ... (or any other Surah)", meaning: { en: "Say: He is Allah, the One... (or any other Surah of your choice)", bn: "বলুন: তিনি আল্লাহ, এক... (অথবা আপনার পছন্দের যেকোনো সূরা)", ur: "کہو: وہ اللہ ہے، ایک... (یا آپ کی پسند کی کوئی سورت)", ar: "قل هو الله أحد... (أو أي سورة أخرى تختارها)", tr: "De ki: O Allah'tır, bir tektir... (veya başka bir sure)", ms: "Katakanlah: Dialah Allah Yang Maha Esa... (atau surah pilihan anda)", id: "Katakanlah: Dialah Allah Yang Maha Esa... (atau surah pilihan Anda)" } },
    // 7. Ruku
    { stepNumber: 7, action: { en: "Say Allahu Akbar and go into Ruku (bow) — recite 3 times", bn: "আল্লাহু আকবার বলে রুকুতে যান — ৩ বার পড়ুন", ur: "اللہ اکبر کہہ کر رکوع میں جائیں — ۳ بار پڑھیں", ar: "كبّر واركع — كرر ثلاث مرات", tr: "Allahu Ekber deyip rükuya eğilin — 3 kez okuyun", ms: "Ucapkan Allahu Akbar dan rukuk — baca 3 kali", id: "Ucapkan Allahu Akbar dan rukuk — baca 3 kali" }, arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ", transliteration: "Subhana Rabbiyal-Adheem (3 times)", meaning: { en: "Glory be to my Lord, the Most Great", bn: "আমার মহান রবের পবিত্রতা ঘোষণা করছি", ur: "پاک ہے میرا رب بڑی عظمت والا", ar: "سبحان ربي العظيم", tr: "Yüce Rabbimi tesbih ederim", ms: "Maha Suci Tuhanku Yang Maha Agung", id: "Maha Suci Tuhanku Yang Maha Agung" } },
    // 8. Stand from Ruku
    { stepNumber: 8, action: { en: "Stand up from Ruku", bn: "রুকু থেকে সোজা হয়ে দাঁড়ান", ur: "رکوع سے سیدھے کھڑے ہوں", ar: "قم من الركوع", tr: "Rükudan doğrulun", ms: "Bangun dari rukuk", id: "Bangun dari rukuk" }, arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ ، رَبَّنَا لَكَ الْحَمْدُ", transliteration: "Sami'Allahu liman hamidah. Rabbana lakal hamd.", meaning: { en: "Allah hears whoever praises Him. Our Lord, all praise is for You.", bn: "যে আল্লাহর প্রশংসা করে আল্লাহ তার কথা শোনেন। হে আমাদের রব, সকল প্রশংসা তোমার।", ur: "اللہ نے سنا جس نے اس کی حمد کی۔ اے ہمارے رب، تمام تعریف تیرے لیے ہے۔", ar: "سمع الله لمن حمده. ربنا لك الحمد", tr: "Allah hamd edenin hamdini işitir. Rabbimiz, hamd Sana mahsustur.", ms: "Allah mendengar pujian orang yang memuji-Nya. Wahai Tuhan kami, segala puji bagi-Mu.", id: "Allah mendengar pujian orang yang memuji-Nya. Ya Tuhan kami, segala puji bagi-Mu." } },
    // 9. First Sajdah
    { stepNumber: 9, action: { en: "Go into Sajdah (prostration) saying Allahu Akbar — recite 3 times", bn: "আল্লাহু আকবার বলে সিজদায় যান — ৩ বার পড়ুন", ur: "اللہ اکبر کہہ کر سجدے میں جائیں — ۳ بار پڑھیں", ar: "اسجد مكبّراً — كرر ثلاث مرات", tr: "Allahu Ekber deyip secdeye gidin — 3 kez okuyun", ms: "Sujud ucapkan Allahu Akbar — baca 3 kali", id: "Sujud ucapkan Allahu Akbar — baca 3 kali" }, arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ", transliteration: "Subhana Rabbiyal-A'la (3 times)", meaning: { en: "Glory be to my Lord, the Most High", bn: "আমার সর্বোচ্চ রবের পবিত্রতা ঘোষণা করছি", ur: "پاک ہے میرا رب سب سے بلند", ar: "سبحان ربي الأعلى", tr: "Yüce Rabbimi tesbih ederim", ms: "Maha Suci Tuhanku Yang Maha Tinggi", id: "Maha Suci Tuhanku Yang Maha Tinggi" } },
    // 10. Sit between sajdahs
    { stepNumber: 10, action: { en: "Sit briefly between two Sajdahs", bn: "দুই সিজদার মাঝে সংক্ষেপে বসুন", ur: "دو سجدوں کے درمیان بیٹھیں", ar: "اجلس بين السجدتين", tr: "İki secde arasında kısa oturun", ms: "Duduk sebentar antara dua sujud", id: "Duduk sebentar antara dua sujud" }, arabic: "رَبِّ اغْفِرْ لِي", transliteration: "Rabbighfir li", meaning: { en: "My Lord, forgive me", bn: "হে আমার রব, আমাকে ক্ষমা করুন", ur: "اے میرے رب مجھے بخش دے", ar: "رب اغفر لي", tr: "Rabbim, beni bağışla", ms: "Ya Tuhanku, ampunkan aku", id: "Ya Tuhanku, ampunkan aku" } },
    // 11. Second Sajdah
    { stepNumber: 11, action: { en: "Second Sajdah — same as the first", bn: "দ্বিতীয় সিজদা — প্রথমটির মতো", ur: "دوسرا سجدہ — پہلے کی طرح", ar: "السجدة الثانية — كالأولى", tr: "İkinci secde — birincisi gibi", ms: "Sujud kedua — sama seperti pertama", id: "Sujud kedua — sama seperti pertama" }, arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ", transliteration: "Subhana Rabbiyal-A'la (3 times)", meaning: { en: "Glory be to my Lord, the Most High", bn: "আমার সর্বোচ্চ রবের পবিত্রতা ঘোষণা করছি", ur: "پاک ہے میرا رب سب سے بلند", ar: "سبحان ربي الأعلى", tr: "Yüce Rabbimi tesbih ederim", ms: "Maha Suci Tuhanku Yang Maha Tinggi", id: "Maha Suci Tuhanku Yang Maha Tinggi" } },
    // 12. Stand for 2nd rakat
    { stepNumber: 12, action: { en: "Stand for 2nd rakat — repeat Fatiha + Surah + Ruku + Sajdahs", bn: "২য় রাকাতের জন্য দাঁড়ান — ফাতিহা + সূরা + রুকু + সিজদা পুনরাবৃত্তি করুন", ur: "دوسری رکعت کے لیے کھڑے ہوں — فاتحہ + سورت + رکوع + سجدے دہرائیں", ar: "قم للركعة الثانية — كرر الفاتحة + سورة + ركوع + سجود", tr: "2. rekat için kalkın — Fatiha + Sure + Rüku + Secdeler tekrarlayın", ms: "Berdiri untuk rakaat ke-2 — ulang Fatihah + Surah + Rukuk + Sujud", id: "Berdiri untuk rakaat ke-2 — ulangi Fatihah + Surah + Rukuk + Sujud" }, arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", meaning: { en: "Allah is the Greatest", bn: "আল্লাহ সবচেয়ে মহান", ur: "اللہ سب سے بڑا ہے", ar: "الله أكبر", tr: "Allah en büyüktür", ms: "Allah Maha Besar", id: "Allah Maha Besar" } },
    // 13. First Tashahhud (Qa'dah Ula) after 2nd rakat
    { stepNumber: 13, action: { en: "After 2nd rakat's Sajdahs, sit for first Tashahhud (Qa'dah Ula)", bn: "২য় রাকাতের সিজদার পর প্রথম তাশাহহুদের (কা'দায়ে ঊলা) জন্য বসুন", ur: "دوسری رکعت کے سجدوں کے بعد پہلے تشہد (قعدہ اولیٰ) کے لیے بیٹھیں", ar: "بعد سجود الركعة الثانية اجلس للتشهد الأول (القعدة الأولى)", tr: "2. rekatın secdelerinden sonra ilk Tahiyyat için oturun", ms: "Selepas sujud rakaat ke-2, duduk untuk Tahiyyat pertama (Qa'dah Ula)", id: "Setelah sujud rakaat ke-2, duduk untuk Tahiyyat pertama (Qa'dah Ula)" }, arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ ... أَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat ... Ash-hadu anna Muhammadan 'abduhu wa rasuluh.", meaning: { en: "All greetings, prayers, and good deeds are for Allah ... I bear witness that Muhammad is His servant and messenger.", bn: "সকল সম্মান, নামাজ ও পবিত্র কথা আল্লাহর জন্য ... আমি সাক্ষ্য দিচ্ছি মুহাম্মাদ তাঁর বান্দা ও রাসূল।", ur: "تمام تعظیمات، نمازیں اور پاکیزہ باتیں اللہ کے لیے ہیں ... میں گواہی دیتا ہوں کہ محمد اس کے بندے اور رسول ہیں۔", ar: "التحيات لله والصلوات والطيبات ... أشهد أن محمداً عبده ورسوله", tr: "Tahiyyat Allah'a, salavat ve tayyibat da O'nadır ... Muhammed O'nun kulu ve elçisidir.", ms: "Segala penghormatan bagi Allah, segala solat dan segala yang baik ... Muhammad itu hamba-Nya dan Rasul-Nya.", id: "Segala penghormatan bagi Allah, segala shalat dan segala yang baik ... Muhammad itu hamba-Nya dan Rasul-Nya." } },
    // 14. Stand for 3rd rakat
    { stepNumber: 14, action: { en: "Stand for 3rd rakat — recite only Surah Al-Fatiha (no additional Surah)", bn: "৩য় রাকাতের জন্য দাঁড়ান — শুধু সূরা ফাতিহা পড়ুন (অতিরিক্ত সূরা নেই)", ur: "تیسری رکعت کے لیے کھڑے ہوں — صرف سورۃ الفاتحہ پڑھیں (اضافی سورت نہیں)", ar: "قم للركعة الثالثة — اقرأ الفاتحة فقط (بدون سورة إضافية)", tr: "3. rekat için kalkın — sadece Fatiha okuyun (ek sure yok)", ms: "Berdiri untuk rakaat ke-3 — baca hanya Surah Al-Fatihah (tiada surah tambahan)", id: "Berdiri untuk rakaat ke-3 — baca hanya Surah Al-Fatihah (tanpa surah tambahan)" }, arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", meaning: { en: "Allah is the Greatest", bn: "আল্লাহ সবচেয়ে মহান", ur: "اللہ سب سے بڑا ہے", ar: "الله أكبر", tr: "Allah en büyüktür", ms: "Allah Maha Besar", id: "Allah Maha Besar" } },
    // 15. Complete 3rd rakat with Ruku + Sajdahs, then stand for 4th rakat (same as 3rd)
    { stepNumber: 15, action: { en: "Complete Ruku + Sajdahs for 3rd rakat, then stand for 4th rakat (same — only Fatiha)", bn: "৩য় রাকাতের রুকু + সিজদা সম্পন্ন করুন, তারপর ৪র্থ রাকাতে দাঁড়ান (একই — শুধু ফাতিহা)", ur: "تیسری رکعت کا رکوع + سجدے مکمل کریں، پھر چوتھی رکعت کے لیے کھڑے ہوں (وہی — صرف فاتحہ)", ar: "أكمل ركوع وسجود الركعة الثالثة ثم قم للرابعة (نفس الطريقة — الفاتحة فقط)", tr: "3. rekatın Rüku + Secdelerini tamamlayın, 4. rekat için kalkın (aynı — sadece Fatiha)", ms: "Selesaikan Rukuk + Sujud rakaat ke-3, berdiri untuk rakaat ke-4 (sama — hanya Fatihah)", id: "Selesaikan Rukuk + Sujud rakaat ke-3, berdiri untuk rakaat ke-4 (sama — hanya Fatihah)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // 16. Final Tashahhud + Durood + Dua + Salam
    { stepNumber: 16, action: { en: "After 4th rakat's Sajdahs, sit for final Tashahhud + Durood Ibrahim + Dua + Salam", bn: "৪র্থ রাকাতের সিজদার পর চূড়ান্ত তাশাহহুদ + দরূদ ইবরাহীম + দু'আ + সালাম", ur: "چوتھی رکعت کے سجدوں کے بعد آخری تشہد + درود ابراہیم + دعا + سلام", ar: "بعد سجود الركعة الرابعة اجلس للتشهد الأخير + الصلاة الإبراهيمية + الدعاء + السلام", tr: "4. rekatın secdelerinden sonra son Tahiyyat + Salli-Barik + Dua + Selam", ms: "Selepas sujud rakaat ke-4, duduk untuk Tahiyyat akhir + Selawat Ibrahim + Doa + Salam", id: "Setelah sujud rakaat ke-4, duduk untuk Tahiyyat akhir + Shalawat Ibrahim + Doa + Salam" }, arabic: "التَّحِيَّاتُ ... اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ ... السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", transliteration: "At-tahiyyatu ... Allahumma salli 'ala Muhammad ... Assalamu 'alaikum wa rahmatullah", meaning: { en: "Tashahhud + Durood Ibrahim + Salam to right and left", bn: "তাশাহহুদ + দরূদ ইবরাহীম + ডানে ও বামে সালাম", ur: "تشہد + درود ابراہیم + دائیں اور بائیں سلام", ar: "التشهد + الصلاة الإبراهيمية + السلام يميناً ويساراً", tr: "Tahiyyat + Salli-Barik + Sağa ve sola selam", ms: "Tahiyyat + Selawat Ibrahim + Salam ke kanan dan kiri", id: "Tahiyyat + Shalawat Ibrahim + Salam ke kanan dan kiri" } },
  ],
  specialNotes: { en: "Dhuhr is a silent (Sirriyyah) prayer — all recitations are done quietly. On Fridays, Dhuhr is replaced by Jummah prayer for men who attend the congregation.", bn: "যোহর একটি নীরব (সিররিয়্যাহ) নামাজ — সকল কিরাত চুপে চুপে পড়া হয়। শুক্রবার পুরুষদের জন্য জামাতে উপস্থিত হলে জুমার নামাজ যোহরের স্থলে আদায় করা হয়।", ur: "ظہر ایک آہستہ (سری) نماز ہے — تمام تلاوت آہستہ کی جاتی ہے۔ جمعے کو مردوں کے لیے جمعے کی نماز ظہر کی جگہ ادا ہوتی ہے۔", ar: "صلاة الظهر سرية — جميع القراءات تُؤدى بصوت منخفض. يوم الجمعة تُستبدل بصلاة الجمعة للرجال.", tr: "Öğle namazı sessiz (sirrî) kılınır — tüm kıraatler sessizce yapılır. Cuma günleri erkekler için Cuma namazı ile değiştirilir.", ms: "Zuhur adalah solat senyap (sirriyyah) — semua bacaan dibaca secara senyap. Pada hari Jumaat, Zuhur digantikan solat Jumaat untuk lelaki.", id: "Dzuhur adalah shalat pelan (sirriyyah) — semua bacaan dibaca secara pelan. Pada hari Jumat, Dzuhur digantikan shalat Jumat untuk laki-laki." },
};
