import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const ISHA_PRAYER: PrayerInfo = {
  id: "isha",
  name: {
    en: "Isha",
    bn: "ইশা",
    ur: "عشاء",
    ar: "العشاء",
    tr: "Yatsı",
    ms: "Isyak",
    id: "Isya",
  },
  arabicName: "صلاة العشاء",
  type: "fard",
  category: "daily",
  totalRakats: "15",
  rakatBreakdown: {
    en: "4 Sunnah + 4 Fard + 2 Sunnah + 2 Nafl + 3 Witr",
    bn: "৪ সুন্নত + ৪ ফরজ + ২ সুন্নত + ২ নফল + ৩ বিতর",
    ur: "۴ سنت + ۴ فرض + ۲ سنت + ۲ نفل + ۳ وتر",
    ar: "٤ سنة + ٤ فرض + ٢ سنة + ٢ نفل + ٣ وتر",
    tr: "4 Sünnet + 4 Farz + 2 Sünnet + 2 Nafile + 3 Vitir",
    ms: "4 Sunat + 4 Fardu + 2 Sunat + 2 Sunat + 3 Witir",
    id: "4 Sunah + 4 Fardu + 2 Sunah + 2 Nafilah + 3 Witir",
  },
  time: {
    en: "After twilight disappears until midnight (or before Fajr)",
    bn: "গোধূলি অদৃশ্য হওয়ার পর থেকে মধ্যরাত পর্যন্ত (অথবা ফজরের আগে)",
    ur: "شفق غائب ہونے کے بعد سے آدھی رات تک (یا فجر سے پہلے)",
    ar: "بعد غياب الشفق إلى منتصف الليل (أو قبل الفجر)",
    tr: "Şafak kaybolduktan sonra gece yarısına kadar (veya Fecir'den önce)",
    ms: "Selepas mega merah hilang sehingga tengah malam (atau sebelum Subuh)",
    id: "Setelah mega merah hilang hingga tengah malam (atau sebelum Subuh)",
  },
  description: {
    en: "Isha is the fifth and final daily prayer, performed after twilight has completely disappeared. It consists of 4 Sunnah, 4 Fard (recited aloud in the first 2 rakats), 2 Sunnah, 2 Nafl, and 3 Witr.",
    bn: "ইশা হলো পঞ্চম ও শেষ দৈনিক নামাজ, যা গোধূলি সম্পূর্ণ অদৃশ্য হওয়ার পর আদায় করা হয়। এতে ৪ রাকাত সুন্নত, ৪ রাকাত ফরজ (প্রথম ২ রাকাতে সশব্দে পড়া হয়), ২ রাকাত সুন্নত, ২ রাকাত নফল এবং ৩ রাকাত বিতর রয়েছে।",
    ur: "عشاء پانچویں اور آخری روزانہ نماز ہے، جو شفق مکمل طور پر غائب ہونے کے بعد پڑھی جاتی ہے۔ اس میں ۴ سنت، ۴ فرض (پہلی ۲ رکعتوں میں بلند آواز سے)، ۲ سنت، ۲ نفل اور ۳ وتر شامل ہیں۔",
    ar: "العشاء هي الصلاة اليومية الخامسة والأخيرة، تُؤدَّى بعد غياب الشفق تماماً. تتكون من ٤ ركعات سنة، و٤ ركعات فرض (يُجهَر بالقراءة في الركعتين الأوليين)، و٢ ركعات سنة، و٢ ركعات نفل، و٣ ركعات وتر.",
    tr: "Yatsı, akşam kızıllığı tamamen kaybolduktan sonra kılınan beşinci ve son günlük namazdır. 4 Sünnet, 4 Farz (ilk 2 rekâtta sesli okunur), 2 Sünnet, 2 Nafile ve 3 Vitir olmak üzere toplam 15 rekâttır.",
    ms: "Isyak adalah solat harian kelima dan terakhir, dilakukan selepas mega merah hilang sepenuhnya. Ia terdiri daripada 4 Sunat, 4 Fardu (dibaca dengan suara kuat pada 2 rakaat pertama), 2 Sunat, 2 Sunat dan 3 Witir.",
    id: "Isya adalah shalat harian kelima dan terakhir, dilaksanakan setelah mega merah hilang sepenuhnya. Terdiri dari 4 Sunah, 4 Fardu (dibaca dengan suara keras pada 2 rakaat pertama), 2 Sunah, 2 Nafilah, dan 3 Witir.",
  },
  steps: [
    // Step 1: Niyyah (Intention)
    {
      stepNumber: 1,
      action: {
        en: "Stand facing the Qiblah and make the intention (Niyyah) in your heart to pray 4 rakats Fard of Isha",
        bn: "কিবলামুখী হয়ে দাঁড়ান এবং অন্তরে ইশার ৪ রাকাত ফরজ নামাজের নিয়ত করুন",
        ur: "قبلہ رخ کھڑے ہوں اور دل میں عشاء کی ۴ رکعت فرض نماز کی نیت کریں",
        ar: "قِف مستقبلاً القبلة وانوِ في قلبك صلاة ٤ ركعات فرض العشاء",
        tr: "Kıbleye dönüp durun ve kalbinizden Yatsı namazının 4 rekât farzına niyet edin",
        ms: "Berdiri menghadap kiblat dan niat dalam hati untuk solat 4 rakaat Fardu Isyak",
        id: "Berdiri menghadap kiblat dan niat dalam hati untuk shalat 4 rakaat Fardu Isya",
      },
      arabic: "",
      transliteration: "",
      meaning: {
        en: "",
        bn: "",
        ur: "",
        ar: "",
        tr: "",
        ms: "",
        id: "",
      },
    },
    // Step 2: Takbiratul Ihram
    {
      stepNumber: 2,
      action: {
        en: "Raise both hands to ear level and say the Takbiratul Ihram",
        bn: "দুই হাত কান পর্যন্ত উঠান এবং তাকবীরে তাহরীমা বলুন",
        ur: "دونوں ہاتھ کانوں تک اٹھائیں اور تکبیرِ تحریمہ کہیں",
        ar: "ارفع يديك حذو أذنيك وكبّر تكبيرة الإحرام",
        tr: "İki elinizi kulak hizasına kaldırın ve Tekbiratul İhram söyleyin",
        ms: "Angkat kedua tangan ke paras telinga dan lafazkan Takbiratul Ihram",
        id: "Angkat kedua tangan ke telinga dan ucapkan Takbiratul Ihram",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সর্বশ্রেষ্ঠ",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    // Step 3: Place hands and recite Thana
    {
      stepNumber: 3,
      action: {
        en: "Place your right hand over the left on your chest (or below the navel per Hanafi) and recite the opening supplication (Thana)",
        bn: "ডান হাত বাম হাতের উপর বুকে (অথবা হানাফী মতে নাভির নিচে) রাখুন এবং সানা পড়ুন",
        ur: "دایاں ہاتھ بائیں پر سینے پر (یا حنفی کے مطابق ناف کے نیچے) رکھیں اور ثنا پڑھیں",
        ar: "ضع يدك اليمنى على اليسرى فوق صدرك (أو تحت السُّرّة عند الحنفية) واقرأ دعاء الاستفتاح (الثناء)",
        tr: "Sağ elinizi sol elinizin üzerine göğsünüze (veya Hanefi'ye göre göbek altına) koyun ve Sübhaneke duasını okuyun",
        ms: "Letakkan tangan kanan di atas tangan kiri di dada (atau di bawah pusat mengikut Hanafi) dan baca doa Iftitah (Sana)",
        id: "Letakkan tangan kanan di atas tangan kiri di dada (atau di bawah pusar menurut Hanafi) dan baca doa Iftitah (Sana)",
      },
      arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ",
      transliteration: "Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta'ala jadduka, wa la ilaha ghairuk",
      meaning: {
        en: "Glory be to You, O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, and there is no god but You.",
        bn: "হে আল্লাহ! আপনার পবিত্রতা ঘোষণা করছি এবং আপনার প্রশংসা করছি। আপনার নাম বরকতময়, আপনার মর্যাদা সুউচ্চ এবং আপনি ছাড়া কোনো ইলাহ নেই।",
        ur: "اے اللہ! تیری پاکی بیان کرتا ہوں اور تیری حمد کرتا ہوں۔ تیرا نام بابرکت ہے، تیری شان بلند ہے اور تیرے سوا کوئی معبود نہیں۔",
        ar: "سبحانك اللهم وبحمدك، تبارك اسمك، وتعالى جدّك، ولا إله غيرك.",
        tr: "Seni tespih ederim Allah'ım ve Sana hamd ederim. Senin adın mübarektir, şanın yücedir ve Senden başka ilah yoktur.",
        ms: "Maha Suci Engkau ya Allah dan dengan memuji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu dan tiada Tuhan selain Engkau.",
        id: "Maha Suci Engkau ya Allah dan dengan memuji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu dan tiada Tuhan selain Engkau.",
      },
    },
    // Step 4: Ta'awwudh and Bismillah
    {
      stepNumber: 4,
      action: {
        en: "Recite Ta'awwudh and Bismillah silently",
        bn: "তাআউয ও বিসমিল্লাহ নীরবে পড়ুন",
        ur: "تعوذ اور بسملہ آہستہ پڑھیں",
        ar: "اقرأ التعوّذ والبسملة سرّاً",
        tr: "Eûzü ve Besmele'yi sessizce okuyun",
        ms: "Baca Ta'awwudh dan Bismillah secara senyap",
        id: "Baca Ta'awwudh dan Bismillah secara pelan",
      },
      arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\nبِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      transliteration: "A'udhu billahi minash-shaytanir-rajim\nBismillahir-Rahmanir-Rahim",
      meaning: {
        en: "I seek refuge in Allah from the accursed Satan.\nIn the name of Allah, the Most Gracious, the Most Merciful.",
        bn: "আমি বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় চাই।\nপরম করুণাময় অসীম দয়ালু আল্লাহর নামে।",
        ur: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں۔\nاللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔",
        ar: "أعوذ بالله من الشيطان الرجيم.\nبسم الله الرحمن الرحيم.",
        tr: "Kovulmuş şeytandan Allah'a sığınırım.\nRahman ve Rahim olan Allah'ın adıyla.",
        ms: "Aku berlindung dengan Allah dari syaitan yang terkutuk.\nDengan nama Allah yang Maha Pemurah lagi Maha Penyayang.",
        id: "Aku berlindung kepada Allah dari setan yang terkutuk.\nDengan nama Allah yang Maha Pengasih lagi Maha Penyayang.",
      },
    },
    // Step 5: Recite Surah Al-Fatiha ALOUD (1st rakat)
    {
      stepNumber: 5,
      action: {
        en: "Recite Surah Al-Fatiha ALOUD (this is the 1st rakat)",
        bn: "সশব্দে সূরা আল-ফাতিহা পড়ুন (এটি ১ম রাকাত)",
        ur: "سورۃ الفاتحہ بلند آواز سے پڑھیں (یہ پہلی رکعت ہے)",
        ar: "اقرأ سورة الفاتحة جهراً (هذه الركعة الأولى)",
        tr: "Fatiha Suresi'ni SESLİ okuyun (bu 1. rekâttır)",
        ms: "Baca Surah Al-Fatihah dengan KUAT (ini rakaat pertama)",
        id: "Baca Surah Al-Fatihah dengan KERAS (ini rakaat pertama)",
      },
      arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ﴿١﴾ الرَّحْمَٰنِ الرَّحِيمِ ﴿٢﴾ مَالِكِ يَوْمِ الدِّينِ ﴿٣﴾ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ﴿٤﴾ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ﴿٥﴾ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ ﴿٦﴾",
      transliteration: "Al-hamdu lillahi Rabbil-'alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na'budu wa iyyaka nasta'in. Ihdinas-siratal-mustaqim. Siratal-ladhina an'amta 'alaihim, ghairil-maghdubi 'alaihim wa lad-dallin.",
      meaning: {
        en: "All praise is for Allah, Lord of all worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us on the Straight Path. The path of those You have blessed, not of those who earned anger, nor of those who went astray.",
        bn: "সমস্ত প্রশংসা আল্লাহর, যিনি সকল জগতের প্রতিপালক। পরম করুণাময়, অসীম দয়ালু। বিচার দিবসের মালিক। আমরা কেবল আপনারই ইবাদত করি এবং কেবল আপনারই কাছে সাহায্য চাই। আমাদের সরল পথে পরিচালিত করুন। তাদের পথে যাদের আপনি অনুগ্রহ করেছেন, তাদের পথে নয় যাদের উপর গজব পড়েছে এবং তাদের পথেও নয় যারা পথভ্রষ্ট।",
        ur: "تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا رب ہے۔ بڑا مہربان نہایت رحم والا۔ روزِ جزا کا مالک۔ ہم صرف تیری ہی عبادت کرتے ہیں اور صرف تجھ سے ہی مدد مانگتے ہیں۔ ہمیں سیدھا راستہ دکھا۔ ان لوگوں کا راستہ جن پر تو نے انعام کیا، نہ ان کا جن پر غضب ہوا اور نہ گمراہوں کا۔",
        ar: "الحمد لله رب العالمين. الرحمن الرحيم. مالك يوم الدين. إياك نعبد وإياك نستعين. اهدنا الصراط المستقيم. صراط الذين أنعمت عليهم غير المغضوب عليهم ولا الضالين.",
        tr: "Hamd, âlemlerin Rabbi Allah'a mahsustur. Rahman ve Rahim olan. Din gününün sahibi. Yalnız Sana kulluk eder, yalnız Senden yardım dileriz. Bizi dosdoğru yola ilet. Kendilerine nimet verdiklerinin yoluna; gazaba uğrayanların ve sapıtanların yoluna değil.",
        ms: "Segala puji bagi Allah, Tuhan sekalian alam. Yang Maha Pemurah lagi Maha Penyayang. Pemilik hari pembalasan. Hanya Engkau yang kami sembah dan hanya kepada Engkau kami memohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang yang Engkau beri nikmat, bukan jalan mereka yang dimurkai dan bukan jalan mereka yang sesat.",
        id: "Segala puji bagi Allah, Tuhan seluruh alam. Yang Maha Pengasih lagi Maha Penyayang. Pemilik hari pembalasan. Hanya kepada-Mu kami menyembah dan hanya kepada-Mu kami memohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang yang Engkau beri nikmat, bukan jalan mereka yang dimurkai dan bukan jalan mereka yang sesat.",
      },
    },
    // Step 6: Recite an additional Surah ALOUD
    {
      stepNumber: 6,
      action: {
        en: "Recite an additional Surah or verses ALOUD (e.g. Surah Al-Ikhlas)",
        bn: "সশব্দে একটি অতিরিক্ত সূরা বা আয়াত পড়ুন (যেমন সূরা আল-ইখলাস)",
        ur: "بلند آواز سے ایک اضافی سورت یا آیات پڑھیں (مثلاً سورۃ الاخلاص)",
        ar: "اقرأ سورة أو آيات إضافية جهراً (مثل سورة الإخلاص)",
        tr: "Ek bir sure veya ayetleri SESLİ okuyun (örneğin İhlâs Suresi)",
        ms: "Baca surah atau ayat tambahan dengan KUAT (contoh: Surah Al-Ikhlas)",
        id: "Baca surah atau ayat tambahan dengan KERAS (contoh: Surah Al-Ikhlas)",
      },
      arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ﴿١﴾ اللَّهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ﴿٤﴾",
      transliteration: "Qul huwa Allahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
      meaning: {
        en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. And there is none comparable to Him.",
        bn: "বলুন: তিনি আল্লাহ, এক। আল্লাহ অমুখাপেক্ষী। তিনি কাউকে জন্ম দেননি এবং তাঁকেও জন্ম দেওয়া হয়নি। এবং তাঁর সমতুল্য কেউ নেই।",
        ur: "کہو: وہ اللہ ہے، ایک۔ اللہ بے نیاز ہے۔ نہ اس نے کسی کو جنا اور نہ وہ جنا گیا۔ اور اس کا کوئی ہمسر نہیں۔",
        ar: "قل هو الله أحد. الله الصمد. لم يلد ولم يولد. ولم يكن له كفواً أحد.",
        tr: "De ki: O Allah birdir. Allah Samed'dir. Doğurmamıştır ve doğurulmamıştır. Hiçbir şey O'nun dengi değildir.",
        ms: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada sesuatu pun yang setara dengan-Nya.",
        id: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada sesuatu pun yang setara dengan-Nya.",
      },
    },
    // Step 7: Ruku (Bowing)
    {
      stepNumber: 7,
      action: {
        en: "Say Allahu Akbar and go into Ruku (bowing), placing hands on knees, back straight",
        bn: "আল্লাহু আকবার বলে রুকুতে যান, হাত হাঁটুতে রাখুন, পিঠ সোজা রাখুন",
        ur: "اللہ اکبر کہتے ہوئے رکوع میں جائیں، ہاتھ گھٹنوں پر رکھیں، کمر سیدھی رکھیں",
        ar: "كبّر واركع واضعاً يديك على ركبتيك مع استواء الظهر",
        tr: "Allahu Ekber diyerek rükûya gidin, ellerinizi dizlerinize koyun, sırtınız düz olsun",
        ms: "Sebut Allahu Akbar dan pergi ke Rukuk, letakkan tangan di lutut, belakang lurus",
        id: "Ucapkan Allahu Akbar dan pergi ke Rukuk, letakkan tangan di lutut, punggung lurus",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
      transliteration: "Subhana Rabbiyal-'Azim (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most Great",
        bn: "আমার মহান প্রতিপালকের পবিত্রতা ঘোষণা করছি",
        ur: "میرے عظیم رب کی پاکی بیان کرتا ہوں",
        ar: "سبحان ربي العظيم",
        tr: "Yüce Rabbimi tespih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Agung",
        id: "Maha Suci Tuhanku Yang Maha Agung",
      },
    },
    // Step 8: Rising from Ruku
    {
      stepNumber: 8,
      action: {
        en: "Rise from Ruku while saying Sami'Allahu liman hamidah, then say Rabbana lakal hamd while standing upright",
        bn: "সামিআল্লাহু লিমান হামিদাহ বলে রুকু থেকে উঠুন, সোজা দাঁড়িয়ে রাব্বানা লাকাল হামদ বলুন",
        ur: "سمع اللہ لمن حمدہ کہتے ہوئے رکوع سے اٹھیں، سیدھے کھڑے ہو کر ربنا لک الحمد کہیں",
        ar: "ارفع من الركوع قائلاً سمع الله لمن حمده، ثم قل ربنا ولك الحمد وأنت معتدل قائماً",
        tr: "Semiallahu limen hamideh diyerek rükûdan kalkın, dikilip Rabbena lekel hamd deyin",
        ms: "Bangun dari Rukuk sambil membaca Sami'Allahu liman hamidah, kemudian sebut Rabbana lakal hamd sambil berdiri tegak",
        id: "Bangun dari Rukuk sambil membaca Sami'Allahu liman hamidah, kemudian ucapkan Rabbana lakal hamd sambil berdiri tegak",
      },
      arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ\nرَبَّنَا وَلَكَ الْحَمْدُ",
      transliteration: "Sami'Allahu liman hamidah\nRabbana wa lakal hamd",
      meaning: {
        en: "Allah hears whoever praises Him.\nOur Lord, to You belongs all praise.",
        bn: "যে আল্লাহর প্রশংসা করে আল্লাহ তার কথা শোনেন।\nহে আমাদের প্রতিপালক, সমস্ত প্রশংসা আপনার জন্য।",
        ur: "اللہ نے اس کی سنی جس نے اس کی حمد کی۔\nاے ہمارے رب، تمام تعریف تیرے لیے ہے۔",
        ar: "سمع الله لمن حمده.\nربنا ولك الحمد.",
        tr: "Allah kendisine hamd edeni işitir.\nRabbimiz, hamd Sana mahsustur.",
        ms: "Allah mendengar sesiapa yang memuji-Nya.\nWahai Tuhan kami, bagi-Mu segala puji.",
        id: "Allah mendengar siapa yang memuji-Nya.\nWahai Tuhan kami, bagi-Mu segala puji.",
      },
    },
    // Step 9: First Sujud (Prostration)
    {
      stepNumber: 9,
      action: {
        en: "Say Allahu Akbar and prostrate (Sujud). Place forehead, nose, both palms, both knees, and toes on the ground",
        bn: "আল্লাহু আকবার বলে সিজদায় যান। কপাল, নাক, দুই হাতের তালু, দুই হাঁটু ও পায়ের আঙুল মাটিতে রাখুন",
        ur: "اللہ اکبر کہتے ہوئے سجدے میں جائیں۔ پیشانی، ناک، دونوں ہتھیلیاں، دونوں گھٹنے اور پاؤں کی انگلیاں زمین پر رکھیں",
        ar: "كبّر واسجد. ضع جبهتك وأنفك وكفّيك وركبتيك وأطراف أصابع قدميك على الأرض",
        tr: "Allahu Ekber diyerek secdeye gidin. Alın, burun, iki avuç, iki diz ve ayak parmakları yere değsin",
        ms: "Sebut Allahu Akbar dan sujud. Letakkan dahi, hidung, kedua tapak tangan, kedua lutut dan hujung jari kaki di atas tanah",
        id: "Ucapkan Allahu Akbar dan sujud. Letakkan dahi, hidung, kedua telapak tangan, kedua lutut dan ujung jari kaki di atas tanah",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
      transliteration: "Subhana Rabbiyal-A'la (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most High",
        bn: "আমার সর্বোচ্চ প্রতিপালকের পবিত্রতা ঘোষণা করছি",
        ur: "میرے بلند و بالا رب کی پاکی بیان کرتا ہوں",
        ar: "سبحان ربي الأعلى",
        tr: "En yüce Rabbimi tespih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi",
        id: "Maha Suci Tuhanku Yang Maha Tinggi",
      },
    },
    // Step 10: Sitting between two Sujuds
    {
      stepNumber: 10,
      action: {
        en: "Rise from Sujud saying Allahu Akbar and sit briefly between the two prostrations",
        bn: "আল্লাহু আকবার বলে সিজদা থেকে উঠুন এবং দুই সিজদার মাঝে সংক্ষেপে বসুন",
        ur: "اللہ اکبر کہتے ہوئے سجدے سے اٹھیں اور دو سجدوں کے درمیان مختصر بیٹھیں",
        ar: "ارفع من السجود مكبّراً واجلس بين السجدتين",
        tr: "Allahu Ekber diyerek secdeden kalkın ve iki secde arasında kısa süre oturun",
        ms: "Bangun dari sujud sambil membaca Allahu Akbar dan duduk sebentar antara dua sujud",
        id: "Bangun dari sujud sambil membaca Allahu Akbar dan duduk sebentar antara dua sujud",
      },
      arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
      transliteration: "Rabbighfir li, Rabbighfir li",
      meaning: {
        en: "My Lord, forgive me. My Lord, forgive me.",
        bn: "হে আমার প্রতিপালক, আমাকে ক্ষমা করুন। হে আমার প্রতিপালক, আমাকে ক্ষমা করুন।",
        ur: "اے میرے رب، مجھے معاف کر۔ اے میرے رب، مجھے معاف کر۔",
        ar: "رب اغفر لي، رب اغفر لي.",
        tr: "Rabbim beni bağışla. Rabbim beni bağışla.",
        ms: "Tuhanku, ampunilah aku. Tuhanku, ampunilah aku.",
        id: "Tuhanku, ampunilah aku. Tuhanku, ampunilah aku.",
      },
    },
    // Step 11: Second Sujud
    {
      stepNumber: 11,
      action: {
        en: "Perform the second Sujud saying Allahu Akbar, recite the same as the first Sujud",
        bn: "আল্লাহু আকবার বলে দ্বিতীয় সিজদা করুন, প্রথম সিজদার মতো একই পড়ুন",
        ur: "اللہ اکبر کہتے ہوئے دوسرا سجدہ کریں، پہلے سجدے کی طرح وہی پڑھیں",
        ar: "اسجد السجدة الثانية مكبّراً واقرأ كما في السجدة الأولى",
        tr: "Allahu Ekber diyerek ikinci secdeye gidin, birinci secdedeki gibi okuyun",
        ms: "Lakukan sujud kedua sambil membaca Allahu Akbar, baca seperti sujud pertama",
        id: "Lakukan sujud kedua sambil membaca Allahu Akbar, baca seperti sujud pertama",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
      transliteration: "Subhana Rabbiyal-A'la (3 times)",
      meaning: {
        en: "Glory be to my Lord, the Most High",
        bn: "আমার সর্বোচ্চ প্রতিপালকের পবিত্রতা ঘোষণা করছি",
        ur: "میرے بلند و بالا رب کی پاکی بیان کرتا ہوں",
        ar: "سبحان ربي الأعلى",
        tr: "En yüce Rabbimi tespih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi",
        id: "Maha Suci Tuhanku Yang Maha Tinggi",
      },
    },
    // Step 12: Stand for 2nd Rakat (aloud)
    {
      stepNumber: 12,
      action: {
        en: "Stand up for the 2nd rakat saying Allahu Akbar. Recite Surah Al-Fatiha ALOUD followed by another Surah ALOUD",
        bn: "আল্লাহু আকবার বলে ২য় রাকাতের জন্য দাঁড়ান। সশব্দে সূরা আল-ফাতিহা এবং আরেকটি সূরা সশব্দে পড়ুন",
        ur: "اللہ اکبر کہتے ہوئے دوسری رکعت کے لیے کھڑے ہوں۔ سورۃ الفاتحہ بلند آواز سے اور ایک اور سورت بلند آواز سے پڑھیں",
        ar: "قم للركعة الثانية مكبّراً. اقرأ سورة الفاتحة جهراً ثم سورة أخرى جهراً",
        tr: "Allahu Ekber diyerek 2. rekâta kalkın. Fatiha Suresi'ni SESLİ ve ardından başka bir sureyi SESLİ okuyun",
        ms: "Berdiri untuk rakaat ke-2 sambil membaca Allahu Akbar. Baca Surah Al-Fatihah dengan KUAT diikuti surah lain dengan KUAT",
        id: "Berdiri untuk rakaat ke-2 sambil membaca Allahu Akbar. Baca Surah Al-Fatihah dengan KERAS diikuti surah lain dengan KERAS",
      },
      arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\n﴿الْفَاتِحَة + سُورَة﴾",
      transliteration: "Bismillahir-Rahmanir-Rahim + Al-Fatiha + another Surah",
      meaning: {
        en: "Recite Al-Fatiha and another Surah aloud, then perform Ruku, rise, and two Sujuds as before",
        bn: "সশব্দে আল-ফাতিহা ও আরেকটি সূরা পড়ুন, তারপর আগের মতো রুকু, দাঁড়ানো ও দুই সিজদা করুন",
        ur: "بلند آواز سے الفاتحہ اور ایک اور سورت پڑھیں، پھر پہلے کی طرح رکوع، قیام اور دو سجدے کریں",
        ar: "اقرأ الفاتحة وسورة أخرى جهراً، ثم اركع وارفع واسجد سجدتين كما سبق",
        tr: "Fatiha'yı ve başka bir sureyi sesli okuyun, sonra önceki gibi rükû, kalkış ve iki secde yapın",
        ms: "Baca Al-Fatihah dan surah lain dengan kuat, kemudian lakukan Rukuk, berdiri dan dua sujud seperti sebelumnya",
        id: "Baca Al-Fatihah dan surah lain dengan keras, kemudian lakukan Rukuk, berdiri dan dua sujud seperti sebelumnya",
      },
    },
    // Step 13: First Tashahhud (after 2nd rakat)
    {
      stepNumber: 13,
      action: {
        en: "After the 2nd Sujud of the 2nd rakat, sit for the first Tashahhud (At-Tahiyyat)",
        bn: "২য় রাকাতের ২য় সিজদার পর প্রথম তাশাহহুদের (আত-তাহিয়্যাত) জন্য বসুন",
        ur: "دوسری رکعت کے دوسرے سجدے کے بعد پہلے تشہد (التحیات) کے لیے بیٹھیں",
        ar: "بعد السجدة الثانية من الركعة الثانية اجلس للتشهد الأول (التحيات)",
        tr: "2. rekâtın 2. secdesinden sonra ilk Teşehhüd (Ettehiyyatü) için oturun",
        ms: "Selepas sujud kedua rakaat ke-2, duduk untuk Tashahhud pertama (At-Tahiyyat)",
        id: "Setelah sujud kedua rakaat ke-2, duduk untuk Tashahhud pertama (At-Tahiyyat)",
      },
      arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
      transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu 'alaika ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alaina wa 'ala 'ibadillahis-salihin. Ash-hadu an la ilaha illallahu wa ash-hadu anna Muhammadan 'abduhu wa rasuluh.",
      meaning: {
        en: "All greetings, prayers, and good deeds are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger.",
        bn: "সকল সম্মান, সালাত ও পবিত্র কথা আল্লাহর জন্য। হে নবী, আপনার উপর শান্তি, আল্লাহর রহমত ও বরকত বর্ষিত হোক। আমাদের উপর এবং আল্লাহর নেক বান্দাদের উপর শান্তি বর্ষিত হোক। আমি সাক্ষ্য দিচ্ছি যে আল্লাহ ছাড়া কোনো ইলাহ নেই এবং আমি সাক্ষ্য দিচ্ছি যে মুহাম্মাদ তাঁর বান্দা ও রাসূল।",
        ur: "تمام تعظیمات، نمازیں اور پاکیزہ باتیں اللہ کے لیے ہیں۔ اے نبی، آپ پر سلام ہو، اللہ کی رحمت اور اس کی برکتیں ہوں۔ ہم پر اور اللہ کے نیک بندوں پر سلام ہو۔ میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں اور میں گواہی دیتا ہوں کہ محمد اس کے بندے اور رسول ہیں۔",
        ar: "التحيات لله والصلوات والطيبات. السلام عليك أيها النبي ورحمة الله وبركاته. السلام علينا وعلى عباد الله الصالحين. أشهد أن لا إله إلا الله وأشهد أن محمداً عبده ورسوله.",
        tr: "Bütün tahiyyatlar, namazlar ve güzel sözler Allah içindir. Ey Peygamber, sana selam olsun, Allah'ın rahmeti ve bereketi üzerine olsun. Bize ve Allah'ın salih kullarına selam olsun. Şehadet ederim ki Allah'tan başka ilah yoktur ve şehadet ederim ki Muhammed O'nun kulu ve elçisidir.",
        ms: "Segala penghormatan, solat dan kebaikan adalah untuk Allah. Salam ke atas kamu wahai Nabi dan rahmat Allah serta keberkatannya. Salam ke atas kami dan hamba-hamba Allah yang soleh. Aku bersaksi bahawa tiada Tuhan melainkan Allah dan aku bersaksi bahawa Muhammad itu hamba-Nya dan Rasul-Nya.",
        id: "Segala penghormatan, shalat dan kebaikan adalah untuk Allah. Salam atas kamu wahai Nabi dan rahmat Allah serta keberkatannya. Salam atas kami dan hamba-hamba Allah yang saleh. Aku bersaksi bahwa tiada Tuhan selain Allah dan aku bersaksi bahwa Muhammad itu hamba-Nya dan Rasul-Nya.",
      },
    },
    // Step 14: Stand for 3rd Rakat (silent)
    {
      stepNumber: 14,
      action: {
        en: "Stand up for the 3rd rakat saying Allahu Akbar. Recite only Surah Al-Fatiha SILENTLY",
        bn: "আল্লাহু আকবার বলে ৩য় রাকাতের জন্য দাঁড়ান। কেবল সূরা আল-ফাতিহা নীরবে পড়ুন",
        ur: "اللہ اکبر کہتے ہوئے تیسری رکعت کے لیے کھڑے ہوں۔ صرف سورۃ الفاتحہ آہستہ پڑھیں",
        ar: "قم للركعة الثالثة مكبّراً. اقرأ سورة الفاتحة فقط سرّاً",
        tr: "Allahu Ekber diyerek 3. rekâta kalkın. Yalnızca Fatiha Suresi'ni SESSİZCE okuyun",
        ms: "Berdiri untuk rakaat ke-3 sambil membaca Allahu Akbar. Baca hanya Surah Al-Fatihah secara SENYAP",
        id: "Berdiri untuk rakaat ke-3 sambil membaca Allahu Akbar. Baca hanya Surah Al-Fatihah secara PELAN",
      },
      arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\n﴿الْفَاتِحَة﴾",
      transliteration: "Bismillahir-Rahmanir-Rahim + Al-Fatiha only",
      meaning: {
        en: "Recite only Al-Fatiha silently, then perform Ruku, rise, and two Sujuds as before",
        bn: "কেবল আল-ফাতিহা নীরবে পড়ুন, তারপর আগের মতো রুকু, দাঁড়ানো ও দুই সিজদা করুন",
        ur: "صرف الفاتحہ آہستہ پڑھیں، پھر پہلے کی طرح رکوع، قیام اور دو سجدے کریں",
        ar: "اقرأ الفاتحة فقط سرّاً، ثم اركع وارفع واسجد سجدتين كما سبق",
        tr: "Yalnızca Fatiha'yı sessizce okuyun, sonra önceki gibi rükû, kalkış ve iki secde yapın",
        ms: "Baca Al-Fatihah sahaja secara senyap, kemudian lakukan Rukuk, berdiri dan dua sujud seperti sebelumnya",
        id: "Baca Al-Fatihah saja secara pelan, kemudian lakukan Rukuk, berdiri dan dua sujud seperti sebelumnya",
      },
    },
    // Step 15: Stand for 4th Rakat (silent)
    {
      stepNumber: 15,
      action: {
        en: "Stand up for the 4th rakat saying Allahu Akbar. Recite only Surah Al-Fatiha SILENTLY, then perform Ruku and two Sujuds",
        bn: "আল্লাহু আকবার বলে ৪র্থ রাকাতের জন্য দাঁড়ান। কেবল সূরা আল-ফাতিহা নীরবে পড়ুন, তারপর রুকু ও দুই সিজদা করুন",
        ur: "اللہ اکبر کہتے ہوئے چوتھی رکعت کے لیے کھڑے ہوں۔ صرف سورۃ الفاتحہ آہستہ پڑھیں، پھر رکوع اور دو سجدے کریں",
        ar: "قم للركعة الرابعة مكبّراً. اقرأ سورة الفاتحة فقط سرّاً ثم اركع واسجد سجدتين",
        tr: "Allahu Ekber diyerek 4. rekâta kalkın. Yalnızca Fatiha Suresi'ni SESSİZCE okuyun, ardından rükû ve iki secde yapın",
        ms: "Berdiri untuk rakaat ke-4 sambil membaca Allahu Akbar. Baca hanya Surah Al-Fatihah secara SENYAP, kemudian lakukan Rukuk dan dua sujud",
        id: "Berdiri untuk rakaat ke-4 sambil membaca Allahu Akbar. Baca hanya Surah Al-Fatihah secara PELAN, kemudian lakukan Rukuk dan dua sujud",
      },
      arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\n﴿الْفَاتِحَة﴾",
      transliteration: "Bismillahir-Rahmanir-Rahim + Al-Fatiha only",
      meaning: {
        en: "Recite only Al-Fatiha silently, perform Ruku and two Sujuds, then sit for the final Tashahhud",
        bn: "কেবল আল-ফাতিহা নীরবে পড়ুন, রুকু ও দুই সিজদা করুন, তারপর শেষ তাশাহহুদের জন্য বসুন",
        ur: "صرف الفاتحہ آہستہ پڑھیں، رکوع اور دو سجدے کریں، پھر آخری تشہد کے لیے بیٹھیں",
        ar: "اقرأ الفاتحة فقط سرّاً، اركع واسجد سجدتين، ثم اجلس للتشهد الأخير",
        tr: "Yalnızca Fatiha'yı sessizce okuyun, rükû ve iki secde yapın, sonra son Teşehhüd için oturun",
        ms: "Baca Al-Fatihah sahaja secara senyap, lakukan Rukuk dan dua sujud, kemudian duduk untuk Tashahhud akhir",
        id: "Baca Al-Fatihah saja secara pelan, lakukan Rukuk dan dua sujud, kemudian duduk untuk Tashahhud akhir",
      },
    },
    // Step 16: Final Tashahhud, Durood Ibrahim, Dua, and Salam
    {
      stepNumber: 16,
      action: {
        en: "Sit for the final Tashahhud: recite At-Tahiyyat, then Durood Ibrahim (Salawat), then a Dua, and end with Salam to both sides",
        bn: "শেষ তাশাহহুদের জন্য বসুন: আত-তাহিয়্যাত পড়ুন, তারপর দুরূদ ইবরাহীম (সালাওয়াত), তারপর দু'আ পড়ুন এবং উভয় দিকে সালাম দিয়ে শেষ করুন",
        ur: "آخری تشہد کے لیے بیٹھیں: التحیات پڑھیں، پھر درود ابراہیم (صلوات)، پھر دعا پڑھیں اور دونوں طرف سلام پھیر کر ختم کریں",
        ar: "اجلس للتشهد الأخير: اقرأ التحيات ثم الصلاة الإبراهيمية ثم الدعاء ثم سلّم عن يمينك وعن شمالك",
        tr: "Son Teşehhüd için oturun: Ettehiyyatü, Salli-Barik (Salâvat), ardından dua okuyun ve iki tarafa selam vererek bitirin",
        ms: "Duduk untuk Tashahhud akhir: baca At-Tahiyyat, kemudian Selawat Ibrahim, kemudian doa, dan akhiri dengan Salam ke kedua belah pihak",
        id: "Duduk untuk Tashahhud akhir: baca At-Tahiyyat, kemudian Shalawat Ibrahim, kemudian doa, dan akhiri dengan Salam ke kedua sisi",
      },
      arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ\n\nالسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
      transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallaita 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin kama barakta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid.\n\nAs-salamu 'alaikum wa rahmatullah",
      meaning: {
        en: "O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious.\n\nPeace and mercy of Allah be upon you. (Turn head right, then left)",
        bn: "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর রহমত বর্ষণ করুন, যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর রহমত বর্ষণ করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত। হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর বরকত দান করুন, যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর বরকত দান করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত।\n\nআপনার উপর শান্তি ও আল্লাহর রহমত বর্ষিত হোক। (প্রথমে ডানে, তারপর বামে মাথা ঘোরান)",
        ur: "اے اللہ، محمد اور آلِ محمد پر رحمتیں بھیج جیسے تو نے ابراہیم اور آلِ ابراہیم پر رحمتیں بھیجیں۔ بیشک تو قابلِ تعریف بزرگی والا ہے۔ اے اللہ، محمد اور آلِ محمد پر برکتیں نازل فرما جیسے تو نے ابراہیم اور آلِ ابراہیم پر برکتیں نازل فرمائیں۔ بیشک تو قابلِ تعریف بزرگی والا ہے۔\n\nتم پر اللہ کی سلامتی اور رحمت ہو۔ (پہلے دائیں پھر بائیں سر پھیریں)",
        ar: "اللهم صلِّ على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد.\n\nالسلام عليكم ورحمة الله. (التفت يميناً ثم يساراً)",
        tr: "Allah'ım, Muhammed'e ve Muhammed'in ailesine rahmet eyle; İbrahim'e ve İbrahim'in ailesine rahmet ettiğin gibi. Şüphesiz Sen övülmüş ve yücesin. Allah'ım, Muhammed'e ve Muhammed'in ailesine bereket ver; İbrahim'e ve İbrahim'in ailesine bereket verdiğin gibi. Şüphesiz Sen övülmüş ve yücesin.\n\nAllah'ın selamı ve rahmeti üzerinize olsun. (Önce sağa, sonra sola selam verin)",
        ms: "Ya Allah, selawat ke atas Muhammad dan keluarga Muhammad sebagaimana Engkau selawat ke atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkati Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.\n\nSemoga keselamatan dan rahmat Allah ke atas kamu. (Paling ke kanan kemudian ke kiri)",
        id: "Ya Allah, limpahkanlah shalawat atas Muhammad dan keluarga Muhammad sebagaimana Engkau limpahkan shalawat atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkati Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.\n\nSemoga keselamatan dan rahmat Allah atas kamu. (Menoleh ke kanan kemudian ke kiri)",
      },
    },
  ],
  specialNotes: {
    en: "Isha is recited aloud (Jahr) in the first 2 rakats of the Fard prayer. Witr is Wajib (according to the Hanafi school) and should be prayed after Isha. The time for Isha extends until before Fajr, but it is best to pray before midnight.",
    bn: "ইশার ফরজ নামাজের প্রথম ২ রাকাতে সশব্দে (জাহর) কিরাত পড়া হয়। বিতর নামাজ ওয়াজিব (হানাফী মাযহাব অনুযায়ী) এবং ইশার পর পড়তে হয়। ইশার সময় ফজরের আগ পর্যন্ত বিস্তৃত, তবে মধ্যরাতের আগে পড়া উত্তম।",
    ur: "عشاء کی فرض نماز کی پہلی ۲ رکعتوں میں بلند آواز (جہر) سے قراءت کی جاتی ہے۔ وتر واجب ہے (حنفی مسلک کے مطابق) اور عشاء کے بعد پڑھی جانی چاہیے۔ عشاء کا وقت فجر سے پہلے تک ہے، لیکن آدھی رات سے پہلے پڑھنا بہتر ہے۔",
    ar: "تُقرأ صلاة العشاء جهراً في الركعتين الأوليين من صلاة الفرض. صلاة الوتر واجبة (عند الحنفية) وتُصلَّى بعد العشاء. يمتد وقت العشاء إلى ما قبل الفجر، ولكن الأفضل أن تُصلَّى قبل منتصف الليل.",
    tr: "Yatsı namazının farz kısmında ilk 2 rekâtta kıraat sesli (cehrî) okunur. Vitir namazı vaciptir (Hanefi mezhebine göre) ve Yatsı'dan sonra kılınmalıdır. Yatsı namazının vakti Fecir'den önceye kadar uzanır, ancak gece yarısından önce kılınması daha faziletlidir.",
    ms: "Solat Isyak dibaca dengan suara kuat (Jahr) pada 2 rakaat pertama solat Fardu. Solat Witir adalah Wajib (menurut mazhab Hanafi) dan perlu dilakukan selepas Isyak. Waktu Isyak berlanjutan sehingga sebelum Subuh, tetapi lebih baik solat sebelum tengah malam.",
    id: "Shalat Isya dibaca dengan suara keras (Jahr) pada 2 rakaat pertama shalat Fardu. Shalat Witir adalah Wajib (menurut mazhab Hanafi) dan harus dilaksanakan setelah Isya. Waktu Isya berlanjut hingga sebelum Subuh, tetapi lebih baik shalat sebelum tengah malam.",
  },
};
