import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const JANAZAH_PRAYER: PrayerInfo = {
  id: "janazah",
  name: { en: "Janazah (Funeral)", bn: "জানাযা (দাফন)", ur: "جنازہ (نمازِ جنازہ)", ar: "صلاة الجنازة", tr: "Cenaze Namazı", ms: "Solat Jenazah", id: "Shalat Jenazah" },
  arabicName: "صلاة الجنازة",
  type: "fard",
  category: "special",
  totalRakats: "No Ruku/Sajdah — 4 Takbirs standing",
  rakatBreakdown: { en: "4 Takbirs — entirely standing, no Ruku or Sajdah", bn: "৪ তাকবীর — সম্পূর্ণ দাঁড়িয়ে, কোনো রুকু বা সিজদা নেই", ur: "۴ تکبیریں — مکمل طور پر کھڑے ہو کر، کوئی رکوع یا سجدہ نہیں", ar: "٤ تكبيرات — وقوفاً بالكامل، بلا ركوع أو سجود", tr: "4 Tekbir — tamamen ayakta, rüku veya secde yok", ms: "4 Takbir — sepenuhnya berdiri, tiada rukuk atau sujud", id: "4 Takbir — sepenuhnya berdiri, tidak ada rukuk atau sujud" },
  time: { en: "Anytime (when a Muslim passes away)", bn: "যেকোনো সময় (কোনো মুসলিম মারা গেলে)", ur: "کسی بھی وقت (جب کوئی مسلمان فوت ہو)", ar: "في أي وقت (عند وفاة مسلم)", tr: "Herhangi bir zaman (bir Müslüman vefat ettiğinde)", ms: "Bila-bila masa (apabila seorang Muslim meninggal dunia)", id: "Kapan saja (ketika seorang Muslim meninggal dunia)" },
  description: { en: "Janazah prayer is Fard Kifayah — a communal obligation. If some Muslims perform it, the obligation is fulfilled for all. It is performed entirely standing, with no Ruku or Sajdah, and consists of 4 Takbirs.", bn: "জানাযা নামাজ ফরজে কিফায়া — সামষ্টিক দায়িত্ব। কিছু মুসলিম আদায় করলে সকলের দায়িত্ব পূরণ হয়। এটি সম্পূর্ণ দাঁড়িয়ে আদায় করা হয়, কোনো রুকু বা সিজদা নেই এবং ৪টি তাকবীর দিয়ে গঠিত।", ur: "نمازِ جنازہ فرضِ کفایہ ہے — اجتماعی فریضہ۔ اگر کچھ مسلمان ادا کریں تو سب کی ذمہ داری پوری ہو جاتی ہے۔ یہ مکمل طور پر کھڑے ہو کر ادا کی جاتی ہے، کوئی رکوع یا سجدہ نہیں، اور ۴ تکبیرات پر مشتمل ہے۔", ar: "صلاة الجنازة فرض كفاية — فريضة جماعية. إذا أداها بعض المسلمين سقطت عن الباقين. تُؤدّى وقوفاً بالكامل بلا ركوع أو سجود، وتتكون من ٤ تكبيرات.", tr: "Cenaze namazı Farz-ı Kifaye'dir — toplumsal bir farzdır. Bazı Müslümanlar kılarsa diğerlerinden sorumluluk düşer. Tamamen ayakta kılınır, rüku ve secde yoktur, 4 tekbirden oluşur.", ms: "Solat Jenazah adalah Fardhu Kifayah — kewajipan bersama. Jika sebahagian Muslim menunaikannya, kewajipan gugur bagi semua. Ia dilakukan sepenuhnya berdiri, tiada rukuk atau sujud, dan terdiri daripada 4 takbir.", id: "Shalat Jenazah adalah Fardhu Kifayah — kewajiban kolektif. Jika sebagian Muslim menunaikannya, kewajiban gugur bagi semua. Dilakukan sepenuhnya berdiri, tidak ada rukuk atau sujud, dan terdiri dari 4 takbir." },
  steps: [
    // Step 1: Stand facing Qibla
    {
      stepNumber: 1,
      action: { en: "Stand facing Qibla with the body of the deceased placed in front. Make intention (Niyyah) for Janazah prayer.", bn: "কিবলামুখী দাঁড়ান, মৃত ব্যক্তির দেহ সামনে রাখুন। জানাযা নামাজের নিয়ত করুন।", ur: "قبلہ رخ کھڑے ہوں، میت کی لاش سامنے ہو۔ نمازِ جنازہ کی نیت کریں۔", ar: "قف مستقبلاً القبلة وجثمان الميت أمامك. انوِ صلاة الجنازة.", tr: "Kıbleye dönüp cenaze önünüzde olacak şekilde durun. Cenaze namazı için niyet edin.", ms: "Berdiri menghadap Kiblat dengan jenazah di hadapan. Niat solat Jenazah.", id: "Berdiri menghadap Kiblat dengan jenazah di depan. Niat shalat Jenazah." },
      arabic: "",
      transliteration: "",
      meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" },
    },
    // Step 2: 1st Takbir — Thana
    {
      stepNumber: 2,
      action: { en: "Say the 1st Takbir (Allahu Akbar), fold hands and recite Thana (Subhanaka Allahumma…)", bn: "১ম তাকবীর (আল্লাহু আকবার) বলুন, হাত বাঁধুন এবং সানা পড়ুন (সুবহানাকা আল্লাহুম্মা…)", ur: "پہلی تکبیر (اللہ اکبر) کہیں، ہاتھ باندھیں اور ثنا پڑھیں (سبحانک اللہم…)", ar: "كبّر التكبيرة الأولى (الله أكبر)، ضع يديك واقرأ الثناء (سبحانك اللهم…)", tr: "1. tekbiri getirin (Allahu Ekber), elleri bağlayıp Sena okuyun (Sübhaneke Allahumme…)", ms: "Ucapkan takbir pertama (Allahu Akbar), lipat tangan dan baca Thana (Subhanaka Allahumma…)", id: "Ucapkan takbir pertama (Allahu Akbar), lipat tangan dan baca Thana (Subhanaka Allahumma…)" },
      arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَجَلَّ ثَنَاؤُكَ وَلَا إِلَٰهَ غَيْرُكَ",
      transliteration: "Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta'ala jadduka, wa jalla thana'uka, wa la ilaha ghairuk",
      meaning: { en: "Glory be to You O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, lofty is Your praise, and there is no god but You.", bn: "হে আল্লাহ! তুমি পবিত্র, তোমার প্রশংসা সহ। তোমার নাম বরকতময়, তোমার মর্যাদা সুউচ্চ, তোমার প্রশংসা মহান, তুমি ছাড়া কোনো ইলাহ নেই।", ur: "اے اللہ! تو پاک ہے اور تیری حمد ہے۔ تیرا نام بابرکت ہے، تیری شان بلند ہے، تیری ثنا عظیم ہے، اور تیرے سوا کوئی معبود نہیں۔", ar: "سبحانك اللهم وبحمدك وتبارك اسمك وتعالى جدك وجلّ ثناؤك ولا إله غيرك", tr: "Allah'ım! Sen münezzehsin, hamdınla. İsmin mübarektir, şanın yücedir, senân uludur, Senden başka ilah yoktur.", ms: "Maha Suci Engkau ya Allah, dengan segala puji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu, Maha Mulia pujian-Mu, tiada Tuhan selain Engkau.", id: "Maha Suci Engkau ya Allah, dengan segala puji-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu, Maha Mulia pujian-Mu, tiada Tuhan selain Engkau." },
    },
    // Step 3: 2nd Takbir — Durood Ibrahim
    {
      stepNumber: 3,
      action: { en: "Say the 2nd Takbir (Allahu Akbar) and recite Durood Ibrahim (Salawat upon the Prophet ﷺ)", bn: "২য় তাকবীর (আল্লাহু আকবার) বলুন এবং দরূদ ইবরাহীম পড়ুন (নবী ﷺ এর উপর সালাওয়াত)", ur: "دوسری تکبیر (اللہ اکبر) کہیں اور درود ابراہیم پڑھیں (نبی ﷺ پر صلوات)", ar: "كبّر التكبيرة الثانية (الله أكبر) واقرأ الصلاة الإبراهيمية", tr: "2. tekbiri getirin (Allahu Ekber) ve Salli-Barik dualarını okuyun", ms: "Ucapkan takbir kedua (Allahu Akbar) dan baca Selawat Ibrahim", id: "Ucapkan takbir kedua (Allahu Akbar) dan baca Shalawat Ibrahim" },
      arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ ، اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
      transliteration: "Allahumma salli 'ala Muhammadin wa 'ala aali Muhammadin, kama sallaita 'ala Ibrahima wa 'ala aali Ibrahima, innaka Hamidun Majeed. Allahumma barik 'ala Muhammadin wa 'ala aali Muhammadin, kama barakta 'ala Ibrahima wa 'ala aali Ibrahima, innaka Hamidun Majeed.",
      meaning: { en: "O Allah, send blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim. You are Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. You are Praiseworthy, Glorious.", bn: "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর রহমত বর্ষণ করুন, যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর রহমত বর্ষণ করেছিলেন। নিশ্চয়ই আপনি প্রশংসিত, মহিমান্বিত। হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের উপর বরকত দিন, যেমন আপনি ইবরাহীম ও তাঁর পরিবারের উপর বরকত দিয়েছিলেন।", ur: "اے اللہ، محمد اور آل محمد پر رحمت نازل فرما جیسے تو نے ابراہیم اور آل ابراہیم پر رحمت نازل فرمائی۔ بے شک تو قابلِ حمد بزرگی والا ہے۔ اے اللہ، محمد اور آل محمد پر برکت نازل فرما جیسے تو نے ابراہیم اور آل ابراہیم پر برکت نازل فرمائی۔", ar: "اللهم صل على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد.", tr: "Allah'ım! Muhammed'e ve Muhammed'in ailesine rahmet et, İbrahim'e ve İbrahim'in ailesine rahmet ettiğin gibi. Sen Hamîd ve Mecîd'sin. Allah'ım! Muhammed'e ve Muhammed'in ailesine bereket ver, İbrahim'e ve İbrahim'in ailesine bereket verdiğin gibi.", ms: "Ya Allah, selawatkanlah ke atas Muhammad dan keluarga Muhammad, sebagaimana Engkau selawatkan ke atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad, sebagaimana Engkau berkatkan Ibrahim dan keluarga Ibrahim.", id: "Ya Allah, limpahkanlah shalawat atas Muhammad dan keluarga Muhammad, sebagaimana Engkau limpahkan shalawat atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad, sebagaimana Engkau berkati Ibrahim dan keluarga Ibrahim." },
    },
    // Step 4: 3rd Takbir — Dua for the deceased
    {
      stepNumber: 4,
      action: { en: "Say the 3rd Takbir (Allahu Akbar) and recite the dua for the deceased", bn: "৩য় তাকবীর (আল্লাহু আকবার) বলুন এবং মৃত ব্যক্তির জন্য দু'আ পড়ুন", ur: "تیسری تکبیر (اللہ اکبر) کہیں اور میت کے لیے دعا پڑھیں", ar: "كبّر التكبيرة الثالثة (الله أكبر) وادعُ للميت", tr: "3. tekbiri getirin (Allahu Ekber) ve cenaze için dua okuyun", ms: "Ucapkan takbir ketiga (Allahu Akbar) dan baca doa untuk si mati", id: "Ucapkan takbir ketiga (Allahu Akbar) dan baca doa untuk jenazah" },
      arabic: "اللَّهُمَّ اغْفِرْ لِحَيِّنَا وَمَيِّتِنَا وَشَاهِدِنَا وَغَائِبِنَا وَصَغِيرِنَا وَكَبِيرِنَا وَذَكَرِنَا وَأُنْثَانَا ، اللَّهُمَّ مَنْ أَحْيَيْتَهُ مِنَّا فَأَحْيِهِ عَلَى الْإِسْلَامِ وَمَنْ تَوَفَّيْتَهُ مِنَّا فَتَوَفَّهُ عَلَى الْإِيمَانِ",
      transliteration: "Allahummaghfir lihayyina wa mayyitina wa shahidina wa gha'ibina wa saghirina wa kabirina wa dhakarina wa unthana. Allahumma man ahyaitahu minna fa ahyihi 'alal-Islam, wa man tawaffaitahu minna fatawaffahu 'alal-Iman.",
      meaning: { en: "O Allah, forgive our living and our dead, those present and those absent, our young and our old, our males and our females. O Allah, whomever You keep alive among us, keep them alive on Islam, and whomever You cause to die, cause them to die upon faith.", bn: "হে আল্লাহ, আমাদের জীবিত ও মৃতদের, উপস্থিত ও অনুপস্থিতদের, ছোট ও বড়দের, পুরুষ ও নারীদের ক্ষমা করুন। হে আল্লাহ, আমাদের মধ্যে যাকে তুমি জীবিত রাখো তাকে ইসলামের উপর জীবিত রাখো, এবং যাকে তুমি মৃত্যু দাও তাকে ঈমানের উপর মৃত্যু দাও।", ur: "اے اللہ، ہمارے زندوں اور مُردوں کو، حاضروں اور غائبوں کو، چھوٹوں اور بڑوں کو، مردوں اور عورتوں کو معاف فرما۔ اے اللہ، ہم میں سے جسے تو زندہ رکھے اسے اسلام پر زندہ رکھ، اور جسے تو موت دے اسے ایمان پر موت دے۔", ar: "اللهم اغفر لحيّنا وميّتنا وشاهدنا وغائبنا وصغيرنا وكبيرنا وذكرنا وأنثانا. اللهم من أحييته منا فأحيه على الإسلام ومن توفيته منا فتوفه على الإيمان.", tr: "Allah'ım! Dirilerimizi ve ölülerimizi, burada olanlarımızı ve olmayanlarımızı, küçüklerimizi ve büyüklerimizi, erkeklerimizi ve kadınlarımızı bağışla. Allah'ım! Bizden yaşattığını İslam üzere yaşat, öldürdüğünü iman üzere öldür.", ms: "Ya Allah, ampunkan orang hidup kami dan orang mati kami, yang hadir dan yang ghaib, yang kecil dan yang besar, lelaki dan perempuan kami. Ya Allah, sesiapa yang Engkau hidupkan dari kalangan kami, hidupkanlah dia atas Islam, dan sesiapa yang Engkau matikan, matikanlah dia atas iman.", id: "Ya Allah, ampunilah orang hidup kami dan orang mati kami, yang hadir dan yang gaib, yang kecil dan yang besar, laki-laki dan perempuan kami. Ya Allah, siapa saja yang Engkau hidupkan di antara kami, hidupkanlah dia atas Islam, dan siapa saja yang Engkau matikan, matikanlah dia atas iman." },
    },
    // Step 5: 4th Takbir — brief silence or short dua
    {
      stepNumber: 5,
      action: { en: "Say the 4th Takbir (Allahu Akbar) and remain silent briefly, or recite a short dua", bn: "৪র্থ তাকবীর (আল্লাহু আকবার) বলুন এবং সংক্ষেপে চুপ থাকুন, অথবা একটি ছোট দু'আ পড়ুন", ur: "چوتھی تکبیر (اللہ اکبر) کہیں اور تھوڑی دیر خاموش رہیں، یا مختصر دعا پڑھیں", ar: "كبّر التكبيرة الرابعة (الله أكبر) واسكت قليلاً أو ادعُ بدعاء قصير", tr: "4. tekbiri getirin (Allahu Ekber) ve kısa bir süre sessiz kalın veya kısa bir dua okuyun", ms: "Ucapkan takbir keempat (Allahu Akbar) dan berdiam sebentar, atau baca doa pendek", id: "Ucapkan takbir keempat (Allahu Akbar) dan berdiam sebentar, atau baca doa pendek" },
      arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      transliteration: "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhaban-nar",
      meaning: { en: "Our Lord, give us good in this world and good in the Hereafter, and save us from the punishment of the Fire.", bn: "হে আমাদের রব, আমাদের দুনিয়ায় কল্যাণ দিন এবং আখিরাতেও কল্যাণ দিন, এবং আমাদের জাহান্নামের আযাব থেকে রক্ষা করুন।", ur: "اے ہمارے رب، ہمیں دنیا میں بھلائی دے اور آخرت میں بھلائی دے، اور ہمیں آگ کے عذاب سے بچا۔", ar: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار", tr: "Rabbimiz! Bize dünyada iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru.", ms: "Wahai Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.", id: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka." },
    },
    // Step 6: Salam
    {
      stepNumber: 6,
      action: { en: "Turn your head to the right and say one Salam (according to the majority of scholars)", bn: "ডানে মাথা ঘুরিয়ে একটি সালাম দিন (অধিকাংশ আলেমদের মতে)", ur: "دائیں طرف سر پھیر کر ایک سلام کہیں (جمہور علماء کے مطابق)", ar: "التفت يميناً وسلّم سلاماً واحداً (عند الجمهور)", tr: "Başınızı sağa çevirip bir selam verin (cumhura göre)", ms: "Paling kepala ke kanan dan ucap satu salam (menurut jumhur ulama)", id: "Palingkan kepala ke kanan dan ucapkan satu salam (menurut mayoritas ulama)" },
      arabic: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
      transliteration: "Assalamu 'alaikum wa rahmatullah",
      meaning: { en: "Peace and mercy of Allah be upon you", bn: "আপনাদের উপর আল্লাহর শান্তি ও রহমত বর্ষিত হোক", ur: "تم پر اللہ کی سلامتی اور رحمت ہو", ar: "السلام عليكم ورحمة الله", tr: "Allah'ın selamı ve rahmeti üzerinize olsun", ms: "Salam dan rahmat Allah ke atas kamu", id: "Salam dan rahmat Allah atas kamu" },
    },
  ],
  specialNotes: { en: "Janazah prayer is Fard Kifayah — if some Muslims perform it, the obligation is fulfilled for all. It is performed entirely standing with no Ruku or Sajdah. The Imam stands at the chest level of a male deceased and at the middle of a female deceased.", bn: "জানাযা নামাজ ফরজে কিফায়া — কিছু মুসলিম আদায় করলে সকলের দায়িত্ব পূরণ হয়। এটি সম্পূর্ণ দাঁড়িয়ে আদায় করা হয়, কোনো রুকু বা সিজদা নেই। ইমাম পুরুষ মৃতের বুকের কাছে এবং মহিলা মৃতের মাঝখানে দাঁড়ান।", ur: "نمازِ جنازہ فرضِ کفایہ ہے — اگر کچھ مسلمان ادا کریں تو سب کی ذمہ داری پوری ہو جاتی ہے۔ یہ مکمل طور پر کھڑے ہو کر ادا کی جاتی ہے، کوئی رکوع یا سجدہ نہیں۔ امام مرد میت کے سینے اور عورت میت کے درمیان کھڑے ہوتے ہیں۔", ar: "صلاة الجنازة فرض كفاية — إذا أداها بعض المسلمين سقطت عن الباقين. تُؤدّى وقوفاً بالكامل بلا ركوع أو سجود. يقف الإمام عند صدر الرجل ووسط المرأة.", tr: "Cenaze namazı Farz-ı Kifaye'dir — bazı Müslümanlar kılarsa diğerlerinden sorumluluk düşer. Tamamen ayakta kılınır, rüku ve secde yoktur. İmam erkek cenazenin göğüs hizasında, kadın cenazenin ortasında durur.", ms: "Solat Jenazah adalah Fardhu Kifayah — jika sebahagian Muslim menunaikannya, kewajipan gugur bagi semua. Ia dilakukan sepenuhnya berdiri, tiada rukuk atau sujud. Imam berdiri di paras dada jenazah lelaki dan di tengah jenazah perempuan.", id: "Shalat Jenazah adalah Fardhu Kifayah — jika sebagian Muslim menunaikannya, kewajiban gugur bagi semua. Dilakukan sepenuhnya berdiri, tidak ada rukuk atau sujud. Imam berdiri di posisi dada jenazah laki-laki dan di tengah jenazah perempuan." },
};
