import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const JUMMAH_PRAYER: PrayerInfo = {
  id: "jummah",
  name: { en: "Jummah (Friday)", bn: "জুমা (শুক্রবার)", ur: "جمعہ", ar: "الجمعة", tr: "Cuma", ms: "Jumaat", id: "Jumat" },
  arabicName: "صلاة الجمعة",
  type: "wajib",
  category: "special",
  totalRakats: "14",
  rakatBreakdown: { en: "4 Sunnah + 2 Fard + 4 Sunnah + 2 Sunnah + 2 Nafl", bn: "৪ সুন্নাত + ২ ফরজ + ৪ সুন্নাত + ২ সুন্নাত + ২ নফল", ur: "۴ سنت + ۲ فرض + ۴ سنت + ۲ سنت + ۲ نفل", ar: "٤ سنة + ٢ فرض + ٤ سنة + ٢ سنة + ٢ نفل", tr: "4 Sünnet + 2 Farz + 4 Sünnet + 2 Sünnet + 2 Nafile", ms: "4 Sunat + 2 Fardhu + 4 Sunat + 2 Sunat + 2 Sunat", id: "4 Sunnah + 2 Fardhu + 4 Sunnah + 2 Sunnah + 2 Nafilah" },
  time: { en: "At the time of Dhuhr on Friday", bn: "শুক্রবার যোহরের সময়", ur: "جمعہ کے دن ظہر کے وقت", ar: "في وقت الظهر يوم الجمعة", tr: "Cuma günü öğle vakti", ms: "Pada waktu Zuhur hari Jumaat", id: "Pada waktu Dzuhur hari Jumat" },
  description: { en: "Jummah prayer replaces the Dhuhr prayer on Friday for men. It consists of 2 Fard rakats led by the Imam after the Khutbah (sermon), along with Sunnah and Nafl prayers before and after.", bn: "জুমার নামাজ শুক্রবারে পুরুষদের জন্য যোহরের পরিবর্তে আদায় করা হয়। খুতবার পর ইমামের নেতৃত্বে ২ রাকাত ফরজ, এবং এর আগে ও পরে সুন্নাত ও নফল নামাজ আদায় করা হয়।", ur: "جمعہ کی نماز جمعہ کے دن مردوں کے لیے ظہر کی جگہ ادا کی جاتی ہے۔ خطبے کے بعد امام کی قیادت میں ۲ فرض رکعتیں ہوتی ہیں، اس کے علاوہ پہلے اور بعد میں سنت اور نفل نمازیں ہیں۔", ar: "صلاة الجمعة تحل محل صلاة الظهر يوم الجمعة للرجال. تتكون من ركعتين فرض يؤمهما الإمام بعد الخطبة، مع سنن ونوافل قبلها وبعدها.", tr: "Cuma namazı, Cuma günü erkekler için öğle namazının yerini alır. Hutbeden sonra imam tarafından kıldırılan 2 farz rekattan oluşur, öncesinde ve sonrasında sünnet ve nafile namazlar vardır.", ms: "Solat Jumaat menggantikan solat Zuhur pada hari Jumaat untuk lelaki. Ia terdiri daripada 2 rakaat fardhu yang diimamkan selepas khutbah, serta solat sunat dan nafilah sebelum dan selepasnya.", id: "Shalat Jumat menggantikan shalat Dzuhur pada hari Jumat untuk laki-laki. Terdiri dari 2 rakaat fardhu yang dipimpin imam setelah khutbah, serta shalat sunnah dan nafilah sebelum dan sesudahnya." },
  steps: [
    // Step 1: Ghusl and go early
    { stepNumber: 1, action: { en: "Perform Ghusl (bath), wear clean clothes, apply fragrance, and go to the mosque early", bn: "গোসল করুন, পরিষ্কার কাপড় পরুন, সুগন্ধি লাগান এবং তাড়াতাড়ি মসজিদে যান", ur: "غسل کریں، صاف کپڑے پہنیں، خوشبو لگائیں اور جلدی مسجد جائیں", ar: "اغتسل والبس ثياباً نظيفة وتطيّب واذهب إلى المسجد مبكراً", tr: "Gusül abdesti alın, temiz giysiler giyin, güzel koku sürün ve camiye erken gidin", ms: "Mandi, pakai pakaian bersih, pakai wangian dan pergi ke masjid awal", id: "Mandi, pakai pakaian bersih, pakai wewangian dan pergi ke masjid lebih awal" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 2: 4 Sunnah before
    { stepNumber: 2, action: { en: "Pray 4 rakats Sunnah (like a regular 4-rakat prayer with Tashahhud in the middle and end)", bn: "৪ রাকাত সুন্নাত পড়ুন (সাধারণ ৪ রাকাত নামাজের মতো মাঝে ও শেষে তাশাহহুদ সহ)", ur: "۴ رکعت سنت پڑھیں (عام ۴ رکعت نماز کی طرح درمیان اور آخر میں تشہد کے ساتھ)", ar: "صلِّ ٤ ركعات سنة (كصلاة عادية بتشهد أوسط وأخير)", tr: "4 rekat sünnet kılın (ortada ve sonda Tahiyyat ile normal 4 rekatlık namaz gibi)", ms: "Solat 4 rakaat sunat (seperti solat 4 rakaat biasa dengan Tahiyyat di tengah dan akhir)", id: "Shalat 4 rakaat sunnah (seperti shalat 4 rakaat biasa dengan Tahiyyat di tengah dan akhir)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 3: Khutbah
    { stepNumber: 3, action: { en: "Listen to the Khutbah (two sermons by the Imam) — it is obligatory to listen silently and attentively", bn: "খুতবা শুনুন (ইমামের দুটি ভাষণ) — চুপ থেকে মনোযোগ দিয়ে শোনা ফরজ", ur: "خطبہ سنیں (امام کے دو خطبے) — خاموشی اور توجہ سے سننا فرض ہے", ar: "استمع إلى الخطبتين — يجب الإنصات والاستماع بانتباه", tr: "Hutbeyi dinleyin (imamın iki hutbesi) — sessizce ve dikkatle dinlemek farzdır", ms: "Dengar khutbah (dua khutbah oleh imam) — wajib mendengar dengan senyap dan penuh perhatian", id: "Dengarkan khutbah (dua khutbah oleh imam) — wajib mendengarkan dengan diam dan penuh perhatian" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 4: Stand for 2 Fard
    { stepNumber: 4, action: { en: "Stand for 2 Fard rakats — the Imam leads the prayer and recites aloud", bn: "২ রাকাত ফরজের জন্য দাঁড়ান — ইমাম নামাজ পড়ান এবং উচ্চস্বরে কিরাত পড়েন", ur: "۲ فرض رکعتوں کے لیے کھڑے ہوں — امام نماز پڑھاتے ہیں اور بلند آواز سے قراءت کرتے ہیں", ar: "قم لصلاة ركعتي الفرض — يؤم الإمام ويقرأ جهراً", tr: "2 farz rekat için kalkın — imam namazı kıldırır ve sesli okur", ms: "Berdiri untuk 2 rakaat fardhu — imam memimpin solat dan membaca dengan kuat", id: "Berdiri untuk 2 rakaat fardhu — imam memimpin shalat dan membaca dengan keras" }, arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", meaning: { en: "Allah is the Greatest", bn: "আল্লাহ সবচেয়ে মহান", ur: "اللہ سب سے بڑا ہے", ar: "الله أكبر", tr: "Allah en büyüktür", ms: "Allah Maha Besar", id: "Allah Maha Besar" } },
    // Step 5: Follow Imam in 1st rakat
    { stepNumber: 5, action: { en: "Follow the Imam: Takbir, Imam recites Fatiha and a Surah aloud, then Ruku and two Sajdahs", bn: "ইমামকে অনুসরণ করুন: তাকবীর, ইমাম উচ্চস্বরে ফাতিহা ও সূরা পড়েন, তারপর রুকু ও দুই সিজদা", ur: "امام کی پیروی کریں: تکبیر، امام بلند آواز سے فاتحہ اور سورت پڑھتے ہیں، پھر رکوع اور دو سجدے", ar: "اتبع الإمام: التكبير ثم يقرأ الإمام الفاتحة وسورة جهراً ثم الركوع والسجدتان", tr: "İmamı takip edin: Tekbir, imam Fatiha ve sure sesli okur, sonra rüku ve iki secde", ms: "Ikut imam: Takbir, imam baca Fatihah dan surah dengan kuat, kemudian rukuk dan dua sujud", id: "Ikuti imam: Takbir, imam membaca Fatihah dan surah dengan keras, kemudian rukuk dan dua sujud" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 6: 2nd rakat + Tashahhud + Durood + Salam
    { stepNumber: 6, action: { en: "2nd rakat same as first, then sit for final Tashahhud, recite Durood Ibrahim, dua, and give Salam to both sides", bn: "২য় রাকাত প্রথমটির মতো, তারপর শেষ তাশাহহুদে বসুন, দরূদ ইবরাহীম ও দু'আ পড়ুন এবং উভয় দিকে সালাম দিন", ur: "دوسری رکعت پہلی کی طرح، پھر آخری تشہد میں بیٹھیں، درود ابراہیم اور دعا پڑھیں اور دونوں طرف سلام پھیریں", ar: "الركعة الثانية كالأولى ثم اجلس للتشهد الأخير واقرأ الصلاة الإبراهيمية والدعاء ثم سلّم", tr: "2. rekat birincisi gibi, sonra son Tahiyyat için oturun, Salli-Barik ve dua okuyun, iki tarafa selam verin", ms: "Rakaat ke-2 sama seperti pertama, kemudian duduk untuk Tahiyyat akhir, baca Selawat Ibrahim dan doa, beri salam ke kedua belah", id: "Rakaat ke-2 sama seperti pertama, kemudian duduk untuk Tahiyyat akhir, baca Shalawat Ibrahim dan doa, beri salam ke kedua sisi" }, arabic: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", transliteration: "Assalamu 'alaikum wa rahmatullah (right side, then left side)", meaning: { en: "Peace and mercy of Allah be upon you", bn: "আপনাদের উপর আল্লাহর শান্তি ও রহমত বর্ষিত হোক", ur: "تم پر اللہ کی سلامتی اور رحمت ہو", ar: "السلام عليكم ورحمة الله", tr: "Allah'ın selamı ve rahmeti üzerinize olsun", ms: "Salam dan rahmat Allah ke atas kamu", id: "Salam dan rahmat Allah atas kamu" } },
    // Step 7: 4 Sunnah after
    { stepNumber: 7, action: { en: "Pray 4 rakats Sunnah after the Fard (like a regular 4-rakat prayer)", bn: "ফরজের পর ৪ রাকাত সুন্নাত পড়ুন (সাধারণ ৪ রাকাত নামাজের মতো)", ur: "فرض کے بعد ۴ رکعت سنت پڑھیں (عام ۴ رکعت نماز کی طرح)", ar: "صلِّ ٤ ركعات سنة بعد الفرض (كصلاة عادية)", tr: "Farzdan sonra 4 rekat sünnet kılın (normal 4 rekatlık namaz gibi)", ms: "Solat 4 rakaat sunat selepas fardhu (seperti solat 4 rakaat biasa)", id: "Shalat 4 rakaat sunnah setelah fardhu (seperti shalat 4 rakaat biasa)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 8: 2 Sunnah + 2 Nafl
    { stepNumber: 8, action: { en: "Pray 2 rakats Sunnah, then 2 rakats Nafl to complete the Jummah prayer", bn: "২ রাকাত সুন্নাত পড়ুন, তারপর ২ রাকাত নফল পড়ে জুমার নামাজ সম্পূর্ণ করুন", ur: "۲ رکعت سنت پڑھیں، پھر ۲ رکعت نفل پڑھ کر جمعہ کی نماز مکمل کریں", ar: "صلِّ ركعتين سنة ثم ركعتين نافلة لإتمام صلاة الجمعة", tr: "2 rekat sünnet kılın, sonra 2 rekat nafile kılarak Cuma namazını tamamlayın", ms: "Solat 2 rakaat sunat, kemudian 2 rakaat nafilah untuk melengkapkan solat Jumaat", id: "Shalat 2 rakaat sunnah, kemudian 2 rakaat nafilah untuk melengkapi shalat Jumat" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
  ],
  specialNotes: { en: "Jummah is Fard (obligatory) for every adult Muslim man. The Khutbah replaces 2 extra rakats of Dhuhr. Bathing (Ghusl) on Friday is Sunnah Muakkadah. Going early to the mosque earns extra reward. It is recommended to recite Surah Al-Kahf on Friday.", bn: "জুমা প্রতিটি প্রাপ্তবয়স্ক মুসলিম পুরুষের জন্য ফরজ। খুতবা যোহরের অতিরিক্ত ২ রাকাতের স্থলাভিষিক্ত। শুক্রবারে গোসল করা সুন্নাতে মুআক্কাদা। তাড়াতাড়ি মসজিদে যাওয়ায় অতিরিক্ত সওয়াব রয়েছে। শুক্রবারে সূরা আল-কাহফ পড়া মুস্তাহাব।", ur: "جمعہ ہر بالغ مسلمان مرد پر فرض ہے۔ خطبہ ظہر کی اضافی ۲ رکعتوں کی جگہ لیتا ہے۔ جمعہ کے دن غسل کرنا سنت مؤکدہ ہے۔ جلدی مسجد جانے میں اضافی ثواب ہے۔ جمعہ کے دن سورۃ الکہف پڑھنا مستحب ہے۔", ar: "صلاة الجمعة فرض على كل مسلم بالغ ذكر. الخطبة تحل محل ركعتين إضافيتين من الظهر. الاغتسال يوم الجمعة سنة مؤكدة. التبكير إلى المسجد فيه أجر عظيم. يُستحب قراءة سورة الكهف يوم الجمعة.", tr: "Cuma namazı her yetişkin Müslüman erkek için farzdır. Hutbe, öğle namazının 2 ekstra rekatının yerini alır. Cuma günü gusül almak sünnet-i müekkededir. Camiye erken gitmek ekstra sevap kazandırır. Cuma günü Kehf Suresi'ni okumak müstehaptır.", ms: "Solat Jumaat adalah Fardhu bagi setiap lelaki Muslim dewasa. Khutbah menggantikan 2 rakaat tambahan Zuhur. Mandi pada hari Jumaat adalah Sunat Muakkad. Pergi awal ke masjid mendapat pahala tambahan. Digalakkan membaca Surah Al-Kahfi pada hari Jumaat.", id: "Shalat Jumat adalah Fardhu bagi setiap laki-laki Muslim dewasa. Khutbah menggantikan 2 rakaat tambahan Dzuhur. Mandi pada hari Jumat adalah Sunnah Muakkad. Pergi awal ke masjid mendapat pahala tambahan. Dianjurkan membaca Surah Al-Kahfi pada hari Jumat." },
};
