import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const MAGHRIB_PRAYER: PrayerInfo = {
  id: "maghrib",
  name: {
    en: "Maghrib",
    bn: "মাগরিব",
    ur: "مغرب",
    ar: "المغرب",
    tr: "Akşam",
    ms: "Maghrib",
    id: "Maghrib",
  },
  arabicName: "صلاة المغرب",
  type: "fard",
  category: "daily",
  totalRakats: "7",
  rakatBreakdown: {
    en: "3 Fard + 2 Sunnah + 2 Nafl",
    bn: "৩ ফরজ + ২ সুন্নাত + ২ নফল",
    ur: "۳ فرض + ۲ سنت + ۲ نفل",
    ar: "٣ فرض + ٢ سنة + ٢ نافلة",
    tr: "3 Farz + 2 Sünnet + 2 Nafile",
    ms: "3 Fardu + 2 Sunat + 2 Nafl",
    id: "3 Fardu + 2 Sunah + 2 Nafl",
  },
  time: {
    en: "After sunset until twilight disappears",
    bn: "সূর্যাস্তের পর থেকে গোধূলি অদৃশ্য হওয়া পর্যন্ত",
    ur: "غروب آفتاب کے بعد سے شفق غائب ہونے تک",
    ar: "بعد غروب الشمس حتى يغيب الشفق",
    tr: "Güneş battıktan sonra şafak kaybolana kadar",
    ms: "Selepas matahari terbenam sehingga mega merah hilang",
    id: "Setelah matahari terbenam hingga mega merah hilang",
  },
  description: {
    en: "Maghrib is a 3-rakat Fard prayer, unique among the five daily prayers for having an odd number of obligatory rakats. It is recited aloud (Jahr) in the first 2 rakats and silently in the 3rd rakat.",
    bn: "মাগরিব ৩ রাকাত ফরজ নামাজ, পাঁচ ওয়াক্ত নামাজের মধ্যে বেজোড় সংখ্যক ফরজ রাকাতের জন্য অনন্য। প্রথম ২ রাকাতে সশব্দে (জাহর) এবং ৩য় রাকাতে নীরবে পড়া হয়।",
    ur: "مغرب ۳ رکعت فرض نماز ہے، پانچ وقت کی نمازوں میں طاق فرض رکعتوں کی وجہ سے منفرد ہے۔ پہلی ۲ رکعتوں میں بلند آواز سے (جہر) اور تیسری رکعت میں آہستہ پڑھی جاتی ہے۔",
    ar: "صلاة المغرب ٣ ركعات فرض، وهي فريدة بين الصلوات الخمس لكونها ذات عدد فردي من الركعات المفروضة. تُقرأ جهراً في الركعتين الأوليين وسراً في الركعة الثالثة.",
    tr: "Akşam namazı 3 rekât farz olup, beş vakit namaz arasında tek sayıda farz rekâtı olan namazdır. İlk 2 rekâtta sesli (cehri) ve 3. rekâtta sessiz kılınır.",
    ms: "Maghrib adalah solat Fardu 3 rakaat, unik di antara lima solat harian kerana mempunyai bilangan rakaat fardu yang ganjil. Ia dibaca dengan suara kuat (Jahr) pada 2 rakaat pertama dan senyap pada rakaat ke-3.",
    id: "Maghrib adalah shalat Fardu 3 rakaat, unik di antara lima shalat harian karena memiliki jumlah rakaat fardu yang ganjil. Dibaca dengan suara keras (Jahr) pada 2 rakaat pertama dan diam pada rakaat ke-3.",
  },
  steps: [
    {
      stepNumber: 1,
      action: {
        en: "Make intention (Niyyah) for 3 Fard of Maghrib",
        bn: "মাগরিবের ৩ রাকাত ফরজের নিয়ত করুন",
        ur: "مغرب کی ۳ رکعت فرض کی نیت کریں",
        ar: "انوِ صلاة ٣ ركعات فرض المغرب",
        tr: "Akşam namazının 3 rekât farzı için niyet edin",
        ms: "Niat 3 rakaat Fardu Maghrib",
        id: "Niat 3 rakaat Fardu Maghrib",
      },
      arabic: "نَوَيْتُ أَنْ أُصَلِّيَ صَلَاةَ الْمَغْرِبِ ثَلَاثَ رَكَعَاتٍ فَرْضًا لِلَّهِ تَعَالَىٰ",
      transliteration: "Nawaytu an usalliya salatal Maghribi thalatha raka'atin fardan lillahi ta'ala",
      meaning: {
        en: "I intend to pray 3 rakats of Fard Maghrib prayer for the sake of Allah the Most High",
        bn: "আমি আল্লাহ তায়ালার জন্য মাগরিবের ৩ রাকাত ফরজ নামাজ পড়ার নিয়ত করছি",
        ur: "میں اللہ تعالیٰ کی رضا کے لیے مغرب کی ۳ رکعت فرض نماز پڑھنے کی نیت کرتا ہوں",
        ar: "أنوي أن أصلي ثلاث ركعات فرض صلاة المغرب لله تعالى",
        tr: "Allah rızası için Akşam namazının 3 rekât farzını kılmaya niyet ettim",
        ms: "Saya berniat menunaikan 3 rakaat Fardu solat Maghrib kerana Allah Taala",
        id: "Saya berniat menunaikan 3 rakaat Fardu shalat Maghrib karena Allah Taala",
      },
    },
    {
      stepNumber: 2,
      action: {
        en: "Raise hands to ears and say Takbiratul Ihram",
        bn: "দুই হাত কান পর্যন্ত উঠান এবং তাকবীরাতুল ইহরাম বলুন",
        ur: "دونوں ہاتھ کانوں تک اٹھائیں اور تکبیر تحریمہ کہیں",
        ar: "ارفع يديك إلى أذنيك وكبّر تكبيرة الإحرام",
        tr: "Ellerinizi kulaklarınıza kadar kaldırın ve iftitah tekbiri alın",
        ms: "Angkat kedua tangan ke paras telinga dan lafazkan Takbiratul Ihram",
        id: "Angkat kedua tangan ke telinga dan ucapkan Takbiratul Ihram",
      },
      arabic: "اللَّهُ أَكْبَرُ",
      transliteration: "Allahu Akbar",
      meaning: {
        en: "Allah is the Greatest",
        bn: "আল্লাহ সর্বশ্রেষ্ঠ",
        ur: "اللہ سب سے بڑا ہے",
        ar: "الله أكبر",
        tr: "Allah en büyüktür",
        ms: "Allah Maha Besar",
        id: "Allah Maha Besar",
      },
    },
    {
      stepNumber: 3,
      action: {
        en: "Recite the opening supplication (Thana)",
        bn: "সানা (উদ্বোধনী দু'আ) পড়ুন",
        ur: "ثناء (افتتاحی دعا) پڑھیں",
        ar: "اقرأ دعاء الاستفتاح (الثناء)",
        tr: "Sübhaneke duasını okuyun",
        ms: "Baca doa iftitah (Thana)",
        id: "Baca doa iftitah (Sana)",
      },
      arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ",
      transliteration: "Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta'ala jadduka wa la ilaha ghayruk",
      meaning: {
        en: "Glory be to You, O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, and there is no god besides You.",
        bn: "হে আল্লাহ, আপনার পবিত্রতা ও প্রশংসা ঘোষণা করছি। আপনার নাম বরকতময়, আপনার মর্যাদা সুউচ্চ এবং আপনি ছাড়া কোনো ইলাহ নেই।",
        ur: "اے اللہ! تو پاک ہے اور تیری حمد ہے۔ تیرا نام بابرکت ہے، تیری شان بلند ہے اور تیرے سوا کوئی معبود نہیں۔",
        ar: "سبحانك اللهم وبحمدك، تبارك اسمك وتعالى جدك ولا إله غيرك.",
        tr: "Allah'ım! Sen her türlü noksanlıktan münezzehsin. Seni hamd ile tesbih ederim. Senin adın mübarektir, şanın yücedir. Senden başka ilah yoktur.",
        ms: "Maha Suci Engkau ya Allah dan dengan pujian-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu dan tiada Tuhan selain Engkau.",
        id: "Maha Suci Engkau ya Allah dan dengan pujian-Mu. Berkat nama-Mu, Maha Tinggi kebesaran-Mu dan tiada Tuhan selain Engkau.",
      },
    },
    {
      stepNumber: 4,
      action: {
        en: "Recite Ta'awwudh and Bismillah",
        bn: "তাআউয ও বিসমিল্লাহ পড়ুন",
        ur: "تعوذ اور بسم اللہ پڑھیں",
        ar: "اقرأ التعوذ والبسملة",
        tr: "Eûzü Besmele okuyun",
        ms: "Baca Ta'awwudh dan Bismillah",
        id: "Baca Ta'awwudh dan Bismillah",
      },
      arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ ۝ بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      transliteration: "A'udhu billahi minash-shaytanir-rajim. Bismillahir-Rahmanir-Rahim",
      meaning: {
        en: "I seek refuge in Allah from the accursed Satan. In the name of Allah, the Most Gracious, the Most Merciful.",
        bn: "আমি বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় চাই। পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে।",
        ur: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں۔ اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔",
        ar: "أعوذ بالله من الشيطان الرجيم. بسم الله الرحمن الرحيم.",
        tr: "Kovulmuş şeytandan Allah'a sığınırım. Rahman ve Rahim olan Allah'ın adıyla.",
        ms: "Aku berlindung dengan Allah daripada syaitan yang terkutuk. Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang.",
        id: "Aku berlindung kepada Allah dari setan yang terkutuk. Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang.",
      },
    },
    {
      stepNumber: 5,
      action: {
        en: "Recite Surah Al-Fatiha aloud",
        bn: "সশব্দে সূরা আল-ফাতিহা পড়ুন",
        ur: "سورۃ الفاتحہ بلند آواز سے پڑھیں",
        ar: "اقرأ سورة الفاتحة جهراً",
        tr: "Fatiha suresini sesli okuyun",
        ms: "Baca Surah Al-Fatihah dengan suara kuat",
        id: "Baca Surah Al-Fatihah dengan suara keras",
      },
      arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
      transliteration: "Bismillahir-Rahmanir-Rahim. Alhamdu lillahi Rabbil 'alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na'budu wa iyyaka nasta'in. Ihdinas-siratal mustaqim. Siratal-ladhina an'amta 'alayhim ghayril-maghdubi 'alayhim walad-dallin. Amin.",
      meaning: {
        en: "In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of all the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us on the Straight Path. The path of those who have received Your grace; not the path of those who have brought down wrath upon themselves, nor of those who have gone astray.",
        bn: "পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে। সকল প্রশংসা আল্লাহর যিনি সকল জগতের প্রতিপালক। পরম করুণাময় ও অসীম দয়ালু। বিচার দিবসের মালিক। আমরা কেবল আপনারই ইবাদত করি এবং কেবল আপনারই কাছে সাহায্য চাই। আমাদের সরল সঠিক পথ দেখান। তাদের পথ যাদের আপনি অনুগ্রহ করেছেন, তাদের পথ নয় যাদের প্রতি আপনার গজব নাযিল হয়েছে এবং যারা পথভ্রষ্ট হয়েছে।",
        ur: "اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔ سب تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے۔ بڑا مہربان نہایت رحم والا۔ روزِ جزا کا مالک۔ ہم صرف تیری عبادت کرتے ہیں اور تجھ ہی سے مدد مانگتے ہیں۔ ہمیں سیدھا راستہ دکھا۔ ان لوگوں کا راستہ جن پر تو نے انعام کیا، نہ ان کا جن پر غضب ہوا اور نہ گمراہوں کا۔",
        ar: "بسم الله الرحمن الرحيم. الحمد لله رب العالمين. الرحمن الرحيم. مالك يوم الدين. إياك نعبد وإياك نستعين. اهدنا الصراط المستقيم. صراط الذين أنعمت عليهم غير المغضوب عليهم ولا الضالين.",
        tr: "Rahman ve Rahim olan Allah'ın adıyla. Hamd, âlemlerin Rabbi Allah'a mahsustur. Rahman'dır, Rahim'dir. Din gününün sahibidir. Yalnız Sana ibadet ederiz ve yalnız Senden yardım dileriz. Bizi doğru yola ilet. Kendilerine nimet verdiklerinin yoluna; gazaba uğramışların ve sapmışların yoluna değil.",
        ms: "Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang. Segala puji bagi Allah Tuhan sekalian alam. Yang Maha Pemurah lagi Maha Penyayang. Yang menguasai hari pembalasan. Hanya Engkau yang kami sembah dan hanya kepada Engkau kami memohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang-orang yang Engkau kurniakan nikmat kepada mereka, bukan jalan mereka yang dimurkai dan bukan jalan mereka yang sesat.",
        id: "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah Tuhan seluruh alam. Yang Maha Pengasih lagi Maha Penyayang. Pemilik hari pembalasan. Hanya kepada-Mu kami menyembah dan hanya kepada-Mu kami memohon pertolongan. Tunjukilah kami jalan yang lurus. Jalan orang-orang yang telah Engkau beri nikmat, bukan jalan mereka yang dimurkai dan bukan pula jalan mereka yang sesat.",
      },
    },
    {
      stepNumber: 6,
      action: {
        en: "Recite another Surah aloud (e.g., Surah Al-Ikhlas) — recited aloud in the 1st and 2nd rakat only",
        bn: "সশব্দে আরেকটি সূরা পড়ুন (যেমন সূরা আল-ইখলাস) — শুধু ১ম ও ২য় রাকাতে সশব্দে পড়া হয়",
        ur: "بلند آواز سے ایک اور سورت پڑھیں (مثلاً سورۃ الاخلاص) — صرف پہلی اور دوسری رکعت میں بلند آواز سے",
        ar: "اقرأ سورة أخرى جهراً (مثل سورة الإخلاص) — تُقرأ جهراً في الركعة الأولى والثانية فقط",
        tr: "Başka bir sure sesli okuyun (örn. İhlâs suresi) — sadece 1. ve 2. rekâtta sesli okunur",
        ms: "Baca surah lain dengan suara kuat (cth. Surah Al-Ikhlas) — dibaca kuat pada rakaat 1 dan 2 sahaja",
        id: "Baca surah lain dengan suara keras (mis. Surah Al-Ikhlas) — dibaca keras pada rakaat 1 dan 2 saja",
      },
      arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
      transliteration: "Qul Huwa Allahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
      meaning: {
        en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. And there is none comparable to Him.",
        bn: "বলুন: তিনি আল্লাহ, এক ও অদ্বিতীয়। আল্লাহ অমুখাপেক্ষী। তিনি কাউকে জন্ম দেননি এবং তাঁকেও জন্ম দেওয়া হয়নি। এবং তাঁর সমতুল্য কেউ নেই।",
        ur: "کہو: وہ اللہ ایک ہے۔ اللہ بے نیاز ہے۔ نہ اس سے کوئی پیدا ہوا نہ وہ کسی سے پیدا ہوا۔ اور نہ اس کا کوئی ہمسر ہے۔",
        ar: "قل هو الله أحد. الله الصمد. لم يلد ولم يولد. ولم يكن له كفواً أحد.",
        tr: "De ki: O Allah birdir. Allah Samed'dir (her şey O'na muhtaçtır). O doğurmamıştır ve doğurulmamıştır. Hiçbir şey O'nun dengi değildir.",
        ms: "Katakanlah: Dialah Allah Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada seorang pun yang setara dengan-Nya.",
        id: "Katakanlah: Dialah Allah Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada sesuatu pun yang setara dengan-Nya.",
      },
    },
    {
      stepNumber: 7,
      action: {
        en: "Perform Ruku (bow down) and recite Tasbeeh 3 times",
        bn: "রুকু করুন (ঝুঁকে পড়ুন) এবং ৩ বার তাসবীহ পড়ুন",
        ur: "رکوع کریں (جھکیں) اور ۳ بار تسبیح پڑھیں",
        ar: "اركع وسبّح ثلاث مرات",
        tr: "Rükûya gidin ve 3 kez tesbih okuyun",
        ms: "Lakukan rukuk dan baca tasbih 3 kali",
        id: "Lakukan ruku dan baca tasbih 3 kali",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
      transliteration: "Subhana Rabbiyal Adheem",
      meaning: {
        en: "Glory be to my Lord, the Most Great",
        bn: "আমার মহান প্রভুর পবিত্রতা ঘোষণা করছি",
        ur: "پاک ہے میرا رب بڑی عظمت والا",
        ar: "سبحان ربي العظيم",
        tr: "Yüce Rabbimi tüm noksanlıklardan tenzih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Agung",
        id: "Maha Suci Tuhanku Yang Maha Agung",
      },
    },
    {
      stepNumber: 8,
      action: {
        en: "Stand up from Ruku and recite Tasmee and Tahmeed",
        bn: "রুকু থেকে দাঁড়ান এবং তাসমি' ও তাহমিদ পড়ুন",
        ur: "رکوع سے کھڑے ہوں اور تسمیع و تحمید پڑھیں",
        ar: "قم من الركوع واقرأ التسميع والتحميد",
        tr: "Rükûdan kalkın ve semi'allahu limen hamideh deyin",
        ms: "Bangun dari rukuk dan baca Tasmee dan Tahmeed",
        id: "Bangun dari ruku dan baca Tasmee dan Tahmeed",
      },
      arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ ۝ رَبَّنَا لَكَ الْحَمْدُ",
      transliteration: "Sami' Allahu liman hamidah. Rabbana lakal hamd.",
      meaning: {
        en: "Allah hears the one who praises Him. Our Lord, to You belongs all praise.",
        bn: "আল্লাহ তার প্রশংসাকারীর প্রশংসা শুনেন। হে আমাদের রব, সকল প্রশংসা আপনার।",
        ur: "اللہ نے اس کی سن لی جس نے اس کی حمد کی۔ اے ہمارے رب! تیرے لیے ہی تمام تعریفیں ہیں۔",
        ar: "سمع الله لمن حمده. ربنا لك الحمد.",
        tr: "Allah kendisine hamd edeni işitir. Rabbimiz! Hamd Sanadır.",
        ms: "Allah mendengar orang yang memuji-Nya. Wahai Tuhan kami, bagi-Mu segala pujian.",
        id: "Allah mendengar orang yang memuji-Nya. Ya Tuhan kami, bagi-Mu segala pujian.",
      },
    },
    {
      stepNumber: 9,
      action: {
        en: "Perform the first Sajdah (prostration) and recite Tasbeeh 3 times",
        bn: "প্রথম সিজদা করুন এবং ৩ বার তাসবীহ পড়ুন",
        ur: "پہلا سجدہ کریں اور ۳ بار تسبیح پڑھیں",
        ar: "اسجد السجدة الأولى وسبّح ثلاث مرات",
        tr: "İlk secdeyi yapın ve 3 kez tesbih okuyun",
        ms: "Lakukan sujud pertama dan baca tasbih 3 kali",
        id: "Lakukan sujud pertama dan baca tasbih 3 kali",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ",
      transliteration: "Subhana Rabbiyal A'la",
      meaning: {
        en: "Glory be to my Lord, the Most High",
        bn: "আমার সুমহান প্রভুর পবিত্রতা ঘোষণা করছি",
        ur: "پاک ہے میرا رب جو سب سے بلند ہے",
        ar: "سبحان ربي الأعلى",
        tr: "En yüce Rabbimi tüm noksanlıklardan tenzih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi",
        id: "Maha Suci Tuhanku Yang Maha Tinggi",
      },
    },
    {
      stepNumber: 10,
      action: {
        en: "Sit between the two Sajdahs briefly",
        bn: "দুই সিজদার মধ্যে সংক্ষেপে বসুন",
        ur: "دونوں سجدوں کے درمیان مختصراً بیٹھیں",
        ar: "اجلس بين السجدتين",
        tr: "İki secde arasında kısa bir süre oturun",
        ms: "Duduk sebentar antara dua sujud",
        id: "Duduk sebentar antara dua sujud",
      },
      arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
      transliteration: "Rabbighfir li, Rabbighfir li",
      meaning: {
        en: "My Lord, forgive me. My Lord, forgive me.",
        bn: "হে আমার রব, আমাকে ক্ষমা করুন। হে আমার রব, আমাকে ক্ষমা করুন।",
        ur: "اے میرے رب مجھے بخش دے۔ اے میرے رب مجھے بخش دے۔",
        ar: "رب اغفر لي. رب اغفر لي.",
        tr: "Rabbim beni bağışla. Rabbim beni bağışla.",
        ms: "Ya Tuhanku, ampunkan aku. Ya Tuhanku, ampunkan aku.",
        id: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.",
      },
    },
    {
      stepNumber: 11,
      action: {
        en: "Perform the second Sajdah and recite Tasbeeh 3 times",
        bn: "দ্বিতীয় সিজদা করুন এবং ৩ বার তাসবীহ পড়ুন",
        ur: "دوسرا سجدہ کریں اور ۳ بار تسبیح پڑھیں",
        ar: "اسجد السجدة الثانية وسبّح ثلاث مرات",
        tr: "İkinci secdeyi yapın ve 3 kez tesbih okuyun",
        ms: "Lakukan sujud kedua dan baca tasbih 3 kali",
        id: "Lakukan sujud kedua dan baca tasbih 3 kali",
      },
      arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ",
      transliteration: "Subhana Rabbiyal A'la",
      meaning: {
        en: "Glory be to my Lord, the Most High",
        bn: "আমার সুমহান প্রভুর পবিত্রতা ঘোষণা করছি",
        ur: "پاک ہے میرا رب جو سب سے بلند ہے",
        ar: "سبحان ربي الأعلى",
        tr: "En yüce Rabbimi tüm noksanlıklardan tenzih ederim",
        ms: "Maha Suci Tuhanku Yang Maha Tinggi",
        id: "Maha Suci Tuhanku Yang Maha Tinggi",
      },
    },
    {
      stepNumber: 12,
      action: {
        en: "Stand for the 2nd rakat — repeat Surah Al-Fatiha + another Surah (aloud) + Ruku + Sajdahs",
        bn: "২য় রাকাতের জন্য দাঁড়ান — সূরা আল-ফাতিহা + অন্য সূরা (সশব্দে) + রুকু + সিজদা পুনরাবৃত্তি করুন",
        ur: "دوسری رکعت کے لیے کھڑے ہوں — سورۃ الفاتحہ + ایک اور سورت (بلند آواز سے) + رکوع + سجدے دہرائیں",
        ar: "قم للركعة الثانية — أعد قراءة الفاتحة + سورة أخرى (جهراً) + الركوع + السجدتين",
        tr: "2. rekât için kalkın — Fatiha + başka sure (sesli) + Rükû + Secdeler tekrarlayın",
        ms: "Berdiri untuk rakaat ke-2 — ulang Surah Al-Fatihah + surah lain (kuat) + Rukuk + Sujud",
        id: "Berdiri untuk rakaat ke-2 — ulang Surah Al-Fatihah + surah lain (keras) + Ruku + Sujud",
      },
      arabic: "",
      transliteration: "",
      meaning: {
        en: "Repeat the same actions as the 1st rakat: Fatiha and a Surah recited aloud, Ruku, and two Sajdahs",
        bn: "১ম রাকাতের মতো একই কাজ পুনরাবৃত্তি করুন: সশব্দে ফাতিহা ও একটি সূরা, রুকু এবং দুই সিজদা",
        ur: "پہلی رکعت کی طرح دہرائیں: بلند آواز سے فاتحہ اور ایک سورت، رکوع اور دو سجدے",
        ar: "كرر نفس أفعال الركعة الأولى: الفاتحة وسورة جهراً والركوع والسجدتين",
        tr: "1. rekâtın aynısını tekrarlayın: sesli Fatiha ve sure, Rükû ve iki Secde",
        ms: "Ulang tindakan yang sama seperti rakaat 1: Fatihah dan surah dengan suara kuat, Rukuk dan dua Sujud",
        id: "Ulang tindakan yang sama seperti rakaat 1: Fatihah dan surah dengan suara keras, Ruku dan dua Sujud",
      },
    },
    {
      stepNumber: 13,
      action: {
        en: "Sit for the first Tashahhud after the 2nd rakat — recite At-Tahiyyat only",
        bn: "২য় রাকাতের পর প্রথম তাশাহহুদের জন্য বসুন — শুধু আত-তাহিয়্যাত পড়ুন",
        ur: "دوسری رکعت کے بعد پہلے تشہد کے لیے بیٹھیں — صرف التحیات پڑھیں",
        ar: "اجلس للتشهد الأول بعد الركعة الثانية — اقرأ التحيات فقط",
        tr: "2. rekâttan sonra ilk teşehhüd için oturun — sadece Ettehiyyatü okuyun",
        ms: "Duduk untuk Tashahhud pertama selepas rakaat ke-2 — baca At-Tahiyyat sahaja",
        id: "Duduk untuk Tashahhud pertama setelah rakaat ke-2 — baca At-Tahiyyat saja",
      },
      arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ ۝ السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ ۝ السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللَّهِ الصَّالِحِينَ ۝ أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
      transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu 'alayka ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alayna wa 'ala 'ibadillahis-salihin. Ash-hadu an la ilaha illallah wa ash-hadu anna Muhammadan 'abduhu wa rasuluh.",
      meaning: {
        en: "All greetings, prayers, and good deeds are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger.",
        bn: "সকল অভিবাদন, সালাত ও পবিত্র কথা আল্লাহর জন্য। হে নবী, আপনার উপর শান্তি, আল্লাহর রহমত ও বরকত বর্ষিত হোক। আমাদের উপর এবং আল্লাহর নেক বান্দাদের উপর শান্তি বর্ষিত হোক। আমি সাক্ষ্য দিচ্ছি যে আল্লাহ ছাড়া কোনো ইলাহ নেই এবং আমি সাক্ষ্য দিচ্ছি যে মুহাম্মাদ তাঁর বান্দা ও রাসূল।",
        ur: "تمام تعظیمیں، نمازیں اور پاکیزہ باتیں اللہ کے لیے ہیں۔ اے نبی آپ پر سلام ہو اور اللہ کی رحمت اور برکتیں ہوں۔ ہم پر اور اللہ کے نیک بندوں پر سلام ہو۔ میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں اور میں گواہی دیتا ہوں کہ محمد اس کے بندے اور رسول ہیں۔",
        ar: "التحيات لله والصلوات والطيبات. السلام عليك أيها النبي ورحمة الله وبركاته. السلام علينا وعلى عباد الله الصالحين. أشهد أن لا إله إلا الله وأشهد أن محمداً عبده ورسوله.",
        tr: "Bütün tahiyyatlar, salavâtlar ve tayyibatlar Allah'a mahsustur. Ey Peygamber! Sana selam, Allah'ın rahmeti ve bereketi olsun. Bize ve Allah'ın salih kullarına selam olsun. Şehadet ederim ki Allah'tan başka ilah yoktur ve şehadet ederim ki Muhammed O'nun kulu ve elçisidir.",
        ms: "Segala penghormatan, selawat dan kebaikan adalah untuk Allah. Salam sejahtera ke atas engkau wahai Nabi dan rahmat Allah serta keberkatan-Nya. Salam ke atas kami dan hamba-hamba Allah yang soleh. Aku bersaksi bahawa tiada Tuhan melainkan Allah dan aku bersaksi bahawa Muhammad adalah hamba-Nya dan rasul-Nya.",
        id: "Segala penghormatan, selawat dan kebaikan adalah untuk Allah. Salam sejahtera atas engkau wahai Nabi dan rahmat Allah serta keberkahan-Nya. Salam atas kami dan hamba-hamba Allah yang saleh. Aku bersaksi bahwa tiada Tuhan selain Allah dan aku bersaksi bahwa Muhammad adalah hamba-Nya dan rasul-Nya.",
      },
    },
    {
      stepNumber: 14,
      action: {
        en: "Stand for the 3rd rakat — recite only Surah Al-Fatiha silently + Ruku + Sajdahs",
        bn: "৩য় রাকাতের জন্য দাঁড়ান — নীরবে শুধু সূরা আল-ফাতিহা পড়ুন + রুকু + সিজদা",
        ur: "تیسری رکعت کے لیے کھڑے ہوں — آہستہ صرف سورۃ الفاتحہ پڑھیں + رکوع + سجدے",
        ar: "قم للركعة الثالثة — اقرأ الفاتحة فقط سراً + الركوع + السجدتين",
        tr: "3. rekât için kalkın — sadece Fatiha'yı sessiz okuyun + Rükû + Secdeler",
        ms: "Berdiri untuk rakaat ke-3 — baca Surah Al-Fatihah sahaja secara senyap + Rukuk + Sujud",
        id: "Berdiri untuk rakaat ke-3 — baca Surah Al-Fatihah saja secara diam + Ruku + Sujud",
      },
      arabic: "",
      transliteration: "",
      meaning: {
        en: "In the 3rd rakat, recite only Surah Al-Fatiha silently (no additional Surah), then perform Ruku and two Sajdahs",
        bn: "৩য় রাকাতে নীরবে শুধু সূরা আল-ফাতিহা পড়ুন (অতিরিক্ত সূরা নেই), তারপর রুকু ও দুই সিজদা করুন",
        ur: "تیسری رکعت میں آہستہ صرف سورۃ الفاتحہ پڑھیں (کوئی اضافی سورت نہیں)، پھر رکوع اور دو سجدے کریں",
        ar: "في الركعة الثالثة اقرأ الفاتحة فقط سراً (بدون سورة إضافية) ثم اركع واسجد سجدتين",
        tr: "3. rekâtta sadece Fatiha'yı sessiz okuyun (ek sure yok), ardından Rükû ve iki Secde yapın",
        ms: "Pada rakaat ke-3, baca hanya Surah Al-Fatihah secara senyap (tiada surah tambahan), kemudian Rukuk dan dua Sujud",
        id: "Pada rakaat ke-3, baca hanya Surah Al-Fatihah secara diam (tanpa surah tambahan), kemudian Ruku dan dua Sujud",
      },
    },
    {
      stepNumber: 15,
      action: {
        en: "Final sitting: Tashahhud + Durood Ibrahim + Dua + Salam",
        bn: "শেষ বৈঠক: তাশাহহুদ + দুরূদ ইবরাহীম + দু'আ + সালাম",
        ur: "آخری قعدہ: تشہد + درود ابراہیم + دعا + سلام",
        ar: "الجلوس الأخير: التشهد + الصلاة الإبراهيمية + الدعاء + التسليم",
        tr: "Son oturuş: Teşehhüd + Salli-Barik + Dua + Selam",
        ms: "Duduk akhir: Tashahhud + Selawat Ibrahim + Doa + Salam",
        id: "Duduk akhir: Tashahhud + Shalawat Ibrahim + Doa + Salam",
      },
      arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ ۝ اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ ۝ السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
      transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallayta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin kama barakta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid. As-salamu 'alaykum wa rahmatullah.",
      meaning: {
        en: "O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim. You are indeed Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. You are indeed Praiseworthy, Glorious. Peace and mercy of Allah be upon you.",
        bn: "হে আল্লাহ, মুহাম্মাদ ও মুহাম্মাদের পরিবারের উপর রহমত বর্ষণ করুন, যেমন আপনি ইবরাহীম ও ইবরাহীমের পরিবারের উপর রহমত বর্ষণ করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত। হে আল্লাহ, মুহাম্মাদ ও মুহাম্মাদের পরিবারের উপর বরকত দান করুন, যেমন আপনি ইবরাহীম ও ইবরাহীমের পরিবারের উপর বরকত দান করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত। আপনাদের উপর আল্লাহর শান্তি ও রহমত বর্ষিত হোক।",
        ur: "اے اللہ! محمد اور آلِ محمد پر رحمت نازل فرما جیسے تو نے ابراہیم اور آلِ ابراہیم پر رحمت نازل فرمائی۔ بے شک تو تعریف والا بزرگی والا ہے۔ اے اللہ! محمد اور آلِ محمد پر برکت نازل فرما جیسے تو نے ابراہیم اور آلِ ابراہیم پر برکت نازل فرمائی۔ بے شک تو تعریف والا بزرگی والا ہے۔ تم پر اللہ کی سلامتی اور رحمت ہو۔",
        ar: "اللهم صلِّ على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد. السلام عليكم ورحمة الله.",
        tr: "Allah'ım! Muhammed'e ve Muhammed'in ailesine rahmet eyle; İbrahim'e ve İbrahim'in ailesine rahmet ettiğin gibi. Şüphesiz Sen övülmeye layık ve yücesin. Allah'ım! Muhammed'e ve Muhammed'in ailesine bereket ver; İbrahim'e ve İbrahim'in ailesine bereket verdiğin gibi. Şüphesiz Sen övülmeye layık ve yücesin. Allah'ın selamı ve rahmeti üzerinize olsun.",
        ms: "Ya Allah, selawat ke atas Muhammad dan keluarga Muhammad sebagaimana Engkau selawat ke atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkati Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Salam sejahtera dan rahmat Allah ke atas kamu.",
        id: "Ya Allah, limpahkanlah selawat atas Muhammad dan keluarga Muhammad sebagaimana Engkau limpahkan selawat atas Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkati Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Salam sejahtera dan rahmat Allah atas kamu.",
      },
    },
  ],
  specialNotes: {
    en: "Maghrib should be prayed promptly after sunset without delay. It is recited aloud (Jahr) in the first 2 rakats and silently in the 3rd rakat.",
    bn: "মাগরিব সূর্যাস্তের পরপরই বিলম্ব না করে পড়া উচিত। প্রথম ২ রাকাতে সশব্দে (জাহর) এবং ৩য় রাকাতে নীরবে পড়া হয়।",
    ur: "مغرب غروب آفتاب کے فوراً بعد بغیر تاخیر کے پڑھنی چاہیے۔ پہلی ۲ رکعتوں میں بلند آواز سے (جہر) اور تیسری رکعت میں آہستہ پڑھی جاتی ہے۔",
    ar: "ينبغي أداء صلاة المغرب فور غروب الشمس دون تأخير. تُقرأ جهراً في الركعتين الأوليين وسراً في الركعة الثالثة.",
    tr: "Akşam namazı güneş battıktan hemen sonra gecikmeden kılınmalıdır. İlk 2 rekâtta sesli (cehri) ve 3. rekâtta sessiz kılınır.",
    ms: "Maghrib perlu ditunaikan segera selepas matahari terbenam tanpa berlengah. Ia dibaca dengan suara kuat (Jahr) pada 2 rakaat pertama dan senyap pada rakaat ke-3.",
    id: "Maghrib harus dikerjakan segera setelah matahari terbenam tanpa menunda. Dibaca dengan suara keras (Jahr) pada 2 rakaat pertama dan diam pada rakaat ke-3.",
  },
};
