import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const QADHA_PRAYER: PrayerInfo = {
  id: "qadha",
  name: { en: "Qadha (Missed Prayer)", bn: "কাযা (ছুটে যাওয়া নামাজ)", ur: "قضا (چھوٹی ہوئی نماز)", ar: "صلاة القضاء", tr: "Kaza Namazı", ms: "Solat Qadha", id: "Shalat Qadha" },
  arabicName: "صلاة القضاء",
  type: "fard",
  category: "special",
  totalRakats: "Same as original prayer",
  rakatBreakdown: { en: "Same number of rakats as the original missed prayer", bn: "মূল ছুটে যাওয়া নামাজের সমান রাকাত সংখ্যা", ur: "اصل چھوٹی ہوئی نماز کی رکعتوں کی تعداد کے برابر", ar: "نفس عدد ركعات الصلاة الأصلية الفائتة", tr: "Kaçırılan asıl namazın rekat sayısı kadar", ms: "Bilangan rakaat yang sama seperti solat asal yang tertinggal", id: "Jumlah rakaat yang sama seperti shalat asal yang terlewat" },
  time: { en: "As soon as possible after remembering the missed prayer", bn: "ছুটে যাওয়া নামাজ মনে পড়ার সাথে সাথে যত তাড়াতাড়ি সম্ভব", ur: "چھوٹی ہوئی نماز یاد آتے ہی جلد از جلد", ar: "فور تذكُّر الصلاة الفائتة في أقرب وقت", tr: "Kaçırılan namazı hatırlayınca mümkün olan en kısa sürede", ms: "Secepat mungkin selepas teringat solat yang tertinggal", id: "Sesegera mungkin setelah teringat shalat yang terlewat" },
  description: { en: "Qadha is making up missed Fard (obligatory) prayers. It must be prayed as soon as one remembers. If multiple prayers are missed consecutively, they should be prayed in chronological order. The prayer is performed exactly like the original prayer.", bn: "কাযা হলো ছুটে যাওয়া ফরজ নামাজ আদায় করা। মনে পড়ার সাথে সাথে আদায় করতে হবে। একাধিক নামাজ পরপর ছুটে গেলে ক্রমানুসারে আদায় করতে হবে। মূল নামাজের মতোই আদায় করা হয়।", ur: "قضا چھوٹی ہوئی فرض نمازوں کو ادا کرنا ہے۔ یاد آتے ہی فوراً ادا کرنی چاہیے۔ اگر متعدد نمازیں لگاتار چھوٹ جائیں تو ترتیب سے ادا کریں۔ نماز بالکل اصل نماز کی طرح ادا کی جاتی ہے۔", ar: "القضاء هو أداء الصلوات الفرض الفائتة. يجب أداؤها فور التذكر. إذا فاتت عدة صلوات متتالية فتُقضى بالترتيب الزمني. تُصلَّى بنفس طريقة الصلاة الأصلية.", tr: "Kaza, kaçırılan farz namazların telafi edilmesidir. Hatırlayınca hemen kılınmalıdır. Birden fazla namaz art arda kaçırılmışsa kronolojik sırayla kılınmalıdır. Namaz, asıl namaz gibi kılınır.", ms: "Qadha adalah menunaikan solat fardhu yang tertinggal. Mesti ditunaikan sebaik sahaja teringat. Jika beberapa solat tertinggal berturut-turut, hendaklah ditunaikan mengikut susunan. Solat dilakukan sama seperti solat asal.", id: "Qadha adalah menunaikan shalat fardhu yang terlewat. Harus dilakukan segera setelah teringat. Jika beberapa shalat terlewat berturut-turut, harus dilakukan secara berurutan. Shalat dilakukan sama persis seperti shalat aslinya." },
  steps: [
    // Step 1: Make intention specifying which missed prayer
    { stepNumber: 1, action: { en: "Make intention (Niyyah) specifying which missed prayer you are making up (e.g., 'I intend to pray Qadha of today's Fajr')", bn: "নিয়ত করুন কোন ছুটে যাওয়া নামাজ আদায় করছেন তা নির্দিষ্ট করে (যেমন, 'আমি আজকের ফজরের কাযা আদায়ের নিয়ত করছি')", ur: "نیت کریں کہ کون سی چھوٹی ہوئی نماز ادا کر رہے ہیں (مثلاً 'آج کی فجر کی قضا کی نیت کرتا ہوں')", ar: "انوِ تحديد الصلاة الفائتة التي تقضيها (مثلاً: 'أنوي قضاء صلاة فجر اليوم')", tr: "Hangi kaçırılan namazı kaza ettiğinizi belirterek niyet edin (örn. 'Bugünkü Sabah namazının kazasına niyet ettim')", ms: "Niat dengan menyatakan solat mana yang diqadha (cth. 'Aku berniat menunaikan qadha solat Subuh hari ini')", id: "Niat dengan menyebutkan shalat mana yang diqadha (cth. 'Aku berniat menunaikan qadha shalat Subuh hari ini')" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 2: Pray exactly like the original prayer
    { stepNumber: 2, action: { en: "Pray exactly like the original prayer with the same number of rakats (e.g., 2 for Fajr, 4 for Dhuhr, etc.)", bn: "মূল নামাজের মতোই একই রাকাত সংখ্যায় আদায় করুন (যেমন, ফজরের জন্য ২, যোহরের জন্য ৪ ইত্যাদি)", ur: "اصل نماز کی طرح اتنی ہی رکعتوں میں ادا کریں (مثلاً فجر کے لیے ۲، ظہر کے لیے ۴ وغیرہ)", ar: "صلِّ بنفس طريقة الصلاة الأصلية وبنفس عدد الركعات (مثلاً: ٢ للفجر، ٤ للظهر، إلخ)", tr: "Asıl namazı aynı rekat sayısıyla aynen kılın (örn. Sabah için 2, Öğle için 4, vb.)", ms: "Solat sama seperti solat asal dengan bilangan rakaat yang sama (cth. 2 untuk Subuh, 4 untuk Zuhur, dll.)", id: "Shalat sama persis seperti shalat aslinya dengan jumlah rakaat yang sama (cth. 2 untuk Subuh, 4 untuk Zuhur, dll.)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 3: Follow all the same steps
    { stepNumber: 3, action: { en: "Follow all the same steps of the original prayer — Takbir, Fatiha, Surah, Ruku, Sajdah, Tashahhud, Salam", bn: "মূল নামাজের সমস্ত ধাপ অনুসরণ করুন — তাকবীর, ফাতিহা, সূরা, রুকু, সিজদা, তাশাহহুদ, সালাম", ur: "اصل نماز کے تمام مراحل کی پیروی کریں — تکبیر، فاتحہ، سورت، رکوع، سجدہ، تشہد، سلام", ar: "اتبع جميع خطوات الصلاة الأصلية — تكبير، فاتحة، سورة، ركوع، سجود، تشهد، سلام", tr: "Asıl namazın tüm adımlarını takip edin — Tekbir, Fatiha, Sure, Rükû, Secde, Tahiyyat, Selam", ms: "Ikut semua langkah solat asal — Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam", id: "Ikuti semua langkah shalat aslinya — Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 4: Pray in chronological order if multiple missed
    { stepNumber: 4, action: { en: "If you have multiple missed prayers, pray them in chronological order (e.g., Fajr first, then Dhuhr, then Asr)", bn: "একাধিক ছুটে যাওয়া নামাজ থাকলে ক্রমানুসারে আদায় করুন (যেমন, প্রথমে ফজর, তারপর যোহর, তারপর আসর)", ur: "اگر متعدد نمازیں چھوٹی ہوئی ہوں تو ترتیب سے ادا کریں (مثلاً پہلے فجر، پھر ظہر، پھر عصر)", ar: "إذا فاتتك عدة صلوات فصلِّها بالترتيب الزمني (مثلاً: الفجر أولاً ثم الظهر ثم العصر)", tr: "Birden fazla kaçırılan namaz varsa kronolojik sırayla kılın (örn. önce Sabah, sonra Öğle, sonra İkindi)", ms: "Jika ada beberapa solat yang tertinggal, tunaikan mengikut susunan (cth. Subuh dahulu, kemudian Zuhur, kemudian Asar)", id: "Jika ada beberapa shalat yang terlewat, tunaikan secara berurutan (cth. Subuh dulu, kemudian Zuhur, kemudian Ashar)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 5: Make Tawbah
    { stepNumber: 5, action: { en: "Make sincere repentance (Tawbah) to Allah for missing the prayer and resolve not to miss prayers again", bn: "নামাজ ছুটে যাওয়ার জন্য আল্লাহর কাছে আন্তরিক তওবা করুন এবং আর নামাজ না ছাড়ার সংকল্প করুন", ur: "نماز چھوڑنے پر اللہ سے سچی توبہ کریں اور آئندہ نماز نہ چھوڑنے کا عزم کریں", ar: "تب إلى الله توبة نصوحاً على تفويت الصلاة واعزم على عدم تفويتها مرة أخرى", tr: "Namazı kaçırdığınız için Allah'a samimi tövbe edin ve bir daha kaçırmamaya karar verin", ms: "Bertaubat dengan ikhlas kepada Allah kerana meninggalkan solat dan berazam untuk tidak meninggalkan solat lagi", id: "Bertaubat dengan sungguh-sungguh kepada Allah karena meninggalkan shalat dan bertekad untuk tidak meninggalkan shalat lagi" }, arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", transliteration: "Astaghfirullaha wa atubu ilaih", meaning: { en: "I seek Allah's forgiveness and I repent to Him", bn: "আমি আল্লাহর ক্ষমা চাই এবং তাঁর কাছে তওবা করি", ur: "میں اللہ سے معافی مانگتا ہوں اور اس کی طرف توبہ کرتا ہوں", ar: "أستغفر الله وأتوب إليه", tr: "Allah'tan bağışlanma diler ve O'na tövbe ederim", ms: "Aku memohon keampunan Allah dan bertaubat kepada-Nya", id: "Aku memohon ampunan Allah dan bertaubat kepada-Nya" } },
  ],
  specialNotes: { en: "It is Fard (obligatory) to make up missed prayers — there is no excuse to skip them permanently. Qadha should be prayed as soon as one remembers the missed prayer. According to the Hanafi view, if less than 6 prayers have been missed, they must be prayed in order before the current prayer.", bn: "ছুটে যাওয়া নামাজ কাযা আদায় করা ফরজ — স্থায়ীভাবে ছেড়ে দেওয়ার কোনো অজুহাত নেই। মনে পড়ার সাথে সাথে কাযা আদায় করতে হবে। হানাফী মতে, ৬টির কম নামাজ ছুটে গেলে বর্তমান নামাজের আগে ক্রমানুসারে আদায় করতে হবে।", ur: "چھوٹی ہوئی نمازوں کی قضا ادا کرنا فرض ہے — انہیں مستقل چھوڑنے کا کوئی عذر نہیں۔ یاد آتے ہی فوراً قضا ادا کرنی چاہیے۔ حنفی نقطہ نظر کے مطابق، اگر ۶ سے کم نمازیں چھوٹی ہوں تو موجودہ نماز سے پہلے ترتیب سے ادا کرنی ضروری ہیں۔", ar: "قضاء الصلوات الفائتة فرض — لا عذر في تركها نهائياً. يجب قضاؤها فور التذكر. عند الحنفية: إذا فات أقل من ٦ صلوات فيجب قضاؤها بالترتيب قبل الصلاة الحاضرة.", tr: "Kaçırılan namazları kaza etmek farzdır — kalıcı olarak terk etmek için mazeret yoktur. Kaza, hatırlayınca hemen kılınmalıdır. Hanefi görüşüne göre, 6'dan az namaz kaçırılmışsa mevcut namazdan önce sırasıyla kılınmalıdır.", ms: "Mengqadha solat yang tertinggal adalah fardhu — tiada alasan untuk meninggalkannya secara kekal. Qadha hendaklah ditunaikan sebaik sahaja teringat. Menurut pandangan Hanafi, jika kurang daripada 6 solat tertinggal, ia mesti ditunaikan mengikut susunan sebelum solat semasa.", id: "Mengqadha shalat yang terlewat adalah fardhu — tidak ada alasan untuk meninggalkannya secara permanen. Qadha harus ditunaikan segera setelah teringat. Menurut pandangan Hanafi, jika kurang dari 6 shalat terlewat, harus ditunaikan secara berurutan sebelum shalat saat ini." },
};
