import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const TAHAJJUD_PRAYER: PrayerInfo = {
  id: "tahajjud",
  name: { en: "Tahajjud (Night Prayer)", bn: "তাহাজ্জুদ", ur: "تہجد", ar: "صلاة التهجد", tr: "Teheccüd", ms: "Tahajjud", id: "Tahajud" },
  arabicName: "صلاة التهجد",
  type: "nafl",
  category: "special",
  totalRakats: "2-12",
  rakatBreakdown: { en: "Prayed in sets of 2 rakats", bn: "২ রাকাত করে সেটে আদায় করা হয়", ur: "۲ رکعت کے جوڑوں میں ادا کی جاتی ہے", ar: "تُصلَّى مثنى مثنى (ركعتين ركعتين)", tr: "2'şer rekat halinde kılınır", ms: "Dilakukan dalam set 2 rakaat", id: "Dilakukan dalam set 2 rakaat" },
  time: { en: "Last third of the night (after sleeping, before Fajr)", bn: "রাতের শেষ তৃতীয়াংশে (ঘুমের পর, ফজরের আগে)", ur: "رات کا آخری تہائی حصہ (نیند کے بعد، فجر سے پہلے)", ar: "الثلث الأخير من الليل (بعد النوم وقبل الفجر)", tr: "Gecenin son üçte biri (uykudan sonra, Fecirden önce)", ms: "Sepertiga akhir malam (selepas tidur, sebelum Subuh)", id: "Sepertiga akhir malam (setelah tidur, sebelum Subuh)" },
  description: { en: "Tahajjud is the best voluntary prayer. It is prayed in the last third of the night in sets of 2 rakats after waking from sleep.", bn: "তাহাজ্জুদ সর্বোত্তম নফল নামাজ। ঘুম থেকে জেগে রাতের শেষ তৃতীয়াংশে ২ রাকাত করে আদায় করা হয়।", ur: "تہجد بہترین نفل نماز ہے۔ نیند سے بیدار ہو کر رات کے آخری تہائی حصے میں ۲ رکعت کے جوڑوں میں ادا کی جاتی ہے۔", ar: "التهجد أفضل صلاة النوافل. تُصلَّى في الثلث الأخير من الليل بعد الاستيقاظ من النوم، ركعتين ركعتين.", tr: "Teheccüd en faziletli nafile namazdır. Uykudan kalkıp gecenin son üçte birinde 2'şer rekat halinde kılınır.", ms: "Tahajjud adalah solat sunat yang paling utama. Dilakukan sepertiga akhir malam selepas bangun tidur dalam set 2 rakaat.", id: "Tahajud adalah shalat sunnah yang paling utama. Dilakukan sepertiga akhir malam setelah bangun tidur dalam set 2 rakaat." },
  steps: [
    // Step 1: Wake up and make intention
    { stepNumber: 1, action: { en: "Wake up in the last third of the night and make intention (Niyyah) for Tahajjud prayer", bn: "রাতের শেষ তৃতীয়াংশে জাগুন এবং তাহাজ্জুদ নামাজের নিয়ত করুন", ur: "رات کے آخری تہائی حصے میں بیدار ہوں اور تہجد نماز کی نیت کریں", ar: "استيقظ في الثلث الأخير من الليل وانوِ صلاة التهجد", tr: "Gecenin son üçte birinde uyanın ve Teheccüd namazı için niyet edin", ms: "Bangun pada sepertiga akhir malam dan niat solat Tahajjud", id: "Bangun pada sepertiga akhir malam dan niat shalat Tahajud" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 2: Make Wudu
    { stepNumber: 2, action: { en: "Perform Wudu (ablution) properly", bn: "সঠিকভাবে ওজু করুন", ur: "صحیح طریقے سے وضو کریں", ar: "توضأ وضوءاً كاملاً", tr: "Abdest alın", ms: "Ambil wuduk dengan sempurna", id: "Ambil wudhu dengan sempurna" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 3: Pray 2 rakats at a time
    { stepNumber: 3, action: { en: "Pray 2 rakats at a time — same as Fajr Fard prayer pattern (Niyyah, Takbir, Fatiha, Surah, Ruku, Sajdah, Tashahhud, Salam)", bn: "একবারে ২ রাকাত পড়ুন — ফজর ফরজ নামাজের মতো (নিয়ত, তাকবীর, ফাতিহা, সূরা, রুকু, সিজদা, তাশাহহুদ, সালাম)", ur: "ایک وقت میں ۲ رکعت پڑھیں — فجر فرض نماز کی طرح (نیت، تکبیر، فاتحہ، سورت، رکوع، سجدہ، تشہد، سلام)", ar: "صلِّ ركعتين ركعتين — بنفس طريقة فرض الفجر (نية، تكبير، فاتحة، سورة، ركوع، سجود، تشهد، سلام)", tr: "2'şer rekat kılın — Fajr farz namazı gibi (Niyet, Tekbir, Fatiha, Sure, Rükû, Secde, Tahiyyat, Selam)", ms: "Solat 2 rakaat pada satu masa — sama seperti solat fardhu Subuh (Niat, Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam)", id: "Shalat 2 rakaat pada satu waktu — sama seperti shalat fardhu Subuh (Niat, Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 4: Can pray up to 12 rakats
    { stepNumber: 4, action: { en: "Repeat in sets of 2 rakats — you can pray up to 12 rakats total (minimum 2, recommended 8)", bn: "২ রাকাত করে পুনরাবৃত্তি করুন — সর্বমোট ১২ রাকাত পর্যন্ত পড়তে পারেন (সর্বনিম্ন ২, প্রস্তাবিত ৮)", ur: "۲ رکعت کے جوڑوں میں دہرائیں — کل ۱۲ رکعت تک پڑھ سکتے ہیں (کم از کم ۲، تجویز کردہ ۸)", ar: "كرر ركعتين ركعتين — يمكنك صلاة حتى ١٢ ركعة (الحد الأدنى ٢، والمستحب ٨)", tr: "2'şer rekat tekrarlayın — toplam 12 rekata kadar kılabilirsiniz (en az 2, tavsiye edilen 8)", ms: "Ulang dalam set 2 rakaat — boleh solat sehingga 12 rakaat (minimum 2, disyorkan 8)", id: "Ulangi dalam set 2 rakaat — dapat shalat hingga 12 rakaat (minimum 2, disarankan 8)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 5: End with Witr
    { stepNumber: 5, action: { en: "End with Witr prayer if you have not already prayed it after Isha", bn: "শেষে বিতর নামাজ পড়ুন যদি ইশার পর আগে না পড়ে থাকেন", ur: "اگر عشاء کے بعد وتر نہیں پڑھی تو آخر میں وتر پڑھیں", ar: "اختم بصلاة الوتر إن لم تكن قد صليتها بعد العشاء", tr: "Yatsıdan sonra Vitir kılmadıysanız Vitir ile bitirin", ms: "Akhiri dengan solat Witir jika belum solat Witir selepas Isyak", id: "Akhiri dengan shalat Witir jika belum shalat Witir setelah Isya" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
  ],
  specialNotes: { en: "The best time for Tahajjud is the last third of the night. Allah descends to the lowest heaven in the last third of the night and says: 'Who is calling upon Me that I may answer him?' (Hadith, Bukhari & Muslim). Tahajjud is very highly recommended and was obligatory on the Prophet ﷺ.", bn: "তাহাজ্জুদের সর্বোত্তম সময় রাতের শেষ তৃতীয়াংশ। আল্লাহ রাতের শেষ তৃতীয়াংশে নিকটতম আসমানে অবতরণ করেন এবং বলেন: 'কে আমাকে ডাকছে যে আমি তার ডাকে সাড়া দেব?' (হাদীস, বুখারী ও মুসলিম)। তাহাজ্জুদ অত্যন্ত গুরুত্বপূর্ণ এবং নবী ﷺ এর উপর ফরজ ছিল।", ur: "تہجد کا بہترین وقت رات کا آخری تہائی حصہ ہے۔ اللہ تعالیٰ رات کے آخری تہائی حصے میں آسمانِ دنیا پر نزول فرماتے ہیں اور فرماتے ہیں: 'کون ہے جو مجھے پکارے تاکہ میں اسے جواب دوں؟' (حدیث، بخاری و مسلم)۔ تہجد انتہائی مستحب ہے اور نبی ﷺ پر فرض تھی۔", ar: "أفضل وقت للتهجد الثلث الأخير من الليل. ينزل الله إلى السماء الدنيا في الثلث الأخير ويقول: 'من يدعوني فأستجيب له؟' (حديث البخاري ومسلم). التهجد مستحب جداً وكان فرضاً على النبي ﷺ.", tr: "Teheccüd için en faziletli vakit gecenin son üçte biridir. Allah gecenin son üçte birinde dünya semasına iner ve 'Kim bana dua eder ki ona icabet edeyim?' buyurur (Hadis, Buhari ve Müslim). Teheccüd çok tavsiye edilen bir namazdır ve Hz. Peygamber ﷺ'e farzdı.", ms: "Waktu terbaik untuk Tahajjud ialah sepertiga akhir malam. Allah turun ke langit dunia pada sepertiga akhir malam dan berfirman: 'Siapakah yang berdoa kepada-Ku supaya Aku perkenankan?' (Hadis, Bukhari & Muslim). Tahajjud sangat digalakkan dan wajib ke atas Nabi ﷺ.", id: "Waktu terbaik untuk Tahajud adalah sepertiga akhir malam. Allah turun ke langit dunia pada sepertiga akhir malam dan berfirman: 'Siapakah yang berdoa kepada-Ku agar Aku kabulkan?' (Hadis, Bukhari & Muslim). Tahajud sangat dianjurkan dan wajib atas Nabi ﷺ." },
};
