import type { TransLang } from "@/lib/islamic-content";
import type { PrayerInfo } from "@/lib/how-to-pray-data";

export const TARAWEEH_PRAYER: PrayerInfo = {
  id: "taraweeh",
  name: { en: "Taraweeh", bn: "তারাবীহ", ur: "تراویح", ar: "التراويح", tr: "Teravih", ms: "Tarawih", id: "Tarawih" },
  arabicName: "صلاة التراويح",
  type: "sunnah",
  category: "special",
  totalRakats: "20 or 8",
  rakatBreakdown: { en: "20 rakats (Hanafi) or 8 rakats, in sets of 2", bn: "২০ রাকাত (হানাফী) বা ৮ রাকাত, ২ রাকাত করে সেটে", ur: "۲۰ رکعت (حنفی) یا ۸ رکعت، ۲ رکعت کے جوڑوں میں", ar: "٢٠ ركعة (الحنفية) أو ٨ ركعات، كل ركعتين بسلام", tr: "20 rekat (Hanefi) veya 8 rekat, 2'şer rekat halinde", ms: "20 rakaat (Hanafi) atau 8 rakaat, dalam set 2 rakaat", id: "20 rakaat (Hanafi) atau 8 rakaat, dalam set 2 rakaat" },
  time: { en: "After Isha prayer, during Ramadan only", bn: "শুধুমাত্র রমজানে, ইশার নামাজের পর", ur: "صرف رمضان میں، عشاء کی نماز کے بعد", ar: "بعد صلاة العشاء في رمضان فقط", tr: "Sadece Ramazan'da, Yatsı namazından sonra", ms: "Selepas solat Isyak, semasa Ramadan sahaja", id: "Setelah shalat Isya, selama Ramadan saja" },
  description: { en: "Taraweeh is a special Ramadan night prayer performed in congregation at the mosque. It is prayed in sets of 2 rakats after Isha prayer throughout the month of Ramadan.", bn: "তারাবীহ হলো রমজানের বিশেষ রাতের নামাজ যা মসজিদে জামাতে আদায় করা হয়। রমজান মাসে ইশার পর ২ রাকাত করে সেটে পড়া হয়।", ur: "تراویح رمضان کی خصوصی رات کی نماز ہے جو مسجد میں جماعت کے ساتھ ادا کی جاتی ہے۔ رمضان المبارک میں عشاء کے بعد ۲ رکعت کے جوڑوں میں پڑھی جاتی ہے۔", ar: "التراويح صلاة ليلية خاصة بشهر رمضان تُؤدَّى جماعةً في المسجد. تُصلَّى ركعتين ركعتين بعد صلاة العشاء طوال شهر رمضان.", tr: "Teravih, Ramazan'a özel cami cemaatiyle kılınan gece namazıdır. Ramazan boyunca Yatsı namazından sonra 2'şer rekat halinde kılınır.", ms: "Tarawih adalah solat malam khas Ramadan yang dilakukan secara berjemaah di masjid. Dilakukan dalam set 2 rakaat selepas solat Isyak sepanjang bulan Ramadan.", id: "Tarawih adalah shalat malam khusus Ramadan yang dilakukan secara berjamaah di masjid. Dilakukan dalam set 2 rakaat setelah shalat Isya sepanjang bulan Ramadan." },
  steps: [
    // Step 1: Pray after Isha
    { stepNumber: 1, action: { en: "Complete Isha prayer first, then stand for Taraweeh with the congregation", bn: "প্রথমে ইশার নামাজ সম্পন্ন করুন, তারপর জামাতের সাথে তারাবীহের জন্য দাঁড়ান", ur: "پہلے عشاء کی نماز مکمل کریں، پھر جماعت کے ساتھ تراویح کے لیے کھڑے ہوں", ar: "أتمّ صلاة العشاء أولاً ثم قم لصلاة التراويح مع الجماعة", tr: "Önce Yatsı namazını tamamlayın, sonra cemaatle Teravih için kalkın", ms: "Selesaikan solat Isyak dahulu, kemudian berdiri untuk Tarawih bersama jemaah", id: "Selesaikan shalat Isya terlebih dahulu, kemudian berdiri untuk Tarawih bersama jamaah" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 2: Pray 2 rakats at a time
    { stepNumber: 2, action: { en: "Pray 2 rakats at a time — same as regular 2 rakat prayer (Niyyah, Takbir, Fatiha, Surah, Ruku, Sajdah, Tashahhud, Salam)", bn: "একবারে ২ রাকাত পড়ুন — সাধারণ ২ রাকাত নামাজের মতো (নিয়ত, তাকবীর, ফাতিহা, সূরা, রুকু, সিজদা, তাশাহহুদ, সালাম)", ur: "ایک وقت میں ۲ رکعت پڑھیں — عام ۲ رکعت نماز کی طرح (نیت، تکبیر، فاتحہ، سورت، رکوع، سجدہ، تشہد، سلام)", ar: "صلِّ ركعتين — بنفس طريقة صلاة الركعتين العادية (نية، تكبير، فاتحة، سورة، ركوع، سجود، تشهد، سلام)", tr: "2 rekat kılın — normal 2 rekatlık namaz gibi (Niyet, Tekbir, Fatiha, Sure, Rükû, Secde, Tahiyyat, Selam)", ms: "Solat 2 rakaat — sama seperti solat 2 rakaat biasa (Niat, Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam)", id: "Shalat 2 rakaat — sama seperti shalat 2 rakaat biasa (Niat, Takbir, Fatihah, Surah, Rukuk, Sujud, Tahiyyat, Salam)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 3: Rest briefly between sets of 4
    { stepNumber: 3, action: { en: "Rest briefly between every set of 4 rakats (this rest is called Tarweeha)", bn: "প্রতি ৪ রাকাতের সেটের মাঝে সংক্ষিপ্ত বিশ্রাম নিন (এই বিশ্রামকে তারবীহা বলে)", ur: "ہر ۴ رکعت کے بعد مختصر آرام کریں (اس آرام کو ترویحہ کہتے ہیں)", ar: "استرح قليلاً بعد كل أربع ركعات (يُسمَّى هذا الاستراحة ترويحة)", tr: "Her 4 rekattan sonra kısa bir ara verin (bu araya Tarviha denir)", ms: "Rehat sebentar antara setiap set 4 rakaat (rehat ini dipanggil Tarwihah)", id: "Istirahat sebentar antara setiap set 4 rakaat (istirahat ini disebut Tarwihah)" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 4: Complete all rakats
    { stepNumber: 4, action: { en: "Complete all rakats — 20 rakats (Hanafi/traditional) or 8 rakats, following the Imam", bn: "সমস্ত রাকাত সম্পন্ন করুন — ২০ রাকাত (হানাফী/ঐতিহ্যবাহী) বা ৮ রাকাত, ইমামের অনুসরণে", ur: "تمام رکعات مکمل کریں — ۲۰ رکعت (حنفی/روایتی) یا ۸ رکعت، امام کی پیروی میں", ar: "أتمّ جميع الركعات — ٢٠ ركعة (الحنفية/التقليدي) أو ٨ ركعات، متابعاً للإمام", tr: "Tüm rekatları tamamlayın — 20 rekat (Hanefi/geleneksel) veya 8 rekat, imama uyarak", ms: "Lengkapkan semua rakaat — 20 rakaat (Hanafi/tradisional) atau 8 rakaat, mengikut imam", id: "Lengkapi semua rakaat — 20 rakaat (Hanafi/tradisional) atau 8 rakaat, mengikuti imam" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
    // Step 5: Pray Witr
    { stepNumber: 5, action: { en: "After completing Taraweeh, pray Witr prayer (3 rakats) in congregation with the Imam", bn: "তারাবীহ সম্পন্ন করার পর, ইমামের সাথে জামাতে বিতর নামাজ (৩ রাকাত) পড়ুন", ur: "تراویح مکمل کرنے کے بعد، امام کے ساتھ جماعت میں وتر نماز (۳ رکعت) پڑھیں", ar: "بعد إتمام التراويح، صلِّ الوتر (٣ ركعات) جماعةً مع الإمام", tr: "Teravih'i tamamladıktan sonra, imamla birlikte cemaatle Vitir namazı (3 rekat) kılın", ms: "Selepas selesai Tarawih, solat Witir (3 rakaat) secara berjemaah bersama imam", id: "Setelah selesai Tarawih, shalat Witir (3 rakaat) secara berjamaah bersama imam" }, arabic: "", transliteration: "", meaning: { en: "", bn: "", ur: "", ar: "", tr: "", ms: "", id: "" } },
  ],
  specialNotes: { en: "Taraweeh is Sunnah Muakkadah (strongly emphasized Sunnah) during Ramadan. It is highly encouraged to pray in congregation at the mosque. Many mosques aim to complete the entire Quran recitation during Taraweeh over the course of Ramadan.", bn: "তারাবীহ রমজানে সুন্নাতে মুআক্কাদা (অত্যন্ত গুরুত্বপূর্ণ সুন্নাত)। মসজিদে জামাতে পড়া অত্যন্ত উৎসাহিত। অনেক মসজিদে রমজানে তারাবীহের মাধ্যমে পুরো কুরআন তিলাওয়াত সম্পন্ন করা হয়।", ur: "تراویح رمضان میں سنت مؤکدہ ہے۔ مسجد میں جماعت کے ساتھ پڑھنا انتہائی مستحب ہے۔ بہت سی مساجد میں رمضان کے دوران تراویح میں پورا قرآن مکمل کرنے کا اہتمام کیا جاتا ہے۔", ar: "التراويح سنة مؤكدة في رمضان. يُستحب صلاتها جماعة في المسجد. تحرص كثير من المساجد على ختم القرآن الكريم كاملاً خلال صلاة التراويح في رمضان.", tr: "Teravih, Ramazan'da sünnet-i müekkededir. Camide cemaatle kılınması çok tavsiye edilir. Birçok camide Ramazan boyunca Teravih'te Kur'an hatmi yapılır.", ms: "Tarawih adalah Sunat Muakkad semasa Ramadan. Sangat digalakkan untuk bersolat secara berjemaah di masjid. Banyak masjid bertujuan untuk mengkhatamkan seluruh Al-Quran semasa Tarawih sepanjang Ramadan.", id: "Tarawih adalah Sunnah Muakkad selama Ramadan. Sangat dianjurkan untuk shalat secara berjamaah di masjid. Banyak masjid bertujuan mengkhatamkan seluruh Al-Quran selama Tarawih sepanjang Ramadan." },
};
