import type { TransLang } from "@/lib/islamic-content";

export interface AsmaUlHusna {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: Record<TransLang, string>;
  shortDescription: Record<TransLang, string>;
  quranReference?: string;
}

export const ASMA_UL_HUSNA: AsmaUlHusna[] = [
  {
    id: 1,
    arabic: "الرَّحْمَٰنُ",
    transliteration: "Ar-Rahman",
    meaning: { en: "The Most Gracious", bn: "পরম করুণাময়", ur: "بے حد مہربان", ar: "الرحمن", tr: "Rahman", ms: "Yang Maha Pemurah", id: "Yang Maha Pengasih" },
    shortDescription: { en: "He who bestows boundless grace and mercy upon all creation.", bn: "যিনি সমস্ত সৃষ্টির উপর অসীম অনুগ্রহ ও দয়া বর্ষণ করেন।", ur: "جو تمام مخلوقات پر بے حد فضل اور رحمت نازل کرتا ہے۔", ar: "الذي يمنح النعمة والرحمة اللامتناهية لجميع المخلوقات.", tr: "Tüm yaratılmışlara sınırsız lütuf ve merhamet bahşeden.", ms: "Yang melimpahkan rahmat dan kurnia tanpa batas kepada seluruh makhluk.", id: "Yang melimpahkan rahmat dan karunia tanpa batas kepada seluruh makhluk." },
    quranReference: "1:1",
  },
  {
    id: 2,
    arabic: "الرَّحِيمُ",
    transliteration: "Ar-Raheem",
    meaning: { en: "The Most Merciful", bn: "পরম দয়ালু", ur: "نہایت رحم کرنے والا", ar: "الرحيم", tr: "Rahim", ms: "Yang Maha Penyayang", id: "Yang Maha Penyayang" },
    shortDescription: { en: "He who bestows special mercy upon the believers.", bn: "যিনি বিশেষভাবে মুমিনদের প্রতি দয়া করেন।", ur: "جو خاص طور پر مومنوں پر رحمت فرماتا ہے۔", ar: "الذي يختص المؤمنين برحمته الخاصة.", tr: "Müminlere özel rahmetiyle lütufta bulunan.", ms: "Yang menganugerahkan rahmat khusus kepada orang-orang beriman.", id: "Yang menganugerahkan rahmat khusus kepada orang-orang beriman." },
    quranReference: "2:163",
  },
  {
    id: 3,
    arabic: "الْمَلِكُ",
    transliteration: "Al-Malik",
    meaning: { en: "The King", bn: "রাজাধিরাজ", ur: "بادشاہ", ar: "الملك", tr: "Melik", ms: "Yang Maha Raja", id: "Yang Maha Raja" },
    shortDescription: { en: "He who is the absolute sovereign and ruler of all that exists.", bn: "যিনি সমস্ত অস্তিত্বের পরম সার্বভৌম ও শাসনকর্তা।", ur: "جو تمام موجودات کا مطلق حکمران اور بادشاہ ہے۔", ar: "الذي هو المالك المطلق والحاكم على كل ما هو موجود.", tr: "Var olan her şeyin mutlak hükümdarı ve yöneticisi.", ms: "Yang merupakan pemerintah mutlak bagi segala yang wujud.", id: "Yang merupakan penguasa mutlak atas segala yang ada." },
    quranReference: "59:23",
  },
  {
    id: 4,
    arabic: "الْقُدُّوسُ",
    transliteration: "Al-Quddus",
    meaning: { en: "The Most Holy", bn: "পবিত্রতম", ur: "پاک ذات", ar: "القدوس", tr: "Kuddüs", ms: "Yang Maha Suci", id: "Yang Maha Suci" },
    shortDescription: { en: "He who is free from all imperfections and defects.", bn: "যিনি সমস্ত অসম্পূর্ণতা ও ত্রুটি থেকে মুক্ত।", ur: "جو ہر نقص اور عیب سے پاک ہے۔", ar: "المنزّه عن كل نقص وعيب.", tr: "Her türlü kusur ve eksiklikten münezzeh olan.", ms: "Yang bersih daripada segala kekurangan dan kecacatan.", id: "Yang bersih dari segala kekurangan dan kecacatan." },
    quranReference: "59:23",
  },
  {
    id: 5,
    arabic: "السَّلَامُ",
    transliteration: "As-Salam",
    meaning: { en: "The Source of Peace", bn: "শান্তির উৎস", ur: "سلامتی دینے والا", ar: "السلام", tr: "Selam", ms: "Yang Maha Sejahtera", id: "Yang Maha Sejahtera" },
    shortDescription: { en: "He who is the source of all peace and safety.", bn: "যিনি সমস্ত শান্তি ও নিরাপত্তার উৎস।", ur: "جو تمام امن اور سلامتی کا سرچشمہ ہے۔", ar: "الذي هو مصدر كل سلام وأمان.", tr: "Tüm barış ve güvenliğin kaynağı olan.", ms: "Yang menjadi sumber segala kedamaian dan keselamatan.", id: "Yang menjadi sumber segala kedamaian dan keselamatan." },
    quranReference: "59:23",
  },
  {
    id: 6,
    arabic: "الْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    meaning: { en: "The Guardian of Faith", bn: "বিশ্বাসের রক্ষক", ur: "امن دینے والا", ar: "المؤمن", tr: "Mü'min", ms: "Yang Maha Pengaman", id: "Yang Maha Pengaman" },
    shortDescription: { en: "He who grants security and confirms the faith of His servants.", bn: "যিনি নিরাপত্তা প্রদান করেন এবং বান্দাদের ঈমান নিশ্চিত করেন।", ur: "جو امان عطا کرتا ہے اور اپنے بندوں کے ایمان کی تصدیق کرتا ہے۔", ar: "الذي يمنح الأمان ويصدق إيمان عباده.", tr: "Kullarına güven veren ve imanlarını tasdik eden.", ms: "Yang memberi keamanan dan mengesahkan iman hamba-hamba-Nya.", id: "Yang memberi keamanan dan membenarkan iman hamba-hamba-Nya." },
    quranReference: "59:23",
  },
  {
    id: 7,
    arabic: "الْمُهَيْمِنُ",
    transliteration: "Al-Muhaymin",
    meaning: { en: "The Protector", bn: "রক্ষাকারী", ur: "نگہبان", ar: "المهيمن", tr: "Müheymin", ms: "Yang Maha Pemelihara", id: "Yang Maha Pemelihara" },
    shortDescription: { en: "He who watches over and protects all of creation.", bn: "যিনি সমস্ত সৃষ্টির উপর নজর রাখেন এবং রক্ষা করেন।", ur: "جو تمام مخلوقات کی نگرانی اور حفاظت کرتا ہے۔", ar: "الذي يراقب ويحفظ جميع المخلوقات.", tr: "Tüm yaratılmışları gözetip koruyan.", ms: "Yang mengawasi dan melindungi seluruh makhluk.", id: "Yang mengawasi dan melindungi seluruh makhluk." },
    quranReference: "59:23",
  },
  {
    id: 8,
    arabic: "الْعَزِيزُ",
    transliteration: "Al-Aziz",
    meaning: { en: "The Almighty", bn: "পরাক্রমশালী", ur: "غالب", ar: "العزيز", tr: "Aziz", ms: "Yang Maha Perkasa", id: "Yang Maha Perkasa" },
    shortDescription: { en: "He who possesses absolute might and is unmatched in power.", bn: "যিনি পরম শক্তির অধিকারী এবং ক্ষমতায় যার কোনো তুলনা নেই।", ur: "جو مطلق طاقت کا مالک ہے اور قوت میں بے مثال ہے۔", ar: "الذي يملك القوة المطلقة ولا مثيل له في العزة.", tr: "Mutlak güce sahip ve kudretinde eşsiz olan.", ms: "Yang memiliki kekuasaan mutlak dan tiada tandingan dalam kekuatan.", id: "Yang memiliki kekuasaan mutlak dan tiada tandingan dalam kekuatan." },
    quranReference: "59:23",
  },
  {
    id: 9,
    arabic: "الْجَبَّارُ",
    transliteration: "Al-Jabbar",
    meaning: { en: "The Compeller", bn: "পরাক্রান্ত", ur: "زبردست", ar: "الجبار", tr: "Cebbar", ms: "Yang Maha Pemaksa", id: "Yang Maha Pemaksa" },
    shortDescription: { en: "He who compels all things according to His divine will.", bn: "যিনি নিজ ইচ্ছায় সবকিছু পরিচালিত করেন।", ur: "جو اپنی الہٰی مرضی کے مطابق سب کچھ چلاتا ہے۔", ar: "الذي يُخضع كل شيء لإرادته الإلهية.", tr: "İlahi iradesiyle her şeyi yönlendiren.", ms: "Yang menundukkan segala sesuatu mengikut kehendak-Nya.", id: "Yang menundukkan segala sesuatu sesuai kehendak-Nya." },
    quranReference: "59:23",
  },
  {
    id: 10,
    arabic: "الْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    meaning: { en: "The Supreme", bn: "শ্রেষ্ঠ", ur: "بڑائی والا", ar: "المتكبر", tr: "Mütekebbir", ms: "Yang Maha Megah", id: "Yang Maha Megah" },
    shortDescription: { en: "He who is supreme in greatness and above all creation.", bn: "যিনি মহিমায় সর্বোচ্চ এবং সমস্ত সৃষ্টির ঊর্ধ্বে।", ur: "جو عظمت میں سب سے بلند اور تمام مخلوقات سے برتر ہے۔", ar: "المتعالي في عظمته فوق جميع المخلوقات.", tr: "Büyüklükte en yüce ve tüm yaratılmışların üzerinde olan.", ms: "Yang maha agung dan mengatasi seluruh makhluk.", id: "Yang maha agung dan mengatasi seluruh makhluk." },
    quranReference: "59:23",
  },
  {
    id: 11,
    arabic: "الْخَالِقُ",
    transliteration: "Al-Khaliq",
    meaning: { en: "The Creator", bn: "সৃষ্টিকর্তা", ur: "پیدا کرنے والا", ar: "الخالق", tr: "Halık", ms: "Yang Maha Pencipta", id: "Yang Maha Pencipta" },
    shortDescription: { en: "He who creates everything from nothing.", bn: "যিনি শূন্য থেকে সবকিছু সৃষ্টি করেন।", ur: "جو عدم سے ہر چیز کو پیدا کرتا ہے۔", ar: "الذي يخلق كل شيء من العدم.", tr: "Yoktan her şeyi yaratan.", ms: "Yang mencipta segala sesuatu dari tiada.", id: "Yang menciptakan segala sesuatu dari tiada." },
    quranReference: "59:24",
  },
  {
    id: 12,
    arabic: "الْبَارِئُ",
    transliteration: "Al-Bari'",
    meaning: { en: "The Originator", bn: "উদ্ভাবনকারী", ur: "بنانے والا", ar: "البارئ", tr: "Bari", ms: "Yang Maha Mengadakan", id: "Yang Maha Mengadakan" },
    shortDescription: { en: "He who brings creation into being with perfect harmony.", bn: "যিনি নিখুঁত সামঞ্জস্যে সৃষ্টিকে অস্তিত্বে আনেন।", ur: "جو کامل ہم آہنگی کے ساتھ مخلوقات کو وجود بخشتا ہے۔", ar: "الذي يوجد الخلق في انسجام تام.", tr: "Yaratılışı mükemmel bir uyumla var eden.", ms: "Yang mewujudkan makhluk dengan keharmonian yang sempurna.", id: "Yang mewujudkan makhluk dengan keharmonisan yang sempurna." },
    quranReference: "59:24",
  },
  {
    id: 13,
    arabic: "الْمُصَوِّرُ",
    transliteration: "Al-Musawwir",
    meaning: { en: "The Fashioner", bn: "আকৃতিদাতা", ur: "صورت بنانے والا", ar: "المصور", tr: "Musavvir", ms: "Yang Maha Pembentuk", id: "Yang Maha Pembentuk" },
    shortDescription: { en: "He who shapes and fashions each creation in a unique form.", bn: "যিনি প্রতিটি সৃষ্টিকে অনন্য আকৃতিতে গড়েন।", ur: "جو ہر مخلوق کو منفرد شکل میں ڈھالتا ہے۔", ar: "الذي يشكّل كل مخلوق في صورة فريدة.", tr: "Her yaratılışa benzersiz bir biçim veren.", ms: "Yang membentuk setiap makhluk dalam rupa yang unik.", id: "Yang membentuk setiap makhluk dalam rupa yang unik." },
    quranReference: "59:24",
  },
  {
    id: 14,
    arabic: "الْغَفَّارُ",
    transliteration: "Al-Ghaffar",
    meaning: { en: "The Forgiver", bn: "ক্ষমাশীল", ur: "بہت بخشنے والا", ar: "الغفار", tr: "Gaffar", ms: "Yang Maha Pengampun", id: "Yang Maha Pengampun" },
    shortDescription: { en: "He who forgives sins repeatedly and without limit.", bn: "যিনি বারবার এবং সীমাহীনভাবে পাপ ক্ষমা করেন।", ur: "جو بار بار اور بے حد گناہ معاف کرتا ہے۔", ar: "الذي يغفر الذنوب مرارًا وبلا حدود.", tr: "Günahları tekrar tekrar ve sınırsızca bağışlayan.", ms: "Yang mengampuni dosa berulang kali tanpa batas.", id: "Yang mengampuni dosa berulang kali tanpa batas." },
    quranReference: "20:82",
  },
  {
    id: 15,
    arabic: "الْقَهَّارُ",
    transliteration: "Al-Qahhar",
    meaning: { en: "The Subduer", bn: "পরাভূতকারী", ur: "سب پر غالب", ar: "القهار", tr: "Kahhar", ms: "Yang Maha Penunduk", id: "Yang Maha Penunduk" },
    shortDescription: { en: "He who dominates and overcomes all things with His power.", bn: "যিনি নিজ শক্তিতে সবকিছুর উপর আধিপত্য বিস্তার করেন।", ur: "جو اپنی قوت سے ہر چیز پر غالب ہے۔", ar: "الذي يقهر كل شيء بقدرته.", tr: "Kudretiyle her şeye galip gelen.", ms: "Yang menguasai dan mengatasi segala sesuatu dengan kekuasaan-Nya.", id: "Yang menguasai dan mengatasi segala sesuatu dengan kekuasaan-Nya." },
    quranReference: "13:16",
  },
  {
    id: 16,
    arabic: "الْوَهَّابُ",
    transliteration: "Al-Wahhab",
    meaning: { en: "The Bestower", bn: "মহাদাতা", ur: "بہت عطا کرنے والا", ar: "الوهاب", tr: "Vehhab", ms: "Yang Maha Pemberi", id: "Yang Maha Pemberi" },
    shortDescription: { en: "He who gives generously without expecting anything in return.", bn: "যিনি বিনিময়ের আশা ছাড়াই উদারভাবে দান করেন।", ur: "جو بغیر کسی عوض کے فراخدلی سے عطا کرتا ہے۔", ar: "الذي يعطي بسخاء دون انتظار مقابل.", tr: "Karşılık beklemeden cömertçe bağışlayan.", ms: "Yang memberi dengan murah hati tanpa mengharapkan balasan.", id: "Yang memberi dengan murah hati tanpa mengharapkan balasan." },
    quranReference: "3:8",
  },
  {
    id: 17,
    arabic: "الرَّزَّاقُ",
    transliteration: "Ar-Razzaq",
    meaning: { en: "The Provider", bn: "রিযিকদাতা", ur: "رزق دینے والا", ar: "الرزاق", tr: "Rezzak", ms: "Yang Maha Pemberi Rezeki", id: "Yang Maha Pemberi Rezeki" },
    shortDescription: { en: "He who provides sustenance to all living beings.", bn: "যিনি সকল জীবকে রিযিক প্রদান করেন।", ur: "جو تمام جانداروں کو رزق فراہم کرتا ہے۔", ar: "الذي يرزق جميع الكائنات الحية.", tr: "Tüm canlılara rızık veren.", ms: "Yang memberikan rezeki kepada semua makhluk hidup.", id: "Yang memberikan rezeki kepada semua makhluk hidup." },
    quranReference: "51:58",
  },
  {
    id: 18,
    arabic: "الْفَتَّاحُ",
    transliteration: "Al-Fattah",
    meaning: { en: "The Opener", bn: "উন্মোচনকারী", ur: "فیصلہ کرنے والا", ar: "الفتاح", tr: "Fettah", ms: "Yang Maha Pembuka", id: "Yang Maha Pembuka" },
    shortDescription: { en: "He who opens the doors of mercy, sustenance, and truth.", bn: "যিনি রহমত, রিযিক এবং সত্যের দরজা খুলে দেন।", ur: "جو رحمت، رزق اور سچائی کے دروازے کھولتا ہے۔", ar: "الذي يفتح أبواب الرحمة والرزق والحق.", tr: "Rahmet, rızık ve hakikat kapılarını açan.", ms: "Yang membuka pintu rahmat, rezeki, dan kebenaran.", id: "Yang membuka pintu rahmat, rezeki, dan kebenaran." },
    quranReference: "34:26",
  },
  {
    id: 19,
    arabic: "الْعَلِيمُ",
    transliteration: "Al-'Aleem",
    meaning: { en: "The All-Knowing", bn: "সর্বজ্ঞ", ur: "سب کچھ جاننے والا", ar: "العليم", tr: "Alim", ms: "Yang Maha Mengetahui", id: "Yang Maha Mengetahui" },
    shortDescription: { en: "He whose knowledge encompasses everything, seen and unseen.", bn: "যিনি দৃশ্য-অদৃশ্য সবকিছু সম্পর্কে জ্ঞান রাখেন।", ur: "جس کا علم ہر ظاہر و پوشیدہ چیز کو محیط ہے۔", ar: "الذي يحيط علمه بكل شيء، الظاهر والباطن.", tr: "Bilgisi görünen ve görünmeyen her şeyi kapsayan.", ms: "Yang ilmu-Nya meliputi segala sesuatu, yang zahir dan yang ghaib.", id: "Yang ilmu-Nya meliputi segala sesuatu, yang tampak dan yang gaib." },
    quranReference: "2:158",
  },
  {
    id: 20,
    arabic: "الْقَابِضُ",
    transliteration: "Al-Qabid",
    meaning: { en: "The Constrictor", bn: "সংকোচনকারী", ur: "روزی تنگ کرنے والا", ar: "القابض", tr: "Kabıd", ms: "Yang Maha Penyempit", id: "Yang Maha Penyempit" },
    shortDescription: { en: "He who constricts and withholds as He wills in His wisdom.", bn: "যিনি নিজ প্রজ্ঞায় ইচ্ছামতো সংকুচিত ও রুদ্ধ করেন।", ur: "جو اپنی حکمت سے جیسے چاہے تنگ کرتا ہے۔", ar: "الذي يقبض ويمنع كما يشاء بحكمته.", tr: "Hikmetiyle dilediği gibi daraltıp tutan.", ms: "Yang menyempitkan dan menahan mengikut hikmah-Nya.", id: "Yang menyempitkan dan menahan sesuai hikmah-Nya." },
  },
  {
    id: 21,
    arabic: "الْبَاسِطُ",
    transliteration: "Al-Basit",
    meaning: { en: "The Expander", bn: "প্রসারণকারী", ur: "روزی کشادہ کرنے والا", ar: "الباسط", tr: "Basıt", ms: "Yang Maha Melapangkan", id: "Yang Maha Melapangkan" },
    shortDescription: { en: "He who expands and extends His provision and mercy generously.", bn: "যিনি উদারভাবে রিযিক ও রহমত প্রসারিত করেন।", ur: "جو فراخدلی سے اپنا رزق اور رحمت پھیلاتا ہے۔", ar: "الذي يبسط رزقه ورحمته بسخاء.", tr: "Rızkını ve rahmetini cömertçe genişleten.", ms: "Yang melapangkan rezeki dan rahmat-Nya dengan murah hati.", id: "Yang melapangkan rezeki dan rahmat-Nya dengan murah hati." },
  },
  {
    id: 22,
    arabic: "الْخَافِضُ",
    transliteration: "Al-Khafid",
    meaning: { en: "The Abaser", bn: "অবনমনকারী", ur: "پست کرنے والا", ar: "الخافض", tr: "Hafıd", ms: "Yang Maha Merendahkan", id: "Yang Maha Merendahkan" },
    shortDescription: { en: "He who lowers and humbles the arrogant and the unjust.", bn: "যিনি অহংকারী ও অন্যায়কারীদের অবনত ও লাঞ্ছিত করেন।", ur: "جو متکبروں اور ظالموں کو پست اور ذلیل کرتا ہے۔", ar: "الذي يخفض المتكبرين والظالمين.", tr: "Kibirlileri ve zalimleri alçaltan.", ms: "Yang merendahkan orang-orang yang sombong dan zalim.", id: "Yang merendahkan orang-orang yang sombong dan zalim." },
  },
  {
    id: 23,
    arabic: "الرَّافِعُ",
    transliteration: "Ar-Rafi'",
    meaning: { en: "The Exalter", bn: "উন্নীতকারী", ur: "بلند کرنے والا", ar: "الرافع", tr: "Rafi", ms: "Yang Maha Meninggikan", id: "Yang Maha Meninggikan" },
    shortDescription: { en: "He who raises the status of whomever He wills.", bn: "যিনি যাকে ইচ্ছা তার মর্যাদা উন্নীত করেন।", ur: "جو جسے چاہے اس کا مرتبہ بلند کرتا ہے۔", ar: "الذي يرفع منزلة من يشاء.", tr: "Dilediğinin derecesini yükselten.", ms: "Yang meninggikan darjat sesiapa yang dikehendaki-Nya.", id: "Yang meninggikan derajat siapa saja yang dikehendaki-Nya." },
    quranReference: "58:11",
  },
  {
    id: 24,
    arabic: "الْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    meaning: { en: "The Honorer", bn: "সম্মানদাতা", ur: "عزت دینے والا", ar: "المعز", tr: "Muiz", ms: "Yang Maha Memuliakan", id: "Yang Maha Memuliakan" },
    shortDescription: { en: "He who grants honor and dignity to whomever He wills.", bn: "যিনি যাকে ইচ্ছা সম্মান ও মর্যাদা দান করেন।", ur: "جو جسے چاہے عزت اور وقار عطا کرتا ہے۔", ar: "الذي يمنح العزة والكرامة لمن يشاء.", tr: "Dilediğine izzet ve şeref veren.", ms: "Yang menganugerahkan kemuliaan dan kehormatan kepada sesiapa yang dikehendaki-Nya.", id: "Yang menganugerahkan kemuliaan dan kehormatan kepada siapa saja yang dikehendaki-Nya." },
    quranReference: "3:26",
  },
  {
    id: 25,
    arabic: "الْمُذِلُّ",
    transliteration: "Al-Mudhill",
    meaning: { en: "The Humiliator", bn: "অপমানকারী", ur: "ذلیل کرنے والا", ar: "المذل", tr: "Müzill", ms: "Yang Maha Menghinakan", id: "Yang Maha Menghinakan" },
    shortDescription: { en: "He who humiliates and disgraces those who oppose His will.", bn: "যিনি তাঁর ইচ্ছার বিরোধীদের লাঞ্ছিত ও অপমানিত করেন।", ur: "جو اپنی مرضی کے مخالفوں کو ذلیل و رسوا کرتا ہے۔", ar: "الذي يذل من يعارض إرادته.", tr: "İradesine karşı gelenleri alçaltıp zillete düşüren.", ms: "Yang menghinakan mereka yang menentang kehendak-Nya.", id: "Yang menghinakan mereka yang menentang kehendak-Nya." },
    quranReference: "3:26",
  },
  {
    id: 26,
    arabic: "السَّمِيعُ",
    transliteration: "As-Sami'",
    meaning: { en: "The All-Hearing", bn: "সর্বশ্রোতা", ur: "سب کچھ سننے والا", ar: "السميع", tr: "Semi", ms: "Yang Maha Mendengar", id: "Yang Maha Mendengar" },
    shortDescription: { en: "He who hears all things, whether spoken aloud or whispered in the heart.", bn: "যিনি সবকিছু শোনেন, প্রকাশ্যে বলা হোক বা হৃদয়ে ফিসফিস করা হোক।", ur: "جو سب کچھ سنتا ہے، چاہے بلند آواز سے کہا جائے یا دل میں۔", ar: "الذي يسمع كل شيء، ما يُجهر به وما يُسرّ في القلوب.", tr: "Açıkça söylenen ya da kalpte fısıldanan her şeyi işiten.", ms: "Yang mendengar segala sesuatu, sama ada yang dizahirkan atau yang dibisikkan dalam hati.", id: "Yang mendengar segala sesuatu, baik yang diucapkan maupun yang dibisikkan dalam hati." },
    quranReference: "2:127",
  },
  {
    id: 27,
    arabic: "الْبَصِيرُ",
    transliteration: "Al-Basir",
    meaning: { en: "The All-Seeing", bn: "সর্বদ্রষ্টা", ur: "سب کچھ دیکھنے والا", ar: "البصير", tr: "Basir", ms: "Yang Maha Melihat", id: "Yang Maha Melihat" },
    shortDescription: { en: "He who sees all things, nothing is hidden from His sight.", bn: "যিনি সবকিছু দেখেন, কিছুই তাঁর দৃষ্টি থেকে গোপন নয়।", ur: "جو سب کچھ دیکھتا ہے، کوئی چیز اس کی نظر سے پوشیدہ نہیں۔", ar: "الذي يرى كل شيء، ولا يخفى عليه شيء.", tr: "Her şeyi gören, hiçbir şey gözünden kaçmayan.", ms: "Yang melihat segala sesuatu, tiada yang tersembunyi daripada penglihatan-Nya.", id: "Yang melihat segala sesuatu, tiada yang tersembunyi dari penglihatan-Nya." },
    quranReference: "42:11",
  },
  {
    id: 28,
    arabic: "الْحَكَمُ",
    transliteration: "Al-Hakam",
    meaning: { en: "The Judge", bn: "বিচারক", ur: "فیصلہ کرنے والا", ar: "الحكم", tr: "Hakem", ms: "Yang Maha Memutuskan", id: "Yang Maha Memutuskan" },
    shortDescription: { en: "He who judges between His creation with absolute justice.", bn: "যিনি সৃষ্টির মধ্যে পরম ন্যায়ে বিচার করেন।", ur: "جو اپنی مخلوقات کے درمیان مکمل انصاف سے فیصلہ کرتا ہے۔", ar: "الذي يحكم بين خلقه بالعدل المطلق.", tr: "Yarattıkları arasında mutlak adaletle hükmeden.", ms: "Yang menghakimi antara makhluk-Nya dengan keadilan mutlak.", id: "Yang menghakimi antara makhluk-Nya dengan keadilan mutlak." },
    quranReference: "6:114",
  },
  {
    id: 29,
    arabic: "الْعَدْلُ",
    transliteration: "Al-'Adl",
    meaning: { en: "The Just", bn: "ন্যায়পরায়ণ", ur: "انصاف کرنے والا", ar: "العدل", tr: "Adl", ms: "Yang Maha Adil", id: "Yang Maha Adil" },
    shortDescription: { en: "He who is perfectly just and never wrongs anyone.", bn: "যিনি সম্পূর্ণ ন্যায়পরায়ণ এবং কারো প্রতি অন্যায় করেন না।", ur: "جو بالکل منصف ہے اور کسی پر ظلم نہیں کرتا۔", ar: "الذي هو عادل تمامًا ولا يظلم أحدًا.", tr: "Tamamen adil olan ve kimseye zulmetmeyen.", ms: "Yang maha adil dan tidak pernah menzalimi sesiapapun.", id: "Yang maha adil dan tidak pernah menzalimi siapapun." },
  },
  {
    id: 30,
    arabic: "اللَّطِيفُ",
    transliteration: "Al-Latif",
    meaning: { en: "The Subtle", bn: "সূক্ষ্মদর্শী", ur: "باریک بین", ar: "اللطيف", tr: "Latif", ms: "Yang Maha Halus", id: "Yang Maha Halus" },
    shortDescription: { en: "He who is subtle in His actions and kind to His servants in unseen ways.", bn: "যিনি কর্মে সূক্ষ্ম এবং অদৃশ্যভাবে বান্দাদের প্রতি দয়ালু।", ur: "جو اپنے افعال میں لطیف اور پوشیدہ طریقوں سے بندوں پر مہربان ہے۔", ar: "اللطيف في أفعاله والرفيق بعباده بطرق خفية.", tr: "Fiillerinde ince ve kullarına görünmeyen yollarla lütufkâr olan.", ms: "Yang halus dalam tindakan-Nya dan baik kepada hamba-Nya dengan cara yang tidak kelihatan.", id: "Yang halus dalam tindakan-Nya dan baik kepada hamba-Nya dengan cara yang tidak terlihat." },
    quranReference: "6:103",
  },
  {
    id: 31,
    arabic: "الْخَبِيرُ",
    transliteration: "Al-Khabir",
    meaning: { en: "The All-Aware", bn: "সর্ববিষয়ে অবহিত", ur: "باخبر", ar: "الخبير", tr: "Habir", ms: "Yang Maha Mengetahui", id: "Yang Maha Mengetahui" },
    shortDescription: { en: "He who is aware of the innermost secrets of all things.", bn: "যিনি সবকিছুর অন্তর্নিহিত রহস্য সম্পর্কে অবগত।", ur: "جو ہر چیز کے اندرونی رازوں سے آگاہ ہے۔", ar: "الذي يعلم أدق أسرار كل شيء.", tr: "Her şeyin en gizli sırlarından haberdar olan.", ms: "Yang mengetahui rahsia terdalam segala sesuatu.", id: "Yang mengetahui rahasia terdalam segala sesuatu." },
    quranReference: "6:18",
  },
  {
    id: 32,
    arabic: "الْحَلِيمُ",
    transliteration: "Al-Halim",
    meaning: { en: "The Forbearing", bn: "ধৈর্যশীল", ur: "بردبار", ar: "الحليم", tr: "Halim", ms: "Yang Maha Penyantun", id: "Yang Maha Penyantun" },
    shortDescription: { en: "He who is patient and does not hasten to punish the wrongdoers.", bn: "যিনি ধৈর্যশীল এবং অন্যায়কারীদের শাস্তিতে তাড়াহুড়া করেন না।", ur: "جو صبر کرتا ہے اور گنہگاروں کو سزا دینے میں جلدی نہیں کرتا۔", ar: "الذي يصبر ولا يعجل بعقوبة المذنبين.", tr: "Sabreden ve günahkârları cezalandırmakta acele etmeyen.", ms: "Yang bersabar dan tidak tergesa-gesa menghukum orang yang bersalah.", id: "Yang bersabar dan tidak tergesa-gesa menghukum orang yang bersalah." },
    quranReference: "2:225",
  },
  {
    id: 33,
    arabic: "الْعَظِيمُ",
    transliteration: "Al-'Azeem",
    meaning: { en: "The Magnificent", bn: "মহিমান্বিত", ur: "عظمت والا", ar: "العظيم", tr: "Azim", ms: "Yang Maha Agung", id: "Yang Maha Agung" },
    shortDescription: { en: "He whose greatness and magnificence are beyond comprehension.", bn: "যিনি এমন মহান ও মহিমান্বিত যা উপলব্ধির অতীত।", ur: "جس کی عظمت اور بزرگی فہم سے بالاتر ہے۔", ar: "الذي لا يُدرك عظمته وجلاله.", tr: "Büyüklüğü ve azameti kavranılamayan.", ms: "Yang keagungan dan kemegahan-Nya melebihi segala pemahaman.", id: "Yang keagungan dan kemegahan-Nya melampaui segala pemahaman." },
    quranReference: "2:255",
  },
  {
    id: 34,
    arabic: "الْغَفُورُ",
    transliteration: "Al-Ghafur",
    meaning: { en: "The All-Forgiving", bn: "ক্ষমাকারী", ur: "بخشنے والا", ar: "الغفور", tr: "Gafur", ms: "Yang Maha Pengampun", id: "Yang Maha Pengampun" },
    shortDescription: { en: "He who forgives and pardons all sins for those who sincerely repent.", bn: "যিনি আন্তরিক তওবাকারীদের সকল পাপ ক্ষমা করেন।", ur: "جو سچی توبہ کرنے والوں کے سب گناہ معاف کرتا ہے۔", ar: "الذي يغفر جميع الذنوب لمن تاب توبة صادقة.", tr: "Samimiyetle tövbe edenlerin tüm günahlarını bağışlayan.", ms: "Yang mengampuni segala dosa bagi mereka yang bertaubat dengan ikhlas.", id: "Yang mengampuni segala dosa bagi mereka yang bertaubat dengan ikhlas." },
    quranReference: "2:173",
  },
  {
    id: 35,
    arabic: "الشَّكُورُ",
    transliteration: "Ash-Shakur",
    meaning: { en: "The Appreciative", bn: "কৃতজ্ঞতাপূর্ণ", ur: "قدردان", ar: "الشكور", tr: "Şekur", ms: "Yang Maha Mensyukuri", id: "Yang Maha Mensyukuri" },
    shortDescription: { en: "He who appreciates even the smallest good deed and rewards it abundantly.", bn: "যিনি ক্ষুদ্রতম সৎকর্মেরও মূল্যায়ন করেন এবং প্রচুর পুরস্কার দেন।", ur: "جو چھوٹے سے نیک عمل کی بھی قدر کرتا اور بے حد اجر دیتا ہے۔", ar: "الذي يقدّر أصغر عمل صالح ويجزي عليه بسخاء.", tr: "En küçük iyiliği bile takdir edip bol bol ödüllendiren.", ms: "Yang menghargai amalan baik yang paling kecil sekalipun dan membalasnya dengan berlimpah.", id: "Yang menghargai amalan baik yang paling kecil sekalipun dan membalasnya dengan berlimpah." },
    quranReference: "35:30",
  },
  {
    id: 36,
    arabic: "الْعَلِيُّ",
    transliteration: "Al-'Aliyy",
    meaning: { en: "The Most High", bn: "সর্বোচ্চ", ur: "بلند و بالا", ar: "العلي", tr: "Aliyy", ms: "Yang Maha Tinggi", id: "Yang Maha Tinggi" },
    shortDescription: { en: "He who is exalted above all creation in rank and attributes.", bn: "যিনি মর্যাদা ও গুণে সমস্ত সৃষ্টির ঊর্ধ্বে।", ur: "جو مرتبے اور صفات میں تمام مخلوقات سے بلند ہے۔", ar: "المتعالي فوق جميع المخلوقات في المنزلة والصفات.", tr: "Mertebe ve sıfatlarda tüm yaratılmışların üzerinde olan.", ms: "Yang maha tinggi di atas segala makhluk dalam kedudukan dan sifat.", id: "Yang maha tinggi di atas segala makhluk dalam kedudukan dan sifat." },
    quranReference: "2:255",
  },
  {
    id: 37,
    arabic: "الْكَبِيرُ",
    transliteration: "Al-Kabir",
    meaning: { en: "The Greatest", bn: "সর্বশ্রেষ্ঠ", ur: "بہت بڑا", ar: "الكبير", tr: "Kebir", ms: "Yang Maha Besar", id: "Yang Maha Besar" },
    shortDescription: { en: "He who is the greatest and most exalted in every way.", bn: "যিনি সর্বদিক থেকে সর্বশ্রেষ্ঠ ও সর্বোচ্চ।", ur: "جو ہر لحاظ سے سب سے بڑا اور بلند ترین ہے۔", ar: "الذي هو الأعظم والأجلّ في كل شيء.", tr: "Her açıdan en büyük ve en yüce olan.", ms: "Yang maha besar dan maha mulia dalam segala hal.", id: "Yang maha besar dan maha mulia dalam segala hal." },
    quranReference: "13:9",
  },
  {
    id: 38,
    arabic: "الْحَفِيظُ",
    transliteration: "Al-Hafiz",
    meaning: { en: "The Preserver", bn: "সংরক্ষণকারী", ur: "حفاظت کرنے والا", ar: "الحفيظ", tr: "Hafiz", ms: "Yang Maha Memelihara", id: "Yang Maha Memelihara" },
    shortDescription: { en: "He who preserves and guards all of creation from harm.", bn: "যিনি সমস্ত সৃষ্টিকে ক্ষতি থেকে সংরক্ষণ ও রক্ষা করেন।", ur: "جو تمام مخلوقات کو نقصان سے محفوظ رکھتا ہے۔", ar: "الذي يحفظ جميع المخلوقات من الأذى.", tr: "Tüm yaratılmışları zarardan koruyup muhafaza eden.", ms: "Yang memelihara dan menjaga seluruh makhluk daripada bahaya.", id: "Yang memelihara dan menjaga seluruh makhluk dari bahaya." },
    quranReference: "11:57",
  },
  {
    id: 39,
    arabic: "الْمُقِيتُ",
    transliteration: "Al-Muqit",
    meaning: { en: "The Sustainer", bn: "পোষণকারী", ur: "قوت دینے والا", ar: "المقيت", tr: "Mukit", ms: "Yang Maha Pemberi Kecukupan", id: "Yang Maha Pemberi Kecukupan" },
    shortDescription: { en: "He who sustains and nourishes all living things.", bn: "যিনি সকল জীবকে পুষ্ট ও প্রতিপালন করেন।", ur: "جو تمام جانداروں کی کفالت اور پرورش کرتا ہے۔", ar: "الذي يقيت ويغذي جميع الكائنات الحية.", tr: "Tüm canlıları besleyip ayakta tutan.", ms: "Yang mencukupkan dan memelihara semua makhluk hidup.", id: "Yang mencukupkan dan memelihara semua makhluk hidup." },
    quranReference: "4:85",
  },
  {
    id: 40,
    arabic: "الْحَسِيبُ",
    transliteration: "Al-Hasib",
    meaning: { en: "The Reckoner", bn: "হিসাবকারী", ur: "حساب لینے والا", ar: "الحسيب", tr: "Hasib", ms: "Yang Maha Menghitung", id: "Yang Maha Menghitung" },
    shortDescription: { en: "He who takes account of every deed and is sufficient for His servants.", bn: "যিনি প্রতিটি কর্মের হিসাব রাখেন এবং বান্দাদের জন্য যথেষ্ট।", ur: "جو ہر عمل کا حساب رکھتا ہے اور بندوں کے لیے کافی ہے۔", ar: "الذي يحاسب على كل عمل وهو حسب عباده.", tr: "Her amelin hesabını tutan ve kullarına yeten.", ms: "Yang menghitung setiap amalan dan mencukupi hamba-hamba-Nya.", id: "Yang menghitung setiap amalan dan mencukupi hamba-hamba-Nya." },
    quranReference: "4:6",
  },
  {
    id: 41,
    arabic: "الْجَلِيلُ",
    transliteration: "Al-Jalil",
    meaning: { en: "The Majestic", bn: "মহামহিম", ur: "بزرگ و برتر", ar: "الجليل", tr: "Celil", ms: "Yang Maha Mulia", id: "Yang Maha Mulia" },
    shortDescription: { en: "He who is full of majesty, grandeur, and sublime glory.", bn: "যিনি মহিমা, জাঁকজমক এবং উচ্চ গৌরবে পরিপূর্ণ।", ur: "جو جلال، شان اور رفعت سے بھرپور ہے۔", ar: "الذي هو ذو الجلال والعظمة والمجد السامي.", tr: "Haşmet, ihtişam ve yüce şanla dolu olan.", ms: "Yang penuh dengan keagungan, kebesaran, dan kemuliaan yang tinggi.", id: "Yang penuh dengan keagungan, kebesaran, dan kemuliaan yang tinggi." },
  },
  {
    id: 42,
    arabic: "الْكَرِيمُ",
    transliteration: "Al-Karim",
    meaning: { en: "The Generous", bn: "মহানুভব", ur: "کریم", ar: "الكريم", tr: "Kerim", ms: "Yang Maha Mulia Hati", id: "Yang Maha Mulia Hati" },
    shortDescription: { en: "He who is the most generous and gives without being asked.", bn: "যিনি সবচেয়ে দানশীল এবং চাওয়া ছাড়াই দান করেন।", ur: "جو سب سے زیادہ سخی ہے اور بغیر مانگے عطا کرتا ہے۔", ar: "الذي هو أكرم الأكرمين ويعطي بغير سؤال.", tr: "En cömert olan ve istenmeden veren.", ms: "Yang paling pemurah dan memberi tanpa diminta.", id: "Yang paling pemurah dan memberi tanpa diminta." },
    quranReference: "27:40",
  },
  {
    id: 43,
    arabic: "الرَّقِيبُ",
    transliteration: "Ar-Raqib",
    meaning: { en: "The Watchful", bn: "পর্যবেক্ষণকারী", ur: "نگران", ar: "الرقيب", tr: "Rakib", ms: "Yang Maha Mengawasi", id: "Yang Maha Mengawasi" },
    shortDescription: { en: "He who watches over every soul and knows every action.", bn: "যিনি প্রতিটি আত্মার উপর নজর রাখেন এবং প্রতিটি কর্ম জানেন।", ur: "جو ہر روح کی نگرانی کرتا ہے اور ہر عمل جانتا ہے۔", ar: "الذي يراقب كل نفس ويعلم كل عمل.", tr: "Her nefsi gözetleyen ve her ameli bilen.", ms: "Yang mengawasi setiap jiwa dan mengetahui setiap perbuatan.", id: "Yang mengawasi setiap jiwa dan mengetahui setiap perbuatan." },
    quranReference: "5:117",
  },
  {
    id: 44,
    arabic: "الْمُجِيبُ",
    transliteration: "Al-Mujib",
    meaning: { en: "The Responsive", bn: "সাড়াদানকারী", ur: "دعا قبول کرنے والا", ar: "المجيب", tr: "Mücib", ms: "Yang Maha Mengabulkan", id: "Yang Maha Mengabulkan" },
    shortDescription: { en: "He who responds to the prayers and supplications of His servants.", bn: "যিনি বান্দাদের প্রার্থনা ও দোয়ায় সাড়া দেন।", ur: "جو اپنے بندوں کی دعائیں اور التجائیں قبول کرتا ہے۔", ar: "الذي يستجيب لدعاء عباده وتضرعاتهم.", tr: "Kullarının dua ve yakarışlarına cevap veren.", ms: "Yang mengabulkan doa dan permohonan hamba-hamba-Nya.", id: "Yang mengabulkan doa dan permohonan hamba-hamba-Nya." },
    quranReference: "11:61",
  },
  {
    id: 45,
    arabic: "الْوَاسِعُ",
    transliteration: "Al-Wasi'",
    meaning: { en: "The All-Encompassing", bn: "সর্বব্যাপী", ur: "وسعت والا", ar: "الواسع", tr: "Vasi", ms: "Yang Maha Luas", id: "Yang Maha Luas" },
    shortDescription: { en: "He whose capacity, knowledge, and mercy encompass all things.", bn: "যিনি সামর্থ্য, জ্ঞান ও রহমতে সবকিছুকে পরিবেষ্টন করেন।", ur: "جس کی گنجائش، علم اور رحمت ہر چیز کو محیط ہے۔", ar: "الذي يسع علمه ورحمته وقدرته كل شيء.", tr: "Kapasitesi, ilmi ve rahmeti her şeyi kuşatan.", ms: "Yang kapasiti, ilmu, dan rahmat-Nya meliputi segala sesuatu.", id: "Yang kapasitas, ilmu, dan rahmat-Nya meliputi segala sesuatu." },
    quranReference: "2:115",
  },
  {
    id: 46,
    arabic: "الْحَكِيمُ",
    transliteration: "Al-Hakim",
    meaning: { en: "The Wise", bn: "প্রজ্ঞাময়", ur: "حکمت والا", ar: "الحكيم", tr: "Hakim", ms: "Yang Maha Bijaksana", id: "Yang Maha Bijaksana" },
    shortDescription: { en: "He who is perfectly wise in all His actions and decrees.", bn: "যিনি তাঁর সকল কর্ম ও ফরমানে সম্পূর্ণ প্রজ্ঞাবান।", ur: "جو اپنے تمام افعال اور فیصلوں میں کامل حکمت والا ہے۔", ar: "الذي هو حكيم تمامًا في جميع أفعاله وأحكامه.", tr: "Tüm fiillerinde ve hükümlerinde mükemmel hikmet sahibi.", ms: "Yang maha bijaksana dalam segala tindakan dan ketetapan-Nya.", id: "Yang maha bijaksana dalam segala tindakan dan ketetapan-Nya." },
    quranReference: "2:129",
  },
  {
    id: 47,
    arabic: "الْوَدُودُ",
    transliteration: "Al-Wadud",
    meaning: { en: "The Loving", bn: "প্রেমময়", ur: "محبت کرنے والا", ar: "الودود", tr: "Vedud", ms: "Yang Maha Pengasih", id: "Yang Maha Pengasih" },
    shortDescription: { en: "He who loves His righteous servants and is beloved by them.", bn: "যিনি তাঁর সৎকর্মশীল বান্দাদের ভালোবাসেন এবং তাদের কাছে প্রিয়।", ur: "جو اپنے نیک بندوں سے محبت کرتا ہے اور وہ اسے محبوب رکھتے ہیں۔", ar: "الذي يحب عباده الصالحين وهو محبوبهم.", tr: "Salih kullarını seven ve onlar tarafından sevilen.", ms: "Yang menyayangi hamba-hamba-Nya yang soleh dan disayangi oleh mereka.", id: "Yang menyayangi hamba-hamba-Nya yang saleh dan disayangi oleh mereka." },
    quranReference: "85:14",
  },
  {
    id: 48,
    arabic: "الْمَجِيدُ",
    transliteration: "Al-Majid",
    meaning: { en: "The Glorious", bn: "মহিমান্বিত", ur: "بزرگ و شریف", ar: "المجيد", tr: "Mecid", ms: "Yang Maha Mulia", id: "Yang Maha Mulia" },
    shortDescription: { en: "He who is most glorious and majestic, full of honor and nobility.", bn: "যিনি সবচেয়ে গৌরবময় ও মহিমান্বিত, সম্মান ও মর্যাদায় পূর্ণ।", ur: "جو سب سے زیادہ جلیل اور عظیم ہے، عزت اور شرافت سے بھرپور۔", ar: "الأمجد والأعظم، المليء بالشرف والنبل.", tr: "En şanlı ve en görkemli, şeref ve asaletle dolu olan.", ms: "Yang paling mulia dan agung, penuh dengan kehormatan dan keluhuran.", id: "Yang paling mulia dan agung, penuh dengan kehormatan dan keluhuran." },
    quranReference: "11:73",
  },
  {
    id: 49,
    arabic: "الْبَاعِثُ",
    transliteration: "Al-Ba'ith",
    meaning: { en: "The Resurrector", bn: "পুনরুত্থানকারী", ur: "اٹھانے والا", ar: "الباعث", tr: "Bais", ms: "Yang Maha Membangkitkan", id: "Yang Maha Membangkitkan" },
    shortDescription: { en: "He who will resurrect all creation on the Day of Judgment.", bn: "যিনি বিচার দিবসে সমস্ত সৃষ্টিকে পুনরুত্থিত করবেন।", ur: "جو قیامت کے دن تمام مخلوقات کو دوبارہ اٹھائے گا۔", ar: "الذي سيبعث جميع المخلوقات يوم القيامة.", tr: "Kıyamet gününde tüm yaratılmışları yeniden diriltecek olan.", ms: "Yang akan membangkitkan semua makhluk pada Hari Kiamat.", id: "Yang akan membangkitkan semua makhluk pada Hari Kiamat." },
    quranReference: "22:7",
  },
  {
    id: 50,
    arabic: "الشَّهِيدُ",
    transliteration: "Ash-Shahid",
    meaning: { en: "The Witness", bn: "সাক্ষী", ur: "گواہ", ar: "الشهيد", tr: "Şehid", ms: "Yang Maha Menyaksikan", id: "Yang Maha Menyaksikan" },
    shortDescription: { en: "He who witnesses all things and nothing escapes His observation.", bn: "যিনি সবকিছুর সাক্ষী এবং কিছুই তাঁর পর্যবেক্ষণের বাইরে নয়।", ur: "جو سب چیزوں کا گواہ ہے اور کوئی چیز اس کی نظر سے نہیں بچتی۔", ar: "الذي يشهد كل شيء ولا يفوته شيء.", tr: "Her şeye şahit olan ve hiçbir şey gözleminden kaçmayan.", ms: "Yang menyaksikan segala sesuatu dan tiada yang terlepas daripada pemerhatian-Nya.", id: "Yang menyaksikan segala sesuatu dan tiada yang terlepas dari pengamatan-Nya." },
    quranReference: "4:166",
  },
  {
    id: 51,
    arabic: "الْحَقُّ",
    transliteration: "Al-Haqq",
    meaning: { en: "The Truth", bn: "সত্য", ur: "حق", ar: "الحق", tr: "Hakk", ms: "Yang Maha Benar", id: "Yang Maha Benar" },
    shortDescription: { en: "Allah is the absolute Truth and Reality.", bn: "আল্লাহ পরম সত্য ও বাস্তবতা।", ur: "اللہ مطلق حق اور حقیقت ہے۔", ar: "الله هو الحق المطلق والحقيقة.", tr: "Allah mutlak Hakk ve gerçekliktir.", ms: "Allah adalah Kebenaran dan Realiti mutlak.", id: "Allah adalah Kebenaran dan Realitas mutlak." },
    quranReference: "20:114",
  },
  {
    id: 52,
    arabic: "الْوَكِيلُ",
    transliteration: "Al-Wakil",
    meaning: { en: "The Trustee", bn: "কার্যসম্পাদনকারী", ur: "وکیل", ar: "الوكيل", tr: "Vekil", ms: "Yang Maha Mewakili", id: "Yang Maha Mewakili" },
    shortDescription: { en: "Allah is the ultimate Trustee and Disposer of affairs.", bn: "আল্লাহ চূড়ান্ত কার্যসম্পাদনকারী ও বিষয় নিষ্পত্তিকারী।", ur: "اللہ حتمی وکیل اور معاملات کا منتظم ہے۔", ar: "الله هو الوكيل المطلق ومدبر الأمور.", tr: "Allah mutlak Vekil ve işlerin yöneticisidir.", ms: "Allah adalah Pentadbir mutlak segala urusan.", id: "Allah adalah Pengurus mutlak segala urusan." },
    quranReference: "3:173",
  },
  {
    id: 53,
    arabic: "الْقَوِيُّ",
    transliteration: "Al-Qawiyy",
    meaning: { en: "The Strong", bn: "শক্তিশালী", ur: "طاقتور", ar: "القوي", tr: "Kuvvetli", ms: "Yang Maha Kuat", id: "Yang Maha Kuat" },
    shortDescription: { en: "Allah possesses unlimited and perfect strength.", bn: "আল্লাহ সীমাহীন ও পরিপূর্ণ শক্তির অধিকারী।", ur: "اللہ لامحدود اور کامل طاقت کا مالک ہے۔", ar: "الله ذو القوة المطلقة والكاملة.", tr: "Allah sınırsız ve mükemmel güce sahiptir.", ms: "Allah memiliki kekuatan yang tidak terbatas dan sempurna.", id: "Allah memiliki kekuatan yang tidak terbatas dan sempurna." },
    quranReference: "22:40",
  },
  {
    id: 54,
    arabic: "الْمَتِينُ",
    transliteration: "Al-Matin",
    meaning: { en: "The Firm", bn: "সুদৃঢ়", ur: "مضبوط", ar: "المتين", tr: "Metin", ms: "Yang Maha Teguh", id: "Yang Maha Teguh" },
    shortDescription: { en: "Allah is the Firm, whose strength never diminishes.", bn: "আল্লাহ সুদৃঢ়, যাঁর শক্তি কখনো হ্রাস পায় না।", ur: "اللہ مضبوط ہے، جس کی طاقت کبھی کم نہیں ہوتی۔", ar: "الله المتين الذي لا تنقص قوته أبدًا.", tr: "Allah Metin'dir, gücü asla azalmaz.", ms: "Allah Maha Teguh, kekuatan-Nya tidak pernah berkurang.", id: "Allah Maha Teguh, kekuatan-Nya tidak pernah berkurang." },
    quranReference: "51:58",
  },
  {
    id: 55,
    arabic: "الْوَلِيُّ",
    transliteration: "Al-Waliyy",
    meaning: { en: "The Protecting Friend", bn: "অভিভাবক বন্ধু", ur: "محافظ دوست", ar: "الولي", tr: "Dost", ms: "Yang Maha Melindungi", id: "Yang Maha Melindungi" },
    shortDescription: { en: "Allah is the Protecting Friend of the believers.", bn: "আল্লাহ মুমিনদের রক্ষাকারী বন্ধু।", ur: "اللہ مومنوں کا حامی دوست ہے۔", ar: "الله هو الولي الحامي للمؤمنين.", tr: "Allah müminlerin koruyucu dostudur.", ms: "Allah adalah Pelindung dan Sahabat orang beriman.", id: "Allah adalah Pelindung dan Sahabat orang beriman." },
    quranReference: "42:28",
  },
  {
    id: 56,
    arabic: "الْحَمِيدُ",
    transliteration: "Al-Hamid",
    meaning: { en: "The Praiseworthy", bn: "প্রশংসিত", ur: "قابل حمد", ar: "الحميد", tr: "Hamid", ms: "Yang Maha Terpuji", id: "Yang Maha Terpuji" },
    shortDescription: { en: "Allah is the one worthy of all praise and gratitude.", bn: "আল্লাহ সকল প্রশংসা ও কৃতজ্ঞতার যোগ্য।", ur: "اللہ تمام حمد اور شکر کا مستحق ہے۔", ar: "الله هو المستحق لكل حمد وثناء.", tr: "Allah tüm hamd ve şükre layık olandır.", ms: "Allah yang layak menerima segala pujian dan syukur.", id: "Allah yang layak menerima segala pujian dan syukur." },
    quranReference: "14:8",
  },
  {
    id: 57,
    arabic: "الْمُحْصِي",
    transliteration: "Al-Muhsi",
    meaning: { en: "The Accounter", bn: "গণনাকারী", ur: "شمار کرنے والا", ar: "المحصي", tr: "Sayan", ms: "Yang Maha Menghitung", id: "Yang Maha Menghitung" },
    shortDescription: { en: "Allah keeps account of all things and nothing escapes His knowledge.", bn: "আল্লাহ সবকিছুর হিসাব রাখেন এবং কিছুই তাঁর জ্ঞানের বাইরে নয়।", ur: "اللہ ہر چیز کا حساب رکھتا ہے اور کچھ بھی اس کے علم سے باہر نہیں۔", ar: "الله يحصي كل شيء ولا يفلت شيء من علمه.", tr: "Allah her şeyin hesabını tutar, hiçbir şey O'nun bilgisinden kaçmaz.", ms: "Allah menghitung segala sesuatu dan tiada yang terlepas dari pengetahuan-Nya.", id: "Allah menghitung segala sesuatu dan tiada yang terlepas dari pengetahuan-Nya." },
  },
  {
    id: 58,
    arabic: "الْمُبْدِئُ",
    transliteration: "Al-Mubdi'",
    meaning: { en: "The Originator", bn: "সৃষ্টির সূচনাকারী", ur: "پہلی بار پیدا کرنے والا", ar: "المبدئ", tr: "İlk Yaratan", ms: "Yang Maha Memulakan", id: "Yang Maha Memulai" },
    shortDescription: { en: "Allah is the Originator who creates all things from nothing.", bn: "আল্লাহ সৃষ্টির সূচনাকারী যিনি শূন্য থেকে সবকিছু সৃষ্টি করেন।", ur: "اللہ موجد ہے جو عدم سے ہر چیز پیدا کرتا ہے۔", ar: "الله هو المبدئ الذي يخلق كل شيء من العدم.", tr: "Allah yoktan var eden Mubdi'dir.", ms: "Allah adalah Pemula yang mencipta segala sesuatu dari ketiadaan.", id: "Allah adalah Pemula yang menciptakan segala sesuatu dari ketiadaan." },
    quranReference: "85:13",
  },
  {
    id: 59,
    arabic: "الْمُعِيدُ",
    transliteration: "Al-Mu'id",
    meaning: { en: "The Restorer", bn: "পুনরুত্থানকারী", ur: "دوبارہ پیدا کرنے والا", ar: "المعيد", tr: "Yeniden Yaratan", ms: "Yang Maha Mengembalikan", id: "Yang Maha Mengembalikan" },
    shortDescription: { en: "Allah restores creation after its extinction.", bn: "আল্লাহ সৃষ্টি ধ্বংসের পর পুনরায় সৃষ্টি করেন।", ur: "اللہ مخلوقات کو فنا کے بعد دوبارہ پیدا کرتا ہے۔", ar: "الله يعيد الخلق بعد فنائه.", tr: "Allah yaratılışı yok olduktan sonra yeniden yaratır.", ms: "Allah mengembalikan ciptaan setelah kepunahannya.", id: "Allah mengembalikan ciptaan setelah kepunahannya." },
    quranReference: "85:13",
  },
  {
    id: 60,
    arabic: "الْمُحْيِي",
    transliteration: "Al-Muhyi",
    meaning: { en: "The Giver of Life", bn: "জীবনদাতা", ur: "زندگی دینے والا", ar: "المحيي", tr: "Hayat Veren", ms: "Yang Maha Menghidupkan", id: "Yang Maha Menghidupkan" },
    shortDescription: { en: "Allah is the Giver of life to all living things.", bn: "আল্লাহ সকল জীবের জীবনদাতা।", ur: "اللہ تمام جانداروں کو زندگی دینے والا ہے۔", ar: "الله هو معطي الحياة لكل الكائنات الحية.", tr: "Allah tüm canlılara hayat verendir.", ms: "Allah adalah Pemberi kehidupan kepada semua makhluk hidup.", id: "Allah adalah Pemberi kehidupan kepada semua makhluk hidup." },
    quranReference: "30:50",
  },
  {
    id: 61,
    arabic: "الْمُمِيتُ",
    transliteration: "Al-Mumit",
    meaning: { en: "The Taker of Life", bn: "মৃত্যুদাতা", ur: "موت دینے والا", ar: "المميت", tr: "Ölümü Veren", ms: "Yang Maha Mematikan", id: "Yang Maha Mematikan" },
    shortDescription: { en: "Allah is the one who takes away life at the appointed time.", bn: "আল্লাহ নির্ধারিত সময়ে প্রাণ হরণ করেন।", ur: "اللہ مقررہ وقت پر جان لینے والا ہے۔", ar: "الله هو الذي يقبض الأرواح في الأجل المحدد.", tr: "Allah belirlenen vakitte canı alandır.", ms: "Allah yang mengambil nyawa pada waktu yang ditetapkan.", id: "Allah yang mengambil nyawa pada waktu yang ditetapkan." },
    quranReference: "15:23",
  },
  {
    id: 62,
    arabic: "الْحَيُّ",
    transliteration: "Al-Hayy",
    meaning: { en: "The Ever-Living", bn: "চিরঞ্জীব", ur: "ہمیشہ زندہ", ar: "الحي", tr: "Diri", ms: "Yang Maha Hidup", id: "Yang Maha Hidup" },
    shortDescription: { en: "Allah is the Ever-Living who never dies.", bn: "আল্লাহ চিরঞ্জীব যিনি কখনো মৃত্যুবরণ করেন না।", ur: "اللہ ہمیشہ زندہ ہے جسے کبھی موت نہیں آتی۔", ar: "الله هو الحي الذي لا يموت أبدًا.", tr: "Allah asla ölmeyen Diri olandır.", ms: "Allah Maha Hidup yang tidak pernah mati.", id: "Allah Maha Hidup yang tidak pernah mati." },
    quranReference: "2:255",
  },
  {
    id: 63,
    arabic: "الْقَيُّومُ",
    transliteration: "Al-Qayyum",
    meaning: { en: "The Self-Subsisting", bn: "স্বয়ংসম্পূর্ণ", ur: "قائم بالذات", ar: "القيوم", tr: "Kayyum", ms: "Yang Maha Berdiri Sendiri", id: "Yang Maha Berdiri Sendiri" },
    shortDescription: { en: "Allah is Self-Subsisting and sustains all that exists.", bn: "আল্লাহ স্বয়ংসম্পূর্ণ এবং সকল অস্তিত্বকে ধারণ করেন।", ur: "اللہ قائم بالذات ہے اور ہر موجود چیز کو قائم رکھتا ہے۔", ar: "الله القيوم الذي يقوم بذاته ويقيم كل شيء.", tr: "Allah kendi kendine var olan ve her şeyi ayakta tutandır.", ms: "Allah Maha Berdiri Sendiri dan menopang segala yang ada.", id: "Allah Maha Berdiri Sendiri dan menopang segala yang ada." },
    quranReference: "2:255",
  },
  {
    id: 64,
    arabic: "الْوَاجِدُ",
    transliteration: "Al-Wajid",
    meaning: { en: "The Finder", bn: "সন্ধানকারী", ur: "پانے والا", ar: "الواجد", tr: "Bulan", ms: "Yang Maha Menemukan", id: "Yang Maha Menemukan" },
    shortDescription: { en: "Allah finds and perceives everything; nothing is lost to Him.", bn: "আল্লাহ সবকিছু খুঁজে পান; তাঁর কাছে কিছুই হারায় না।", ur: "اللہ ہر چیز کو پاتا ہے؛ اس سے کچھ بھی گم نہیں۔", ar: "الله يجد كل شيء ولا يضيع عنه شيء.", tr: "Allah her şeyi bulur; O'ndan hiçbir şey kaybolmaz.", ms: "Allah menemukan segala sesuatu; tiada yang hilang dari-Nya.", id: "Allah menemukan segala sesuatu; tiada yang hilang dari-Nya." },
  },
  {
    id: 65,
    arabic: "الْمَاجِدُ",
    transliteration: "Al-Majid",
    meaning: { en: "The Noble", bn: "মহিমান্বিত", ur: "بزرگ", ar: "الماجد", tr: "Şanlı", ms: "Yang Maha Mulia", id: "Yang Maha Mulia" },
    shortDescription: { en: "Allah is the Most Noble, glorious in His attributes.", bn: "আল্লাহ মহিমান্বিত, তাঁর গুণাবলীতে গৌরবময়।", ur: "اللہ سب سے بزرگ ہے، اپنی صفات میں جلیل ہے۔", ar: "الله الماجد العظيم في صفاته.", tr: "Allah en şanlı olandır, sıfatlarında yücedir.", ms: "Allah Yang Maha Mulia, agung dalam sifat-sifat-Nya.", id: "Allah Yang Maha Mulia, agung dalam sifat-sifat-Nya." },
  },
  {
    id: 66,
    arabic: "الْوَاحِدُ",
    transliteration: "Al-Wahid",
    meaning: { en: "The One", bn: "একক", ur: "ایک", ar: "الواحد", tr: "Bir", ms: "Yang Maha Esa", id: "Yang Maha Esa" },
    shortDescription: { en: "Allah is the One and Only, unique in His essence.", bn: "আল্লাহ একক ও অদ্বিতীয়, তাঁর সত্তায় অনন্য।", ur: "اللہ ایک اور واحد ہے، اپنی ذات میں بے مثال۔", ar: "الله الواحد الأحد، الفريد في ذاته.", tr: "Allah Bir ve Tek'tir, zatında eşsizdir.", ms: "Allah Yang Maha Esa, unik dalam zat-Nya.", id: "Allah Yang Maha Esa, unik dalam zat-Nya." },
    quranReference: "112:1",
  },
  {
    id: 67,
    arabic: "الصَّمَدُ",
    transliteration: "As-Samad",
    meaning: { en: "The Eternal", bn: "অমুখাপেক্ষী", ur: "بے نیاز", ar: "الصمد", tr: "Samed", ms: "Yang Maha Dibutuhkan", id: "Yang Maha Dibutuhkan" },
    shortDescription: { en: "Allah is the Eternal, upon whom all depend and who depends on none.", bn: "আল্লাহ অমুখাপেক্ষী, সকলে তাঁর উপর নির্ভরশীল কিন্তু তিনি কারো উপর নির্ভরশীল নন।", ur: "اللہ بے نیاز ہے، سب اس پر منحصر ہیں لیکن وہ کسی پر منحصر نہیں۔", ar: "الله الصمد الذي يعتمد عليه الجميع ولا يعتمد على أحد.", tr: "Allah Samed'dir; herkes O'na muhtaçtır, O hiç kimseye muhtaç değildir.", ms: "Allah Maha Dibutuhkan, semua bergantung kepada-Nya dan Dia tidak bergantung pada siapa pun.", id: "Allah Maha Dibutuhkan, semua bergantung kepada-Nya dan Dia tidak bergantung pada siapa pun." },
    quranReference: "112:2",
  },
  {
    id: 68,
    arabic: "الْقَادِرُ",
    transliteration: "Al-Qadir",
    meaning: { en: "The Able", bn: "সক্ষম", ur: "قادر", ar: "القادر", tr: "Kadir", ms: "Yang Maha Berkuasa", id: "Yang Maha Berkuasa" },
    shortDescription: { en: "Allah has absolute power and ability over all things.", bn: "আল্লাহ সকল বিষয়ে পরম ক্ষমতা ও সামর্থ্যের অধিকারী।", ur: "اللہ ہر چیز پر مکمل قدرت اور صلاحیت رکھتا ہے۔", ar: "الله له القدرة المطلقة على كل شيء.", tr: "Allah her şey üzerinde mutlak güç ve kudret sahibidir.", ms: "Allah memiliki kuasa dan kemampuan mutlak atas segala sesuatu.", id: "Allah memiliki kuasa dan kemampuan mutlak atas segala sesuatu." },
    quranReference: "6:65",
  },
  {
    id: 69,
    arabic: "الْمُقْتَدِرُ",
    transliteration: "Al-Muqtadir",
    meaning: { en: "The Powerful", bn: "পরাক্রমশালী", ur: "اقتدار والا", ar: "المقتدر", tr: "Muktedir", ms: "Yang Maha Menentukan", id: "Yang Maha Menentukan" },
    shortDescription: { en: "Allah is the All-Powerful who exercises His power with perfect wisdom.", bn: "আল্লাহ সর্বশক্তিমান যিনি পূর্ণ প্রজ্ঞার সাথে তাঁর ক্ষমতা প্রয়োগ করেন।", ur: "اللہ قادر مطلق ہے جو کامل حکمت سے اپنی قدرت کا استعمال کرتا ہے۔", ar: "الله المقتدر الذي يمارس قدرته بحكمة تامة.", tr: "Allah tam bir hikmetle kudretini kullanan Muktedir'dir.", ms: "Allah Maha Berkuasa yang menggunakan kuasa-Nya dengan hikmah sempurna.", id: "Allah Maha Berkuasa yang menggunakan kuasa-Nya dengan hikmah sempurna." },
    quranReference: "54:42",
  },
  {
    id: 70,
    arabic: "الْمُقَدِّمُ",
    transliteration: "Al-Muqaddim",
    meaning: { en: "The Expediter", bn: "অগ্রসরকারী", ur: "آگے کرنے والا", ar: "المقدم", tr: "Öne Geçiren", ms: "Yang Maha Mendahulukan", id: "Yang Maha Mendahulukan" },
    shortDescription: { en: "Allah brings forward whom He wills.", bn: "আল্লাহ যাকে ইচ্ছা অগ্রসর করেন।", ur: "اللہ جسے چاہے آگے کرتا ہے۔", ar: "الله يقدم من يشاء.", tr: "Allah dilediğini öne geçirir.", ms: "Allah mendahulukan sesiapa yang Dia kehendaki.", id: "Allah mendahulukan siapa saja yang Dia kehendaki." },
  },
  {
    id: 71,
    arabic: "الْمُؤَخِّرُ",
    transliteration: "Al-Mu'akhkhir",
    meaning: { en: "The Delayer", bn: "বিলম্বকারী", ur: "پیچھے کرنے والا", ar: "المؤخر", tr: "Erteleyen", ms: "Yang Maha Mengakhirkan", id: "Yang Maha Mengakhirkan" },
    shortDescription: { en: "Allah delays and puts back whom He wills.", bn: "আল্লাহ যাকে ইচ্ছা বিলম্বিত ও পশ্চাতে রাখেন।", ur: "اللہ جسے چاہے پیچھے کرتا ہے۔", ar: "الله يؤخر من يشاء.", tr: "Allah dilediğini erteler ve geri bırakır.", ms: "Allah mengakhirkan sesiapa yang Dia kehendaki.", id: "Allah mengakhirkan siapa saja yang Dia kehendaki." },
  },
  {
    id: 72,
    arabic: "الْأَوَّلُ",
    transliteration: "Al-Awwal",
    meaning: { en: "The First", bn: "প্রথম", ur: "سب سے پہلے", ar: "الأول", tr: "İlk", ms: "Yang Maha Awal", id: "Yang Maha Awal" },
    shortDescription: { en: "Allah is the First; nothing existed before Him.", bn: "আল্লাহ প্রথম; তাঁর আগে কিছুই ছিল না।", ur: "اللہ سب سے پہلے ہے؛ اس سے پہلے کچھ نہیں تھا۔", ar: "الله هو الأول، لم يكن شيء قبله.", tr: "Allah İlk'tir; O'ndan önce hiçbir şey yoktu.", ms: "Allah Yang Maha Awal; tiada sesuatu sebelum-Nya.", id: "Allah Yang Maha Awal; tiada sesuatu sebelum-Nya." },
    quranReference: "57:3",
  },
  {
    id: 73,
    arabic: "الْآخِرُ",
    transliteration: "Al-Akhir",
    meaning: { en: "The Last", bn: "সর্বশেষ", ur: "سب سے آخر", ar: "الآخر", tr: "Son", ms: "Yang Maha Akhir", id: "Yang Maha Akhir" },
    shortDescription: { en: "Allah is the Last; He remains after all else perishes.", bn: "আল্লাহ সর্বশেষ; সবকিছু ধ্বংসের পরও তিনি থাকবেন।", ur: "اللہ سب سے آخر ہے؛ سب کچھ فنا ہونے کے بعد بھی وہ باقی رہے گا۔", ar: "الله هو الآخر، يبقى بعد فناء كل شيء.", tr: "Allah Son'dur; her şey yok olduktan sonra da O baki kalır.", ms: "Allah Yang Maha Akhir; Dia kekal setelah segala sesuatu binasa.", id: "Allah Yang Maha Akhir; Dia kekal setelah segala sesuatu binasa." },
    quranReference: "57:3",
  },
  {
    id: 74,
    arabic: "الظَّاهِرُ",
    transliteration: "Az-Zahir",
    meaning: { en: "The Manifest", bn: "প্রকাশমান", ur: "ظاہر", ar: "الظاهر", tr: "Zahir", ms: "Yang Maha Nyata", id: "Yang Maha Nyata" },
    shortDescription: { en: "Allah is the Manifest, evident through His signs.", bn: "আল্লাহ প্রকাশমান, তাঁর নিদর্শনসমূহের মাধ্যমে প্রতীয়মান।", ur: "اللہ ظاہر ہے، اپنی نشانیوں سے واضح ہے۔", ar: "الله هو الظاهر، البيّن بآياته.", tr: "Allah Zahir'dir, ayetleriyle aşikardır.", ms: "Allah Yang Maha Nyata, terbukti melalui tanda-tanda-Nya.", id: "Allah Yang Maha Nyata, terbukti melalui tanda-tanda-Nya." },
    quranReference: "57:3",
  },
  {
    id: 75,
    arabic: "الْبَاطِنُ",
    transliteration: "Al-Batin",
    meaning: { en: "The Hidden", bn: "গোপন", ur: "پوشیدہ", ar: "الباطن", tr: "Batın", ms: "Yang Maha Tersembunyi", id: "Yang Maha Tersembunyi" },
    shortDescription: { en: "Allah is the Hidden, whose essence cannot be perceived by senses.", bn: "আল্লাহ গোপন, যাঁর সত্তা ইন্দ্রিয়গ্রাহ্য নয়।", ur: "اللہ پوشیدہ ہے، جس کی ذات حواس سے ادراک نہیں ہو سکتی۔", ar: "الله هو الباطن الذي لا تدركه الحواس.", tr: "Allah Batın'dır, zatı duyularla idrak edilemez.", ms: "Allah Yang Maha Tersembunyi, zat-Nya tidak dapat dijangkau oleh pancaindera.", id: "Allah Yang Maha Tersembunyi, zat-Nya tidak dapat dijangkau oleh pancaindera." },
    quranReference: "57:3",
  },
  {
    id: 76,
    arabic: "الْوَالِي",
    transliteration: "Al-Wali",
    meaning: { en: "The Governor", bn: "শাসনকর্তা", ur: "حاکم", ar: "الوالي", tr: "Yöneten", ms: "Yang Maha Memerintah", id: "Yang Maha Memerintah" },
    shortDescription: { en: "Allah is the Governor who manages and rules over all creation.", bn: "আল্লাহ শাসনকর্তা যিনি সমস্ত সৃষ্টি পরিচালনা ও শাসন করেন।", ur: "اللہ حاکم ہے جو تمام مخلوقات کا انتظام اور حکومت کرتا ہے۔", ar: "الله هو الوالي الذي يدبر ويحكم جميع الخلق.", tr: "Allah tüm yaratılışı yöneten ve idare eden Vali'dir.", ms: "Allah adalah Pemerintah yang mengurus dan mentadbir seluruh ciptaan.", id: "Allah adalah Pemerintah yang mengurus dan mentadbir seluruh ciptaan." },
  },
  {
    id: 77,
    arabic: "الْمُتَعَالِي",
    transliteration: "Al-Muta'ali",
    meaning: { en: "The Most Exalted", bn: "সর্বোচ্চ মহিমান্বিত", ur: "بلند و بالا", ar: "المتعالي", tr: "Yüce", ms: "Yang Maha Tinggi", id: "Yang Maha Tinggi" },
    shortDescription: { en: "Allah is supremely exalted above all creation.", bn: "আল্লাহ সকল সৃষ্টির ঊর্ধ্বে সর্বোচ্চ মহিমান্বিত।", ur: "اللہ تمام مخلوقات سے بلند و بالا ہے۔", ar: "الله متعال فوق جميع الخلق.", tr: "Allah tüm yaratılışın üstünde yücedir.", ms: "Allah Maha Tinggi di atas segala ciptaan.", id: "Allah Maha Tinggi di atas segala ciptaan." },
    quranReference: "13:9",
  },
  {
    id: 78,
    arabic: "الْبَرُّ",
    transliteration: "Al-Barr",
    meaning: { en: "The Source of Goodness", bn: "কল্যাণের উৎস", ur: "نیکی کا سرچشمہ", ar: "البر", tr: "İyilik Kaynağı", ms: "Sumber Kebaikan", id: "Sumber Kebaikan" },
    shortDescription: { en: "Allah is the Source of all goodness and kindness.", bn: "আল্লাহ সকল কল্যাণ ও দয়ার উৎস।", ur: "اللہ تمام نیکی اور مہربانی کا سرچشمہ ہے۔", ar: "الله هو مصدر كل خير وإحسان.", tr: "Allah tüm iyilik ve lütfun kaynağıdır.", ms: "Allah adalah sumber segala kebaikan dan kemuliaan.", id: "Allah adalah sumber segala kebaikan dan kemuliaan." },
    quranReference: "52:28",
  },
  {
    id: 79,
    arabic: "التَّوَّابُ",
    transliteration: "At-Tawwab",
    meaning: { en: "The Acceptor of Repentance", bn: "তওবা কবুলকারী", ur: "توبہ قبول کرنے والا", ar: "التواب", tr: "Tövbeleri Kabul Eden", ms: "Yang Maha Penerima Taubat", id: "Yang Maha Penerima Tobat" },
    shortDescription: { en: "Allah accepts repentance and forgives those who sincerely return to Him.", bn: "আল্লাহ তওবা কবুল করেন এবং যারা আন্তরিকভাবে ফিরে আসে তাদের ক্ষমা করেন।", ur: "اللہ توبہ قبول کرتا ہے اور ان کو معاف کرتا ہے جو خلوص سے اس کی طرف لوٹتے ہیں۔", ar: "الله يقبل التوبة ويغفر لمن يعود إليه بصدق.", tr: "Allah tövbeleri kabul eder ve samimiyetle dönenler bağışlar.", ms: "Allah menerima taubat dan mengampuni mereka yang kembali kepada-Nya dengan tulus.", id: "Allah menerima tobat dan mengampuni mereka yang kembali kepada-Nya dengan tulus." },
    quranReference: "2:128",
  },
  {
    id: 80,
    arabic: "الْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    meaning: { en: "The Avenger", bn: "প্রতিশোধ গ্রহণকারী", ur: "بدلہ لینے والا", ar: "المنتقم", tr: "İntikam Alan", ms: "Yang Maha Membalas", id: "Yang Maha Membalas" },
    shortDescription: { en: "Allah is the Avenger who justly punishes wrongdoers.", bn: "আল্লাহ প্রতিশোধ গ্রহণকারী যিনি ন্যায়সংগতভাবে অপরাধীদের শাস্তি দেন।", ur: "اللہ بدلہ لینے والا ہے جو انصاف سے ظالموں کو سزا دیتا ہے۔", ar: "الله المنتقم الذي يعاقب الظالمين بالعدل.", tr: "Allah zalimleri adaletle cezalandıran Müntakim'dir.", ms: "Allah Yang Maha Membalas yang menghukum orang zalim dengan adil.", id: "Allah Yang Maha Membalas yang menghukum orang zalim dengan adil." },
    quranReference: "32:22",
  },
  {
    id: 81,
    arabic: "الْعَفُوُّ",
    transliteration: "Al-'Afuww",
    meaning: { en: "The Pardoner", bn: "ক্ষমাশীল", ur: "معاف کرنے والا", ar: "العفو", tr: "Affeden", ms: "Yang Maha Pemaaf", id: "Yang Maha Pemaaf" },
    shortDescription: { en: "Allah pardons and erases sins completely.", bn: "আল্লাহ সম্পূর্ণরূপে পাপ ক্ষমা করেন ও মুছে দেন।", ur: "اللہ گناہوں کو مکمل طور پر معاف اور مٹا دیتا ہے۔", ar: "الله يعفو عن الذنوب ويمحوها تمامًا.", tr: "Allah günahları tamamen affeder ve siler.", ms: "Allah memaafkan dan menghapus dosa sepenuhnya.", id: "Allah memaafkan dan menghapus dosa sepenuhnya." },
    quranReference: "4:99",
  },
  {
    id: 82,
    arabic: "الرَّؤُوفُ",
    transliteration: "Ar-Ra'uf",
    meaning: { en: "The Compassionate", bn: "স্নেহশীল", ur: "شفیق", ar: "الرؤوف", tr: "Şefkatli", ms: "Yang Maha Pengasih", id: "Yang Maha Pengasih" },
    shortDescription: { en: "Allah is full of compassion and tenderness toward His servants.", bn: "আল্লাহ তাঁর বান্দাদের প্রতি স্নেহ ও কোমলতায় পরিপূর্ণ।", ur: "اللہ اپنے بندوں کے لیے شفقت اور نرمی سے بھرپور ہے۔", ar: "الله رؤوف رحيم بعباده.", tr: "Allah kullarına karşı şefkat ve merhametle doludur.", ms: "Allah penuh kasih sayang dan kelembutan terhadap hamba-hamba-Nya.", id: "Allah penuh kasih sayang dan kelembutan terhadap hamba-hamba-Nya." },
    quranReference: "3:30",
  },
  {
    id: 83,
    arabic: "مَالِكُ الْمُلْكِ",
    transliteration: "Malik al-Mulk",
    meaning: { en: "Owner of Sovereignty", bn: "সার্বভৌমত্বের মালিক", ur: "بادشاہی کا مالک", ar: "مالك الملك", tr: "Mülkün Sahibi", ms: "Pemilik Kedaulatan", id: "Pemilik Kedaulatan" },
    shortDescription: { en: "Allah is the Owner of all sovereignty and dominion.", bn: "আল্লাহ সকল সার্বভৌমত্ব ও কর্তৃত্বের মালিক।", ur: "اللہ تمام بادشاہی اور حکمرانی کا مالک ہے۔", ar: "الله مالك الملك والسيادة كلها.", tr: "Allah tüm egemenlik ve hükümranlığın sahibidir.", ms: "Allah adalah Pemilik segala kedaulatan dan kekuasaan.", id: "Allah adalah Pemilik segala kedaulatan dan kekuasaan." },
    quranReference: "3:26",
  },
  {
    id: 84,
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Dhul-Jalali wal-Ikram",
    meaning: { en: "Lord of Majesty and Generosity", bn: "মহিমা ও সম্মানের অধিকারী", ur: "عظمت اور کرم والا", ar: "ذو الجلال والإكرام", tr: "Celal ve İkram Sahibi", ms: "Pemilik Keagungan dan Kemuliaan", id: "Pemilik Keagungan dan Kemuliaan" },
    shortDescription: { en: "Allah is the Lord of Majesty and Generosity, possessing perfect greatness and honor.", bn: "আল্লাহ মহিমা ও সম্মানের অধিকারী, পরিপূর্ণ মহত্ত্ব ও সম্মানের মালিক।", ur: "اللہ عظمت اور کرم کا مالک ہے، کامل بڑائی اور عزت والا۔", ar: "الله ذو الجلال والإكرام، صاحب العظمة والشرف الكامل.", tr: "Allah celal ve ikram sahibidir, mükemmel büyüklük ve şeref sahibidir.", ms: "Allah adalah Pemilik Keagungan dan Kemuliaan, memiliki kebesaran dan kehormatan yang sempurna.", id: "Allah adalah Pemilik Keagungan dan Kemuliaan, memiliki kebesaran dan kehormatan yang sempurna." },
    quranReference: "55:27",
  },
  {
    id: 85,
    arabic: "الْمُقْسِطُ",
    transliteration: "Al-Muqsit",
    meaning: { en: "The Equitable", bn: "ন্যায়পরায়ণ", ur: "انصاف کرنے والا", ar: "المقسط", tr: "Adaletli", ms: "Yang Maha Adil", id: "Yang Maha Adil" },
    shortDescription: { en: "Allah is the Equitable who acts with perfect justice.", bn: "আল্লাহ ন্যায়পরায়ণ যিনি পরিপূর্ণ ন্যায়বিচার করেন।", ur: "اللہ منصف ہے جو کامل انصاف سے عمل کرتا ہے۔", ar: "الله المقسط الذي يعمل بالعدل التام.", tr: "Allah tam adaletle hareket eden Muksit'tir.", ms: "Allah Yang Maha Adil yang bertindak dengan keadilan sempurna.", id: "Allah Yang Maha Adil yang bertindak dengan keadilan sempurna." },
  },
  {
    id: 86,
    arabic: "الْجَامِعُ",
    transliteration: "Al-Jami'",
    meaning: { en: "The Gatherer", bn: "একত্রকারী", ur: "جمع کرنے والا", ar: "الجامع", tr: "Toplayan", ms: "Yang Maha Mengumpulkan", id: "Yang Maha Mengumpulkan" },
    shortDescription: { en: "Allah is the Gatherer who will gather all people on the Day of Judgment.", bn: "আল্লাহ একত্রকারী যিনি বিচার দিবসে সকল মানুষকে একত্রিত করবেন।", ur: "اللہ جمع کرنے والا ہے جو قیامت کے دن سب لوگوں کو جمع کرے گا۔", ar: "الله الجامع الذي سيجمع الناس يوم القيامة.", tr: "Allah Kıyamet Günü tüm insanları toplayacak olan Cami'dir.", ms: "Allah Yang Maha Mengumpulkan yang akan mengumpulkan semua manusia pada Hari Kiamat.", id: "Allah Yang Maha Mengumpulkan yang akan mengumpulkan semua manusia pada Hari Kiamat." },
    quranReference: "3:9",
  },
  {
    id: 87,
    arabic: "الْغَنِيُّ",
    transliteration: "Al-Ghaniyy",
    meaning: { en: "The Self-Sufficient", bn: "অমুখাপেক্ষী", ur: "بے نیاز", ar: "الغني", tr: "Zengin", ms: "Yang Maha Kaya", id: "Yang Maha Kaya" },
    shortDescription: { en: "Allah is the Self-Sufficient who is free from all needs.", bn: "আল্লাহ অমুখাপেক্ষী যিনি সকল প্রয়োজন থেকে মুক্ত।", ur: "اللہ بے نیاز ہے جو ہر ضرورت سے پاک ہے۔", ar: "الله الغني المستغني عن كل حاجة.", tr: "Allah her ihtiyaçtan münezzeh olan Gani'dir.", ms: "Allah Yang Maha Kaya yang bebas dari segala keperluan.", id: "Allah Yang Maha Kaya yang bebas dari segala keperluan." },
    quranReference: "2:263",
  },
  {
    id: 88,
    arabic: "الْمُغْنِي",
    transliteration: "Al-Mughni",
    meaning: { en: "The Enricher", bn: "সমৃদ্ধকারী", ur: "غنی کرنے والا", ar: "المغني", tr: "Zengin Kılan", ms: "Yang Maha Memberi Kekayaan", id: "Yang Maha Memberi Kekayaan" },
    shortDescription: { en: "Allah is the Enricher who bestows wealth and sufficiency upon His servants.", bn: "আল্লাহ সমৃদ্ধকারী যিনি তাঁর বান্দাদের সম্পদ ও পর্যাপ্ততা দান করেন।", ur: "اللہ غنی کرنے والا ہے جو اپنے بندوں کو دولت اور کفایت عطا کرتا ہے۔", ar: "الله المغني الذي يمنح عباده الغنى والكفاية.", tr: "Allah kullarına zenginlik ve yeterlilik bahşeden Muğni'dir.", ms: "Allah Yang Maha Memberi Kekayaan yang menganugerahkan kekayaan dan kecukupan kepada hamba-Nya.", id: "Allah Yang Maha Memberi Kekayaan yang menganugerahkan kekayaan dan kecukupan kepada hamba-Nya." },
  },
  {
    id: 89,
    arabic: "الْمَانِعُ",
    transliteration: "Al-Mani'",
    meaning: { en: "The Preventer", bn: "প্রতিরোধকারী", ur: "روکنے والا", ar: "المانع", tr: "Engelleyen", ms: "Yang Maha Mencegah", id: "Yang Maha Mencegah" },
    shortDescription: { en: "Allah is the Preventer who withholds harm from His servants.", bn: "আল্লাহ প্রতিরোধকারী যিনি তাঁর বান্দাদের থেকে ক্ষতি রোধ করেন।", ur: "اللہ روکنے والا ہے جو اپنے بندوں سے نقصان کو روکتا ہے۔", ar: "الله المانع الذي يدفع الأذى عن عباده.", tr: "Allah kullarından zararı engelleyen Mani'dir.", ms: "Allah Yang Maha Mencegah yang menghindarkan kemudaratan dari hamba-Nya.", id: "Allah Yang Maha Mencegah yang menghindarkan kemudaratan dari hamba-Nya." },
  },
  {
    id: 90,
    arabic: "الضَّارُّ",
    transliteration: "Ad-Darr",
    meaning: { en: "The Distresser", bn: "কষ্টদাতা", ur: "نقصان پہنچانے والا", ar: "الضار", tr: "Zarar Veren", ms: "Yang Maha Memberi Mudarat", id: "Yang Maha Memberi Mudarat" },
    shortDescription: { en: "Allah is the one who can cause harm to those who go against His will.", bn: "আল্লাহ তাঁর ইচ্ছার বিরুদ্ধে যায় তাদের ক্ষতি করতে সক্ষম।", ur: "اللہ ان لوگوں کو نقصان پہنچا سکتا ہے جو اس کی مرضی کے خلاف جائیں۔", ar: "الله قادر على إلحاق الضرر بمن يخالف إرادته.", tr: "Allah iradesine karşı gelenlere zarar verebilir.", ms: "Allah berkuasa mendatangkan mudarat kepada mereka yang menentang kehendak-Nya.", id: "Allah berkuasa mendatangkan mudarat kepada mereka yang menentang kehendak-Nya." },
  },
  {
    id: 91,
    arabic: "النَّافِعُ",
    transliteration: "An-Nafi'",
    meaning: { en: "The Propitious", bn: "উপকারকারী", ur: "نفع دینے والا", ar: "النافع", tr: "Fayda Veren", ms: "Yang Maha Memberi Manfaat", id: "Yang Maha Memberi Manfaat" },
    shortDescription: { en: "Allah is the one who grants benefit and advantage to whom He wills.", bn: "আল্লাহ যাকে ইচ্ছা উপকার ও সুবিধা প্রদান করেন।", ur: "اللہ جسے چاہے فائدہ اور نفع عطا کرتا ہے۔", ar: "الله ينفع من يشاء بما يشاء.", tr: "Allah dilediğine fayda ve menfaat bahşeder.", ms: "Allah memberi manfaat dan kebaikan kepada sesiapa yang Dia kehendaki.", id: "Allah memberi manfaat dan kebaikan kepada siapa saja yang Dia kehendaki." },
  },
  {
    id: 92,
    arabic: "النُّورُ",
    transliteration: "An-Nur",
    meaning: { en: "The Light", bn: "জ্যোতি", ur: "نور", ar: "النور", tr: "Nur", ms: "Yang Maha Bercahaya", id: "Yang Maha Bercahaya" },
    shortDescription: { en: "Allah is the Light of the heavens and the earth.", bn: "আল্লাহ আসমান ও জমিনের জ্যোতি।", ur: "اللہ آسمانوں اور زمین کا نور ہے۔", ar: "الله نور السماوات والأرض.", tr: "Allah göklerin ve yerin nurudur.", ms: "Allah adalah cahaya langit dan bumi.", id: "Allah adalah cahaya langit dan bumi." },
    quranReference: "24:35",
  },
  {
    id: 93,
    arabic: "الْهَادِي",
    transliteration: "Al-Hadi",
    meaning: { en: "The Guide", bn: "পথপ্রদর্শক", ur: "ہدایت دینے والا", ar: "الهادي", tr: "Hidayet Veren", ms: "Yang Maha Memberi Petunjuk", id: "Yang Maha Memberi Petunjuk" },
    shortDescription: { en: "Allah is the Guide who leads people to the straight path.", bn: "আল্লাহ পথপ্রদর্শক যিনি মানুষকে সরল পথে পরিচালিত করেন।", ur: "اللہ ہادی ہے جو لوگوں کو سیدھے راستے کی طرف رہنمائی کرتا ہے۔", ar: "الله الهادي الذي يهدي الناس إلى الصراط المستقيم.", tr: "Allah insanları doğru yola ileten Hadi'dir.", ms: "Allah Yang Maha Memberi Petunjuk yang memimpin manusia ke jalan yang lurus.", id: "Allah Yang Maha Memberi Petunjuk yang memimpin manusia ke jalan yang lurus." },
    quranReference: "22:54",
  },
  {
    id: 94,
    arabic: "الْبَدِيعُ",
    transliteration: "Al-Badi'",
    meaning: { en: "The Incomparable", bn: "অতুলনীয় স্রষ্টা", ur: "بے مثال موجد", ar: "البديع", tr: "Eşsiz Yaratan", ms: "Yang Maha Pencipta yang Tiada Tara", id: "Yang Maha Pencipta yang Tiada Tara" },
    shortDescription: { en: "Allah is the Incomparable Originator who creates without precedent.", bn: "আল্লাহ অতুলনীয় স্রষ্টা যিনি পূর্ব নমুনা ছাড়া সৃষ্টি করেন।", ur: "اللہ بے مثال موجد ہے جو بغیر کسی سابقہ نمونے کے تخلیق کرتا ہے۔", ar: "الله البديع الذي يخلق بلا مثال سابق.", tr: "Allah önceden bir örnek olmaksızın yaratan eşsiz Bedi'dir.", ms: "Allah adalah Pencipta yang tiada tara yang mencipta tanpa contoh terdahulu.", id: "Allah adalah Pencipta yang tiada tara yang menciptakan tanpa contoh terdahulu." },
    quranReference: "2:117",
  },
  {
    id: 95,
    arabic: "الْبَاقِي",
    transliteration: "Al-Baqi",
    meaning: { en: "The Everlasting", bn: "চিরস্থায়ী", ur: "ہمیشہ رہنے والا", ar: "الباقي", tr: "Baki", ms: "Yang Maha Kekal", id: "Yang Maha Kekal" },
    shortDescription: { en: "Allah is the Everlasting whose existence has no end.", bn: "আল্লাহ চিরস্থায়ী যাঁর অস্তিত্বের কোনো শেষ নেই।", ur: "اللہ ہمیشہ رہنے والا ہے جس کے وجود کا کوئی خاتمہ نہیں۔", ar: "الله الباقي الذي لا نهاية لوجوده.", tr: "Allah varlığının sonu olmayan Baki'dir.", ms: "Allah Yang Maha Kekal yang kewujudan-Nya tiada akhir.", id: "Allah Yang Maha Kekal yang keberadaan-Nya tiada akhir." },
  },
  {
    id: 96,
    arabic: "الْوَارِثُ",
    transliteration: "Al-Warith",
    meaning: { en: "The Inheritor", bn: "উত্তরাধিকারী", ur: "وارث", ar: "الوارث", tr: "Varis", ms: "Yang Maha Mewarisi", id: "Yang Maha Mewarisi" },
    shortDescription: { en: "Allah is the Inheritor to whom all things return after they perish.", bn: "আল্লাহ উত্তরাধিকারী যাঁর কাছে সবকিছু ধ্বংসের পর ফিরে যায়।", ur: "اللہ وارث ہے جس کی طرف ہر چیز فنا ہونے کے بعد لوٹتی ہے۔", ar: "الله الوارث الذي يرجع إليه كل شيء بعد فنائه.", tr: "Allah her şeyin yok olduktan sonra kendisine döndüğü Varis'tir.", ms: "Allah Yang Maha Mewarisi yang kepada-Nya segala sesuatu kembali setelah binasa.", id: "Allah Yang Maha Mewarisi yang kepada-Nya segala sesuatu kembali setelah binasa." },
    quranReference: "15:23",
  },
  {
    id: 97,
    arabic: "الرَّشِيدُ",
    transliteration: "Ar-Rashid",
    meaning: { en: "The Guide to the Right Path", bn: "সঠিক পথের নির্দেশক", ur: "سیدھی راہ دکھانے والا", ar: "الرشيد", tr: "Doğru Yola İleten", ms: "Yang Maha Membimbing ke Jalan Benar", id: "Yang Maha Membimbing ke Jalan Benar" },
    shortDescription: { en: "Allah is the Rightly Guided who directs all affairs with perfect wisdom.", bn: "আল্লাহ সঠিক পথনির্দেশক যিনি পরিপূর্ণ প্রজ্ঞায় সকল বিষয় পরিচালনা করেন।", ur: "اللہ رشید ہے جو کامل حکمت سے تمام معاملات کی رہنمائی کرتا ہے۔", ar: "الله الرشيد الذي يدبر الأمور بحكمة تامة.", tr: "Allah tüm işleri mükemmel hikmetle yöneten Reşid'dir.", ms: "Allah Yang Maha Membimbing yang mengatur segala urusan dengan hikmah sempurna.", id: "Allah Yang Maha Membimbing yang mengatur segala urusan dengan hikmah sempurna." },
  },
  {
    id: 98,
    arabic: "الصَّبُورُ",
    transliteration: "As-Sabur",
    meaning: { en: "The Patient", bn: "ধৈর্যশীল", ur: "صبر کرنے والا", ar: "الصبور", tr: "Sabırlı", ms: "Yang Maha Penyabar", id: "Yang Maha Penyabar" },
    shortDescription: { en: "Allah is the Most Patient, who does not hasten punishment for the disobedient.", bn: "আল্লাহ সর্বাধিক ধৈর্যশীল, যিনি অবাধ্যদের শাস্তি তাড়াতাড়ি দেন না।", ur: "اللہ سب سے زیادہ صبر والا ہے، جو نافرمانوں کی سزا میں جلدی نہیں کرتا۔", ar: "الله الصبور الذي لا يعجل بعقوبة العاصين.", tr: "Allah isyan edenlerin cezasını acele etmeyen Sabur'dur.", ms: "Allah Yang Maha Penyabar yang tidak menyegerakan hukuman bagi mereka yang ingkar.", id: "Allah Yang Maha Penyabar yang tidak menyegerakan hukuman bagi mereka yang ingkar." },
  },
  {
    id: 99,
    arabic: "اللَّهُ",
    transliteration: "Allah",
    meaning: { en: "The Greatest Name", bn: "মহান নাম", ur: "سب سے عظیم نام", ar: "الاسم الأعظم", tr: "En Yüce İsim", ms: "Nama Yang Maha Agung", id: "Nama Yang Maha Agung" },
    shortDescription: { en: "Allah — the supreme name encompassing all divine attributes and perfection.", bn: "আল্লাহ — সর্বোচ্চ নাম যা সকল ঐশ্বরিক গুণ ও পূর্ণতাকে ধারণ করে।", ur: "اللہ — عظیم ترین نام جو تمام الہٰی صفات اور کمال کو شامل ہے۔", ar: "الله — الاسم الأعظم الجامع لجميع الصفات الإلهية والكمال.", tr: "Allah — tüm ilahi sıfatları ve mükemmelliği kapsayan en yüce isim.", ms: "Allah — nama yang maha agung yang merangkumi semua sifat ilahi dan kesempurnaan.", id: "Allah — nama yang maha agung yang mencakup semua sifat ilahi dan kesempurnaan." },
  },
];
