import type { TransLang } from "@/lib/islamic-content";

export const LOGIN_PAGE_TEXTS: Record<TransLang, {
  welcomeBack: string;
  signInSubtitle: string;
  signIn: string;
  enterCredentials: string;
  email: string;
  password: string;
  signingIn: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  noAccount: string;
  createOne: string;
  continueWithout: string;
}> = {
  en: {
    welcomeBack: "Welcome Back",
    signInSubtitle: "Sign in to access your Zakat history",
    signIn: "Sign In",
    enterCredentials: "Enter your email and password",
    email: "Email",
    password: "Password",
    signingIn: "Signing in...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Your password",
    noAccount: "Don't have an account?",
    createOne: "Create one",
    continueWithout: "Continue without signing in",
  },
  bn: {
    welcomeBack: "স্বাগতম",
    signInSubtitle: "আপনার যাকাত ইতিহাস দেখতে সাইন ইন করুন",
    signIn: "সাইন ইন",
    enterCredentials: "আপনার ইমেইল এবং পাসওয়ার্ড দিন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    signingIn: "সাইন ইন হচ্ছে...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "আপনার পাসওয়ার্ড",
    noAccount: "অ্যাকাউন্ট নেই?",
    createOne: "তৈরি করুন",
    continueWithout: "সাইন ইন ছাড়া চালিয়ে যান",
  },
  ur: {
    welcomeBack: "خوش آمدید",
    signInSubtitle: "اپنی زکاۃ کی تاریخ دیکھنے کے لیے سائن ان کریں",
    signIn: "سائن ان",
    enterCredentials: "اپنا ای میل اور پاسورڈ درج کریں",
    email: "ای میل",
    password: "پاسورڈ",
    signingIn: "سائن ان ہو رہا ہے...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "آپ کا پاسورڈ",
    noAccount: "اکاؤنٹ نہیں ہے؟",
    createOne: "بنائیں",
    continueWithout: "بغیر سائن ان کے جاری رکھیں",
  },
  ar: {
    welcomeBack: "مرحباً بعودتك",
    signInSubtitle: "سجّل الدخول للوصول إلى سجل زكاتك",
    signIn: "تسجيل الدخول",
    enterCredentials: "أدخل بريدك الإلكتروني وكلمة المرور",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signingIn: "جارٍ تسجيل الدخول...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "كلمة المرور",
    noAccount: "ليس لديك حساب؟",
    createOne: "أنشئ حساباً",
    continueWithout: "المتابعة بدون تسجيل الدخول",
  },
  tr: {
    welcomeBack: "Tekrar Hoş Geldiniz",
    signInSubtitle: "Zekât geçmişinize erişmek için giriş yapın",
    signIn: "Giriş Yap",
    enterCredentials: "E-posta ve şifrenizi girin",
    email: "E-posta",
    password: "Şifre",
    signingIn: "Giriş yapılıyor...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Şifreniz",
    noAccount: "Hesabınız yok mu?",
    createOne: "Oluşturun",
    continueWithout: "Giriş yapmadan devam et",
  },
  ms: {
    welcomeBack: "Selamat Kembali",
    signInSubtitle: "Log masuk untuk mengakses sejarah zakat anda",
    signIn: "Log Masuk",
    enterCredentials: "Masukkan e-mel dan kata laluan anda",
    email: "E-mel",
    password: "Kata Laluan",
    signingIn: "Sedang log masuk...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Kata laluan anda",
    noAccount: "Tiada akaun?",
    createOne: "Daftar sekarang",
    continueWithout: "Teruskan tanpa log masuk",
  },
  id: {
    welcomeBack: "Selamat Datang Kembali",
    signInSubtitle: "Masuk untuk mengakses riwayat zakat Anda",
    signIn: "Masuk",
    enterCredentials: "Masukkan email dan kata sandi Anda",
    email: "Email",
    password: "Kata Sandi",
    signingIn: "Sedang masuk...",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Kata sandi Anda",
    noAccount: "Belum punya akun?",
    createOne: "Buat akun",
    continueWithout: "Lanjutkan tanpa masuk",
  },
};

export const REGISTER_PAGE_TEXTS: Record<TransLang, {
  createAccount: string;
  saveCalculations: string;
  register: string;
  registerDescription: string;
  creatingAccount: string;
  name: string;
  email: string;
  password: string;
  namePlaceholder: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  checkEmail: string;
  verifyEmail: string;
  confirmationSent: string;
  goToLogin: string;
  alreadyHaveAccount: string;
  signIn: string;
}> = {
  en: {
    createAccount: "Create Account",
    saveCalculations: "Save your Zakat calculations across years",
    register: "Register",
    registerDescription: "Create a free account to track your Zakat history",
    creatingAccount: "Creating account...",
    name: "Name",
    email: "Email",
    password: "Password",
    namePlaceholder: "Your name",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Min 6 characters",
    checkEmail: "Check Your Email",
    verifyEmail: "Please verify your email to complete registration.",
    confirmationSent: "We've sent a confirmation link to",
    goToLogin: "Go to Login",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
  },
  bn: {
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    saveCalculations: "বছরের পর বছর আপনার যাকাত হিসাব সংরক্ষণ করুন",
    register: "নিবন্ধন",
    registerDescription: "আপনার যাকাত ইতিহাস ট্র্যাক করতে বিনামূল্যে অ্যাকাউন্ট তৈরি করুন",
    creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    name: "নাম",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    namePlaceholder: "আপনার নাম",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "সর্বনিম্ন ৬ অক্ষর",
    checkEmail: "আপনার ইমেইল চেক করুন",
    verifyEmail: "নিবন্ধন সম্পন্ন করতে আপনার ইমেইল যাচাই করুন।",
    confirmationSent: "আমরা একটি নিশ্চিতকরণ লিঙ্ক পাঠিয়েছি",
    goToLogin: "লগইনে যান",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    signIn: "সাইন ইন",
  },
  ur: {
    createAccount: "اکاؤنٹ بنائیں",
    saveCalculations: "سالوں میں اپنی زکاۃ کی حساب کتاب محفوظ کریں",
    register: "رجسٹر",
    registerDescription: "اپنی زکاۃ کی تاریخ ٹریک کرنے کے لیے مفت اکاؤنٹ بنائیں",
    creatingAccount: "اکاؤنٹ بنایا جا رہا ہے...",
    name: "نام",
    email: "ای میل",
    password: "پاسورڈ",
    namePlaceholder: "آپ کا نام",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "کم از کم ۶ حروف",
    checkEmail: "اپنا ای میل چیک کریں",
    verifyEmail: "رجسٹریشن مکمل کرنے کے لیے اپنا ای میل تصدیق کریں۔",
    confirmationSent: "ہم نے تصدیقی لنک بھیج دیا ہے",
    goToLogin: "لاگ ان پر جائیں",
    alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟",
    signIn: "سائن ان",
  },
  ar: {
    createAccount: "إنشاء حساب",
    saveCalculations: "احفظ حسابات زكاتك عبر السنوات",
    register: "التسجيل",
    registerDescription: "أنشئ حساباً مجانياً لتتبع سجل زكاتك",
    creatingAccount: "جارٍ إنشاء الحساب...",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    namePlaceholder: "اسمك",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "٦ أحرف على الأقل",
    checkEmail: "تحقق من بريدك الإلكتروني",
    verifyEmail: "يرجى التحقق من بريدك الإلكتروني لإكمال التسجيل.",
    confirmationSent: "لقد أرسلنا رابط التأكيد إلى",
    goToLogin: "الذهاب لتسجيل الدخول",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    signIn: "تسجيل الدخول",
  },
  tr: {
    createAccount: "Hesap Oluştur",
    saveCalculations: "Zekât hesaplamalarınızı yıllar boyunca kaydedin",
    register: "Kayıt Ol",
    registerDescription: "Zekât geçmişinizi takip etmek için ücretsiz hesap oluşturun",
    creatingAccount: "Hesap oluşturuluyor...",
    name: "Ad",
    email: "E-posta",
    password: "Şifre",
    namePlaceholder: "Adınız",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "En az 6 karakter",
    checkEmail: "E-postanızı Kontrol Edin",
    verifyEmail: "Kaydı tamamlamak için e-postanızı doğrulayın.",
    confirmationSent: "Onay bağlantısını gönderdik",
    goToLogin: "Girişe Git",
    alreadyHaveAccount: "Zaten hesabınız var mı?",
    signIn: "Giriş yap",
  },
  ms: {
    createAccount: "Buat Akaun",
    saveCalculations: "Simpan pengiraan zakat anda merentasi tahun",
    register: "Daftar",
    registerDescription: "Buat akaun percuma untuk menjejaki sejarah zakat anda",
    creatingAccount: "Membuat akaun...",
    name: "Nama",
    email: "E-mel",
    password: "Kata Laluan",
    namePlaceholder: "Nama anda",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Minimum 6 aksara",
    checkEmail: "Semak E-mel Anda",
    verifyEmail: "Sila sahkan e-mel anda untuk melengkapkan pendaftaran.",
    confirmationSent: "Kami telah menghantar pautan pengesahan ke",
    goToLogin: "Pergi ke Log Masuk",
    alreadyHaveAccount: "Sudah mempunyai akaun?",
    signIn: "Log masuk",
  },
  id: {
    createAccount: "Buat Akun",
    saveCalculations: "Simpan perhitungan zakat Anda selama bertahun-tahun",
    register: "Daftar",
    registerDescription: "Buat akun gratis untuk melacak riwayat zakat Anda",
    creatingAccount: "Membuat akun...",
    name: "Nama",
    email: "Email",
    password: "Kata Sandi",
    namePlaceholder: "Nama Anda",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Minimal 6 karakter",
    checkEmail: "Periksa Email Anda",
    verifyEmail: "Silakan verifikasi email Anda untuk menyelesaikan pendaftaran.",
    confirmationSent: "Kami telah mengirim tautan konfirmasi ke",
    goToLogin: "Ke Halaman Masuk",
    alreadyHaveAccount: "Sudah punya akun?",
    signIn: "Masuk",
  },
};
