import type { TransLang } from "@/lib/islamic-content";

export interface Hadith {
  id: string;
  arabic: string;
  source: string;
  narrator: string;
  translations: Record<TransLang, string>;
}

export const HADITHS: Hadith[] = [
  {
    id: "h1",
    arabic: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
    source: "Sahih al-Bukhari 1",
    narrator: "Umar ibn al-Khattab (RA)",
    translations: {
      en: "Actions are judged by intentions, and every person will get what they intended.",
      bn: "কাজের ফলাফল নিয়্যতের উপর নির্ভরশীল এবং প্রত্যেক ব্যক্তি তাই পাবে যা সে নিয়্যত করেছে।",
      ur: "اعمال کا دارومدار نیتوں پر ہے اور ہر شخص کو وہی ملے گا جو اس نے نیت کی۔",
      ar: "إنما الأعمال بالنيات وإنما لكل امرئ ما نوى",
      tr: "Ameller niyetlere goredir ve herkes niyet ettigi seyi alir.",
      ms: "Sesungguhnya amalan itu bergantung kepada niat dan setiap orang mendapat apa yang diniatkannya.",
      id: "Sesungguhnya amal itu tergantung pada niat dan setiap orang mendapatkan apa yang diniatkannya.",
    },
  },
  {
    id: "h2",
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    source: "Sahih al-Bukhari 5027",
    narrator: "Uthman ibn Affan (RA)",
    translations: {
      en: "The best of you are those who learn the Quran and teach it.",
      bn: "তোমাদের মধ্যে সর্বোত্তম ব্যক্তি সে যে কুরআন শিখে এবং শেখায়।",
      ur: "تم میں سے بہترین وہ ہے جو قرآن سیکھے اور سکھائے۔",
      ar: "خيركم من تعلم القرآن وعلمه",
      tr: "En hayirliniz Kuran'i ogrenen ve ogretendir.",
      ms: "Sebaik-baik kamu adalah yang mempelajari Al-Quran dan mengajarkannya.",
      id: "Sebaik-baik kalian adalah yang mempelajari Al-Quran dan mengajarkannya.",
    },
  },
  {
    id: "h3",
    arabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",
    source: "Sahih Muslim 2699",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "Whoever takes a path in search of knowledge, Allah will make easy for him a path to Paradise.",
      bn: "যে ব্যক্তি জ্ঞান অন্বেষণে পথ চলে, আল্লাহ তার জন্য জান্নাতের পথ সহজ করে দেন।",
      ur: "جو شخص علم کی تلاش میں راستہ چلے، اللہ اس کے لیے جنت کا راستہ آسان کر دیتا ہے۔",
      ar: "من سلك طريقاً يلتمس فيه علماً سهّل الله له طريقاً إلى الجنة",
      tr: "Kim ilim aramak icin bir yola girerse, Allah ona cennete giden yolu kolaylastirir.",
      ms: "Siapa yang menempuh jalan mencari ilmu, Allah akan mudahkan baginya jalan ke syurga.",
      id: "Siapa yang menempuh jalan mencari ilmu, Allah akan mudahkan baginya jalan ke surga.",
    },
  },
  {
    id: "h4",
    arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    source: "Sahih al-Bukhari 10",
    narrator: "Abdullah ibn Amr (RA)",
    translations: {
      en: "A Muslim is one from whose tongue and hand other Muslims are safe.",
      bn: "মুসলিম সেই ব্যক্তি যার জিহ্বা ও হাত থেকে অন্য মুসলিমরা নিরাপদ।",
      ur: "مسلمان وہ ہے جس کی زبان اور ہاتھ سے دوسرے مسلمان محفوظ رہیں۔",
      ar: "المسلم من سلم المسلمون من لسانه ويده",
      tr: "Musluman, dilinden ve elinden diger Muslumanlarin guvenlikte oldugu kimsedir.",
      ms: "Muslim itu ialah orang yang Muslim lain selamat daripada lidah dan tangannya.",
      id: "Muslim itu ialah orang yang Muslim lain selamat dari lidah dan tangannya.",
    },
  },
  {
    id: "h5",
    arabic: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    source: "Sahih al-Bukhari 13",
    narrator: "Anas ibn Malik (RA)",
    translations: {
      en: "None of you truly believes until he loves for his brother what he loves for himself.",
      bn: "তোমাদের কেউ সত্যিকার মুমিন হতে পারবে না যতক্ষণ না সে তার ভাইয়ের জন্য তাই পছন্দ করে যা সে নিজের জন্য পছন্দ করে।",
      ur: "تم میں سے کوئی اس وقت تک مومن نہیں ہو سکتا جب تک وہ اپنے بھائی کے لیے وہی پسند نہ کرے جو اپنے لیے پسند کرتا ہے۔",
      ar: "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه",
      tr: "Sizden biriniz, kendisi icin sevdigini kardesi icin de sevmedikce iman etmis olmaz.",
      ms: "Tidak sempurna iman seseorang sehingga dia mencintai saudaranya sebagaimana mencintai dirinya.",
      id: "Tidak sempurna iman seseorang hingga dia mencintai saudaranya seperti mencintai dirinya.",
    },
  },
  {
    id: "h6",
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    source: "Sahih al-Bukhari 6018",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
      bn: "যে আল্লাহ ও শেষ দিবসে বিশ্বাস করে, সে যেন ভালো কথা বলে অথবা চুপ থাকে।",
      ur: "جو اللہ اور آخرت پر ایمان رکھتا ہے وہ اچھی بات کہے یا خاموش رہے۔",
      ar: "من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت",
      tr: "Allah'a ve ahiret gunune iman eden, ya hayir soylesin ya da sussun.",
      ms: "Sesiapa yang beriman kepada Allah dan Hari Akhirat, hendaklah berkata baik atau diam.",
      id: "Siapa yang beriman kepada Allah dan Hari Akhir, hendaklah berkata baik atau diam.",
    },
  },
  {
    id: "h7",
    arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    source: "Jami at-Tirmidhi 1956",
    narrator: "Abu Dharr (RA)",
    translations: {
      en: "Your smile in the face of your brother is an act of charity.",
      bn: "তোমার ভাইয়ের মুখে তোমার হাসি একটি সদকা।",
      ur: "اپنے بھائی کے سامنے تمہارا مسکرانا صدقہ ہے۔",
      ar: "تبسمك في وجه أخيك لك صدقة",
      tr: "Kardesinin yuzune gulumseyin, bu bir sadakadir.",
      ms: "Senyumanmu di hadapan saudaramu adalah sedekah.",
      id: "Senyumanmu di hadapan saudaramu adalah sedekah.",
    },
  },
  {
    id: "h8",
    arabic: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ",
    source: "Sahih Muslim 2956",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "The world is a prison for the believer and a paradise for the disbeliever.",
      bn: "দুনিয়া মুমিনের জন্য কারাগার এবং কাফিরের জন্য জান্নাত।",
      ur: "دنیا مومن کے لیے قید خانہ اور کافر کے لیے جنت ہے۔",
      ar: "الدنيا سجن المؤمن وجنة الكافر",
      tr: "Dunya müminin zindani, kafirin cennetidir.",
      ms: "Dunia ini penjara orang beriman dan syurga orang kafir.",
      id: "Dunia ini penjara orang beriman dan surga orang kafir.",
    },
  },
  {
    id: "h9",
    arabic: "إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    source: "Sahih Muslim 2564",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "Allah does not look at your appearance or wealth, but He looks at your hearts and deeds.",
      bn: "আল্লাহ তোমাদের চেহারা বা সম্পদ দেখেন না, বরং তোমাদের হৃদয় ও কর্ম দেখেন।",
      ur: "اللہ تمہاری شکل و صورت اور مال نہیں دیکھتا بلکہ تمہارے دل اور اعمال دیکھتا ہے۔",
      ar: "إن الله لا ينظر إلى صوركم وأموالكم ولكن ينظر إلى قلوبكم وأعمالكم",
      tr: "Allah sizin suretlerinize ve mallariniza degil, kalplerinize ve amellerinize bakar.",
      ms: "Sesungguhnya Allah tidak melihat rupa dan harta kamu, tetapi melihat hati dan amalan kamu.",
      id: "Sesungguhnya Allah tidak melihat rupa dan harta kalian, tetapi melihat hati dan amal kalian.",
    },
  },
  {
    id: "h10",
    arabic: "الطُّهُورُ شَطْرُ الْإِيمَانِ",
    source: "Sahih Muslim 223",
    narrator: "Abu Malik al-Ashari (RA)",
    translations: {
      en: "Cleanliness is half of faith.",
      bn: "পরিচ্ছন্নতা ঈমানের অর্ধেক।",
      ur: "صفائی آدھا ایمان ہے۔",
      ar: "الطهور شطر الإيمان",
      tr: "Temizlik imanin yarisidir.",
      ms: "Kebersihan itu separuh daripada iman.",
      id: "Kebersihan itu sebagian dari iman.",
    },
  },
  {
    id: "h11",
    arabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ",
    source: "Sahih Muslim 2588",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "Charity does not decrease wealth.",
      bn: "সদকা সম্পদ কমায় না।",
      ur: "صدقہ مال میں کمی نہیں کرتا۔",
      ar: "ما نقصت صدقة من مال",
      tr: "Sadaka mali eksiltmez.",
      ms: "Sedekah tidak mengurangkan harta.",
      id: "Sedekah tidak mengurangi harta.",
    },
  },
  {
    id: "h12",
    arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ",
    source: "Jami at-Tirmidhi 1987",
    narrator: "Abu Dharr & Muadh ibn Jabal (RA)",
    translations: {
      en: "Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.",
      bn: "তুমি যেখানেই থাকো আল্লাহকে ভয় করো, মন্দ কাজের পর ভালো কাজ করো তা মুছে যাবে, এবং মানুষের সাথে ভালো ব্যবহার করো।",
      ur: "جہاں بھی ہو اللہ سے ڈرو، برائی کے بعد نیکی کرو وہ مٹ جائے گی، اور لوگوں سے اچھے اخلاق سے پیش آؤ۔",
      ar: "اتق الله حيثما كنت وأتبع السيئة الحسنة تمحها وخالق الناس بخلق حسن",
      tr: "Nerede olursan ol Allah'tan kork, kotulugu iyilikle takip et ki onu silsin, ve insanlara guzel ahlakla davran.",
      ms: "Bertakwalah kepada Allah di mana sahaja kamu berada, ikutilah keburukan dengan kebaikan nescaya ia menghapusnya, dan bergaullah dengan manusia dengan akhlak yang baik.",
      id: "Bertakwalah kepada Allah di mana saja kamu berada, ikutilah keburukan dengan kebaikan niscaya ia menghapusnya, dan bergaullah dengan manusia dengan akhlak yang baik.",
    },
  },
  {
    id: "h13",
    arabic: "الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ",
    source: "Sahih Muslim 2664",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.",
      bn: "শক্তিশালী মুমিন দুর্বল মুমিনের চেয়ে আল্লাহর কাছে উত্তম ও অধিক প্রিয়, তবে উভয়ের মধ্যেই কল্যাণ রয়েছে।",
      ur: "طاقتور مومن کمزور مومن سے اللہ کے نزدیک بہتر اور زیادہ محبوب ہے، حالانکہ دونوں میں خیر ہے۔",
      ar: "المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف وفي كل خير",
      tr: "Guclu mumin, zayif muminden daha hayirli ve Allah'a daha sevimlidir, her ikisinde de hayir vardir.",
      ms: "Mukmin yang kuat lebih baik dan lebih dicintai Allah daripada mukmin yang lemah, dan pada kedua-duanya ada kebaikan.",
      id: "Mukmin yang kuat lebih baik dan lebih dicintai Allah daripada mukmin yang lemah, dan pada keduanya ada kebaikan.",
    },
  },
  {
    id: "h14",
    arabic: "مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا",
    source: "Sahih Muslim 408",
    narrator: "Abu Hurairah (RA)",
    translations: {
      en: "Whoever sends blessings upon me once, Allah will send blessings upon him tenfold.",
      bn: "যে আমার উপর একবার দরুদ পাঠায়, আল্লাহ তার উপর দশবার রহমত পাঠান।",
      ur: "جو مجھ پر ایک بار درود بھیجے، اللہ اس پر دس بار رحمت نازل کرتا ہے۔",
      ar: "من صلى عليّ صلاة صلى الله عليه بها عشراً",
      tr: "Kim bana bir kez salavat getirirse, Allah ona on kez rahmet eder.",
      ms: "Sesiapa yang berselawat ke atasku satu kali, Allah akan berselawat ke atasnya sepuluh kali.",
      id: "Siapa yang bershalawat kepadaku satu kali, Allah akan bershalawat kepadanya sepuluh kali.",
    },
  },
  {
    id: "h15",
    arabic: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ",
    source: "Mu'jam al-Awsat 5787",
    narrator: "Jabir ibn Abdullah (RA)",
    translations: {
      en: "The best of people are those most beneficial to people.",
      bn: "মানুষের মধ্যে সর্বোত্তম সেই যে মানুষের সবচেয়ে বেশি উপকারী।",
      ur: "لوگوں میں سب سے بہتر وہ ہے جو لوگوں کو سب سے زیادہ فائدہ پہنچائے۔",
      ar: "خير الناس أنفعهم للناس",
      tr: "Insanlarin en hayirlisi, insanlara en faydali olanidir.",
      ms: "Sebaik-baik manusia ialah yang paling bermanfaat kepada manusia.",
      id: "Sebaik-baik manusia ialah yang paling bermanfaat bagi manusia.",
    },
  },
];

export const HADITH_TEXTS: Record<TransLang, {
  title: string;
  subtitle: string;
  todaysHadith: string;
  narrator: string;
  source: string;
  favorites: string;
  allHadiths: string;
  noFavorites: string;
  copied: string;
  share: string;
  copy: string;
}> = {
  en: {
    title: "Hadith of the Day",
    subtitle: "Daily wisdom from the Prophet Muhammad (PBUH)",
    todaysHadith: "Today's Hadith",
    narrator: "Narrator",
    source: "Source",
    favorites: "Favorites",
    allHadiths: "All Hadiths",
    noFavorites: "No favorite hadiths yet. Tap the heart icon to save!",
    copied: "Copied!",
    share: "Share",
    copy: "Copy",
  },
  bn: {
    title: "আজকের হাদিস",
    subtitle: "নবী মুহাম্মদ (সাঃ) এর দৈনিক জ্ঞান",
    todaysHadith: "আজকের হাদিস",
    narrator: "বর্ণনাকারী",
    source: "উৎস",
    favorites: "পছন্দসমূহ",
    allHadiths: "সকল হাদিস",
    noFavorites: "এখনো কোনো পছন্দের হাদিস নেই। সংরক্ষণ করতে হার্ট আইকনে ট্যাপ করুন!",
    copied: "কপি হয়েছে!",
    share: "শেয়ার",
    copy: "কপি",
  },
  ur: {
    title: "آج کی حدیث",
    subtitle: "نبی محمد ﷺ کی روزانہ حکمت",
    todaysHadith: "آج کی حدیث",
    narrator: "راوی",
    source: "ماخذ",
    favorites: "پسندیدہ",
    allHadiths: "تمام احادیث",
    noFavorites: "ابھی تک کوئی پسندیدہ حدیث نہیں۔ محفوظ کرنے کے لیے دل کے آئیکن پر ٹیپ کریں!",
    copied: "کاپی ہو گیا!",
    share: "شیئر",
    copy: "کاپی",
  },
  ar: {
    title: "حديث اليوم",
    subtitle: "حكمة يومية من النبي محمد ﷺ",
    todaysHadith: "حديث اليوم",
    narrator: "الراوي",
    source: "المصدر",
    favorites: "المفضلة",
    allHadiths: "جميع الأحاديث",
    noFavorites: "لا توجد أحاديث مفضلة بعد. اضغط على أيقونة القلب للحفظ!",
    copied: "تم النسخ!",
    share: "مشاركة",
    copy: "نسخ",
  },
  tr: {
    title: "Gunun Hadisi",
    subtitle: "Hz. Muhammed'den (SAV) gunluk hikmet",
    todaysHadith: "Gunun Hadisi",
    narrator: "Ravi",
    source: "Kaynak",
    favorites: "Favoriler",
    allHadiths: "Tum Hadisler",
    noFavorites: "Henuz favori hadis yok. Kaydetmek icin kalp simgesine dokunun!",
    copied: "Kopyalandi!",
    share: "Paylas",
    copy: "Kopyala",
  },
  ms: {
    title: "Hadis Hari Ini",
    subtitle: "Hikmah harian dari Nabi Muhammad SAW",
    todaysHadith: "Hadis Hari Ini",
    narrator: "Perawi",
    source: "Sumber",
    favorites: "Kegemaran",
    allHadiths: "Semua Hadis",
    noFavorites: "Belum ada hadis kegemaran. Ketik ikon hati untuk simpan!",
    copied: "Disalin!",
    share: "Kongsi",
    copy: "Salin",
  },
  id: {
    title: "Hadis Hari Ini",
    subtitle: "Hikmah harian dari Nabi Muhammad SAW",
    todaysHadith: "Hadis Hari Ini",
    narrator: "Perawi",
    source: "Sumber",
    favorites: "Favorit",
    allHadiths: "Semua Hadis",
    noFavorites: "Belum ada hadis favorit. Ketuk ikon hati untuk simpan!",
    copied: "Disalin!",
    share: "Bagikan",
    copy: "Salin",
  },
};
