import type { TransLang } from "@/lib/islamic-content";

export interface HistoryChapter {
  id: string;
  order: number;
  hijriYear: string;
  gregorianYear: string;
  title: Record<TransLang, string>;
  subtitle: Record<TransLang, string>;
  content: Record<TransLang, string>;
  keyFigures: string[];
  quranReference?: string;
}

export const ISLAMIC_HISTORY_CHAPTERS: HistoryChapter[] = [
  {
    id: "jahiliyyah",
    order: 1,
    hijriYear: "Pre-Islamic",
    gregorianYear: "~500-610 CE",
    title: {
      en: "Pre-Islamic Arabia (Jahiliyyah)",
      bn: "প্রাক-ইসলামিক আরব (জাহিলিয়্যাহ)",
      ur: "قبل از اسلام عرب (جاہلیت)",
      ar: "الجزيرة العربية قبل الإسلام (الجاهلية)",
      tr: "İslam Öncesi Arabistan (Cahiliye)",
      ms: "Arabia Pra-Islam (Jahiliyyah)",
      id: "Arabia Pra-Islam (Jahiliyyah)",
    },
    subtitle: {
      en: "The Arabian Peninsula Before the Dawn of Islam",
      bn: "ইসলামের ঊষালগ্নের পূর্বে আরব উপদ্বীপ",
      ur: "اسلام کی سحر سے پہلے جزیرہ نما عرب",
      ar: "شبه الجزيرة العربية قبل فجر الإسلام",
      tr: "İslam'ın Doğuşundan Önce Arap Yarımadası",
      ms: "Semenanjung Arab Sebelum Fajar Islam",
      id: "Semenanjung Arab Sebelum Fajar Islam",
    },
    content: {
      en: "The Arabian Peninsula before Islam was a land of stark contrasts. Vast deserts separated scattered oases and trading towns, while the coastal regions of Yemen and the Hejaz served as vital links in international trade routes connecting the Roman Empire, Persia, India, and East Africa. Makkah, situated in a barren valley, rose to prominence as both a commercial hub and a religious center.\n\nTribal identity formed the bedrock of Arabian society. Each tribe operated as an independent political unit, bound by ties of kinship and collective honor. The concept of asabiyyah (tribal solidarity) governed social relations, and inter-tribal conflicts could last for generations. Justice was administered through customary law, and poets served as the chroniclers and propagandists of tribal virtues.\n\nReligiously, the Arabs practiced a form of polytheism. The Ka'bah in Makkah housed over 360 idols, attracting pilgrims from across the peninsula. Despite this widespread idolatry, traces of the monotheistic legacy of Prophet Ibrahim (Abraham) persisted among a group known as the Hanifs, who rejected idol worship and sought the original pure faith. Christianity and Judaism also had footholds in parts of Arabia, particularly in Najran and Yathrib (later Madinah).\n\nSocial conditions during the Jahiliyyah period were harsh for many. Women had limited rights, female infanticide was practiced by some tribes, and slavery was widespread. The wealthy merchant class in Makkah, led by the Quraysh tribe, accumulated vast fortunes while the poor and enslaved had little recourse. Yet this same society also upheld values of hospitality, generosity, and eloquence in poetry that would later be channeled and elevated by Islam.",
      bn: "ইসলামের আগে আরব উপদ্বীপ ছিল তীব্র বৈপরীত্যের ভূমি। বিস্তীর্ণ মরুভূমি ছড়িয়ে থাকা মরূদ্যান ও বাণিজ্যিক শহরগুলোকে পৃথক করত, আর ইয়েমেন ও হেজাজের উপকূলীয় অঞ্চল রোমান সাম্রাজ্য, পারস্য, ভারত এবং পূর্ব আফ্রিকাকে সংযুক্তকারী আন্তর্জাতিক বাণিজ্য পথে গুরুত্বপূর্ণ সংযোগ হিসেবে কাজ করত। মক্কা, একটি অনুর্বর উপত্যকায় অবস্থিত, বাণিজ্যিক ও ধর্মীয় কেন্দ্র হিসেবে প্রাধান্য লাভ করে।\n\nগোত্রীয় পরিচয় আরব সমাজের ভিত্তি গঠন করত। প্রতিটি গোত্র আত্মীয়তা ও সম্মানের বন্ধনে আবদ্ধ স্বাধীন রাজনৈতিক একক হিসেবে কাজ করত। আসাবিয়্যাহ (গোত্রীয় সংহতি) সামাজিক সম্পর্ক নিয়ন্ত্রণ করত এবং আন্তঃগোত্রীয় সংঘাত প্রজন্মের পর প্রজন্ম চলত। বিচার প্রথাগত আইনের মাধ্যমে হতো এবং কবিরা গোত্রীয় গুণাবলির ইতিহাসবিদ হিসেবে কাজ করতেন।\n\nধর্মীয়ভাবে আরবরা বহুদেবতাবাদের চর্চা করত। মক্কার কাবায় ৩৬০টিরও বেশি মূর্তি ছিল যা সমগ্র উপদ্বীপ থেকে তীর্থযাত্রীদের আকৃষ্ট করত। এই ব্যাপক মূর্তিপূজা সত্ত্বেও, ইব্রাহিম (আ.)-এর একেশ্বরবাদী উত্তরাধিকার হানিফ নামে পরিচিত একটি গোষ্ঠীর মধ্যে টিকে ছিল। খ্রিস্টধর্ম ও ইহুদি ধর্মেরও নাজরান ও ইয়াসরিবে (পরবর্তীতে মদিনা) অবস্থান ছিল।\n\nজাহিলিয়্যাহ যুগে সামাজিক পরিস্থিতি অনেকের জন্য কঠোর ছিল। নারীদের অধিকার সীমিত ছিল, কিছু গোত্র কন্যা সন্তান হত্যা করত এবং দাসপ্রথা ব্যাপক ছিল। কুরাইশ গোত্রের নেতৃত্বে মক্কার ধনী বণিক শ্রেণী বিপুল সম্পদ জমা করলেও দরিদ্র ও দাসদের কোনো আশ্রয় ছিল না। তবুও এই সমাজ আতিথেয়তা, উদারতা ও কাব্যে বাগ্মিতার মূল্যবোধও ধারণ করত যা পরে ইসলাম দ্বারা উন্নীত হয়।",
      ur: "اسلام سے پہلے جزیرہ نما عرب شدید تضادات کی سرزمین تھی۔ وسیع صحراؤں نے بکھری نخلستانوں اور تجارتی قصبوں کو الگ کیا، جبکہ یمن اور حجاز کے ساحلی علاقے رومی سلطنت، فارس، ہند اور مشرقی افریقہ کو جوڑنے والے بین الاقوامی تجارتی راستوں میں اہم کڑی تھے۔ مکہ ایک بنجر وادی میں واقع تجارتی اور مذہبی مرکز کے طور پر نمایاں ہوا۔\n\nقبائلی شناخت عرب معاشرے کی بنیاد تھی۔ ہر قبیلہ رشتہ داری اور اجتماعی عزت سے بندھا آزاد سیاسی اکائی تھا۔ عصبیت (قبائلی یکجہتی) سماجی تعلقات پر حاوی تھی اور بین القبائلی تنازعات نسلوں تک جاری رہتے۔ انصاف رواجی قانون سے ہوتا اور شعراء قبائلی فضائل کے مؤرخ تھے۔\n\nمذہبی طور پر عرب شرک کرتے تھے۔ مکہ میں کعبہ میں 360 سے زیادہ بت تھے جو پورے جزیرے سے زائرین کھینچتے۔ اس وسیع بت پرستی کے باوجود حضرت ابراہیم علیہ السلام کی توحیدی میراث حنفاء نامی گروہ میں باقی تھی جو بت پرستی سے انکاری تھے۔ عیسائیت اور یہودیت کا بھی نجران اور یثرب (بعد میں مدینہ) میں وجود تھا۔\n\nجاہلیت میں سماجی حالات سخت تھے۔ عورتوں کے حقوق محدود، بعض قبائل میں لڑکیاں زندہ دفنائی جاتیں اور غلامی عام تھی۔ قریش کی سربراہی میں مکہ کے دولت مند تاجروں نے بے پناہ دولت جمع کی جبکہ غریب بے سہارا تھے۔ تاہم اسی معاشرے نے مہمان نوازی، سخاوت اور فصاحت کی اقدار بھی بلند رکھیں جنہیں اسلام نے بعد میں سمت دی۔",
      ar: "كانت شبه الجزيرة العربية قبل الإسلام أرض تناقضات صارخة. فصلت الصحاري الشاسعة الواحات والمدن التجارية المتناثرة، بينما كانت سواحل اليمن والحجاز حلقات وصل حيوية في طرق التجارة الدولية بين الإمبراطورية الرومانية وفارس والهند وشرق أفريقيا. وبرزت مكة في واد قاحل كمركز تجاري وديني.\n\nشكّلت الهوية القبلية أساس المجتمع العربي. كل قبيلة وحدة سياسية مستقلة مرتبطة بالقرابة والشرف الجماعي. حكمت العصبية العلاقات الاجتماعية واستمرت النزاعات القبلية أجيالاً. أُدير العدل بالعرف وكان الشعراء مؤرخي فضائل القبيلة.\n\nدينياً مارس العرب الشرك. ضمّت الكعبة أكثر من 360 صنماً تستقطب الحجاج من أنحاء الجزيرة. رغم ذلك بقي إرث إبراهيم التوحيدي عند الحنفاء الذين رفضوا الأصنام. كما وُجدت المسيحية واليهودية في نجران ويثرب.\n\nكانت الأوضاع الاجتماعية في الجاهلية قاسية. حقوق المرأة محدودة ومارست بعض القبائل الوأد وانتشرت العبودية. جمع تجار قريش الأثرياء ثروات طائلة بينما افتقر الفقراء والعبيد لأي سند. ومع ذلك أعلى هذا المجتمع الضيافة والكرم والبلاغة التي وجّهها الإسلام لاحقاً.",
      tr: "İslam öncesi Arap Yarımadası keskin zıtlıkların toprağıydı. Geniş çöller vahaları ve ticaret kasabalarını ayırırken, Yemen ve Hicaz kıyıları Roma, Pers, Hindistan ve Doğu Afrika'yı bağlayan uluslararası ticaret yollarında hayati bağlantılardı. Çorak bir vadideki Mekke hem ticari hem dini merkez olarak öne çıktı.\n\nKabile kimliği Arap toplumunun temeliydi. Her kabile akrabalık ve kolektif onurla bağlı bağımsız siyasi birimdi. Asabiyet sosyal ilişkileri yönetiyor, kabileler arası çatışmalar nesiller boyu sürebiliyordu. Adalet örfi hukukla sağlanır, şairler kabile erdemlerinin tarihçileriydi.\n\nDini açıdan Araplar çok tanrıcılık uygulardı. Kâbe'de 360'tan fazla put bulunuyor, yarımadanın her yerinden hacı çekiyordu. Yaygın putperestliğe rağmen Hz. İbrahim'in tevhid mirası Hanifler arasında sürdü. Hristiyanlık ve Yahudilik de Necran ve Yesrib'de varlığını koruyordu.\n\nCahiliye'de sosyal koşullar sertti. Kadın hakları sınırlı, bazı kabileler kız çocuklarını diri gömer, kölelik yaygındı. Kureyş'in zengin tüccarları servet biriktirirken yoksullar çaresizdi. Yine de aynı toplum misafirperverlik, cömertlik ve şiirsel belagat değerlerini yüceltti; İslam bunları sonra yönlendirip yükseltti.",
      ms: "Semenanjung Arab sebelum Islam penuh kontras ketara. Gurun luas memisahkan oasis dan pekan perdagangan, manakala pesisir Yaman dan Hijaz menjadi penghubung penting jalur perdagangan antarabangsa antara Empayar Rom, Parsi, India, dan Afrika Timur. Makkah di lembah gersang muncul sebagai pusat perdagangan dan keagamaan.\n\nIdentiti kesukuan menjadi asas masyarakat Arab. Setiap suku beroperasi sebagai unit politik bebas terikat kekeluargaan dan kehormatan kolektif. Asabiyyah mengawal hubungan sosial dan konflik antara suku boleh berlanjutan beberapa generasi. Keadilan ditadbir melalui adat dan penyair mencatat kebaikan suku.\n\nDari segi agama, orang Arab mengamalkan politeisme. Kaabah menempatkan lebih 360 berhala menarik jemaah dari seluruh semenanjung. Meskipun begitu, warisan monoteisme Nabi Ibrahim a.s. kekal dalam kalangan Hanif yang menolak berhala. Kristian dan Yahudi juga wujud di Najran dan Yathrib.\n\nKeadaan sosial zaman Jahiliyyah keras. Hak wanita terhad, sesetengah suku membunuh bayi perempuan, dan perhambaan berleluasa. Saudagar kaya Quraisy mengumpul kekayaan besar manakala golongan miskin tiada jalan keluar. Namun masyarakat ini juga menjunjung keramahtamahan, kemurahan hati, dan kefasihan puisi yang kemudian ditinggikan Islam.",
      id: "Semenanjung Arab sebelum Islam penuh kontras tajam. Gurun luas memisahkan oasis dan kota perdagangan, sementara pesisir Yaman dan Hijaz menjadi penghubung vital jalur perdagangan internasional antara Kekaisaran Romawi, Persia, India, dan Afrika Timur. Makkah di lembah gersang menonjol sebagai pusat perdagangan dan keagamaan.\n\nIdentitas kesukuan membentuk fondasi masyarakat Arab. Setiap suku beroperasi sebagai unit politik independen terikat kekerabatan dan kehormatan kolektif. Asabiyyah mengatur hubungan sosial dan konflik antarsuku bisa berlangsung beberapa generasi. Keadilan dilaksanakan melalui hukum adat dan penyair berperan sebagai pencatat keutamaan suku.\n\nSecara agama, bangsa Arab mempraktikkan politeisme. Ka'bah menampung lebih dari 360 berhala menarik peziarah dari seluruh semenanjung. Meskipun demikian, warisan monoteisme Nabi Ibrahim a.s. bertahan di kalangan Hanif yang menolak berhala. Kristen dan Yahudi juga hadir di Najran dan Yatsrib.\n\nKondisi sosial Jahiliyyah sangat keras. Hak perempuan terbatas, beberapa suku membunuh bayi perempuan, dan perbudakan meluas. Pedagang kaya Quraisy mengumpulkan kekayaan besar sementara kaum miskin tak berdaya. Namun masyarakat ini juga menjunjung keramahan, kemurahan hati, dan kefasihan puisi yang kemudian diarahkan dan ditinggikan oleh Islam.",
    },
    keyFigures: ["Various Arab tribes", "Quraysh", "Hashim clan"],
  },
  {
    id: "birth-early-life",
    order: 2,
    hijriYear: "Pre-Islamic",
    gregorianYear: "570 CE",
    title: {
      en: "Birth & Early Life of Prophet Muhammad \uFDFA",
      bn: "নবী মুহাম্মদ ﷺ-এর জন্ম ও প্রারম্ভিক জীবন",
      ur: "نبی محمد ﷺ کی ولادت اور ابتدائی زندگی",
      ar: "مولد النبي محمد ﷺ وحياته المبكرة",
      tr: "Hz. Muhammed \uFDFA'in Doğumu ve İlk Yılları",
      ms: "Kelahiran & Kehidupan Awal Nabi Muhammad \uFDFA",
      id: "Kelahiran & Kehidupan Awal Nabi Muhammad \uFDFA",
    },
    subtitle: {
      en: "The Beloved Prophet's Journey from Orphanhood to Prophethood",
      bn: "প্রিয় নবীর এতিমত্ব থেকে নবুওয়াত পর্যন্ত যাত্রা",
      ur: "محبوب نبی کا یتیمی سے نبوت تک کا سفر",
      ar: "رحلة النبي الحبيب من اليُتم إلى النبوة",
      tr: "Sevgili Peygamber'in Yetimlikten Peygamberliğe Yolculuğu",
      ms: "Perjalanan Nabi dari Yatim ke Kenabian",
      id: "Perjalanan Nabi dari Yatim Piatu hingga Kenabian",
    },
    content: {
      en: "Prophet Muhammad \uFDFA was born in Makkah in the Year of the Elephant (570 CE), so named because of the failed attempt by Abraha, the Abyssinian governor of Yemen, to destroy the Ka'bah with an army that included war elephants. His father Abdullah ibn Abdul Muttalib had passed away before his birth, and his mother Aminah bint Wahb would pass away when he was only six years old, making him an orphan at a tender age.\n\nFollowing the custom of the Quraysh, the infant Muhammad was sent to the desert to be nursed by Halimah al-Sa'diyah of the Banu Sa'd tribe. In the open desert the young child grew strong and learned the pure Arabic dialect. Remarkable events during his time with Halimah's family hinted at his extraordinary future. After his mother's death, his grandfather Abdul Muttalib, the respected chief of the Hashim clan and custodian of the Ka'bah, cared for him with great affection.\n\nWhen Abdul Muttalib passed away two years later, the young Muhammad came under the guardianship of his uncle Abu Talib, who was kind and protective but of modest means. As a youth, Muhammad \uFDFA worked as a shepherd, a profession shared by many prophets before him. This humble work taught him patience, responsibility, and a contemplative nature that would define his character.\n\nAs he grew older, Muhammad \uFDFA became known for his exceptional honesty and trustworthiness, earning the titles Al-Sadiq (The Truthful) and Al-Amin (The Trustworthy). He accompanied his uncle on trading journeys to Syria, where a Christian monk named Bahira recognized signs of prophethood in him. At twenty-five, he married Khadijah bint Khuwaylid, a successful businesswoman of forty. Their marriage was one of deep love and mutual respect. Khadijah would become the first person to accept Islam.",
      bn: "নবী মুহাম্মদ ﷺ হাতির বছরে (৫৭০ খ্রি.) মক্কায় জন্মগ্রহণ করেন। ইয়েমেনের আবিসিনীয় গভর্নর আবরাহা যুদ্ধের হাতিসহ সেনাবাহিনী নিয়ে কাবা ধ্বংসের ব্যর্থ চেষ্টা করায় এই নামকরণ। তাঁর পিতা আব্দুল্লাহ জন্মের আগেই ইন্তেকাল করেন এবং মা আমিনা ছয় বছর বয়সে ইন্তেকাল করেন।\n\nকুরাইশ প্রথা অনুযায়ী শিশু মুহাম্মদকে বনু সাদ গোত্রের হালিমা সাদিয়ার কাছে মরুভূমিতে পাঠানো হয়। সেখানে তিনি শক্তিশালী হয়ে ওঠেন ও বিশুদ্ধ আরবি শেখেন। মায়ের মৃত্যুর পর দাদা আব্দুল মুত্তালিব, হাশিম বংশের প্রধান ও কাবার তত্ত্বাবধায়ক, স্নেহে তাঁর যত্ন নেন।\n\nদুই বছর পর দাদার ইন্তেকালে চাচা আবু তালিবের অভিভাবকত্বে আসেন। যুবক মুহাম্মদ ﷺ মেষপালক হিসেবে কাজ করেন যা তাঁকে ধৈর্য ও দায়িত্ববোধ শেখায়। এটি আগের অনেক নবীরও পেশা ছিল।\n\nবয়স বাড়তে থাকলে তিনি আল-সাদিক ও আল-আমিন উপাধি পান। চাচার সাথে সিরিয়ায় বাণিজ্যিক সফরে যান যেখানে বাহিরা নামক সন্ন্যাসী নবুওয়াতের চিহ্ন চেনেন। পঁচিশ বছর বয়সে সফল ব্যবসায়ী খাদিজা বিনতে খুওয়াইলিদকে বিয়ে করেন। তাঁদের বিবাহ গভীর ভালোবাসা ও সম্মানের ছিল। খাদিজাই প্রথম ইসলাম গ্রহণকারী।",
      ur: "نبی محمد ﷺ مکہ میں عام الفیل (570 ء) میں پیدا ہوئے۔ یمن کے حبشی گورنر ابرہہ نے ہاتھیوں کی فوج سے کعبہ تباہ کرنے کی ناکام کوشش کی اس لیے یہ نام پڑا۔ والد عبداللہ ولادت سے پہلے اور والدہ آمنہ چھ سال کی عمر میں وفات پا گئیں۔\n\nقریش کے رواج کے مطابق شیرخوار محمد کو بنو سعد کی حلیمہ سعدیہ کے پاس صحرا میں بھیجا گیا۔ وہاں آپ نے طاقت اور خالص عربی سیکھی۔ والدہ کی وفات کے بعد دادا عبدالمطلب، بنو ہاشم کے سردار اور کعبہ کے متولی، نے شفقت سے پرورش کی۔\n\nدو سال بعد دادا کی وفات پر چچا ابوطالب کی سرپرستی میں آئے۔ نوجوانی میں چرواہے کا کام کیا جو بہت سے انبیاء کا پیشہ تھا۔ اس نے صبر اور ذمہ داری سکھائی۔\n\nبڑے ہوئے تو الصادق اور الامین کے القاب ملے۔ چچا کے ساتھ شام کے تجارتی سفر میں بحیرا راہب نے نبوت کی نشانیاں پہچانیں۔ پچیس سال میں خدیجہ بنت خویلد سے شادی کی جو کامیاب تاجر خاتون تھیں۔ یہ محبت اور احترام کا رشتہ تھا۔ وحی آنے پر خدیجہ پہلی مسلمان بنیں۔",
      ar: "وُلد النبي محمد ﷺ في مكة عام الفيل (570 م) حين فشل أبرهة والي اليمن الحبشي في هدم الكعبة بجيش فيه أفيال حربية. توفي والده عبد الله قبل ولادته وتوفيت أمه آمنة وهو في السادسة فصار يتيماً.\n\nوفق عادة قريش أُرسل الرضيع محمد إلى حليمة السعدية في بني سعد بالبادية. نشأ قوياً وتعلم العربية الفصحى. بعد وفاة أمه رعاه جده عبد المطلب زعيم بني هاشم وسادن الكعبة بحنان بالغ.\n\nبعد وفاة جده بعامين انتقل لكفالة عمه أبي طالب الحنون المحدود الموارد. عمل محمد ﷺ شاباً راعياً للغنم كما فعل أنبياء قبله. علّمه ذلك الصبر والمسؤولية والتأمل.\n\nاشتُهر بالصدق والأمانة فلُقّب بالصادق الأمين. رافق عمه في رحلات تجارية للشام حيث تعرّف عليه الراهب بحيرا. تزوج في الخامسة والعشرين من خديجة بنت خويلد سيدة الأعمال الناجحة. كان زواجهما قائماً على الحب والاحترام. وكانت خديجة أول من أسلم.",
      tr: "Hz. Muhammed \uFDFA Fil Yılı'nda (570) Mekke'de doğdu. Yemen valisi Ebrehe'nin fillerle Kâbe'yi yıkma girişimi başarısız olmuş ve yıl bu adı almıştı. Babası Abdullah doğumundan önce, annesi Âmine altı yaşındayken vefat etti.\n\nKureyş geleneğiyle bebek Muhammed Beni Sa'd'dan Halime es-Sa'diyye'ye çöle gönderildi. Burada güçlü büyüdü ve saf Arapça öğrendi. Annesi vefat edince dedesi Abdülmuttalib, Hâşimoğulları reisi ve Kâbe hizmetkârı, onu şefkatle yetiştirdi.\n\nDedesi iki yıl sonra vefat edince amcası Ebû Tâlib'in himayesine girdi. Gençliğinde çobanlık yaptı; birçok peygamberin de mesleğiydi. Bu ona sabır ve sorumluluk öğretti.\n\nBüyüdükçe es-Sâdık ve el-Emîn unvanlarını kazandı. Amcasıyla Suriye'ye ticaret yolculuklarında rahip Bahira onda peygamberlik işaretleri gördü. Yirmi beşinde başarılı iş kadını Hatice bint Huveylid'le evlendi. Evlilikleri sevgi ve saygı üzerineydi. Vahiy geldiğinde ilk Müslüman Hatice oldu.",
      ms: "Nabi Muhammad \uFDFA lahir di Makkah pada Tahun Gajah (570 M) ketika Abrahah gagal memusnahkan Kaabah dengan tentera bergajah. Bapanya Abdullah wafat sebelum kelahirannya dan ibunya Aminah wafat ketika baginda berusia enam tahun.\n\nMengikut adat Quraisy, bayi Muhammad dihantar ke padang pasir kepada Halimah al-Sa'diyah dari Bani Sa'd. Di situ baginda membesar dengan sihat dan mempelajari bahasa Arab tulen. Selepas ibunya wafat, datuknya Abdul Muttalib, ketua Bani Hashim dan penjaga Kaabah, menjaga baginda penuh kasih sayang.\n\nApabila datuknya wafat dua tahun kemudian, baginda di bawah jagaan bapa saudara Abu Talib yang baik hati tetapi sederhana. Sebagai pemuda, baginda bekerja sebagai pengembala seperti ramai nabi sebelumnya. Ini mengajar kesabaran dan tanggungjawab.\n\nBaginda terkenal dengan gelaran Al-Sadiq dan Al-Amin. Dalam perjalanan dagang ke Syam bersama bapa saudara, rahib Bahira mengenali tanda kenabian. Pada usia 25 tahun berkahwin dengan Khadijah binti Khuwaylid, wanita perniagaan berjaya. Perkahwinan mereka penuh cinta dan hormat. Khadijah menjadi orang pertama memeluk Islam.",
      id: "Nabi Muhammad \uFDFA lahir di Makkah pada Tahun Gajah (570 M) saat Abrahah gagal menghancurkan Ka'bah dengan pasukan bergajah. Ayahnya Abdullah wafat sebelum kelahirannya dan ibunya Aminah wafat saat beliau berusia enam tahun.\n\nMengikuti kebiasaan Quraisy, bayi Muhammad dikirim ke padang pasir kepada Halimah al-Sa'diyah dari Bani Sa'd. Di sana beliau tumbuh kuat dan mempelajari bahasa Arab murni. Setelah ibunya wafat, kakeknya Abdul Muthalib, pemimpin Bani Hasyim dan penjaga Ka'bah, merawatnya dengan penuh kasih sayang.\n\nKetika kakeknya wafat dua tahun kemudian, beliau berada di bawah perwalian paman Abu Thalib yang baik hati namun sederhana. Sebagai pemuda, beliau bekerja sebagai penggembala seperti banyak nabi sebelumnya. Ini mengajarkan kesabaran dan tanggung jawab.\n\nBeliau terkenal dengan gelar Al-Shadiq dan Al-Amin. Dalam perjalanan dagang ke Syam bersama paman, rahib Bahira mengenali tanda kenabian. Pada usia 25 tahun menikahi Khadijah binti Khuwaylid, pengusaha wanita sukses. Pernikahan mereka penuh cinta dan saling hormat. Khadijah menjadi orang pertama memeluk Islam.",
    },
    keyFigures: ["Prophet Muhammad \uFDFA", "Aminah bint Wahb", "Abdul Muttalib", "Halimah al-Sa'diyah", "Abu Talib", "Khadijah bint Khuwaylid"],
  },
  {
    id: "first-revelation",
    order: 3,
    hijriYear: "Pre-Hijri",
    gregorianYear: "610 CE",
    title: {
      en: "First Revelation & Early Dawah",
      bn: "প্রথম ওহী ও প্রারম্ভিক দাওয়াহ",
      ur: "پہلی وحی اور ابتدائی دعوت",
      ar: "الوحي الأول والدعوة المبكرة",
      tr: "İlk Vahiy ve Erken Davet",
      ms: "Wahyu Pertama & Dakwah Awal",
      id: "Wahyu Pertama & Dakwah Awal",
    },
    subtitle: {
      en: "The Moment That Changed the World Forever",
      bn: "যে মুহূর্ত চিরতরে বিশ্বকে বদলে দিল",
      ur: "وہ لمحہ جس نے دنیا ہمیشہ کے لیے بدل دی",
      ar: "اللحظة التي غيّرت العالم إلى الأبد",
      tr: "Dünyayı Sonsuza Dek Değiştiren An",
      ms: "Detik Yang Mengubah Dunia Selama-lamanya",
      id: "Momen Yang Mengubah Dunia Selamanya",
    },
    content: {
      en: "In the year 610 CE, Prophet Muhammad \uFDFA, then forty years old, was meditating in the Cave of Hira on Jabal al-Nour (Mountain of Light) near Makkah, as was his habit during the month of Ramadan. It was here that the Angel Jibreel (Gabriel) appeared to him and commanded him to read. When Muhammad \uFDFA replied that he could not read, Jibreel embraced him tightly and repeated the command three times before revealing the first verses of the Quran: \"Read in the name of your Lord who created. Created man from a clinging substance. Read, and your Lord is the Most Generous\" (Surah Al-Alaq, 96:1-5).\n\nShaken by this extraordinary experience, Muhammad \uFDFA rushed home to Khadijah, who comforted him and wrapped him in a cloak. She immediately believed in his message and became the first person to accept Islam. She took him to her cousin Waraqah ibn Nawfal, an elderly Christian scholar, who confirmed that the angel who visited Muhammad was the same who had visited Prophet Musa (Moses) and that Muhammad was the awaited prophet of this nation.\n\nThe early period of dawah (invitation to Islam) was conducted secretly for three years. The first converts included Khadijah, young Ali ibn Abi Talib, Zayd ibn Harithah (the freed slave of Muhammad), and Abu Bakr al-Siddiq, whose influence brought several other prominent Makkans to Islam. Abu Bakr helped convert Uthman ibn Affan, Zubayr ibn al-Awwam, Sa'd ibn Abi Waqqas, and Abdur-Rahman ibn Awf.\n\nWhen the Prophet \uFDFA began preaching publicly, the Quraysh elite fiercely opposed him, seeing Islam as a threat to their social order, economic interests, and ancestral traditions. The early Muslims, especially those without tribal protection, faced severe persecution. Bilal ibn Rabah, an Abyssinian slave, was tortured by his master Umayyah ibn Khalaf by placing heavy rocks on his chest under the scorching sun, yet he persisted in declaring \"Ahad, Ahad\" (One, One). Abu Bakr purchased and freed Bilal and several other enslaved Muslims.",
      bn: "৬১০ খ্রিস্টাব্দে নবী মুহাম্মদ ﷺ, তখন চল্লিশ বছর বয়সী, রমজান মাসে তাঁর অভ্যাস অনুযায়ী মক্কার নিকটে জাবাল আল-নূরের (আলোর পর্বত) হেরা গুহায় ধ্যানমগ্ন ছিলেন। এখানেই ফেরেশতা জিবরীল (আ.) তাঁর কাছে আবির্ভূত হন এবং পড়তে আদেশ দেন। মুহাম্মদ ﷺ বললেন তিনি পড়তে পারেন না, জিবরীল তাঁকে জড়িয়ে ধরে তিনবার আদেশ দেন এবং কুরআনের প্রথম আয়াত নাজিল করেন: \"পড় তোমার প্রভুর নামে যিনি সৃষ্টি করেছেন\" (সূরা আলাক, ৯৬:১-৫)।\n\nএই অসাধারণ অভিজ্ঞতায় বিচলিত হয়ে তিনি খাদিজার কাছে ছুটে যান। খাদিজা তাঁকে সান্ত্বনা দেন এবং চাদর দিয়ে ঢেকে দেন। তিনি তৎক্ষণাৎ তাঁর বার্তায় বিশ্বাস করেন এবং প্রথম মুসলিম হন। তিনি তাঁকে তাঁর চাচাতো ভাই ওয়ারাকা ইবন নওফলের কাছে নিয়ে যান, যিনি নিশ্চিত করেন যে এটি সেই ফেরেশতা যিনি মূসা (আ.)-এর কাছে এসেছিলেন।\n\nদাওয়াতের প্রাথমিক পর্ব তিন বছর গোপনে পরিচালিত হয়। প্রথম দিকের ইসলাম গ্রহণকারীদের মধ্যে ছিলেন খাদিজা, কিশোর আলী ইবন আবি তালিব, যায়দ ইবন হারিসা এবং আবু বকর সিদ্দিক, যাঁর প্রভাবে আরও কয়েকজন বিশিষ্ট মক্কাবাসী ইসলাম গ্রহণ করেন।\n\nনবী ﷺ প্রকাশ্যে প্রচার শুরু করলে কুরাইশ নেতৃত্ব তীব্র বিরোধিতা করে। গোত্রীয় সুরক্ষাহীন প্রাথমিক মুসলিমরা কঠোর নির্যাতনের শিকার হন। বিলাল ইবন রাবাহকে তাঁর মালিক প্রচণ্ড রোদে বুকের ওপর ভারী পাথর চাপা দিয়ে নির্যাতন করত, তবু তিনি \"আহাদ, আহাদ\" বলতে থাকেন। আবু বকর বিলাল ও আরও কয়েকজন দাসকে মুক্ত করেন।",
      ur: "610 ء میں نبی محمد ﷺ، اس وقت چالیس سال کے، رمضان میں اپنی عادت کے مطابق مکہ کے قریب جبل النور پر غار حرا میں عبادت میں مصروف تھے۔ یہاں فرشتہ جبریل ظاہر ہوئے اور پڑھنے کا حکم دیا۔ آپ نے فرمایا کہ پڑھ نہیں سکتے تو جبریل نے آپ کو سینے سے لگایا اور تین بار حکم دوہرایا پھر قرآن کی پہلی آیات نازل ہوئیں: \"پڑھ اپنے رب کے نام سے جس نے پیدا کیا\" (سورۃ العلق 96:1-5)۔\n\nاس غیرمعمولی تجربے سے لرزتے ہوئے آپ خدیجہ کے پاس گئے جنہوں نے تسلی دی اور چادر اوڑھائی۔ انہوں نے فوراً ایمان لایا اور پہلی مسلمان بنیں۔ وہ آپ کو ورقہ بن نوفل کے پاس لے گئیں جنہوں نے تصدیق کی کہ یہ وہی فرشتہ ہے جو موسیٰ کے پاس آیا تھا۔\n\nابتدائی دعوت تین سال خفیہ رہی۔ پہلے ایمان لانے والوں میں خدیجہ، نوجوان علی بن ابی طالب، زید بن حارثہ اور ابوبکر صدیق شامل تھے۔ ابوبکر کی کوششوں سے عثمان، زبیر، سعد بن ابی وقاص اور عبدالرحمن بن عوف نے بھی اسلام قبول کیا۔\n\nجب آپ نے کھلم کھلا دعوت دی تو قریش کی مخالفت شدید ہوئی۔ بے سہارا مسلمانوں پر ظلم ہوا۔ بلال بن رباح کو ان کے مالک امیہ بن خلف نے دھوپ میں سینے پر بھاری پتھر رکھ کر عذاب دیا مگر وہ \"احد احد\" کہتے رہے۔ ابوبکر نے بلال اور کئی غلام مسلمانوں کو آزاد کرایا۔",
      ar: "في عام 610 م كان النبي محمد ﷺ البالغ أربعين عاماً يتعبد في غار حراء بجبل النور قرب مكة كعادته في رمضان. هنا ظهر جبريل وأمره بالقراءة. فلما قال لا أقرأ ضمّه ثلاثاً ثم نزلت أولى آيات القرآن: \"اقرأ باسم ربك الذي خلق\" (العلق 96:1-5).\n\nعاد مرتجفاً إلى خديجة فطمأنته ولفّته بثوب. آمنت فوراً فكانت أول من أسلم. أخذته إلى ابن عمها ورقة بن نوفل العالم المسيحي فأكد أن هذا الناموس الذي جاء موسى.\n\nاستمرت الدعوة سرّاً ثلاث سنوات. أوائل المسلمين: خديجة وعلي بن أبي طالب الفتى وزيد بن حارثة وأبو بكر الصديق الذي أسلم على يده عثمان والزبير وسعد وعبد الرحمن بن عوف.\n\nحين جهر النبي بالدعوة عارضته قريش بشدة. عُذّب المسلمون الضعفاء. وُضعت الصخور على صدر بلال بن رباح في الشمس فكان يردد \"أحد أحد\". اشتراه أبو بكر وأعتقه مع عدد من العبيد المسلمين.",
      tr: "610 yılında Hz. Muhammed \uFDFA, kırk yaşındayken, Ramazan'da âdeti olduğu üzere Mekke yakınlarındaki Nûr Dağı'ndaki Hira Mağarası'nda ibadet ediyordu. Cebrail burada görünerek oku diye emretti. Okuyamadığını söyleyince üç kez sıkıp bıraktı ve Kur'an'ın ilk ayetleri indi: \"Yaratan Rabbinin adıyla oku\" (Alak 96:1-5).\n\nSarsılmış halde Hatice'ye döndü. Hatice onu teselli edip örttü ve hemen iman ederek ilk Müslüman oldu. Kuzeni Varaka bin Nevfel'e götürdü; o da bunun Musa'ya gelen meleğin aynısı olduğunu doğruladı.\n\nDavet üç yıl gizli sürdü. İlk Müslümanlar arasında Hatice, genç Ali bin Ebî Tâlib, Zeyd bin Hârise ve Ebû Bekir es-Sıddîk vardı. Ebû Bekir'in etkisiyle Osman, Zübeyr, Sa'd ve Abdurrahman bin Avf da Müslüman oldu.\n\nHz. Peygamber açıkça tebliğe başlayınca Kureyş şiddetle karşı çıktı. Korumasız Müslümanlar işkence gördü. Bilal bin Rabah'ın göğsüne kızgın güneşte ağır kayalar konuldu ama o \"Ehad, Ehad\" demeye devam etti. Ebû Bekir Bilal'i ve birçok köle Müslümanı satın alıp azat etti.",
      ms: "Pada tahun 610 M, Nabi Muhammad \uFDFA yang berusia empat puluh tahun sedang beribadat di Gua Hira di Jabal Nur berhampiran Makkah seperti kebiasaan baginda pada bulan Ramadan. Di sinilah Malaikat Jibril muncul dan memerintahkan baginda membaca. Apabila baginda berkata tidak boleh membaca, Jibril memeluk baginda tiga kali lalu menurunkan ayat pertama Al-Quran: \"Bacalah dengan nama Tuhanmu yang menciptakan\" (Surah Al-Alaq 96:1-5).\n\nDengan gementar baginda pulang kepada Khadijah yang menenangkan dan menyelimuti baginda. Khadijah terus beriman menjadi orang pertama memeluk Islam. Beliau membawa baginda kepada sepupunya Waraqah bin Nawfal yang mengesahkan itu malaikat yang sama datang kepada Musa.\n\nDakwah awal berlangsung secara rahsia selama tiga tahun. Muslim terawal termasuk Khadijah, Ali bin Abi Talib yang muda, Zaid bin Haritsah, dan Abu Bakar al-Siddiq yang pengaruhnya membawa Uthman, Zubair, Sa'd, dan Abdur-Rahman bin Auf kepada Islam.\n\nApabila Nabi berdakwah secara terbuka, pembesar Quraisy menentang hebat. Muslim yang tiada perlindungan diseksa. Bilal bin Rabah ditindih batu besar di dada dalam panas terik namun tetap mengucap \"Ahad, Ahad\". Abu Bakar membeli dan membebaskan Bilal serta beberapa hamba Muslim lain.",
      id: "Pada tahun 610 M, Nabi Muhammad \uFDFA yang berusia empat puluh tahun sedang beribadah di Gua Hira di Jabal Nur dekat Makkah sesuai kebiasaan beliau di bulan Ramadan. Di sinilah Malaikat Jibril muncul dan memerintahkan beliau membaca. Ketika beliau menjawab tidak bisa membaca, Jibril memeluknya tiga kali lalu menurunkan ayat pertama Al-Quran: \"Bacalah dengan nama Tuhanmu yang menciptakan\" (Surah Al-Alaq 96:1-5).\n\nDengan gemetar beliau pulang kepada Khadijah yang menenangkan dan menyelimutinya. Khadijah langsung beriman menjadi orang pertama memeluk Islam. Beliau membawa Nabi kepada sepupunya Waraqah bin Naufal yang mengonfirmasi itu malaikat yang sama yang datang kepada Musa.\n\nDakwah awal berlangsung secara rahasia selama tiga tahun. Muslim pertama termasuk Khadijah, Ali bin Abi Thalib yang masih muda, Zaid bin Haritsah, dan Abu Bakar al-Shiddiq yang pengaruhnya membawa Utsman, Zubair, Sa'd, dan Abdurrahman bin Auf kepada Islam.\n\nKetika Nabi berdakwah secara terbuka, pemuka Quraisy menentang keras. Muslim tanpa perlindungan disiksa. Bilal bin Rabah ditindih batu besar di dada di bawah terik matahari namun tetap mengucap \"Ahad, Ahad\". Abu Bakar membeli dan membebaskan Bilal serta beberapa budak Muslim lainnya.",
    },
    keyFigures: ["Prophet Muhammad \uFDFA", "Angel Jibreel", "Khadijah bint Khuwaylid", "Abu Bakr al-Siddiq", "Bilal ibn Rabah"],
    quranReference: "96:1-5",
  },
];
