import type { TransLang } from "@/lib/islamic-content";

export const PROFILE_PAGE_TEXTS: Record<TransLang, {
  title: string;
  subtitle: string;
  memberSince: string;
  quickStats: string;
  zakatCalculated: string;
  sadaqahGiven: string;
  tasbihCount: string;
  favoritesSaved: string;
  zakatOverview: string;
  zakatHistory: string;
  noZakatYet: string;
  sadaqahSummary: string;
  noSadaqahYet: string;
  tasbihSummary: string;
  noTasbihYet: string;
  todaysDhikr: string;
  totalSessions: string;
  topDhikr: string;
  monthlyTrend: string;
  byCategory: string;
  paid: string;
  unpaid: string;
  loading: string;
  signInTitle: string;
  signInDesc: string;
  signIn: string;
  createAccount: string;
  viewAll: string;
  year: string;
  donations: string;
  hadith: string;
  duas: string;
  goToCalculator: string;
  startTracking: string;
  startDhikr: string;
  counts: string;
  back: string;
  salatTracker: string;
  noSalatYet: string;
  currentStreak: string;
  completionRate: string;
  onTimeRate: string;
  jamaahRate: string;
}> = {
  en: {
    title: "My Profile",
    subtitle: "Track your spiritual journey and progress",
    memberSince: "Member since",
    quickStats: "Quick Stats",
    zakatCalculated: "Zakat Calculated",
    sadaqahGiven: "Sadaqah Given",
    tasbihCount: "Tasbih Count",
    favoritesSaved: "Favorites Saved",
    zakatOverview: "Zakat Overview",
    zakatHistory: "Yearly Zakat History",
    noZakatYet: "No Zakat calculations yet. Use the calculator to get started!",
    sadaqahSummary: "Sadaqah Summary",
    noSadaqahYet: "No Sadaqah recorded yet. Start tracking your charity!",
    tasbihSummary: "Tasbih Summary",
    noTasbihYet: "No Tasbih sessions yet. Start your dhikr journey!",
    todaysDhikr: "Today's Dhikr",
    totalSessions: "Total Sessions",
    topDhikr: "Top Dhikr",
    monthlyTrend: "Monthly Trend",
    byCategory: "By Category",
    paid: "Paid",
    unpaid: "Unpaid",
    loading: "Loading your profile...",
    signInTitle: "Sign in to view your profile",
    signInDesc: "Track your Zakat, Sadaqah, Tasbih progress and more by signing in.",
    signIn: "Sign In",
    createAccount: "Create Account",
    viewAll: "View All",
    year: "Year",
    donations: "donations",
    hadith: "Hadith",
    duas: "Duas",
    goToCalculator: "Go to Calculator",
    startTracking: "Start Tracking",
    startDhikr: "Start Dhikr",
    counts: "counts",
    back: "Back",
    salatTracker: "Salat Tracker",
    noSalatYet: "No prayer tracking data yet. Start tracking your salat!",
    currentStreak: "Current Streak",
    completionRate: "Completion",
    onTimeRate: "On-Time",
    jamaahRate: "Jamaah",
  },
  bn: {
    title: "আমার প্রোফাইল",
    subtitle: "আপনার আধ্যাত্মিক যাত্রা ও অগ্রগতি ট্র্যাক করুন",
    memberSince: "সদস্য হয়েছেন",
    quickStats: "দ্রুত পরিসংখ্যান",
    zakatCalculated: "যাকাত হিসাব",
    sadaqahGiven: "সদকা প্রদান",
    tasbihCount: "তাসবিহ গণনা",
    favoritesSaved: "পছন্দ সংরক্ষিত",
    zakatOverview: "যাকাত সারসংক্ষেপ",
    zakatHistory: "বার্ষিক যাকাত ইতিহাস",
    noZakatYet: "এখনো কোনো যাকাত হিসাব নেই। ক্যালকুলেটর ব্যবহার করুন!",
    sadaqahSummary: "সদকা সারসংক্ষেপ",
    noSadaqahYet: "এখনো কোনো সদকা রেকর্ড নেই। আপনার দান ট্র্যাক করা শুরু করুন!",
    tasbihSummary: "তাসবিহ সারসংক্ষেপ",
    noTasbihYet: "এখনো কোনো তাসবিহ সেশন নেই। আপনার যিকর যাত্রা শুরু করুন!",
    todaysDhikr: "আজকের যিকর",
    totalSessions: "মোট সেশন",
    topDhikr: "শীর্ষ যিকর",
    monthlyTrend: "মাসিক প্রবণতা",
    byCategory: "বিভাগ অনুসারে",
    paid: "পরিশোধিত",
    unpaid: "অপরিশোধিত",
    loading: "আপনার প্রোফাইল লোড হচ্ছে...",
    signInTitle: "আপনার প্রোফাইল দেখতে সাইন ইন করুন",
    signInDesc: "সাইন ইন করে আপনার যাকাত, সদকা, তাসবিহ অগ্রগতি ট্র্যাক করুন।",
    signIn: "সাইন ইন",
    createAccount: "অ্যাকাউন্ট তৈরি",
    viewAll: "সব দেখুন",
    year: "বছর",
    donations: "দান",
    hadith: "হাদিস",
    duas: "দোয়া",
    goToCalculator: "ক্যালকুলেটরে যান",
    startTracking: "ট্র্যাকিং শুরু করুন",
    startDhikr: "যিকর শুরু করুন",
    counts: "গণনা",
    back: "পিছনে",
    salatTracker: "সালাত ট্র্যাকার",
    noSalatYet: "এখনো নামাজ ট্র্যাকিং ডেটা নেই। আপনার নামাজ ট্র্যাক করা শুরু করুন!",
    currentStreak: "বর্তমান ধারা",
    completionRate: "সম্পন্নের হার",
    onTimeRate: "সময়মতো",
    jamaahRate: "জামাআত",
  },
  ur: {
    title: "میری پروفائل",
    subtitle: "اپنے روحانی سفر اور پیشرفت کو ٹریک کریں",
    memberSince: "ممبر بنے",
    quickStats: "فوری اعداد و شمار",
    zakatCalculated: "زکوٰۃ حساب",
    sadaqahGiven: "صدقہ دیا گیا",
    tasbihCount: "تسبیح شمار",
    favoritesSaved: "پسندیدہ محفوظ",
    zakatOverview: "زکوٰۃ جائزہ",
    zakatHistory: "سالانہ زکوٰۃ ہسٹری",
    noZakatYet: "ابھی تک کوئی زکوٰۃ حساب نہیں۔ کیلکولیٹر استعمال کریں!",
    sadaqahSummary: "صدقہ خلاصہ",
    noSadaqahYet: "ابھی تک کوئی صدقہ ریکارڈ نہیں۔ اپنے عطیات ٹریک کرنا شروع کریں!",
    tasbihSummary: "تسبیح خلاصہ",
    noTasbihYet: "ابھی تک کوئی تسبیح سیشن نہیں۔ اپنا ذکر شروع کریں!",
    todaysDhikr: "آج کا ذکر",
    totalSessions: "کل سیشنز",
    topDhikr: "سب سے زیادہ ذکر",
    monthlyTrend: "ماہانہ رجحان",
    byCategory: "زمرے کے مطابق",
    paid: "ادا شدہ",
    unpaid: "غیر ادا شدہ",
    loading: "آپ کی پروفائل لوڈ ہو رہی ہے...",
    signInTitle: "اپنی پروفائل دیکھنے کے لیے سائن ان کریں",
    signInDesc: "سائن ان کر کے اپنی زکوٰۃ، صدقہ، تسبیح کی پیشرفت ٹریک کریں۔",
    signIn: "سائن ان",
    createAccount: "اکاؤنٹ بنائیں",
    viewAll: "سب دیکھیں",
    year: "سال",
    donations: "عطیات",
    hadith: "حدیث",
    duas: "دعائیں",
    goToCalculator: "کیلکولیٹر پر جائیں",
    startTracking: "ٹریکنگ شروع کریں",
    startDhikr: "ذکر شروع کریں",
    counts: "شمار",
    back: "واپس",
    salatTracker: "نماز ٹریکر",
    noSalatYet: "ابھی تک نماز ٹریکنگ ڈیٹا نہیں۔ اپنی نمازیں ٹریک کرنا شروع کریں!",
    currentStreak: "موجودہ تسلسل",
    completionRate: "تکمیل",
    onTimeRate: "وقت پر",
    jamaahRate: "جماعت",
  },
  ar: {
    title: "ملفي الشخصي",
    subtitle: "تتبع رحلتك الروحانية وتقدمك",
    memberSince: "عضو منذ",
    quickStats: "إحصائيات سريعة",
    zakatCalculated: "الزكاة المحسوبة",
    sadaqahGiven: "الصدقة المقدمة",
    tasbihCount: "عدد التسبيح",
    favoritesSaved: "المفضلة المحفوظة",
    zakatOverview: "نظرة عامة على الزكاة",
    zakatHistory: "تاريخ الزكاة السنوي",
    noZakatYet: "لا توجد حسابات زكاة بعد. استخدم الحاسبة للبدء!",
    sadaqahSummary: "ملخص الصدقة",
    noSadaqahYet: "لا توجد سجلات صدقة بعد. ابدأ بتتبع صدقاتك!",
    tasbihSummary: "ملخص التسبيح",
    noTasbihYet: "لا توجد جلسات تسبيح بعد. ابدأ رحلة الذكر!",
    todaysDhikr: "ذكر اليوم",
    totalSessions: "إجمالي الجلسات",
    topDhikr: "أكثر الأذكار",
    monthlyTrend: "الاتجاه الشهري",
    byCategory: "حسب الفئة",
    paid: "مدفوع",
    unpaid: "غير مدفوع",
    loading: "جاري تحميل ملفك الشخصي...",
    signInTitle: "سجّل الدخول لعرض ملفك الشخصي",
    signInDesc: "تتبع زكاتك وصدقاتك وتسبيحك والمزيد بتسجيل الدخول.",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    viewAll: "عرض الكل",
    year: "سنة",
    donations: "تبرعات",
    hadith: "حديث",
    duas: "أدعية",
    goToCalculator: "الذهاب إلى الحاسبة",
    startTracking: "ابدأ التتبع",
    startDhikr: "ابدأ الذكر",
    counts: "عدد",
    back: "رجوع",
    salatTracker: "متتبع الصلاة",
    noSalatYet: "لا توجد بيانات تتبع صلاة بعد. ابدأ بتتبع صلواتك!",
    currentStreak: "التسلسل الحالي",
    completionRate: "الإكمال",
    onTimeRate: "في الوقت",
    jamaahRate: "الجماعة",
  },
  tr: {
    title: "Profilim",
    subtitle: "Manevi yolculugunuzu ve ilerlemenizi takip edin",
    memberSince: "Uye olma tarihi",
    quickStats: "Hizli Istatistikler",
    zakatCalculated: "Zekat Hesaplandi",
    sadaqahGiven: "Sadaka Verildi",
    tasbihCount: "Tesbih Sayisi",
    favoritesSaved: "Favoriler Kaydedildi",
    zakatOverview: "Zekat Ozeti",
    zakatHistory: "Yillik Zekat Gecmisi",
    noZakatYet: "Henuz zekat hesaplamasi yok. Hesaplayiciyi kullanin!",
    sadaqahSummary: "Sadaka Ozeti",
    noSadaqahYet: "Henuz sadaka kaydi yok. Bagislarinizi takip etmeye baslayin!",
    tasbihSummary: "Tesbih Ozeti",
    noTasbihYet: "Henuz tesbih oturumu yok. Zikir yolculugunuza baslayin!",
    todaysDhikr: "Bugunun Zikri",
    totalSessions: "Toplam Oturum",
    topDhikr: "En Cok Zikir",
    monthlyTrend: "Aylik Egilim",
    byCategory: "Kategoriye Gore",
    paid: "Odendi",
    unpaid: "Odenmedi",
    loading: "Profiliniz yukleniyor...",
    signInTitle: "Profilinizi gormek icin giris yapin",
    signInDesc: "Giris yaparak zekat, sadaka, tesbih ilerlemenizi takip edin.",
    signIn: "Giris Yap",
    createAccount: "Hesap Olustur",
    viewAll: "Tumunu Gor",
    year: "Yil",
    donations: "bagis",
    hadith: "Hadis",
    duas: "Dualar",
    goToCalculator: "Hesaplayiciya Git",
    startTracking: "Takibe Basla",
    startDhikr: "Zikre Basla",
    counts: "sayi",
    back: "Geri",
    salatTracker: "Namaz Takipçisi",
    noSalatYet: "Henüz namaz takip verisi yok. Namazlarınızı takip etmeye başlayın!",
    currentStreak: "Mevcut Seri",
    completionRate: "Tamamlanma",
    onTimeRate: "Vaktinde",
    jamaahRate: "Cemaat",
  },
  ms: {
    title: "Profil Saya",
    subtitle: "Jejak perjalanan rohani dan kemajuan anda",
    memberSince: "Ahli sejak",
    quickStats: "Statistik Pantas",
    zakatCalculated: "Zakat Dikira",
    sadaqahGiven: "Sedekah Diberikan",
    tasbihCount: "Kiraan Tasbih",
    favoritesSaved: "Kegemaran Disimpan",
    zakatOverview: "Gambaran Zakat",
    zakatHistory: "Sejarah Zakat Tahunan",
    noZakatYet: "Belum ada pengiraan zakat. Gunakan kalkulator untuk mula!",
    sadaqahSummary: "Ringkasan Sedekah",
    noSadaqahYet: "Belum ada rekod sedekah. Mula jejak sedekah anda!",
    tasbihSummary: "Ringkasan Tasbih",
    noTasbihYet: "Belum ada sesi tasbih. Mulakan perjalanan zikir anda!",
    todaysDhikr: "Zikir Hari Ini",
    totalSessions: "Jumlah Sesi",
    topDhikr: "Zikir Teratas",
    monthlyTrend: "Trend Bulanan",
    byCategory: "Mengikut Kategori",
    paid: "Dibayar",
    unpaid: "Belum Dibayar",
    loading: "Memuatkan profil anda...",
    signInTitle: "Log masuk untuk melihat profil anda",
    signInDesc: "Jejak zakat, sedekah, tasbih dan kemajuan anda dengan log masuk.",
    signIn: "Log Masuk",
    createAccount: "Cipta Akaun",
    viewAll: "Lihat Semua",
    year: "Tahun",
    donations: "derma",
    hadith: "Hadis",
    duas: "Doa",
    goToCalculator: "Pergi ke Kalkulator",
    startTracking: "Mula Jejak",
    startDhikr: "Mula Zikir",
    counts: "kiraan",
    back: "Kembali",
    salatTracker: "Penjejak Solat",
    noSalatYet: "Belum ada data jejak solat. Mula jejak solat anda!",
    currentStreak: "Rangkaian Semasa",
    completionRate: "Penyelesaian",
    onTimeRate: "Tepat Waktu",
    jamaahRate: "Jemaah",
  },
  id: {
    title: "Profil Saya",
    subtitle: "Lacak perjalanan spiritual dan kemajuan Anda",
    memberSince: "Anggota sejak",
    quickStats: "Statistik Cepat",
    zakatCalculated: "Zakat Dihitung",
    sadaqahGiven: "Sedekah Diberikan",
    tasbihCount: "Hitungan Tasbih",
    favoritesSaved: "Favorit Disimpan",
    zakatOverview: "Ringkasan Zakat",
    zakatHistory: "Riwayat Zakat Tahunan",
    noZakatYet: "Belum ada perhitungan zakat. Gunakan kalkulator untuk mulai!",
    sadaqahSummary: "Ringkasan Sedekah",
    noSadaqahYet: "Belum ada catatan sedekah. Mulai lacak sedekah Anda!",
    tasbihSummary: "Ringkasan Tasbih",
    noTasbihYet: "Belum ada sesi tasbih. Mulai perjalanan zikir Anda!",
    todaysDhikr: "Zikir Hari Ini",
    totalSessions: "Total Sesi",
    topDhikr: "Zikir Teratas",
    monthlyTrend: "Tren Bulanan",
    byCategory: "Berdasarkan Kategori",
    paid: "Dibayar",
    unpaid: "Belum Dibayar",
    loading: "Memuat profil Anda...",
    signInTitle: "Masuk untuk melihat profil Anda",
    signInDesc: "Lacak zakat, sedekah, tasbih, dan kemajuan Anda dengan masuk.",
    signIn: "Masuk",
    createAccount: "Buat Akun",
    viewAll: "Lihat Semua",
    year: "Tahun",
    donations: "donasi",
    hadith: "Hadis",
    duas: "Doa",
    goToCalculator: "Buka Kalkulator",
    startTracking: "Mulai Lacak",
    startDhikr: "Mulai Zikir",
    counts: "hitungan",
    back: "Kembali",
    salatTracker: "Pelacak Shalat",
    noSalatYet: "Belum ada data pelacakan shalat. Mulai lacak shalat Anda!",
    currentStreak: "Rangkaian Saat Ini",
    completionRate: "Penyelesaian",
    onTimeRate: "Tepat Waktu",
    jamaahRate: "Jamaah",
  },
};
