import type { TransLang } from "@/lib/islamic-content";

export const QIBLA_TEXTS: Record<TransLang, {
  headerSubtitle: string;
  backToHome: string;
  qiblaFinder: string;
  findingLocation: string;
  allowLocation: string;
  locationError: string;
  tryAgain: string;
  findQiblaDirection: string;
  allowLocationDesc: string;
  enableLocation: string;
  enableLiveCompass: string;
  enableCompassDesc: string;
  enableCompass: string;
  qiblaDirection: string;
  fromNorth: string;
  distanceToKaaba: string;
  yourLocation: string;
  usingDesktop: string;
  desktopDesc: string;
  compassDenied: string;
  footerNote: string;
  jazakallah: string;
  geoNotSupported: string;
  permissionDenied: string;
  positionUnavailable: string;
  timeout: string;
  unknownError: string;
  quranVerse: string;
}> = {
  en: {
    headerSubtitle: "Qibla Direction Finder",
    backToHome: "Back to Home",
    qiblaFinder: "Qibla Finder",
    findingLocation: "Finding your location...",
    allowLocation: "Please allow location access when prompted",
    locationError: "Location Error",
    tryAgain: "Try Again",
    findQiblaDirection: "Find Qibla Direction",
    allowLocationDesc: "Allow location access to calculate the precise direction to the Kaaba from your current position.",
    enableLocation: "Enable Location",
    enableLiveCompass: "Enable Live Compass",
    enableCompassDesc: "Grant device orientation permission for a live compass that tracks your phone's direction in real-time.",
    enableCompass: "Enable Compass",
    qiblaDirection: "Qibla Direction",
    fromNorth: "from North",
    distanceToKaaba: "Distance to Kaaba",
    yourLocation: "Your Location",
    usingDesktop: "Using a Desktop?",
    desktopDesc: "The compass shows the Qibla direction relative to North. Use a physical compass or your phone's compass app to face {bearing} from North. For a live compass experience, open this page on your mobile device.",
    compassDenied: "Compass permission was denied. The Qibla direction is shown as {bearing} from North. Use a physical compass or your device's compass app to find this bearing.",
    footerNote: "Qibla direction calculated using great circle bearing to the Kaaba (21.4225°N, 39.8262°E)",
    jazakallah: "May Allah reward you with goodness",
    geoNotSupported: "Geolocation is not supported by your browser.",
    permissionDenied: "Location permission denied. Please enable location access in your browser settings.",
    positionUnavailable: "Location information is unavailable.",
    timeout: "Location request timed out. Please try again.",
    unknownError: "An unknown error occurred.",
    quranVerse: "So turn your face toward al-Masjid al-Haram",
  },
  bn: {
    headerSubtitle: "কিবলা দিকনির্দেশক",
    backToHome: "হোমে ফিরুন",
    qiblaFinder: "কিবলা খুঁজুন",
    findingLocation: "আপনার অবস্থান খোঁজা হচ্ছে...",
    allowLocation: "অনুগ্রহ করে অবস্থান অ্যাক্সেসের অনুমতি দিন",
    locationError: "অবস্থান ত্রুটি",
    tryAgain: "আবার চেষ্টা করুন",
    findQiblaDirection: "কিবলার দিক খুঁজুন",
    allowLocationDesc: "আপনার বর্তমান অবস্থান থেকে কাবার সঠিক দিক নির্ণয় করতে অবস্থান অ্যাক্সেসের অনুমতি দিন।",
    enableLocation: "অবস্থান সক্রিয় করুন",
    enableLiveCompass: "লাইভ কম্পাস সক্রিয় করুন",
    enableCompassDesc: "রিয়েল-টাইমে আপনার ফোনের দিক ট্র্যাক করতে ডিভাইস ওরিয়েন্টেশন অনুমতি দিন।",
    enableCompass: "কম্পাস সক্রিয় করুন",
    qiblaDirection: "কিবলার দিক",
    fromNorth: "উত্তর থেকে",
    distanceToKaaba: "কাবার দূরত্ব",
    yourLocation: "আপনার অবস্থান",
    usingDesktop: "ডেস্কটপ ব্যবহার করছেন?",
    desktopDesc: "কম্পাসটি উত্তরের সাপেক্ষে কিবলার দিক দেখায়। উত্তর থেকে {bearing} দিকে মুখ করতে একটি ফিজিক্যাল কম্পাস ব্যবহার করুন। লাইভ কম্পাসের জন্য, আপনার মোবাইলে এই পেজটি খুলুন।",
    compassDenied: "কম্পাস অনুমতি প্রত্যাখ্যান করা হয়েছে। কিবলার দিক উত্তর থেকে {bearing}। এই বিয়ারিং খুঁজতে একটি ফিজিক্যাল কম্পাস ব্যবহার করুন।",
    footerNote: "কাবার (21.4225°N, 39.8262°E) দিকে গ্রেট সার্কেল বিয়ারিং ব্যবহার করে কিবলার দিক নির্ণয় করা হয়েছে",
    jazakallah: "আল্লাহ আপনাকে উত্তম প্রতিদান দিন",
    geoNotSupported: "আপনার ব্রাউজার জিওলোকেশন সমর্থন করে না।",
    permissionDenied: "অবস্থান অনুমতি প্রত্যাখ্যান করা হয়েছে। অনুগ্রহ করে ব্রাউজার সেটিংসে অবস্থান অ্যাক্সেস সক্রিয় করুন।",
    positionUnavailable: "অবস্থান তথ্য পাওয়া যাচ্ছে না।",
    timeout: "অবস্থান অনুরোধ সময়সীমা অতিক্রম করেছে। আবার চেষ্টা করুন।",
    unknownError: "একটি অজানা ত্রুটি ঘটেছে।",
    quranVerse: "অতএব তোমার মুখ মসজিদুল হারামের দিকে ফেরাও",
  },
  ur: {
    headerSubtitle: "قبلہ سمت تلاش کریں",
    backToHome: "ہوم پر واپس",
    qiblaFinder: "قبلہ تلاش",
    findingLocation: "آپ کی لوکیشن تلاش ہو رہی ہے...",
    allowLocation: "براہ کرم لوکیشن تک رسائی کی اجازت دیں",
    locationError: "لوکیشن کی خرابی",
    tryAgain: "دوبارہ کوشش کریں",
    findQiblaDirection: "قبلہ کی سمت تلاش کریں",
    allowLocationDesc: "اپنی موجودہ پوزیشن سے کعبہ کی صحیح سمت معلوم کرنے کے لیے لوکیشن تک رسائی کی اجازت دیں۔",
    enableLocation: "لوکیشن فعال کریں",
    enableLiveCompass: "لائیو کمپاس فعال کریں",
    enableCompassDesc: "ریئل ٹائم میں آپ کے فون کی سمت ٹریک کرنے کے لیے ڈیوائس اورینٹیشن کی اجازت دیں۔",
    enableCompass: "کمپاس فعال کریں",
    qiblaDirection: "قبلہ کی سمت",
    fromNorth: "شمال سے",
    distanceToKaaba: "کعبہ تک فاصلہ",
    yourLocation: "آپ کی لوکیشن",
    usingDesktop: "ڈیسک ٹاپ استعمال کر رہے ہیں؟",
    desktopDesc: "کمپاس شمال کی نسبت قبلہ کی سمت دکھاتا ہے۔ شمال سے {bearing} کی طرف رخ کرنے کے لیے فزیکل کمپاس استعمال کریں۔ لائیو کمپاس کے لیے، اپنے موبائل پر یہ صفحہ کھولیں۔",
    compassDenied: "کمپاس کی اجازت مسترد کر دی گئی۔ قبلہ کی سمت شمال سے {bearing} ہے۔ فزیکل کمپاس استعمال کریں۔",
    footerNote: "کعبہ (21.4225°N, 39.8262°E) کی طرف گریٹ سرکل بیئرنگ کا استعمال کرتے ہوئے قبلہ کی سمت کا حساب لگایا گیا",
    jazakallah: "اللہ آپ کو بہترین اجر دے",
    geoNotSupported: "آپ کا براؤزر جیولوکیشن کو سپورٹ نہیں کرتا۔",
    permissionDenied: "لوکیشن کی اجازت مسترد کر دی گئی۔ براہ کرم براؤزر سیٹنگز میں لوکیشن رسائی فعال کریں۔",
    positionUnavailable: "لوکیشن کی معلومات دستیاب نہیں ہیں۔",
    timeout: "لوکیشن کی درخواست کا وقت ختم ہو گیا۔ دوبارہ کوشش کریں۔",
    unknownError: "ایک نامعلوم خرابی ہوئی۔",
    quranVerse: "پس اپنا رخ مسجد حرام کی طرف پھیر لو",
  },
  ar: {
    headerSubtitle: "محدد اتجاه القبلة",
    backToHome: "العودة للرئيسية",
    qiblaFinder: "محدد القبلة",
    findingLocation: "جارٍ تحديد موقعك...",
    allowLocation: "يرجى السماح بالوصول إلى الموقع",
    locationError: "خطأ في الموقع",
    tryAgain: "حاول مرة أخرى",
    findQiblaDirection: "حدد اتجاه القبلة",
    allowLocationDesc: "اسمح بالوصول إلى الموقع لحساب الاتجاه الدقيق للكعبة من موقعك الحالي.",
    enableLocation: "تفعيل الموقع",
    enableLiveCompass: "تفعيل البوصلة الحية",
    enableCompassDesc: "امنح إذن توجيه الجهاز لبوصلة حية تتبع اتجاه هاتفك في الوقت الفعلي.",
    enableCompass: "تفعيل البوصلة",
    qiblaDirection: "اتجاه القبلة",
    fromNorth: "من الشمال",
    distanceToKaaba: "المسافة إلى الكعبة",
    yourLocation: "موقعك",
    usingDesktop: "تستخدم حاسوبًا مكتبيًا؟",
    desktopDesc: "تُظهر البوصلة اتجاه القبلة بالنسبة للشمال. استخدم بوصلة حقيقية أو تطبيق البوصلة للتوجه {bearing} من الشمال. لتجربة البوصلة الحية، افتح هذه الصفحة على هاتفك.",
    compassDenied: "تم رفض إذن البوصلة. اتجاه القبلة هو {bearing} من الشمال. استخدم بوصلة حقيقية لتحديد هذا الاتجاه.",
    footerNote: "تم حساب اتجاه القبلة باستخدام اتجاه الدائرة العظمى نحو الكعبة (21.4225°N, 39.8262°E)",
    jazakallah: "جزاكم الله خيراً",
    geoNotSupported: "متصفحك لا يدعم تحديد الموقع الجغرافي.",
    permissionDenied: "تم رفض إذن الموقع. يرجى تفعيل الوصول إلى الموقع في إعدادات المتصفح.",
    positionUnavailable: "معلومات الموقع غير متاحة.",
    timeout: "انتهت مهلة طلب الموقع. حاول مرة أخرى.",
    unknownError: "حدث خطأ غير معروف.",
    quranVerse: "فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ",
  },
  tr: {
    headerSubtitle: "Kible Yön Bulucu",
    backToHome: "Ana Sayfaya Dön",
    qiblaFinder: "Kible Bulucu",
    findingLocation: "Konumunuz bulunuyor...",
    allowLocation: "Lütfen konum erişimine izin verin",
    locationError: "Konum Hatası",
    tryAgain: "Tekrar Dene",
    findQiblaDirection: "Kible Yönünü Bul",
    allowLocationDesc: "Mevcut konumunuzdan Kabe'nin doğru yönünü hesaplamak için konum erişimine izin verin.",
    enableLocation: "Konumu Etkinleştir",
    enableLiveCompass: "Canlı Pusulayı Etkinleştir",
    enableCompassDesc: "Telefonunuzun yönünü gerçek zamanlı takip eden canlı pusula için cihaz yön izni verin.",
    enableCompass: "Pusulayı Etkinleştir",
    qiblaDirection: "Kible Yönü",
    fromNorth: "Kuzeyden",
    distanceToKaaba: "Kabe'ye Uzaklık",
    yourLocation: "Konumunuz",
    usingDesktop: "Masaüstü mü Kullanıyorsunuz?",
    desktopDesc: "Pusula, Kible yönünü Kuzeye göre gösterir. Kuzeyden {bearing} yönüne dönmek için fiziksel pusula kullanın. Canlı pusula deneyimi için bu sayfayı mobil cihazınızda açın.",
    compassDenied: "Pusula izni reddedildi. Kible yönü Kuzeyden {bearing} olarak gösterilmektedir. Bu yönü bulmak için fiziksel pusula kullanın.",
    footerNote: "Kible yönü, Kabe'ye (21.4225°N, 39.8262°E) büyük daire yönü kullanılarak hesaplanmıştır",
    jazakallah: "Allah sizi hayırla mükafatlandırsın",
    geoNotSupported: "Tarayıcınız coğrafi konumu desteklemiyor.",
    permissionDenied: "Konum izni reddedildi. Lütfen tarayıcı ayarlarından konum erişimini etkinleştirin.",
    positionUnavailable: "Konum bilgisi mevcut değil.",
    timeout: "Konum isteği zaman aşımına uğradı. Tekrar deneyin.",
    unknownError: "Bilinmeyen bir hata oluştu.",
    quranVerse: "Yüzünü Mescid-i Haram'a çevir",
  },
  ms: {
    headerSubtitle: "Pencari Arah Kiblat",
    backToHome: "Kembali ke Utama",
    qiblaFinder: "Pencari Kiblat",
    findingLocation: "Mencari lokasi anda...",
    allowLocation: "Sila benarkan akses lokasi",
    locationError: "Ralat Lokasi",
    tryAgain: "Cuba Lagi",
    findQiblaDirection: "Cari Arah Kiblat",
    allowLocationDesc: "Benarkan akses lokasi untuk mengira arah tepat ke Kaabah dari kedudukan semasa anda.",
    enableLocation: "Aktifkan Lokasi",
    enableLiveCompass: "Aktifkan Kompas Langsung",
    enableCompassDesc: "Berikan kebenaran orientasi peranti untuk kompas langsung yang menjejaki arah telefon anda secara masa nyata.",
    enableCompass: "Aktifkan Kompas",
    qiblaDirection: "Arah Kiblat",
    fromNorth: "dari Utara",
    distanceToKaaba: "Jarak ke Kaabah",
    yourLocation: "Lokasi Anda",
    usingDesktop: "Menggunakan Desktop?",
    desktopDesc: "Kompas menunjukkan arah Kiblat relatif kepada Utara. Gunakan kompas fizikal untuk menghadap {bearing} dari Utara. Untuk pengalaman kompas langsung, buka halaman ini di peranti mudah alih anda.",
    compassDenied: "Kebenaran kompas ditolak. Arah Kiblat ditunjukkan sebagai {bearing} dari Utara. Gunakan kompas fizikal untuk mencari arah ini.",
    footerNote: "Arah Kiblat dikira menggunakan bearing bulatan besar ke Kaabah (21.4225°N, 39.8262°E)",
    jazakallah: "Semoga Allah membalas anda dengan kebaikan",
    geoNotSupported: "Pelayar anda tidak menyokong geolokasi.",
    permissionDenied: "Kebenaran lokasi ditolak. Sila aktifkan akses lokasi dalam tetapan pelayar.",
    positionUnavailable: "Maklumat lokasi tidak tersedia.",
    timeout: "Permintaan lokasi tamat masa. Sila cuba lagi.",
    unknownError: "Ralat tidak diketahui berlaku.",
    quranVerse: "Maka hadapkanlah wajahmu ke arah Masjidil Haram",
  },
  id: {
    headerSubtitle: "Pencari Arah Kiblat",
    backToHome: "Kembali ke Beranda",
    qiblaFinder: "Pencari Kiblat",
    findingLocation: "Mencari lokasi Anda...",
    allowLocation: "Silakan izinkan akses lokasi",
    locationError: "Kesalahan Lokasi",
    tryAgain: "Coba Lagi",
    findQiblaDirection: "Cari Arah Kiblat",
    allowLocationDesc: "Izinkan akses lokasi untuk menghitung arah tepat ke Ka'bah dari posisi Anda saat ini.",
    enableLocation: "Aktifkan Lokasi",
    enableLiveCompass: "Aktifkan Kompas Langsung",
    enableCompassDesc: "Berikan izin orientasi perangkat untuk kompas langsung yang melacak arah ponsel Anda secara real-time.",
    enableCompass: "Aktifkan Kompas",
    qiblaDirection: "Arah Kiblat",
    fromNorth: "dari Utara",
    distanceToKaaba: "Jarak ke Ka'bah",
    yourLocation: "Lokasi Anda",
    usingDesktop: "Menggunakan Desktop?",
    desktopDesc: "Kompas menunjukkan arah Kiblat relatif terhadap Utara. Gunakan kompas fisik untuk menghadap {bearing} dari Utara. Untuk pengalaman kompas langsung, buka halaman ini di perangkat seluler Anda.",
    compassDenied: "Izin kompas ditolak. Arah Kiblat ditampilkan sebagai {bearing} dari Utara. Gunakan kompas fisik untuk menemukan arah ini.",
    footerNote: "Arah Kiblat dihitung menggunakan bearing lingkaran besar ke Ka'bah (21.4225°N, 39.8262°E)",
    jazakallah: "Semoga Allah membalas Anda dengan kebaikan",
    geoNotSupported: "Browser Anda tidak mendukung geolokasi.",
    permissionDenied: "Izin lokasi ditolak. Silakan aktifkan akses lokasi di pengaturan browser.",
    positionUnavailable: "Informasi lokasi tidak tersedia.",
    timeout: "Permintaan lokasi habis waktu. Silakan coba lagi.",
    unknownError: "Terjadi kesalahan yang tidak diketahui.",
    quranVerse: "Maka hadapkanlah wajahmu ke arah Masjidil Haram",
  },
};
