import type { TransLang } from "@/lib/islamic-content";

export interface SalatTrackerTexts {
  // Page
  pageTitle: string;
  subtitle: string;
  tabToday: string;
  tabReports: string;
  tabLeaderboard: string;
  tabQaza: string;

  // Prayers
  fajr: string;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
  jummah: string;
  eidAlFitr: string;
  eidAlAdha: string;
  taraweeh: string;
  witr: string;
  tahajjud: string;
  duha: string;
  ishraq: string;
  awwabin: string;
  sunnahFajr: string;
  sunnahDhuhrBefore: string;
  sunnahDhuhrAfter: string;
  sunnahMaghrib: string;
  sunnahIsha: string;

  // Arabic prayer names
  fajrAr: string;
  dhuhrAr: string;
  asrAr: string;
  maghribAr: string;
  ishaAr: string;
  jummahAr: string;

  // Status
  prayed: string;
  missed: string;
  late: string;
  qaza: string;
  onTime: string;
  inJamaah: string;
  jamaah: string;

  // Stats
  streak: string;
  dayStreak: string;
  longestStreak: string;
  completionRate: string;
  onTimeRate: string;
  jamaahRate: string;
  fardCompleted: string;
  todayProgress: string;
  improvement: string;

  // Reports
  weekly: string;
  monthly: string;
  yearly: string;
  downloadReport: string;
  exportAsImage: string;
  thisWeek: string;
  thisMonth: string;
  thisYear: string;
  allTime: string;
  today: string;
  yesterday: string;
  noData: string;

  // Leaderboard
  leaderboard: string;
  topStreaks: string;
  mostConsistent: string;
  jamaahChampion: string;
  onTimeChampion: string;
  yourRank: string;
  rank: string;

  // Qaza
  qazaRemaining: string;
  qazaCompleted: string;
  qazaMadeUp: string;
  logQaza: string;
  totalOwed: string;
  qazaOverview: string;
  prayedQaza: string;

  // Goals
  weeklyGoals: string;
  allFardGoal: string;
  allOnTimeGoal: string;
  jamaahGoal: string;
  sunnahGoal: string;
  zeroMissedGoal: string;
  goalCompleted: string;
  setGoal: string;

  // Sunnah/Nafl
  sunnahPrayers: string;
  naflPrayers: string;
  showSunnah: string;
  hideSunnah: string;

  // Jummah
  jummahMubarak: string;
  fridayBlessing: string;

  // Eid
  eidMubarak: string;
  eidPrayer: string;
  takbeer: string;

  // Ramadan
  ramadanMubarak: string;
  fasting: string;
  suhoor: string;
  iftar: string;
  quranPages: string;
  sadaqah: string;
  itikaf: string;
  laylatalQadr: string;
  dayOf: string;
  daysRemaining: string;
  khatamProgress: string;
  lastTenNights: string;
  seekLaylatalQadr: string;
  fastedToday: string;
  duaBeforeIftar: string;
  ramadanTracker: string;
  ramadanDay: string;

  // Date nav
  previousDay: string;
  nextDay: string;
  goToToday: string;

  // Insights
  perfectDay: string;
  keepGoing: string;
  missedSome: string;
  fajrTip: string;

  // Loading
  loading: string;
  saving: string;

  // Misc
  days: string;
  prayers: string;
  of: string;
  page: string;
  back: string;
  save: string;
  cancel: string;
  loginRequired: string;
  loginToTrack: string;
}

export const SALAT_TRACKER_TEXTS: Record<TransLang, SalatTrackerTexts> = {
  en: {
    pageTitle: "Salat Tracker",
    subtitle: "Track your daily prayers and build consistent habits",
    tabToday: "Today",
    tabReports: "Reports",
    tabLeaderboard: "Leaderboard",
    tabQaza: "Qaza Log",
    fajr: "Fajr",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    jummah: "Jummah",
    eidAlFitr: "Eid al-Fitr Prayer",
    eidAlAdha: "Eid al-Adha Prayer",
    taraweeh: "Taraweeh",
    witr: "Witr",
    tahajjud: "Tahajjud",
    duha: "Duha",
    ishraq: "Ishraq",
    awwabin: "Awwabin",
    sunnahFajr: "Sunnah Fajr",
    sunnahDhuhrBefore: "Sunnah Dhuhr (Before)",
    sunnahDhuhrAfter: "Sunnah Dhuhr (After)",
    sunnahMaghrib: "Sunnah Maghrib",
    sunnahIsha: "Sunnah Isha",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "Prayed",
    missed: "Missed",
    late: "Late",
    qaza: "Qaza",
    onTime: "On Time",
    inJamaah: "In Jamaah",
    jamaah: "Jamaah",
    streak: "Streak",
    dayStreak: "day streak",
    longestStreak: "Longest Streak",
    completionRate: "Completion Rate",
    onTimeRate: "On-Time Rate",
    jamaahRate: "Jamaah Rate",
    fardCompleted: "Fard Completed",
    todayProgress: "Today's Progress",
    improvement: "Improvement",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    downloadReport: "Download Report",
    exportAsImage: "Export as Image",
    thisWeek: "This Week",
    thisMonth: "This Month",
    thisYear: "This Year",
    allTime: "All Time",
    today: "Today",
    yesterday: "Yesterday",
    noData: "No data yet. Start tracking your prayers!",
    leaderboard: "Leaderboard",
    topStreaks: "Top Streaks",
    mostConsistent: "Most Consistent",
    jamaahChampion: "Jamaah Champion",
    onTimeChampion: "On-Time Champion",
    yourRank: "Your Rank",
    rank: "Rank",
    qazaRemaining: "Qaza Remaining",
    qazaCompleted: "Qaza Completed",
    qazaMadeUp: "Made Up",
    logQaza: "Log Qaza Prayer",
    totalOwed: "Total Owed",
    qazaOverview: "Qaza Overview",
    prayedQaza: "Prayed Qaza Today",
    weeklyGoals: "Weekly Goals",
    allFardGoal: "All 5 Fard Daily",
    allOnTimeGoal: "All Prayers On Time",
    jamaahGoal: "3+ Jamaah Days",
    sunnahGoal: "Track Sunnah Prayers",
    zeroMissedGoal: "Zero Missed Prayers",
    goalCompleted: "Goal Completed!",
    setGoal: "Set Goal",
    sunnahPrayers: "Sunnah Prayers",
    naflPrayers: "Nafl Prayers",
    showSunnah: "Show Sunnah & Nafl",
    hideSunnah: "Hide Sunnah & Nafl",
    jummahMubarak: "Jummah Mubarak!",
    fridayBlessing: "The best day the sun rises upon is Friday",
    eidMubarak: "Eid Mubarak!",
    eidPrayer: "Eid Prayer",
    takbeer: "Allahu Akbar, Allahu Akbar, La ilaha illallah",
    ramadanMubarak: "Ramadan Mubarak!",
    fasting: "Fasting",
    suhoor: "Suhoor",
    iftar: "Iftar",
    quranPages: "Quran Pages",
    sadaqah: "Sadaqah",
    itikaf: "I'tikaf",
    laylatalQadr: "Laylatul Qadr Worship",
    dayOf: "Day",
    daysRemaining: "days remaining",
    khatamProgress: "Khatam Progress",
    lastTenNights: "Last 10 Nights",
    seekLaylatalQadr: "Seek Laylatul Qadr in the odd nights",
    fastedToday: "Fasted Today",
    duaBeforeIftar: "Dua Before Iftar",
    ramadanTracker: "Ramadan Tracker",
    ramadanDay: "Ramadan Day",
    previousDay: "Previous Day",
    nextDay: "Next Day",
    goToToday: "Go to Today",
    perfectDay: "MashaAllah! All prayers completed!",
    keepGoing: "Keep going! You're building a beautiful habit.",
    missedSome: "Tomorrow is a fresh start. Every prayer counts.",
    fajrTip: "Try setting an alarm 15 minutes before Fajr",
    loading: "Loading...",
    saving: "Saving...",
    days: "days",
    prayers: "prayers",
    of: "of",
    page: "Page",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    loginRequired: "Login Required",
    loginToTrack: "Please log in to track your prayers",
  },

  bn: {
    pageTitle: "সালাত ট্র্যাকার",
    subtitle: "আপনার দৈনিক নামাজ ট্র্যাক করুন এবং ধারাবাহিক অভ্যাস গড়ুন",
    tabToday: "আজ",
    tabReports: "রিপোর্ট",
    tabLeaderboard: "লিডারবোর্ড",
    tabQaza: "কাযা লগ",
    fajr: "ফজর",
    dhuhr: "যোহর",
    asr: "আসর",
    maghrib: "মাগরিব",
    isha: "ইশা",
    jummah: "জুমআ",
    eidAlFitr: "ঈদুল ফিতরের নামাজ",
    eidAlAdha: "ঈদুল আযহার নামাজ",
    taraweeh: "তারাবীহ",
    witr: "বিতর",
    tahajjud: "তাহাজ্জুদ",
    duha: "চাশত",
    ishraq: "ইশরাক",
    awwabin: "আওয়াবীন",
    sunnahFajr: "সুন্নাত ফজর",
    sunnahDhuhrBefore: "সুন্নাত যোহর (আগে)",
    sunnahDhuhrAfter: "সুন্নাত যোহর (পরে)",
    sunnahMaghrib: "সুন্নাত মাগরিব",
    sunnahIsha: "সুন্নাত ইশা",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "পড়েছি",
    missed: "মিস",
    late: "দেরি",
    qaza: "কাযা",
    onTime: "সময়মতো",
    inJamaah: "জামাআতে",
    jamaah: "জামাআত",
    streak: "ধারাবাহিকতা",
    dayStreak: "পর পর দিন",
    longestStreak: "সর্বোচ্চ রেকর্ড",
    completionRate: "সম্পন্নের হার",
    onTimeRate: "সময়মতো হার",
    jamaahRate: "জামাআত হার",
    fardCompleted: "ফরজ সম্পন্ন",
    todayProgress: "আজকের অগ্রগতি",
    improvement: "উন্নতি",
    weekly: "সাপ্তাহিক",
    monthly: "মাসিক",
    yearly: "বার্ষিক",
    downloadReport: "রিপোর্ট ডাউনলোড",
    exportAsImage: "ছবি হিসেবে রপ্তানি",
    thisWeek: "এই সপ্তাহ",
    thisMonth: "এই মাস",
    thisYear: "এই বছর",
    allTime: "সর্বকালীন",
    today: "আজ",
    yesterday: "গতকাল",
    noData: "এখনো কোনো তথ্য নেই। নামাজ ট্র্যাক করা শুরু করুন!",
    leaderboard: "লিডারবোর্ড",
    topStreaks: "সেরা ধারাবাহিকতা",
    mostConsistent: "সবচেয়ে ধারাবাহিক",
    jamaahChampion: "জামাআত চ্যাম্পিয়ন",
    onTimeChampion: "সময়মতো চ্যাম্পিয়ন",
    yourRank: "আপনার র‍্যাংক",
    rank: "র‍্যাংক",
    qazaRemaining: "বাকি কাযা",
    qazaCompleted: "কাযা সম্পন্ন",
    qazaMadeUp: "আদায় হয়েছে",
    logQaza: "কাযা নামাজ লগ করুন",
    totalOwed: "মোট বাকি",
    qazaOverview: "কাযা সারসংক্ষেপ",
    prayedQaza: "আজ কাযা পড়েছি",
    weeklyGoals: "সাপ্তাহিক লক্ষ্য",
    allFardGoal: "প্রতিদিন ৫ ওয়াক্ত ফরজ",
    allOnTimeGoal: "সব নামাজ সময়মতো",
    jamaahGoal: "৩+ দিন জামাআতে",
    sunnahGoal: "সুন্নাত নামাজ ট্র্যাক",
    zeroMissedGoal: "কোনো নামাজ মিস নয়",
    goalCompleted: "লক্ষ্য অর্জিত!",
    setGoal: "লক্ষ্য নির্ধারণ",
    sunnahPrayers: "সুন্নাত নামাজ",
    naflPrayers: "নফল নামাজ",
    showSunnah: "সুন্নাত ও নফল দেখান",
    hideSunnah: "সুন্নাত ও নফল লুকান",
    jummahMubarak: "জুমআ মুবারক!",
    fridayBlessing: "সূর্য যে দিনে উদিত হয় তার মধ্যে সর্বশ্রেষ্ঠ দিন হলো শুক্রবার",
    eidMubarak: "ঈদ মুবারক!",
    eidPrayer: "ঈদের নামাজ",
    takbeer: "আল্লাহু আকবার, আল্লাহু আকবার, লা ইলাহা ইল্লাল্লাহ",
    ramadanMubarak: "রমজান মুবারক!",
    fasting: "রোজা",
    suhoor: "সেহরি",
    iftar: "ইফতার",
    quranPages: "কুরআন পৃষ্ঠা",
    sadaqah: "সদকা",
    itikaf: "ই'তিকাফ",
    laylatalQadr: "লাইলাতুল কদর ইবাদত",
    dayOf: "দিন",
    daysRemaining: "দিন বাকি",
    khatamProgress: "খতম অগ্রগতি",
    lastTenNights: "শেষ ১০ রাত",
    seekLaylatalQadr: "বেজোড় রাতগুলোতে লাইলাতুল কদর অন্বেষণ করুন",
    fastedToday: "আজ রোজা রেখেছি",
    duaBeforeIftar: "ইফতারের আগে দোয়া",
    ramadanTracker: "রমজান ট্র্যাকার",
    ramadanDay: "রমজানের দিন",
    previousDay: "আগের দিন",
    nextDay: "পরের দিন",
    goToToday: "আজকে যান",
    perfectDay: "মাশাআল্লাহ! সব নামাজ সম্পন্ন!",
    keepGoing: "চালিয়ে যান! আপনি সুন্দর অভ্যাস গড়ছেন।",
    missedSome: "আগামীকাল নতুন শুরু। প্রতিটি নামাজ গুরুত্বপূর্ণ।",
    fajrTip: "ফজরের ১৫ মিনিট আগে অ্যালার্ম দিন",
    loading: "লোড হচ্ছে...",
    saving: "সেভ হচ্ছে...",
    days: "দিন",
    prayers: "নামাজ",
    of: "এর",
    page: "পৃষ্ঠা",
    back: "ফিরে যান",
    save: "সেভ",
    cancel: "বাতিল",
    loginRequired: "লগইন প্রয়োজন",
    loginToTrack: "নামাজ ট্র্যাক করতে লগইন করুন",
  },

  ur: {
    pageTitle: "نماز ٹریکر",
    subtitle: "اپنی روزانہ نمازوں کو ٹریک کریں اور مستقل عادت بنائیں",
    tabToday: "آج",
    tabReports: "رپورٹس",
    tabLeaderboard: "لیڈربورڈ",
    tabQaza: "قضا لاگ",
    fajr: "فجر",
    dhuhr: "ظہر",
    asr: "عصر",
    maghrib: "مغرب",
    isha: "عشاء",
    jummah: "جمعہ",
    eidAlFitr: "نماز عید الفطر",
    eidAlAdha: "نماز عید الاضحی",
    taraweeh: "تراویح",
    witr: "وتر",
    tahajjud: "تہجد",
    duha: "چاشت",
    ishraq: "اشراق",
    awwabin: "اوابین",
    sunnahFajr: "سنت فجر",
    sunnahDhuhrBefore: "سنت ظہر (پہلے)",
    sunnahDhuhrAfter: "سنت ظہر (بعد)",
    sunnahMaghrib: "سنت مغرب",
    sunnahIsha: "سنت عشاء",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "ادا کی",
    missed: "قضا",
    late: "دیر سے",
    qaza: "قضا",
    onTime: "وقت پر",
    inJamaah: "جماعت میں",
    jamaah: "جماعت",
    streak: "تسلسل",
    dayStreak: "دن کا تسلسل",
    longestStreak: "سب سے لمبا تسلسل",
    completionRate: "مکمل ہونے کی شرح",
    onTimeRate: "وقت پر شرح",
    jamaahRate: "جماعت کی شرح",
    fardCompleted: "فرض مکمل",
    todayProgress: "آج کی پیشرفت",
    improvement: "بہتری",
    weekly: "ہفتہ وار",
    monthly: "ماہانہ",
    yearly: "سالانہ",
    downloadReport: "رپورٹ ڈاؤنلوڈ",
    exportAsImage: "تصویر کے طور پر برآمد",
    thisWeek: "اس ہفتے",
    thisMonth: "اس مہینے",
    thisYear: "اس سال",
    allTime: "کل وقت",
    today: "آج",
    yesterday: "کل",
    noData: "ابھی تک کوئی ڈیٹا نہیں۔ نمازیں ٹریک کرنا شروع کریں!",
    leaderboard: "لیڈربورڈ",
    topStreaks: "ٹاپ تسلسل",
    mostConsistent: "سب سے مستقل",
    jamaahChampion: "جماعت چیمپئن",
    onTimeChampion: "وقت پر چیمپئن",
    yourRank: "آپ کی درجہ بندی",
    rank: "درجہ",
    qazaRemaining: "باقی قضا",
    qazaCompleted: "قضا مکمل",
    qazaMadeUp: "ادا کی گئی",
    logQaza: "قضا نماز لاگ کریں",
    totalOwed: "کل واجب الادا",
    qazaOverview: "قضا کا جائزہ",
    prayedQaza: "آج قضا ادا کی",
    weeklyGoals: "ہفتہ وار اہداف",
    allFardGoal: "روزانہ ۵ فرض نمازیں",
    allOnTimeGoal: "تمام نمازیں وقت پر",
    jamaahGoal: "۳+ دن جماعت",
    sunnahGoal: "سنت نمازیں ٹریک",
    zeroMissedGoal: "کوئی نماز قضا نہیں",
    goalCompleted: "ہدف حاصل!",
    setGoal: "ہدف مقرر کریں",
    sunnahPrayers: "سنت نمازیں",
    naflPrayers: "نفل نمازیں",
    showSunnah: "سنت و نفل دکھائیں",
    hideSunnah: "سنت و نفل چھپائیں",
    jummahMubarak: "!جمعہ مبارک",
    fridayBlessing: "سورج جس دن طلوع ہوتا ہے ان میں سب سے افضل دن جمعہ ہے",
    eidMubarak: "!عید مبارک",
    eidPrayer: "نماز عید",
    takbeer: "اللہ اکبر، اللہ اکبر، لا الہ الا اللہ",
    ramadanMubarak: "!رمضان مبارک",
    fasting: "روزہ",
    suhoor: "سحری",
    iftar: "افطار",
    quranPages: "قرآن کے صفحات",
    sadaqah: "صدقہ",
    itikaf: "اعتکاف",
    laylatalQadr: "شب قدر کی عبادت",
    dayOf: "دن",
    daysRemaining: "دن باقی",
    khatamProgress: "ختم کی پیشرفت",
    lastTenNights: "آخری ۱۰ راتیں",
    seekLaylatalQadr: "طاق راتوں میں شب قدر تلاش کریں",
    fastedToday: "آج روزہ رکھا",
    duaBeforeIftar: "افطار سے پہلے دعا",
    ramadanTracker: "رمضان ٹریکر",
    ramadanDay: "رمضان کا دن",
    previousDay: "پچھلا دن",
    nextDay: "اگلا دن",
    goToToday: "آج پر جائیں",
    perfectDay: "!ماشاءاللہ! تمام نمازیں مکمل",
    keepGoing: "جاری رکھیں! آپ خوبصورت عادت بنا رہے ہیں۔",
    missedSome: "کل نئی شروعات ہے۔ ہر نماز اہمیت رکھتی ہے۔",
    fajrTip: "فجر سے ۱۵ منٹ پہلے الارم لگائیں",
    loading: "...لوڈ ہو رہا ہے",
    saving: "...محفوظ ہو رہا ہے",
    days: "دن",
    prayers: "نمازیں",
    of: "کا",
    page: "صفحہ",
    back: "واپس",
    save: "محفوظ",
    cancel: "منسوخ",
    loginRequired: "لاگ ان ضروری ہے",
    loginToTrack: "نمازیں ٹریک کرنے کے لیے لاگ ان کریں",
  },

  ar: {
    pageTitle: "متتبع الصلاة",
    subtitle: "تتبع صلواتك اليومية وابنِ عادات ثابتة",
    tabToday: "اليوم",
    tabReports: "التقارير",
    tabLeaderboard: "لوحة المتصدرين",
    tabQaza: "سجل القضاء",
    fajr: "الفجر",
    dhuhr: "الظهر",
    asr: "العصر",
    maghrib: "المغرب",
    isha: "العشاء",
    jummah: "الجمعة",
    eidAlFitr: "صلاة عيد الفطر",
    eidAlAdha: "صلاة عيد الأضحى",
    taraweeh: "التراويح",
    witr: "الوتر",
    tahajjud: "التهجد",
    duha: "الضحى",
    ishraq: "الإشراق",
    awwabin: "الأوابين",
    sunnahFajr: "سنة الفجر",
    sunnahDhuhrBefore: "سنة الظهر (قبل)",
    sunnahDhuhrAfter: "سنة الظهر (بعد)",
    sunnahMaghrib: "سنة المغرب",
    sunnahIsha: "سنة العشاء",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "صُلّيت",
    missed: "فائتة",
    late: "متأخرة",
    qaza: "قضاء",
    onTime: "في الوقت",
    inJamaah: "في جماعة",
    jamaah: "جماعة",
    streak: "التسلسل",
    dayStreak: "يوم متتالي",
    longestStreak: "أطول تسلسل",
    completionRate: "نسبة الإكمال",
    onTimeRate: "نسبة الوقت",
    jamaahRate: "نسبة الجماعة",
    fardCompleted: "الفرض المكتمل",
    todayProgress: "تقدم اليوم",
    improvement: "تحسن",
    weekly: "أسبوعي",
    monthly: "شهري",
    yearly: "سنوي",
    downloadReport: "تحميل التقرير",
    exportAsImage: "تصدير كصورة",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    thisYear: "هذا العام",
    allTime: "كل الوقت",
    today: "اليوم",
    yesterday: "أمس",
    noData: "لا توجد بيانات بعد. ابدأ بتتبع صلواتك!",
    leaderboard: "لوحة المتصدرين",
    topStreaks: "أعلى التسلسلات",
    mostConsistent: "الأكثر ثباتاً",
    jamaahChampion: "بطل الجماعة",
    onTimeChampion: "بطل الوقت",
    yourRank: "ترتيبك",
    rank: "الترتيب",
    qazaRemaining: "القضاء المتبقي",
    qazaCompleted: "القضاء المكتمل",
    qazaMadeUp: "تم القضاء",
    logQaza: "تسجيل صلاة القضاء",
    totalOwed: "المجموع المستحق",
    qazaOverview: "نظرة عامة على القضاء",
    prayedQaza: "صلاة القضاء اليوم",
    weeklyGoals: "أهداف أسبوعية",
    allFardGoal: "جميع الفروض الخمسة يومياً",
    allOnTimeGoal: "جميع الصلوات في وقتها",
    jamaahGoal: "٣+ أيام جماعة",
    sunnahGoal: "تتبع السنن",
    zeroMissedGoal: "صفر صلوات فائتة",
    goalCompleted: "تم تحقيق الهدف!",
    setGoal: "تحديد هدف",
    sunnahPrayers: "صلوات السنة",
    naflPrayers: "صلوات النوافل",
    showSunnah: "إظهار السنن والنوافل",
    hideSunnah: "إخفاء السنن والنوافل",
    jummahMubarak: "!جمعة مباركة",
    fridayBlessing: "خير يوم طلعت عليه الشمس يوم الجمعة",
    eidMubarak: "!عيد مبارك",
    eidPrayer: "صلاة العيد",
    takbeer: "الله أكبر الله أكبر لا إله إلا الله",
    ramadanMubarak: "!رمضان مبارك",
    fasting: "الصيام",
    suhoor: "السحور",
    iftar: "الإفطار",
    quranPages: "صفحات القرآن",
    sadaqah: "الصدقة",
    itikaf: "الاعتكاف",
    laylatalQadr: "عبادة ليلة القدر",
    dayOf: "يوم",
    daysRemaining: "أيام متبقية",
    khatamProgress: "تقدم الختمة",
    lastTenNights: "العشر الأواخر",
    seekLaylatalQadr: "التمسوها في الوتر من العشر الأواخر",
    fastedToday: "صمت اليوم",
    duaBeforeIftar: "دعاء قبل الإفطار",
    ramadanTracker: "متتبع رمضان",
    ramadanDay: "يوم رمضان",
    previousDay: "اليوم السابق",
    nextDay: "اليوم التالي",
    goToToday: "الذهاب لليوم",
    perfectDay: "!ماشاء الله! أتممت جميع الصلوات",
    keepGoing: "واصل! أنت تبني عادة جميلة.",
    missedSome: "الغد بداية جديدة. كل صلاة مهمة.",
    fajrTip: "حاول ضبط منبه قبل الفجر بـ١٥ دقيقة",
    loading: "...جاري التحميل",
    saving: "...جاري الحفظ",
    days: "أيام",
    prayers: "صلوات",
    of: "من",
    page: "صفحة",
    back: "رجوع",
    save: "حفظ",
    cancel: "إلغاء",
    loginRequired: "تسجيل الدخول مطلوب",
    loginToTrack: "يرجى تسجيل الدخول لتتبع صلواتك",
  },

  tr: {
    pageTitle: "Namaz Takipçisi",
    subtitle: "Günlük namazlarınızı takip edin ve tutarlı alışkanlıklar edinin",
    tabToday: "Bugün",
    tabReports: "Raporlar",
    tabLeaderboard: "Sıralama",
    tabQaza: "Kaza Günlüğü",
    fajr: "Sabah",
    dhuhr: "Öğle",
    asr: "İkindi",
    maghrib: "Akşam",
    isha: "Yatsı",
    jummah: "Cuma",
    eidAlFitr: "Ramazan Bayramı Namazı",
    eidAlAdha: "Kurban Bayramı Namazı",
    taraweeh: "Teravih",
    witr: "Vitir",
    tahajjud: "Teheccüd",
    duha: "Kuşluk",
    ishraq: "İşrak",
    awwabin: "Evvabin",
    sunnahFajr: "Sabah Sünneti",
    sunnahDhuhrBefore: "Öğle Sünneti (Önce)",
    sunnahDhuhrAfter: "Öğle Sünneti (Sonra)",
    sunnahMaghrib: "Akşam Sünneti",
    sunnahIsha: "Yatsı Sünneti",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "Kılındı",
    missed: "Kaçırıldı",
    late: "Geç",
    qaza: "Kaza",
    onTime: "Vaktinde",
    inJamaah: "Cemaatle",
    jamaah: "Cemaat",
    streak: "Seri",
    dayStreak: "gün serisi",
    longestStreak: "En Uzun Seri",
    completionRate: "Tamamlanma Oranı",
    onTimeRate: "Vaktinde Oranı",
    jamaahRate: "Cemaat Oranı",
    fardCompleted: "Farz Tamamlandı",
    todayProgress: "Bugünün İlerlemesi",
    improvement: "Gelişim",
    weekly: "Haftalık",
    monthly: "Aylık",
    yearly: "Yıllık",
    downloadReport: "Raporu İndir",
    exportAsImage: "Görüntü Olarak Dışa Aktar",
    thisWeek: "Bu Hafta",
    thisMonth: "Bu Ay",
    thisYear: "Bu Yıl",
    allTime: "Tüm Zamanlar",
    today: "Bugün",
    yesterday: "Dün",
    noData: "Henüz veri yok. Namazlarınızı takip etmeye başlayın!",
    leaderboard: "Sıralama",
    topStreaks: "En İyi Seriler",
    mostConsistent: "En Tutarlı",
    jamaahChampion: "Cemaat Şampiyonu",
    onTimeChampion: "Vaktinde Şampiyonu",
    yourRank: "Sıralamanız",
    rank: "Sıra",
    qazaRemaining: "Kalan Kaza",
    qazaCompleted: "Tamamlanan Kaza",
    qazaMadeUp: "Kılınan Kaza",
    logQaza: "Kaza Namazı Kaydet",
    totalOwed: "Toplam Borç",
    qazaOverview: "Kaza Özeti",
    prayedQaza: "Bugün Kaza Kılındı",
    weeklyGoals: "Haftalık Hedefler",
    allFardGoal: "Günlük 5 Vakit Farz",
    allOnTimeGoal: "Tüm Namazlar Vaktinde",
    jamaahGoal: "3+ Gün Cemaat",
    sunnahGoal: "Sünnet Namazları Takip",
    zeroMissedGoal: "Sıfır Kaçırılan Namaz",
    goalCompleted: "Hedef Tamamlandı!",
    setGoal: "Hedef Belirle",
    sunnahPrayers: "Sünnet Namazları",
    naflPrayers: "Nafile Namazlar",
    showSunnah: "Sünnet ve Nafile Göster",
    hideSunnah: "Sünnet ve Nafile Gizle",
    jummahMubarak: "Hayırlı Cumalar!",
    fridayBlessing: "Güneşin doğduğu en hayırlı gün Cuma günüdür",
    eidMubarak: "Bayramınız Mübarek Olsun!",
    eidPrayer: "Bayram Namazı",
    takbeer: "Allahu Ekber, Allahu Ekber, La ilahe illallah",
    ramadanMubarak: "Ramazan Mübarek Olsun!",
    fasting: "Oruç",
    suhoor: "Sahur",
    iftar: "İftar",
    quranPages: "Kur'an Sayfaları",
    sadaqah: "Sadaka",
    itikaf: "İtikaf",
    laylatalQadr: "Kadir Gecesi İbadeti",
    dayOf: "Gün",
    daysRemaining: "gün kaldı",
    khatamProgress: "Hatim İlerlemesi",
    lastTenNights: "Son 10 Gece",
    seekLaylatalQadr: "Kadir Gecesini son on günün tek gecelerinde arayın",
    fastedToday: "Bugün Oruç Tutuldu",
    duaBeforeIftar: "İftar Öncesi Dua",
    ramadanTracker: "Ramazan Takipçisi",
    ramadanDay: "Ramazan Günü",
    previousDay: "Önceki Gün",
    nextDay: "Sonraki Gün",
    goToToday: "Bugüne Git",
    perfectDay: "Maşallah! Tüm namazlar tamamlandı!",
    keepGoing: "Devam edin! Güzel bir alışkanlık oluşturuyorsunuz.",
    missedSome: "Yarın yeni bir başlangıç. Her namaz önemli.",
    fajrTip: "Sabah namazından 15 dakika önce alarm kurmayı deneyin",
    loading: "Yükleniyor...",
    saving: "Kaydediliyor...",
    days: "gün",
    prayers: "namaz",
    of: "/",
    page: "Sayfa",
    back: "Geri",
    save: "Kaydet",
    cancel: "İptal",
    loginRequired: "Giriş Gerekli",
    loginToTrack: "Namazlarınızı takip etmek için giriş yapın",
  },

  ms: {
    pageTitle: "Penjejak Solat",
    subtitle: "Jejak solat harian anda dan bina amalan yang konsisten",
    tabToday: "Hari Ini",
    tabReports: "Laporan",
    tabLeaderboard: "Papan Pendahulu",
    tabQaza: "Log Qada",
    fajr: "Subuh",
    dhuhr: "Zohor",
    asr: "Asar",
    maghrib: "Maghrib",
    isha: "Isyak",
    jummah: "Jumaat",
    eidAlFitr: "Solat Hari Raya Aidilfitri",
    eidAlAdha: "Solat Hari Raya Aidiladha",
    taraweeh: "Tarawih",
    witr: "Witir",
    tahajjud: "Tahajjud",
    duha: "Dhuha",
    ishraq: "Isyraq",
    awwabin: "Awwabin",
    sunnahFajr: "Sunat Subuh",
    sunnahDhuhrBefore: "Sunat Zohor (Sebelum)",
    sunnahDhuhrAfter: "Sunat Zohor (Selepas)",
    sunnahMaghrib: "Sunat Maghrib",
    sunnahIsha: "Sunat Isyak",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "Ditunaikan",
    missed: "Terlepas",
    late: "Lewat",
    qaza: "Qada",
    onTime: "Tepat Waktu",
    inJamaah: "Berjemaah",
    jamaah: "Jemaah",
    streak: "Rangkaian",
    dayStreak: "hari berturut",
    longestStreak: "Rangkaian Terpanjang",
    completionRate: "Kadar Penyelesaian",
    onTimeRate: "Kadar Tepat Waktu",
    jamaahRate: "Kadar Jemaah",
    fardCompleted: "Fardhu Selesai",
    todayProgress: "Kemajuan Hari Ini",
    improvement: "Peningkatan",
    weekly: "Mingguan",
    monthly: "Bulanan",
    yearly: "Tahunan",
    downloadReport: "Muat Turun Laporan",
    exportAsImage: "Eksport sebagai Gambar",
    thisWeek: "Minggu Ini",
    thisMonth: "Bulan Ini",
    thisYear: "Tahun Ini",
    allTime: "Sepanjang Masa",
    today: "Hari Ini",
    yesterday: "Semalam",
    noData: "Tiada data lagi. Mula jejak solat anda!",
    leaderboard: "Papan Pendahulu",
    topStreaks: "Rangkaian Teratas",
    mostConsistent: "Paling Konsisten",
    jamaahChampion: "Juara Jemaah",
    onTimeChampion: "Juara Tepat Waktu",
    yourRank: "Kedudukan Anda",
    rank: "Kedudukan",
    qazaRemaining: "Qada Berbaki",
    qazaCompleted: "Qada Selesai",
    qazaMadeUp: "Telah Diqada",
    logQaza: "Log Solat Qada",
    totalOwed: "Jumlah Terhutang",
    qazaOverview: "Gambaran Qada",
    prayedQaza: "Solat Qada Hari Ini",
    weeklyGoals: "Matlamat Mingguan",
    allFardGoal: "5 Fardhu Setiap Hari",
    allOnTimeGoal: "Semua Solat Tepat Waktu",
    jamaahGoal: "3+ Hari Berjemaah",
    sunnahGoal: "Jejak Solat Sunat",
    zeroMissedGoal: "Sifar Solat Terlepas",
    goalCompleted: "Matlamat Dicapai!",
    setGoal: "Tetapkan Matlamat",
    sunnahPrayers: "Solat Sunat",
    naflPrayers: "Solat Sunat Tambahan",
    showSunnah: "Tunjuk Sunat & Nafl",
    hideSunnah: "Sembunyikan Sunat & Nafl",
    jummahMubarak: "Jumaat Mubarak!",
    fridayBlessing: "Hari terbaik matahari terbit adalah hari Jumaat",
    eidMubarak: "Selamat Hari Raya!",
    eidPrayer: "Solat Hari Raya",
    takbeer: "Allahu Akbar, Allahu Akbar, La ilaha illallah",
    ramadanMubarak: "Ramadan Mubarak!",
    fasting: "Puasa",
    suhoor: "Sahur",
    iftar: "Berbuka",
    quranPages: "Muka Surat Al-Quran",
    sadaqah: "Sedekah",
    itikaf: "Iktikaf",
    laylatalQadr: "Ibadah Lailatul Qadr",
    dayOf: "Hari",
    daysRemaining: "hari lagi",
    khatamProgress: "Kemajuan Khatam",
    lastTenNights: "10 Malam Terakhir",
    seekLaylatalQadr: "Carilah Lailatul Qadr pada malam-malam ganjil",
    fastedToday: "Berpuasa Hari Ini",
    duaBeforeIftar: "Doa Sebelum Berbuka",
    ramadanTracker: "Penjejak Ramadan",
    ramadanDay: "Hari Ramadan",
    previousDay: "Hari Sebelumnya",
    nextDay: "Hari Berikutnya",
    goToToday: "Pergi ke Hari Ini",
    perfectDay: "MasyaAllah! Semua solat selesai!",
    keepGoing: "Teruskan! Anda membina amalan yang indah.",
    missedSome: "Esok permulaan baru. Setiap solat penting.",
    fajrTip: "Cuba tetapkan penggera 15 minit sebelum Subuh",
    loading: "Memuatkan...",
    saving: "Menyimpan...",
    days: "hari",
    prayers: "solat",
    of: "daripada",
    page: "Halaman",
    back: "Kembali",
    save: "Simpan",
    cancel: "Batal",
    loginRequired: "Log Masuk Diperlukan",
    loginToTrack: "Sila log masuk untuk jejak solat anda",
  },

  id: {
    pageTitle: "Pelacak Shalat",
    subtitle: "Lacak shalat harian Anda dan bangun kebiasaan yang konsisten",
    tabToday: "Hari Ini",
    tabReports: "Laporan",
    tabLeaderboard: "Papan Peringkat",
    tabQaza: "Log Qadha",
    fajr: "Subuh",
    dhuhr: "Dzuhur",
    asr: "Ashar",
    maghrib: "Maghrib",
    isha: "Isya",
    jummah: "Jumat",
    eidAlFitr: "Shalat Idul Fitri",
    eidAlAdha: "Shalat Idul Adha",
    taraweeh: "Tarawih",
    witr: "Witir",
    tahajjud: "Tahajud",
    duha: "Dhuha",
    ishraq: "Isyraq",
    awwabin: "Awwabin",
    sunnahFajr: "Sunnah Subuh",
    sunnahDhuhrBefore: "Sunnah Dzuhur (Sebelum)",
    sunnahDhuhrAfter: "Sunnah Dzuhur (Sesudah)",
    sunnahMaghrib: "Sunnah Maghrib",
    sunnahIsha: "Sunnah Isya",
    fajrAr: "الفجر",
    dhuhrAr: "الظهر",
    asrAr: "العصر",
    maghribAr: "المغرب",
    ishaAr: "العشاء",
    jummahAr: "الجمعة",
    prayed: "Sudah Shalat",
    missed: "Terlewat",
    late: "Terlambat",
    qaza: "Qadha",
    onTime: "Tepat Waktu",
    inJamaah: "Berjamaah",
    jamaah: "Jamaah",
    streak: "Rangkaian",
    dayStreak: "hari berturut",
    longestStreak: "Rangkaian Terpanjang",
    completionRate: "Tingkat Penyelesaian",
    onTimeRate: "Tingkat Tepat Waktu",
    jamaahRate: "Tingkat Jamaah",
    fardCompleted: "Fardhu Selesai",
    todayProgress: "Progres Hari Ini",
    improvement: "Peningkatan",
    weekly: "Mingguan",
    monthly: "Bulanan",
    yearly: "Tahunan",
    downloadReport: "Unduh Laporan",
    exportAsImage: "Ekspor sebagai Gambar",
    thisWeek: "Minggu Ini",
    thisMonth: "Bulan Ini",
    thisYear: "Tahun Ini",
    allTime: "Sepanjang Waktu",
    today: "Hari Ini",
    yesterday: "Kemarin",
    noData: "Belum ada data. Mulai lacak shalat Anda!",
    leaderboard: "Papan Peringkat",
    topStreaks: "Rangkaian Teratas",
    mostConsistent: "Paling Konsisten",
    jamaahChampion: "Juara Jamaah",
    onTimeChampion: "Juara Tepat Waktu",
    yourRank: "Peringkat Anda",
    rank: "Peringkat",
    qazaRemaining: "Qadha Tersisa",
    qazaCompleted: "Qadha Selesai",
    qazaMadeUp: "Telah Diqadha",
    logQaza: "Catat Shalat Qadha",
    totalOwed: "Total Terhutang",
    qazaOverview: "Ringkasan Qadha",
    prayedQaza: "Shalat Qadha Hari Ini",
    weeklyGoals: "Target Mingguan",
    allFardGoal: "5 Fardhu Setiap Hari",
    allOnTimeGoal: "Semua Shalat Tepat Waktu",
    jamaahGoal: "3+ Hari Berjamaah",
    sunnahGoal: "Lacak Shalat Sunnah",
    zeroMissedGoal: "Nol Shalat Terlewat",
    goalCompleted: "Target Tercapai!",
    setGoal: "Tetapkan Target",
    sunnahPrayers: "Shalat Sunnah",
    naflPrayers: "Shalat Nafilah",
    showSunnah: "Tampilkan Sunnah & Nafilah",
    hideSunnah: "Sembunyikan Sunnah & Nafilah",
    jummahMubarak: "Jumat Barokah!",
    fridayBlessing: "Hari terbaik matahari terbit adalah hari Jumat",
    eidMubarak: "Selamat Hari Raya!",
    eidPrayer: "Shalat Ied",
    takbeer: "Allahu Akbar, Allahu Akbar, La ilaha illallah",
    ramadanMubarak: "Ramadan Mubarak!",
    fasting: "Puasa",
    suhoor: "Sahur",
    iftar: "Berbuka",
    quranPages: "Halaman Al-Quran",
    sadaqah: "Sedekah",
    itikaf: "Itikaf",
    laylatalQadr: "Ibadah Lailatul Qadr",
    dayOf: "Hari",
    daysRemaining: "hari tersisa",
    khatamProgress: "Progres Khatam",
    lastTenNights: "10 Malam Terakhir",
    seekLaylatalQadr: "Carilah Lailatul Qadr di malam-malam ganjil",
    fastedToday: "Berpuasa Hari Ini",
    duaBeforeIftar: "Doa Sebelum Berbuka",
    ramadanTracker: "Pelacak Ramadan",
    ramadanDay: "Hari Ramadan",
    previousDay: "Hari Sebelumnya",
    nextDay: "Hari Berikutnya",
    goToToday: "Ke Hari Ini",
    perfectDay: "MasyaAllah! Semua shalat selesai!",
    keepGoing: "Terus semangat! Anda membangun kebiasaan yang indah.",
    missedSome: "Besok awal yang baru. Setiap shalat berharga.",
    fajrTip: "Coba atur alarm 15 menit sebelum Subuh",
    loading: "Memuat...",
    saving: "Menyimpan...",
    days: "hari",
    prayers: "shalat",
    of: "dari",
    page: "Halaman",
    back: "Kembali",
    save: "Simpan",
    cancel: "Batal",
    loginRequired: "Login Diperlukan",
    loginToTrack: "Silakan login untuk melacak shalat Anda",
  },
};

// Prayer name lookup helper
export function getPrayerDisplayName(
  prayerName: string,
  t: SalatTrackerTexts
): string {
  const map: Record<string, string> = {
    fajr: t.fajr,
    dhuhr: t.dhuhr,
    asr: t.asr,
    maghrib: t.maghrib,
    isha: t.isha,
    jummah: t.jummah,
    eid_al_fitr: t.eidAlFitr,
    eid_al_adha: t.eidAlAdha,
    taraweeh: t.taraweeh,
    witr_ramadan: t.witr,
    tahajjud: t.tahajjud,
    duha: t.duha,
    ishraq: t.ishraq,
    awwabin: t.awwabin,
    sunnah_fajr: t.sunnahFajr,
    sunnah_dhuhr_before: t.sunnahDhuhrBefore,
    sunnah_dhuhr_after: t.sunnahDhuhrAfter,
    sunnah_maghrib: t.sunnahMaghrib,
    sunnah_isha: t.sunnahIsha,
  };
  return map[prayerName] || prayerName;
}

// Arabic name for fard prayers
export function getPrayerArabicName(
  prayerName: string,
  t: SalatTrackerTexts
): string {
  const map: Record<string, string> = {
    fajr: t.fajrAr,
    dhuhr: t.dhuhrAr,
    asr: t.asrAr,
    maghrib: t.maghribAr,
    isha: t.ishaAr,
    jummah: t.jummahAr,
  };
  return map[prayerName] || "";
}
