import type { TransLang } from "@/lib/islamic-content";

export interface DhikrPreset {
  id: string;
  arabic: string;
  transliteration: string;
  translations: Record<TransLang, string>;
  defaultTarget: number;
  color: string;
  iconBg: string;
}

export const DHIKR_PRESETS: DhikrPreset[] = [
  {
    id: "subhanallah",
    arabic: "سُبْحَانَ اللَّهِ",
    transliteration: "SubhanAllah",
    translations: {
      en: "Glory be to Allah",
      bn: "আল্লাহর পবিত্রতা ঘোষণা",
      ur: "اللہ پاک ہے",
      ar: "سبحان الله",
      tr: "Allah'i tenzih ederim",
      ms: "Maha Suci Allah",
      id: "Maha Suci Allah",
    },
    defaultTarget: 33,
    color: "from-emerald-500 to-emerald-600",
    iconBg: "bg-emerald-100 text-emerald-700",
  },
  {
    id: "alhamdulillah",
    arabic: "الْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translations: {
      en: "All praise is due to Allah",
      bn: "সকল প্রশংসা আল্লাহর জন্য",
      ur: "تمام تعریفیں اللہ کے لیے ہیں",
      ar: "الحمد لله",
      tr: "Hamd Allah'a mahsustur",
      ms: "Segala puji bagi Allah",
      id: "Segala puji bagi Allah",
    },
    defaultTarget: 33,
    color: "from-blue-500 to-blue-600",
    iconBg: "bg-blue-100 text-blue-700",
  },
  {
    id: "allahuakbar",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translations: {
      en: "Allah is the Greatest",
      bn: "আল্লাহ সর্বশ্রেষ্ঠ",
      ur: "اللہ سب سے بڑا ہے",
      ar: "الله أكبر",
      tr: "Allah en buyuktur",
      ms: "Allah Maha Besar",
      id: "Allah Maha Besar",
    },
    defaultTarget: 34,
    color: "from-amber-500 to-amber-600",
    iconBg: "bg-amber-100 text-amber-700",
  },
  {
    id: "lailaha",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ",
    transliteration: "La ilaha illallah",
    translations: {
      en: "There is no god but Allah",
      bn: "আল্লাহ ছাড়া কোনো উপাস্য নেই",
      ur: "اللہ کے سوا کوئی معبود نہیں",
      ar: "لا إله إلا الله",
      tr: "Allah'tan baska ilah yoktur",
      ms: "Tiada tuhan selain Allah",
      id: "Tiada tuhan selain Allah",
    },
    defaultTarget: 100,
    color: "from-purple-500 to-purple-600",
    iconBg: "bg-purple-100 text-purple-700",
  },
  {
    id: "astaghfirullah",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    transliteration: "Astaghfirullah",
    translations: {
      en: "I seek forgiveness from Allah",
      bn: "আমি আল্লাহর কাছে ক্ষমা চাই",
      ur: "میں اللہ سے معافی مانگتا ہوں",
      ar: "أستغفر الله",
      tr: "Allah'tan bagislanma dilerim",
      ms: "Aku memohon ampun kepada Allah",
      id: "Aku memohon ampun kepada Allah",
    },
    defaultTarget: 100,
    color: "from-teal-500 to-teal-600",
    iconBg: "bg-teal-100 text-teal-700",
  },
  {
    id: "subhanallahiwabihamdihi",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "SubhanAllahi wa bihamdihi",
    translations: {
      en: "Glory and praise be to Allah",
      bn: "আল্লাহর পবিত্রতা ও প্রশংসা ঘোষণা",
      ur: "اللہ پاک ہے اور اس کی حمد ہے",
      ar: "سبحان الله وبحمده",
      tr: "Allah'i hamdiyle tenzih ederim",
      ms: "Maha Suci Allah dan segala puji bagi-Nya",
      id: "Maha Suci Allah dan segala puji bagi-Nya",
    },
    defaultTarget: 100,
    color: "from-rose-500 to-rose-600",
    iconBg: "bg-rose-100 text-rose-700",
  },
];

export const TASBIH_TEXTS: Record<TransLang, {
  title: string;
  subtitle: string;
  count: string;
  target: string;
  reset: string;
  completed: string;
  todayStats: string;
  sessions: string;
  totalDhikr: string;
  history: string;
  noHistory: string;
  tapToCount: string;
  setTarget: string;
  custom: string;
  customPlaceholder: string;
  signInTitle: string;
  signInDesc: string;
  signIn: string;
  createAccount: string;
  loading: string;
  loadingRecords: string;
  back: string;
  deleteTitle: string;
  deleteDescription: string;
  deleteConfirm: string;
  deleteCancel: string;
}> = {
  en: {
    title: "Tasbih Counter",
    subtitle: "Digital dhikr counter for daily remembrance of Allah",
    count: "Count",
    target: "Target",
    reset: "Reset",
    completed: "Completed! MashaAllah",
    todayStats: "Today's Stats",
    sessions: "Sessions",
    totalDhikr: "Total Dhikr",
    history: "History",
    noHistory: "No tasbih history yet. Start counting!",
    tapToCount: "Tap to count",
    setTarget: "Set Target",
    custom: "Custom Dhikr",
    customPlaceholder: "Enter your dhikr text...",
    signInTitle: "Sign in to track your dhikr",
    signInDesc: "Create an account to save your tasbih sessions, track your daily dhikr progress, and sync across all your devices.",
    signIn: "Sign In",
    createAccount: "Create Account",
    loading: "Loading...",
    loadingRecords: "Loading your tasbih records...",
    back: "Back",
    deleteTitle: "Delete Session",
    deleteDescription: "Are you sure you want to delete this tasbih session? This action cannot be undone.",
    deleteConfirm: "Delete",
    deleteCancel: "Cancel",
  },
  bn: {
    title: "তাসবিহ কাউন্টার",
    subtitle: "আল্লাহর যিকরের জন্য ডিজিটাল তাসবিহ",
    count: "গণনা",
    target: "লক্ষ্য",
    reset: "রিসেট",
    completed: "সম্পন্ন! মাশাআল্লাহ",
    todayStats: "আজকের পরিসংখ্যান",
    sessions: "সেশন",
    totalDhikr: "মোট যিকর",
    history: "ইতিহাস",
    noHistory: "এখনো কোনো তাসবিহ ইতিহাস নেই। গণনা শুরু করুন!",
    tapToCount: "গণনা করতে ট্যাপ করুন",
    setTarget: "লক্ষ্য নির্ধারণ",
    custom: "কাস্টম যিকর",
    customPlaceholder: "আপনার যিকর লিখুন...",
    signInTitle: "আপনার যিকর ট্র্যাক করতে সাইন ইন করুন",
    signInDesc: "আপনার তাসবিহ সেশন সংরক্ষণ করতে, দৈনিক যিকর অগ্রগতি ট্র্যাক করতে এবং সব ডিভাইসে সিঙ্ক করতে একটি অ্যাকাউন্ট তৈরি করুন।",
    signIn: "সাইন ইন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    loading: "লোড হচ্ছে...",
    loadingRecords: "আপনার তাসবিহ রেকর্ড লোড হচ্ছে...",
    back: "ফিরে যান",
    deleteTitle: "সেশন মুছুন",
    deleteDescription: "আপনি কি এই তাসবিহ সেশন মুছে ফেলতে চান? এটি পূর্বাবস্থায় ফেরানো যাবে না।",
    deleteConfirm: "মুছুন",
    deleteCancel: "বাতিল",
  },
  ur: {
    title: "تسبیح کاؤنٹر",
    subtitle: "اللہ کی یاد کے لیے ڈیجیٹل تسبیح",
    count: "شمار",
    target: "ہدف",
    reset: "ری سیٹ",
    completed: "مکمل! ماشاءاللہ",
    todayStats: "آج کے اعداد و شمار",
    sessions: "سیشنز",
    totalDhikr: "کل ذکر",
    history: "تاریخ",
    noHistory: "ابھی تک کوئی تسبیح ریکارڈ نہیں۔ شمار شروع کریں!",
    tapToCount: "شمار کرنے کے لیے ٹیپ کریں",
    setTarget: "ہدف مقرر کریں",
    custom: "اپنا ذکر",
    customPlaceholder: "اپنا ذکر لکھیں...",
    signInTitle: "اپنا ذکر ٹریک کرنے کے لیے سائن ان کریں",
    signInDesc: "اپنے تسبیح سیشن محفوظ کرنے، روزانہ ذکر کی پیش رفت ٹریک کرنے اور تمام آلات پر سنک کرنے کے لیے اکاؤنٹ بنائیں۔",
    signIn: "سائن ان",
    createAccount: "اکاؤنٹ بنائیں",
    loading: "لوڈ ہو رہا ہے...",
    loadingRecords: "آپ کے تسبیح ریکارڈ لوڈ ہو رہے ہیں...",
    back: "واپس",
    deleteTitle: "سیشن حذف کریں",
    deleteDescription: "کیا آپ واقعی اس تسبیح سیشن کو حذف کرنا چاہتے ہیں؟ یہ واپس نہیں ہو سکتا۔",
    deleteConfirm: "حذف کریں",
    deleteCancel: "منسوخ",
  },
  ar: {
    title: "عدّاد التسبيح",
    subtitle: "عدّاد رقمي للذكر اليومي",
    count: "العدد",
    target: "الهدف",
    reset: "إعادة",
    completed: "اكتمل! ما شاء الله",
    todayStats: "إحصائيات اليوم",
    sessions: "الجلسات",
    totalDhikr: "إجمالي الذكر",
    history: "السجل",
    noHistory: "لا يوجد سجل تسبيح بعد. ابدأ العد!",
    tapToCount: "اضغط للعد",
    setTarget: "حدد الهدف",
    custom: "ذكر مخصص",
    customPlaceholder: "اكتب ذكرك...",
    signInTitle: "سجّل الدخول لتتبع ذكرك",
    signInDesc: "أنشئ حساباً لحفظ جلسات التسبيح وتتبع تقدمك اليومي في الذكر ومزامنتها عبر جميع أجهزتك.",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    loading: "جارٍ التحميل...",
    loadingRecords: "جارٍ تحميل سجلات التسبيح...",
    back: "رجوع",
    deleteTitle: "حذف الجلسة",
    deleteDescription: "هل أنت متأكد أنك تريد حذف جلسة التسبيح هذه؟ لا يمكن التراجع عن هذا الإجراء.",
    deleteConfirm: "حذف",
    deleteCancel: "إلغاء",
  },
  tr: {
    title: "Tesbih Sayaci",
    subtitle: "Gunluk zikir icin dijital tesbih",
    count: "Sayi",
    target: "Hedef",
    reset: "Sifirla",
    completed: "Tamamlandi! MasaAllah",
    todayStats: "Bugunun Istatistikleri",
    sessions: "Oturumlar",
    totalDhikr: "Toplam Zikir",
    history: "Gecmis",
    noHistory: "Henuz tesbih gecmisi yok. Saymaya baslayin!",
    tapToCount: "Saymak icin dokun",
    setTarget: "Hedef Belirle",
    custom: "Ozel Zikir",
    customPlaceholder: "Zikrinizi yazin...",
    signInTitle: "Zikirlerinizi takip etmek icin giris yapin",
    signInDesc: "Tesbih oturumlarinizi kaydetmek, gunluk zikir ilerlemenizi takip etmek ve tum cihazlarinizda senkronize etmek icin bir hesap olusturun.",
    signIn: "Giris Yap",
    createAccount: "Hesap Olustur",
    loading: "Yukleniyor...",
    loadingRecords: "Tesbih kayitlariniz yukleniyor...",
    back: "Geri",
    deleteTitle: "Oturumu Sil",
    deleteDescription: "Bu tesbih oturumunu silmek istediginizden emin misiniz? Bu islem geri alinamaz.",
    deleteConfirm: "Sil",
    deleteCancel: "Iptal",
  },
  ms: {
    title: "Pembilang Tasbih",
    subtitle: "Tasbih digital untuk zikir harian",
    count: "Kiraan",
    target: "Sasaran",
    reset: "Set Semula",
    completed: "Selesai! MasyaAllah",
    todayStats: "Statistik Hari Ini",
    sessions: "Sesi",
    totalDhikr: "Jumlah Zikir",
    history: "Sejarah",
    noHistory: "Belum ada sejarah tasbih. Mula mengira!",
    tapToCount: "Ketik untuk mengira",
    setTarget: "Tetapkan Sasaran",
    custom: "Zikir Tersuai",
    customPlaceholder: "Masukkan zikir anda...",
    signInTitle: "Log masuk untuk menjejak zikir anda",
    signInDesc: "Cipta akaun untuk menyimpan sesi tasbih, menjejak kemajuan zikir harian, dan menyegerakkan merentasi semua peranti anda.",
    signIn: "Log Masuk",
    createAccount: "Cipta Akaun",
    loading: "Memuatkan...",
    loadingRecords: "Memuatkan rekod tasbih anda...",
    back: "Kembali",
    deleteTitle: "Padam Sesi",
    deleteDescription: "Adakah anda pasti mahu memadamkan sesi tasbih ini? Tindakan ini tidak boleh dibatalkan.",
    deleteConfirm: "Padam",
    deleteCancel: "Batal",
  },
  id: {
    title: "Penghitung Tasbih",
    subtitle: "Tasbih digital untuk zikir harian",
    count: "Hitungan",
    target: "Target",
    reset: "Atur Ulang",
    completed: "Selesai! MasyaAllah",
    todayStats: "Statistik Hari Ini",
    sessions: "Sesi",
    totalDhikr: "Total Zikir",
    history: "Riwayat",
    noHistory: "Belum ada riwayat tasbih. Mulai menghitung!",
    tapToCount: "Ketuk untuk menghitung",
    setTarget: "Tetapkan Target",
    custom: "Zikir Kustom",
    customPlaceholder: "Masukkan zikir Anda...",
    signInTitle: "Masuk untuk melacak zikir Anda",
    signInDesc: "Buat akun untuk menyimpan sesi tasbih, melacak kemajuan zikir harian, dan menyinkronkan di semua perangkat Anda.",
    signIn: "Masuk",
    createAccount: "Buat Akun",
    loading: "Memuat...",
    loadingRecords: "Memuat catatan tasbih Anda...",
    back: "Kembali",
    deleteTitle: "Hapus Sesi",
    deleteDescription: "Apakah Anda yakin ingin menghapus sesi tasbih ini? Tindakan ini tidak dapat dibatalkan.",
    deleteConfirm: "Hapus",
    deleteCancel: "Batal",
  },
};
