"use client";

import { useRef, useCallback } from "react";
import { Download, Loader2 } from "lucide-react";
import { useState } from "react";
import type { SalatStats } from "@/hooks/use-salat-tracker";
import type { SalatTrackerTexts } from "@/lib/salat-tracker-texts";

interface SalatReportExportProps {
  stats: SalatStats;
  t: SalatTrackerTexts;
}

export function SalatReportExport({ stats, t }: SalatReportExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleExport = useCallback(async () => {
    if (!reportRef.current) return;
    setIsExporting(true);
    try {
      const { toPng } = await import("html-to-image");
      const dataUrl = await toPng(reportRef.current, {
        pixelRatio: 2,
        backgroundColor: "#ffffff",
        width: reportRef.current.scrollWidth,
        height: reportRef.current.scrollHeight,
      });

      const link = document.createElement("a");
      link.download = `salat-report-${new Date().toISOString().split("T")[0]}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error("Failed to export report:", err);
    } finally {
      setIsExporting(false);
    }
  }, []);

  return (
    <div>
      {/* Export button */}
      <button
        onClick={handleExport}
        disabled={isExporting}
        className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-emerald-700 transition-colors disabled:opacity-50"
      >
        {isExporting ? (
          <Loader2 className="h-4 w-4 animate-spin" />
        ) : (
          <Download className="h-4 w-4" />
        )}
        {t.exportAsImage}
      </button>

      {/* Exportable report card (hidden, rendered for export) */}
      <div className="fixed left-[-9999px] top-0">
        <div
          ref={reportRef}
          className="w-[400px] bg-white p-6"
          style={{ fontFamily: "system-ui, sans-serif" }}
        >
          {/* Header */}
          <div className="text-center mb-6">
            <h1 className="text-xl font-bold text-emerald-800">Salat Report</h1>
            <p className="text-xs text-gray-400 mt-1">
              {new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          </div>

          {/* Stats grid */}
          <div className="grid grid-cols-2 gap-3 mb-6">
            <StatBox label={t.streak} value={`${stats.currentStreak} ${t.days}`} />
            <StatBox label={t.longestStreak} value={`${stats.longestStreak} ${t.days}`} />
            <StatBox label={t.completionRate} value={`${stats.completionRate}%`} />
            <StatBox label={t.onTimeRate} value={`${stats.onTimeRate}%`} />
            <StatBox label={t.jamaahRate} value={`${stats.jamaahRate}%`} />
            <StatBox label={t.fardCompleted} value={`${stats.totalFardPrayed}`} />
          </div>

          {/* Watermark */}
          <div className="text-center pt-4 border-t border-gray-100">
            <p className="text-[10px] text-gray-300">Generated by IhsanWealth</p>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-emerald-100 p-3 text-center">
      <p className="text-lg font-bold text-emerald-700">{value}</p>
      <p className="text-[10px] text-gray-400">{label}</p>
    </div>
  );
}
